### ISSUE TITLE
[DTWG] FPWD request for Trace Context

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#101]
# Document title, URLs, estimated publication date
Trace Context
https://w3c.github.io/trace-context/?specStatus=FPWD;publishDate=2018-10-31
October 31, 2018

# Abstract
https://w3c.github.io/trace-context/?specStatus=FPWD;publishDate=2018-10-31#abstract

# Status
https://w3c.github.io/trace-context/?specStatus=FPWD;publishDate=2018-10-31#sotd

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://github.com/w3c/distributed-tracing/blob/master/meeting_notes/2018-08-28.md

# Information about implementations known to the Working Group

No known implementation yet but a test suite is being developed

**Comment by plehegar** [comment]
Correction: There are a few implementations of this protocol available.

**Comment by swickr** [comment]
Transition approved.
