### ISSUE TITLE
[CSWG] FPWD request for CSS Shadow Parts 1

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#105]
# Document title, URLs, estimated publication date
CSS Shadow Parts
https://drafts.csswg.org/css-shadow-parts-1/
After transition meeting

# Abstract
https://drafts.csswg.org/css-shadow-parts-1/#abstract

# Status
https://drafts.csswg.org/css-shadow-parts-1/#status (as ED)

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
[RESOLVED: FPWD for Shadow Parts spec](https://lists.w3.org/Archives/Public/www-style/2018Nov/0003.html)
Minutes Telecon 2018-11-07

# Information about implementations known to the Working Group
Too early

**Comment by plehegar** [comment]
Approved.

**Comment by svgeesus** [comment]
Publication request sent

**Comment by svgeesus** [comment]
[Published 15 Nov 2018](https://www.w3.org/TR/2018/WD-css-shadow-parts-1-20181115/)
