### ISSUE TITLE
[CSSWG][FXTF] CR update for geometry-1

### ISSUE THREAD

**Issue by dirkschulze** [w3c/transitions#107]
# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/www-style/2018Nov/0003.html
https://www.w3.org/2018/11/12-svg-minutes.html

# Link to previous Candidate Recommendation transition request
Don't have a link to the previous request. Here the link to the CR though: https://www.w3.org/TR/2014/CR-geometry-1-20141125/

# Substantive changes
https://drafts.fxtf.org/geometry/#changes
https://github.com/w3c/fxtf-drafts/issues?q=label%3Ageometry-1+is%3Aclosed

# Any changes in normative references?
None.

# Any changes in requirements?
None.

# Wide Review of substantive changes
Most changes were implemented in at least 3 browsers. We have tests for Geometry covering the changes.

# Issues status
https://github.com/w3c/fxtf-drafts/labels/geometry-1
This is an updated CR to make sure that the TR version covers implemented behavior. Remaining open issues are not substantial and mostly editorial.  Require more WG discussion.

# Formal Objections
None.

# Any changes in implementation information?
Changes in ED implemented in 3 browsers.

# Deadline for further comments
2-3 months should be fine.

# Any changes in patent disclosures?
None.

CC @svgeesus

**Comment by svgeesus** [comment]
> Don't have a link to the previous request. Here the link to the CR though: https://www.w3.org/TR/2014/CR-geometry-1-20141125/

[Transition Request (2014): Geometry Interfaces to CR](https://lists.w3.org/Archives/Member/chairs/2014OctDec/0129.html)

**Comment by swickr** [comment]
There are significant changes between the CR and this editors' draft.   To be assured that these changes have received wide review at this (CR) stage we should be able to easily find the issue conversations in Github.  I suggest you add those issue pointers to the Changes section.

**Comment by dirkschulze** [comment]
@swickr I added a link to the closed issues, listing each issue individually seems like a duplication of the already present list.

**Comment by swickr** [comment]
transition approved.

**Comment by dirkschulze** [comment]
@svgeesus @xfq Now that the update was approved. When can we expect the spec to be published?

**Comment by svgeesus** [comment]
Publication request sent 30 Nov, expected publication Tues 4 Dec.

**Comment by svgeesus** [comment]
[published 4 December](https://www.w3.org/TR/2018/CR-geometry-1-20181204/)
