### ISSUE TITLE
[CSSWG] WD change of deliverers for filter-effects-1

### ISSUE THREAD

**Issue by dirkschulze** [w3c/transitions#110]
# Link to Editor's Draft
https://drafts.fxtf.org/filter-effects/

# WG resolution to publish
https://log.csswg.org/irc.w3.org/css/2018-12-05/#e1121240

Based on the resolution of the CSS WG (and SVG as well which I can't seem to find right now), the FXTF specs will be edited by the CSS WG forward (https://lists.w3.org/Archives/Public/www-style/2016Dec/0042.html).

This requires a change of deliverers which can not be done by Echidna.

Bikeshed's fxtf boilerplates were updated to reflect the change of deliverers. So should be easy to update.

**Comment by plehegar** [comment]
Adding @xfq , @svgeesus and  @deniak in this loop since this doesn't need Director's input.

@xfq, @svgeesus , I'm assuming we'll need an updated draft sent to webreq.

**Comment by svgeesus** [comment]
Pubrules is OK but linkchecker is not, because animation type moved from being defined in css-transitions to web-animations (with different values).

```
error Lines: 793, 802, 805, 808, 5571, 5607, 6660 https://www.w3.org/TR/css-transitions-1/
    Status: 200 OK

    Some of the links to this resource point to broken URI fragments (such as index.html#fragment). 
    Broken fragments:

        https://www.w3.org/TR/css-transitions-1/#animtype-shadow-list (line 808)
        https://www.w3.org/TR/css-transitions-1/#animtype-precentage (line 5607)
        https://www.w3.org/TR/css-transitions-1/#animtype-number (lines 802, 805, 5607)
        https://www.w3.org/TR/css-transitions-1/#animtype-color (lines 5571, 6660)
        https://www.w3.org/TR/css-transitions-1/#animtype-length (line 793)
```
working on it, still aiming at publication Tues 18th

**Comment by svgeesus** [comment]
OK, linkchecker no longer complains. Will raise issues on the fxtf repo.

Publication request sent 14 Dec 2018, expected publication 18 Dec 2018.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2018/WD-filter-effects-1-20181218/
