### ISSUE TITLE
[CSSWG] WD change of deliverers for motion-1

### ISSUE THREAD

**Issue by dirkschulze** [w3c/transitions#111]
# Link to editor's draft
https://drafts.fxtf.org/motion-1/

# WG resolution to publish
https://log.csswg.org/irc.w3.org/css/2018-12-05/#e1121253

Based on the resolution of the CSS WG (and SVG as well which I can't seem to find right now), the FXTF specs will be edited by the CSS WG forward (https://lists.w3.org/Archives/Public/www-style/2016Dec/0042.html).

This requires a change of deliverers which can not be done by Echidna.

Bikeshed's fxtf boilerplates were updated to reflect the change of deliverers. So should be easy to update.

**Comment by plehegar** [comment]
Adding @xfq , @svgeesus and  @deniak in this loop since this doesn't need Director's input.

@xfq, @svgeesus , I'm assuming we'll need an updated draft sent to webreq.

**Comment by svgeesus** [comment]
Publication request sent 14 Dec, expected publication 18 Dec.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2018/WD-motion-1-20181218/
