### ISSUE TITLE
[immersive-web] FPWD request for webxr

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#116]
# Document title, URLs, estimated publication date

WebXR Device API
https://immersive-web.github.io/webxr/
Feb 5, 2019

# Abstract

https://immersive-web.github.io/webxr/#abstract
> This specification describes support for accessing virtual reality (VR) and augmented
> reality (AR) devices, including sensors and head-mounted displays, on the Web.

# Status

https://immersive-web.github.io/webxr/#status

[List of issues assigned to FPWD](https://github.com/immersive-web/webxr/milestone/6)

# Is it a delta specification intended to become a W3C Recommendation?

No

# Link to group's decision to request transition

http://lists.w3.org/Archives/Public/public-immersive-web-wg/2019Jan/0015.html

# Information about implementations known to the Working Group

none yet

**Comment by plehegar** [comment]
Approved. Go ahead and publish.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2019/WD-webxr-20190205/
