### ISSUE TITLE
[PointerEvents] PR request for pointerevents2 (aka Section 10 is normative)

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#117]
This is a follow-up from
  https://github.com/w3c/transitions/issues/92

# Document title, URLs, estimated publication date

https://w3c.github.io/pointerevents/?specStatus=PR;prEnd=2019-03-19;crEnd=2019-01-03;publishDate=2019-02-19

# Abstract

https://w3c.github.io/pointerevents/#abstract-0

# Status

[[
This document was published as a Proposed Recommendation to ensure that the Section 10, Pointer Capture was properly identified as normative, as it was the case in the first version of Pointer Events. The implementation report already demonstrates interoperability.
]]
https://w3c.github.io/pointerevents/?specStatus=PR;prEnd=2019-03-19;crEnd=2019-01-03;publishDate=2019-02-19

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-pointer-events/2019JanMar/0030.html

# Changes

No substantive changes since the publication of the CR. One editorial change was done to match thed definition of GlobalEventHandlers (see the note in https://heycam.github.io/webidl/#idl-interface-mixins ).

Diff:
https://services.w3.org/htmldiff?doc1=&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fpointerevents%2F%3FspecStatus%3DPR%3BshortName%3Dpointerevents2%3BpublishDate%3D2019-02-19

Commits:
 https://github.com/w3c/pointerevents/commits/gh-pages/index.html

# Requirements satisfied

No change since previous transition.

# Dependencies met (or not)

No change since https://github.com/w3c/transitions/issues/92

# Wide Review

https://github.com/w3c/pointerevents/issues

# Issues addressed

One issue was opened since the publication of CR and pushed to v3:
 https://github.com/w3c/pointerevents/issues/274

https://github.com/w3c/pointerevents/issues

# Formal Objections

None

# Implementation

No change since 
  https://github.com/w3c/transitions/issues/92

# Patent disclosures

No change
https://www.w3.org/2004/01/pp-impl/59096/status

cc @patrickhlauke

**Comment by swickr** [comment]
Transition approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2019/PR-pointerevents2-20190221/
