### ISSUE TITLE
[WASM] CR transition for WebAssembly Core Specification

### ISSUE THREAD

**Issue by ericprud** [w3c/transitions#119]
# Document title, URLs, estimated publication date
target: https://www.w3.org/TR/2019/CR-wasm-core-1-20190306/
source: https://webassembly.github.io/spec/core/bikeshed/
to be published with: [JavaScript Interface](https://github.com/w3c/transitions/issues/137) and [WebAPI](https://github.com/w3c/transitions/issues/138)

# Abstract
This document describes version 1.0 of the core WebAssembly standard, a safe, portable, low-level code format designed for efficient execution and compact representation.

Part of a collection of related documents: the Core WebAssembly Specification, the WebAssembly JS Interface, and the WebAssembly Web API.

# Status
Standard Bikeshed SOTD plus text about exit criteria and CR deadline (see below).

# Link to group's decision to request transition
https://github.com/WebAssembly/meetings/blob/master/2019/WG-02-13.md#--request-that-we-move-forward-with-a-candidate-recommendation-cr

# Changes
This is a short list so I'd be tempted to include notation changes as it won't saturate the reader's brain.
* changed function reference notation from `anyfunc` to `funcref`
* numerics functions renamed a la s{i64.extend_sx/i32}{i64.extend_i32_sx}
* variable instructions renamed a la s{get_local}{local.get}
* tables are limited to having 2**32 elements [3.2.3]
* memory is limited to having 2**16 pages (of 64k) [3.2.4]
* notation for numeric instructions changed a la s{t2.cvtop/t1}{t2.cvtop_t1_sx}
* conversion targets for `extend`, `trunc` and `convert` identified by superscript type instead of _type, e.g. s{extend_s}{extendˢ}
* semantics for growing tables [4.5.3.6] and growing memory [4.5.3.7] made more explicit
* surrogates eliminated from unicode names
c.f. https://www.google.com/url?q=https://github.com/WebAssembly/spec/issues/884%23issuecomment-426433329&sa=D&source=hangouts&ust=1550693442785000&usg=AFQjCNGr5-jPkwdYKyGNRnJBJ_oF-57WDA

# Requirements satisfied
N/A

# Dependencies met (or not)
no changes to dependencies or normative references.

# Wide Review
see issues
* Tag review:
**   https://github.com/w3ctag/design-reviews/issues/151
**   https://github.com/w3ctag/design-reviews/issues/167
**   https://github.com/w3ctag/design-reviews/issues/299*  I18N review:
**   https://lists.w3.org/Archives/Public/public-i18n/2019Apr/thread.html
**   https://lists.w3.org/Archives/Public/public-i18n-core/2019AprJun/thread.html#msg48
* https://github.com/w3ctag/design-reviews/issues/151
* https://github.com/w3ctag/design-reviews/issues/167
* https://github.com/w3ctag/design-reviews/issues/299

# Issues addressed
- http://github.com/WebAssembly/Design
- http://github.com/WebAssembly/spec

We expect to fix some of the open issues but probably more will emerge and they are typically behavior in error conditions.
#960.  [Clarify alignment "hint" being in "base 2 logarithmic representation"?](https://github.com/WebAssembly/spec/issues/960) will close in the next few hours
#899.  [Embedded devices: i8/i16 and memory pages less than 64KiB](https://github.com/WebAssembly/spec/issues/899) (invited to make WASM profile for embedded devices)
#890.  [Relicense test/js-api/limits.js](https://github.com/WebAssembly/spec/issues/890) possible license issue on [some submitted tests](https://github.com/WebAssembly/spec/pull/934)
#870.  [Optional and dependent features](https://github.com/WebAssembly/spec/issues/870) (Meta discussion about optional features -- no specific proposals)
#830.  [support Unicode(or UTF-8 encoded) identifiers](https://github.com/WebAssembly/spec/issues/830) (affects text representation, only used for testing)
#809. [interpreter] [rounding for floating-point constants](https://github.com/WebAssembly/spec/issues/809) (awaiting close by commenter)
#804.  [Any intention add fp16 & i16 native support in webassembly?](https://github.com/WebAssembly/spec/issues/804) (feature req that will not go into 1st REC)
#757. [spec] [Error type for fetch cancellation](https://github.com/WebAssembly/spec/issues/757) (awaiting close by commenter)
#728. [spec review] [4 - Execution editorial wasm-core-1](https://github.com/WebAssembly/spec/issues/728) (awaiting close by commenter)
#617.  [Roundtrip names with strange symbols in text format](https://github.com/WebAssembly/spec/issues/617) (feature req that will not go into 1st REC)
#573. [web] [Register application/wasm MIME type](https://github.com/WebAssembly/spec/issues/573) (TODO: track down flaxgor's registration and push it along)
#421. [interpreter] [f32.convert_u/i64 and f32_convert_s/i64 have incorrect rounding](https://github.com/WebAssembly/spec/issues/421) (awaiting close by commenter)

# Formal Objections
Commentor [achun](https://github.com/achun) disputes the wisdom of where the group went:
945. [spec] [Support i8 and i16?](https://github.com/WebAssembly/spec/issues/945) (addressed in [meeting](https://github.com/WebAssembly/design/issues/1049#issuecomment-310236177)
941. [spec] [Support address value type?](https://github.com/WebAssembly/spec/issues/941) (addressed in [response](https://github.com/WebAssembly/spec/issues/941#issuecomment-454080432))
We will contact achun during CR to ask if he/she would like to file a formal objection.

# Implementation
  exit criteria: 2+ impls of everything in WPT <https://wpt.fyi/results/wasm>
    We expect to pass all positive tests. Some impls map fail some negative tests so long as they reject.
  minimum CR duration: End of June (4 weeks)
  expect immediate transition to PR.

# Patent disclosures

https://www.w3.org/2004/01/pp-impl/101196/status#current-disclosures

-----
# There are some publication challenges, some of which may be addressed by manual intervention:
#896. [bikeshed] [Incorrect links in footnotes](https://github.com/WebAssembly/spec/issues/896)
#794. [bikeshed] [Vertical alignment of footnote numbers editorial](https://github.com/WebAssembly/spec/issues/794)
#680. [bikeshed] [All references should go to References section editorial](https://github.com/WebAssembly/spec/issues/680)
#676. [bikeshed] [Reduce width of TOC editorial](https://github.com/WebAssembly/spec/issues/676)
#670. [bikeshed] [Vertical alignment of arrays editorial](https://github.com/WebAssembly/spec/issues/670)
#643. [website] [highlighting breaks the MathML render editorial](https://github.com/WebAssembly/spec/issues/643)

# Editorial and scale testing issues:
#886.  [Typo: n -> m](https://github.com/WebAssembly/spec/issues/886) (re-use of names in formulae)
#880.  [Embedding limits test should test max module size of 1 GiB](https://github.com/WebAssembly/spec/issues/880) (practical limitations)
#598. [papers] [Add an index page to the papers directory editorial](https://github.com/WebAssembly/spec/issues/598) (paging)
#593.  [The OPAM package properly provides the `.mli` interfaces, but not the `.ml` files for modules such as Ast](https://github.com/WebAssembly/spec/issues/593) (included files)
#124. [interpreter] [fp tests fail on Windows due to bit pattern mismatches](https://github.com/WebAssembly/spec/issues/124) (Not sure what to do. I last pestered folks in Sept and it was still a PITA for testers.)

# all issues for all specs
This is a reverse-ordered list of open issues. These have been sorted into the three TR transition requests:
985. [js-api] [Review object caching](https://github.com/WebAssembly/spec/issues/985) (Mar 14, 2019)
974. [test] [uncovered edge cases](https://github.com/WebAssembly/spec/issues/974) (Feb 22, 2019)
960.  [Clarify alignment "hint" being in "base 2 logarithmic representation"?](https://github.com/WebAssembly/spec/issues/960) (Feb 1, 2019)
945. [spec] [Support i8 and i16?](https://github.com/WebAssembly/spec/issues/945) (Jan 17, 2019)
941. [spec] [Support address value type?](https://github.com/WebAssembly/spec/issues/941) (Jan 13, 2019)
899.  [Embedded devices: i8/i16 and memory pages less than 64KiB](https://github.com/WebAssembly/spec/issues/899) (Oct 24, 2018)
896. [bikeshed] [Incorrect links in footnotes](https://github.com/WebAssembly/spec/issues/896) (Oct 19, 2018)
890.  [Relicense test/js-api/limits.js](https://github.com/WebAssembly/spec/issues/890) (Oct 11, 2018)
886.  [Typo: n -> m](https://github.com/WebAssembly/spec/issues/886) (Oct 5, 2018)
880.  [Embedding limits test should test max module size of 1 GiB](https://github.com/WebAssembly/spec/issues/880) (Sep 24, 2018)
870.  [Optional and dependent features](https://github.com/WebAssembly/spec/issues/870) (Sep 5, 2018)
830.  [support Unicode(or UTF-8 encoded) identifiers](https://github.com/WebAssembly/spec/issues/830) (Jul 5, 2018)
810.  [js api: improve definition of error objects](https://github.com/WebAssembly/spec/issues/810) (May 24, 2018)
809. [interpreter] [rounding for floating-point constants](https://github.com/WebAssembly/spec/issues/809) (May 23, 2018)
804.  [Any intention add fp16 & i16 native support in webassembly?](https://github.com/WebAssembly/spec/issues/804) (May 13, 2018)
794. [bikeshed] [Vertical alignment of footnote numbers editorial](https://github.com/WebAssembly/spec/issues/794) (May 3, 2018)
757. [spec] [Error type for fetch cancellation](https://github.com/WebAssembly/spec/issues/757) (Mar 21, 2018)
741. [js-api] [Allow optional asynchronous steps after instantiation?](https://github.com/WebAssembly/spec/issues/741) (Mar 4, 2018)
728. [spec review] [4 - Execution editorial wasm-core-1](https://github.com/WebAssembly/spec/issues/728) (Feb 28, 2018)
680. [bikeshed] [All references should go to References section editorial](https://github.com/WebAssembly/spec/issues/680) (Feb 13, 2018)
676. [bikeshed] [Reduce width of TOC editorial](https://github.com/WebAssembly/spec/issues/676) (Feb 13, 2018)
670. [bikeshed] [Vertical alignment of arrays editorial](https://github.com/WebAssembly/spec/issues/670) (Feb 13, 2018)
643. [website] [highlighting breaks the MathML render editorial](https://github.com/WebAssembly/spec/issues/643) (Jan 9, 2018)
617.  [Roundtrip names with strange symbols in text format](https://github.com/WebAssembly/spec/issues/617) (Dec 6, 2017)
598. [papers] [Add an index page to the papers directory editorial](https://github.com/WebAssembly/spec/issues/598) (Nov 6, 2017)
593.  [The OPAM package properly provides the `.mli` interfaces, but not the `.ml` files for modules such as Ast](https://github.com/WebAssembly/spec/issues/593) (Oct 26, 2017)
573. [web] [Register application/wasm MIME type](https://github.com/WebAssembly/spec/issues/573) (Oct 5, 2017)
421. [interpreter] [f32.convert_u/i64 and f32_convert_s/i64 have incorrect rounding](https://github.com/WebAssembly/spec/issues/421) (Feb 9, 2017)
124. [interpreter] [fp tests fail on Windows due to bit pattern mismatches](https://github.com/WebAssembly/spec/issues/124) (Oct 10, 2015)

**Comment by binji** [comment]
Link to meeting notes where we discussed transition: https://github.com/WebAssembly/meetings/blob/master/2019/WG-02-13.md#--request-that-we-move-forward-with-a-candidate-recommendation-cr

**Comment by plehegar** [comment]
@ericprud , not sure about the status of this request. Is it ready for the Director to look at?

**Comment by ericprud** [comment]
We have a few more things to take care of. @binji and I will meet this week to take care of them.

**Comment by plehegar** [comment]
ping?

**Comment by swickr** [comment]
Transition approved.

There are some editorial things I noticed:

- The second paragraph of [section 1.1](https://webassembly.github.io/spec/core/bikeshed/#introduction%E2%91%A2) is inconsistent with the SoTD and likely extraneous.
- There is an extraneous copyright statement at the end of the [Execution](https://webassembly.github.io/spec/core/bikeshed/index.html#execution%E2%91%A5) section of [A.8](https://webassembly.github.io/spec/core/bikeshed/index.html#a8-index-of-semantic-rules).

And a question:
In [2.3.3](https://webassembly.github.io/spec/core/bikeshed/index.html#function-types%E2%91%A0) there's a non-normative note about the length of the result type vector for functions.  Is the correct interpretation of [4.4.7.3](https://webassembly.github.io/spec/core/bikeshed/index.html#exec-invoke-host) that this is a normative constraint on host functions as well?

**Comment by binji** [comment]
Thanks! @rossberg to address your questions.

**Comment by rossberg** [comment]
> There are some editorial things I noticed:
> 
> * The second paragraph of section 1.1 is inconsistent with the SoTD and likely extraneous.

Happy to remove. Do you have a link to the SoTD?

> * There is an extraneous copyright statement at the end of the Execution section of A.8.

This seems to be a problem with the Bikeshed conversion. @binji, do you know?

> And a question:
> In 2.3.3 there's a non-normative note about the length of the result type vector for functions. Is the correct interpretation of 4.4.7.3 that this is a normative constraint on host functions as well?

Yes, indirectly. A function type not satisfying this constraint does not validate, so host functions are constrained in so far that it is not possible to import them with a type not satisfying this constraint.

> One more thing; I encourage a comment for #945 explaining the conclusion.

Hm, do you have anything specific in mind? (Note that the CG decided that the spec is not the right place to discuss design rationales, and it's avoided for everything else.)

**Comment by binji** [comment]
> This seems to be a problem with the Bikeshed conversion. @binji, do you know?

I think this fixes it: https://github.com/WebAssembly/spec/pull/1030

**Comment by plehegar** [comment]
Published
  https://www.w3.org/TR/2019/CR-wasm-core-1-20190718/
