### ISSUE TITLE
[DistributedTracing] FPWG-NOTE request for trace-context-protocols-registry

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#121]
# Document title, URLs, estimated publication date
Trace Context Protocols Registry
https://w3c.github.io/trace-context/?specStatus=WG-NOTE
March 5

# Abstract
This document provides a registry of identified formats of trace context [TRACE-CONTEXT] serialization and deserialization for protocols.

# Status
This is a registry and may be updated without any notices.

This document was published by the Distributed Tracing Working Group as a Working Group Note.

GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-trace-context@w3.org (archives).

Publication as a Working Group Note does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy.

This document is governed by the 1 February 2018 W3C Process Document. 

# Is it a delta specification intended to become a W3C Recommendation?

no. Not intended to become a W3C Recommendation.

# Link to group's decision to request transition

https://github.com/w3c/distributed-tracing-wg/blob/master/meeting_notes/2019-02-19.md
https://github.com/w3c/trace-context/issues/254

# Information about implementations known to the Working Group

N/A

**Comment by plehegar** [comment]
fyi @nikmd23 @AloisReitbauer @mtwo

**Comment by swickr** [comment]
Transition approved.

In SOTD I recommend replacing

> This is a registry and may be updated without any notices.

with

> This is a registry and is expected to be updated as described in [Section 2](#registration-entry-requirements-and-update-process).

**Comment by plehegar** [comment]
published
