### ISSUE TITLE
[WebPerfWG] FPWD request for User-Timing-3

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#122]
# Document title, URLs, estimated publication date
User Timing Level 3
https://www.w3.org/TR/user-timing-3/
05 March 2019
https://www.w3.org/TR/2019/WD-user-timing-3-20190305/

# Abstract
This specification defines an interface to help web developers measure the performance of their applications by giving them access to high precision timestamps.

# Status
User Timing Level 3 is intended to supersede [USER-TIMING-2] and includes:

Ability to execute marks and measures across arbitrary timestamps.
Support for reporting arbitrary metadata along with marks and measures.
This document was published by the Web Performance Working Group as a First Public Working Draft. This document is intended to become a W3C Recommendation.

GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-web-perf@w3.org (archives) with [UserTiming] at the start of your email's subject .

Please see the Working Group's implementation report.

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 1 February 2018 W3C Process Document.
(or Process 2019?)

# Is it a delta specification intended to become a W3C Recommendation?
No.

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-web-perf/2019Feb/0002.html

# Information about implementations known to the Working Group
https://wpt.fyi/results/user-timing
Implemented in most of the major browsers.

**Comment by plehegar** [comment]
This was approved and published.

https://www.w3.org/TR/2019/WD-user-timing-3-20190308/
