### ISSUE TITLE
[webappsec] FPWD request for feature-policy

### ISSUE THREAD

**Issue by dveditz** [w3c/transitions#124]
# Document title, URLs, estimated publication date
Feature Policy
https://gitcdn.link/cdn/w3c/webappsec-feature-policy/db9265d373a695ceb58652144abd65573c4aa213/index.html
April 2, 2019

# Abstract
https://gitcdn.link/cdn/w3c/webappsec-feature-policy/db9265d373a695ceb58652144abd65573c4aa213/index.html#abstract

> This specification defines a mechanism that allows developers to selectively enable and disable use of various browser features and APIs.

# Status
https://gitcdn.link/cdn/w3c/webappsec-feature-policy/db9265d373a695ceb58652144abd65573c4aa213/index.html#status

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://github.com/w3c/webappsec/blob/master/meetings/2019/2019-03-20.minutes.md#cfc-to-publish-feature-policy

# Information about implementations known to the Working Group
Chrome, Firefox, and Safari are publicly working on implementations

**Comment by plehegar** [comment]
Approved. Go ahead and publish.

**Comment by wseltzer** [comment]
@samuelweiler is on it

**Comment by samuelweiler** [comment]
Document is staged at https://www.w3.org/TR/2019/WD-feature-policy-1-20190416/.  Publication is scheduled.
