### ISSUE TITLE
[CSSWG] FPNote request for selectors-nonelement-1

### ISSUE THREAD

**Issue by xfq** [w3c/transitions#125]
# Document title, URLs, estimated publication date

Non-element Selectors Module Level 1
https://xfq.github.io/testing/selectors-nonelement-NOTE/Overview.html
First Tuesday/Thursday after approval.

# Abstract

https://xfq.github.io/testing/selectors-nonelement-NOTE/Overview.html#abstract

# Status

https://xfq.github.io/testing/selectors-nonelement-NOTE/Overview.html#status

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/www-style/2019Mar/0017.html

# Information about implementations known to the Working Group

There was one prototype implementation done as an extension to jQuery.

**Comment by plehegar** [comment]
Approved.

**Comment by xfq** [comment]
[Published](https://www.w3.org/TR/2019/NOTE-selectors-nonelement-1-20190402/).
