### ISSUE TITLE
[TTWG] CR update for WebVTT

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#126]
Draft document

https://raw.githack.com/w3c/webvtt/8108fd5699f510926b439c27e7ee2c52b118b8d6/archives/2019-03-06/Overview.html

# Link to group's decision to request transition
  https://www.w3.org/2019/03/28-tt-minutes.html#item07

# Link to previous Candidate Recommendation transition request
  https://github.com/w3c/transitions/issues/49

# Substantive changes

 None, with the exception of marking the following features at risk:
* collision avoidance with snap-to-lines false
* ::cue-region pseudo-element
* :past and :future pseudo-classes

 https://github.com/w3c/webvtt/commits/gh-pages

 Diff:
  https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fwebvtt1%2F&doc2=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fwebvtt%2F8108fd5699f510926b439c27e7ee2c52b118b8d6%2Farchives%2F2019-03-06%2FOverview.html

# Any changes in normative references?

 No change

# Any changes in requirements?

 None

# Wide Review of substantive changes

 No substantive change in the document except for features marked at risk.

# Issues status

 https://github.com/w3c/webvtt/issues

# Formal Objections

 None

# Any changes in implementation information?

CR exit criteria

  For this specification to exit the CR stage, at least 2 independent implementations of every feature defined in this specification need to be documented in the implementation report. 

 At this point, we're attempting to move the specification forward based on implementations.

 https://docs.google.com/spreadsheets/d/e/2PACX-1vSHzJtwi_2ijdV7hRUH0Fe8qZeSwMaCLErK7w7U_IFzhzNmW9YwPRWrER1eHR9-4Eo0kqyXJ4G35b1b/pubhtml

For more details, see
 https://lists.w3.org/Archives/Public/public-tt/2019Mar/0005.html  

# Deadline for further comments

 May 2, 2019

# Any changes in patent disclosures?

None
https://www.w3.org/2004/01/pp-impl/49309/status

cc @gkatsev
cc @silviapfeiffer

**Comment by nigelmegitt** [comment]
The linked draft currently has a pub date of 15th April which will need to be made earlier to match the 2 May deadline for comments; the previous version link points to an old WD and will also need to be fixed up.

**Comment by swickr** [comment]
Transition approved.

Please formally request from the horizontal review groups whether dropping these features at CR exit (if the WG decides to take that action) would impact their previous review.

**Comment by plehegar** [comment]
Published
