### ISSUE TITLE
[CSSWG] FPWD request for css-nav-1

### ISSUE THREAD

**Issue by jihyerish** [w3c/transitions#128]
# Document title, URLs, estimated publication date
CSS Spatial Navigation Level 1
https://drafts.csswg.org/css-nav-1/
09 April 2019
https://www.w3.org/TR/2019/WD-css-nav-1-20190409/

# Abstract
This specification defines a general model for navigating the focus using the arrow keys, as well as related CSS and JavaScript features.

# Status
This is a public copy of the editors’ draft. It is provided for discussion only and may change at any moment. Its publication here does not imply endorsement of its contents by W3C. Don’t cite this document other than as work in progress.

GitHub Issues are preferred for discussion of this specification. When filing an issue, please put the text “css-nav” in the title, preferably like this: “[css-nav] …summary of comment…”. All issues and comments are archived, and there is also a historical archive.

This document was produced by the CSS Working Group.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 1 March 2019 W3C Process Document.

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://github.com/w3c/csswg-drafts/issues/3384#issuecomment-467666564

# Information about implementations known to the Working Group
Chrome

**Comment by plehegar** [comment]
Approved. Go ahead and publish.

**Comment by plehegar** [comment]
note that we are in a publication moratorium week so publication won't happen before Tuessday, April 16.

**Comment by jihyerish** [comment]
Thank you for guidance!

**Comment by frivoal** [comment]
Hi @xfq @svgeesus. Is anything holding this up?

**Comment by xfq** [comment]
[Published](https://www.w3.org/TR/2019/WD-css-nav-1-20190423/).
