### ISSUE TITLE
The profile "First Public Candidate Recommendation" is missing

### ISSUE THREAD

**Issue by deniak** [w3c/transitions#13]

**Comment by plehegar** [comment]
You mean, instead of
 https://www.w3.org/Guide/transitions?profile=CR&cr=new
 https://www.w3.org/Guide/transitions?profile=CR&cr=rec-update

you would like something like:

https://www.w3.org/Guide/transitions?profile=CR-new
https://www.w3.org/Guide/transitions?profile=CR-new&cr=rec-update
?

**Comment by svgeesus** [comment]
Any update on this issue? Have we ever published a First Public CR? If we haven't, and given the Director has in the past denied advancement to CR for a WD that has not been updated for some time, maybe we **shouldn't encourage** this particular route (where a document goes from an unofficial ED to a CR in one week).

**Comment by plehegar** [comment]
We never published a FP CR so far and no one really tried. Our Process allows it but you're right that the Director might make it really hard. I'll check the latest thinking.

**Comment by fantasai** [comment]
I think the only use case I can think of would be e.g. css-writing-modes-4, where we basically just republished css-writing-modes-3 as css-writing-modes-4 as-is, and dropped some features from L3.

**Comment by plehegar** [comment]
See also https://github.com/w3c/w3process/issues/352

**Comment by plehegar** [comment]
One can do a FPWD and a  CR in close succession. The W3C Process does not prevent it.

Per [February 2020 Process CG](https://github.com/w3c/w3process/issues/352#issuecomment-585260875).

So, the profile FPCR does not need to be created.
