### ISSUE TITLE
[AGWG] FPNote request for ACT-Rules-Aspects

### ISSUE THREAD

**Issue by nitedog** [w3c/transitions#130]
# Document title, URLs, estimated publication date
Title: Accessibility Conformance Testing (ACT) Rules: Common Input Aspects

Staging draft ready for publication (meets PubRules):
https://www.w3.org/2017/09/ACT/WD-act-rules-note-10-20170912/  

Planned Publication URI: https://www.w3.org/TR/2019/NOTE-act-rules-aspects-20190416/ 
Latest version URI: https://www.w3.org/TR/act-rules-aspects/ 

Expected publication date: 16 April 2019

# Abstract
This document is a companion to the Accessibility Conformance Testing (ACT) Rules Format 1.0 specification. It lists common input aspects as defined by the ACT Rules Format 1.0 specification. This document is informative. It provides a reference to well defined input aspects to assist authors in writing ACT Rules and to support the consistency of ACT Rules.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.
The Accessibility Guidelines Working Group published this informative document to support developers of Accessibility Conformance Testing (ACT) Rules to author rules more effectively. It provides short-hand notation for some of the 'aspects' that ACT Rules may be testing. Comments are welcome. To comment, file an issue in the W3C ACT TF GitHub repository. It is free to create a GitHub account to file issues. If filing issues in GitHub is not feasible, send email to public-wcag-act-comments@w3.org (comment archive).
This document was published by the Accessibility Guidelines Working Group as a Working Group Note. This document is not intended to become a W3C Recommendation.
Publication as a Working Group Note does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.
This document was produced by a group operating under the W3C Patent Policy.
This document is governed by the 1 March 2019 W3C Process Document. 

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/w3c-wai-gl/2019JanMar/0371.html

# Information about implementations known to the Working Group
This ACT Rules Format was initially incubated and is continually implemented by the auto-WCAG CG (which is currently changing its name to ACT Rules CG). A list of rules following (the previous draft of) this ACT Rules Format, including this companion Working Group Note, is available already:
	https://auto-wcag.github.io/auto-wcag/pages/rules.html
Many of these existing rules already implement “Common Input Aspects” described in this document.

**Comment by plehegar** [comment]
Approved. First possible date for publication is April 16 due to the moratorium.

**Comment by nitedog** [comment]
Thanks for the quick review @plehegar! @michael-n-cooper noticed that we had wrongly auto-generated "Conformance" and "Normative References". These are Bikeshed boilerplate, which I will simply remove. He also suggested a small edit to the SOTD, which I hope you can still approve:

> This document was published by the Accessibility Guidelines Working Group as a Working Group Note. This informative document supports developers of Accessibility Conformance Testing (ACT) Rules to write rules more efficiently. It is a companion document to Accessibility Conformance Testing (ACT) Rules Format 1.0 and provides short-hand notation for some of the 'aspects' that ACT Rules may be testing.
> This document has been published as a Working Group Note to support the Accessibility Conformance Testing (ACT) Rules Format Candidate Recommendation. The Accessibility Guidelines Working Group intends to publish updated versions of this Note to accompany further publications of ACT Rules Format 1.0, and when new 'aspects' are commonly used.
> Comments on this document are welcome. To comment, file an issue in the W3C ACT TF GitHub repository. It is free to create a GitHub account to file issues. If filing issues in GitHub is not feasible, send email to public-wcag-act-comments@w3.org (comment archive). 

Apologies, next time I will coordinate more closely with @michael-n-cooper.

**Comment by plehegar** [comment]
Still ok to publish.

**Comment by nitedog** [comment]
Published at: https://www.w3.org/TR/2019/NOTE-act-rules-aspects-20190416/
