### ISSUE TITLE
superseding MathML 1 and 2

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#131]
#85 was implemented as
  https://lists.w3.org/Archives/Member/w3c-ac-members/2018OctDec/0048.html

But the Director needs to rule on it.

**Comment by swickr** [comment]
Approved.

**Comment by svgeesus** [comment]
Who has the ball on moving this very old request forward? @bert-github @plehegar

**Comment by bert-github** [comment]
Published:
* [SPSD-MathML-20230307](https://www.w3.org/TR/2023/SPSD-MathML-20230307/)
* [SPSD-MathML2-20230307](https://www.w3.org/TR/2023/SPSD-MathML2-20230307/)
