### ISSUE TITLE
superseding WebCGM 1 and 2

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#132]
#87 was implemented as
 https://lists.w3.org/Archives/Member/w3c-ac-members/2018OctDec/0049.html
but the Director needs to rule on the outcome.

**Comment by swickr** [comment]
Approved.

**Comment by plehegar** [comment]
scheduled for December 5
https://lists.w3.org/Archives/Team/w3t-comm/2019Dec/0000.html

**Comment by plehegar** [comment]
done
 https://lists.w3.org/Archives/Member/w3c-ac-members/2019OctDec/0051.html
