### ISSUE TITLE
[DTWG] CR transition for trace-context

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#133]
# Document title, URLs, estimated publication date

Trace Context
https://w3c.github.io/trace-context/
30 April 2019

# Abstract

https://w3c.github.io/trace-context/#abstract

# Status

https://w3c.github.io/trace-context/#sotd

For this specification to be advanced to Proposed Recommendation, there must be at least two independent, interoperable implementations of each feature.
 This document will remain a Candidate Recommendation at least until 14 May 2019. 

# Link to group's decision to request transition

https://github.com/w3c/distributed-tracing-wg/blob/master/meeting_notes/2019-04-23.md

# Changes

Diff is at
  https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Ftrace-context%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Ftrace-context%2F%3FspecStatus%3DWD%3BshortName%3Dtrace-context

The specification was clarified following wide review, including adding potential privacy risk.

https://github.com/w3c/trace-context/commits/master

# Requirements satisfied

No requirements document.

# Dependencies met (or not)

We registered the HTTP headers as provisional in the IANA registry.

# Wide Review

We requested wide review in particular from security and privacy.

https://www.w3.org/2018/11/29-privacy-minutes.html#item00
https://github.com/w3c/trace-context/issues/210
https://github.com/w3c/trace-context/issues/209

# Issues addressed

https://github.com/w3c/trace-context/issues

# Formal Objections

none

# Implementation

https://github.com/w3c/trace-context#reference-implementations

# Patent disclosures

https://www.w3.org/2004/01/pp-impl/108594/status

**Comment by nikmd23** [comment]
Thanks @plehegar. We are pulling together an abstract over the next few days - so that will be in very soon.

**Comment by plehegar** [comment]
Unfortunately, this won't get on the Director desk before Tuesday, due to AC and AB meetings. So publication is more likely to happen on Thursday next week at the earliest.

**Comment by SergeyKanzhelev** [comment]
@plehegar thank you for the update!

**Comment by swickr** [comment]
Transition approved.

Please remember to update the reference to the registry (in References) now that the registry exists on /TR.

**Comment by plehegar** [comment]
published
