### ISSUE TITLE
[CSSWG] CR update for CSS-CONTAIN

### ISSUE THREAD

**Issue by frivoal** [w3c/transitions#134]
# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/www-style/2019Apr/0003.html

# Link to previous Candidate Recommendation transition request
https://lists.w3.org/Archives/Public/www-style/2018Oct/0005.html

# Substantive changes
https://drafts.csswg.org/css-contain/#2018-11-08-changes

# Any changes in normative references?
No, except updating the link to normative references that have been republished since last CR

# Any changes in requirements?
No.

# Wide Review of substantive changes
Disposition of Comments: https://drafts.csswg.org/css-contain/issues-2018-11-cr.html

Few comments, but the amount of changes is also minimal. The change that did get made has support from all implementers (and the rest of the WG), and no relevance to horizontal review groups.

# Issues status
No open issues: https://github.com/w3c/csswg-drafts/labels/css-contain-1

# Formal Objections
None

# Any changes in implementation information?
Most tests (except those for the at risk feature) now pass in both Chrome and Firefox:
https://wpt.fyi/results/css/css-contain?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned

# Deadline for further comments
Resolution doesn't specify. I propose the default 4 weeks, given then very limited changes since previous CR.

# Any changes in patent disclosures?
None

**Comment by frivoal** [comment]
@plehegar @swickr can you have a look? This should be trivial to approve.

PS: if you grant me access rights to this repo I can help with triage.

**Comment by plehegar** [comment]
Previous transition request is actually: https://github.com/w3c/transitions/issues/98

**Comment by swickr** [comment]
Transition approved.

**Comment by svgeesus** [comment]
Publication request sent 27 April, expected publication 30 April.

**Comment by svgeesus** [comment]
[Published](https://www.w3.org/TR/2019/CR-css-contain-1-20190430/) 30 April
