### ISSUE TITLE
[WASM] CR transition for WebAssembly JavaScript Interface

### ISSUE THREAD

**Issue by binji** [w3c/transitions#137]
# Document title, URIs, estimated publication date

target: https://www.w3.org/TR/2019/CR-wasm-js-api-1-20190516/
source: http://webassembly.github.io/spec/js-api/
to be published with: to be published with: [Core](https://github.com/w3c/transitions/issues/119) and [WebAPI](https://github.com/w3c/transitions/issues/138)

# Abstract

This document provides an explicit JavaScript API for interacting with WebAssembly.

Part of a collection of related documents: the Core WebAssembly Specification, the WebAssembly JS Interface, and the WebAssembly Web API.

# Status
Standard bikeshed SOTD plus advice that the following issue may change implementations:
[[
#985. [js-api] [Review object caching](https://github.com/WebAssembly/spec/issues/985) (Mar 14, 2019)
postMessage re-uses existing objects so as not to not grow memory
]]

# Decision to request transition

https://github.com/WebAssembly/meetings/blob/master/2019/WG-02-13.md#--request-that-we-move-forward-with-a-candidate-recommendation-cr

# Changes

* [validate(bytes)](http://webassembly.github.io/spec/js-api/#dom-webassembly-validate) makes a copy of the bytes before validating.
* [asynchronous compilation](http://webassembly.github.io/spec/js-api/#asynchronously-compile-a-webassembly-module) is done in parallel with constructing the module object.
* [Instantiating a module]() is split into steps, so the logic can be reused for synchronous and asynchronous instantiation: [read the imports](http://webassembly.github.io/spec/js-api/#read-the-imports), [create an instance object](http://webassembly.github.io/spec/js-api/#create-an-instance-object), and [instantiate the core of a WebAssembly module](http://webassembly.github.io/spec/js-api/#instantiate-the-core-of-a-webassembly-module).
* Separate [create a memory buffer](http://webassembly.github.io/spec/js-api/#create-a-memory-buffer) from [create a memory object](http://webassembly.github.io/spec/js-api/#create-a-memory-object), to allow reuse in [reset the Memory buffer](http://webassembly.github.io/spec/js-api/#reset-the-memory-buffer).
* ["initial" in Memory descriptor](http://webassembly.github.io/spec/js-api/#dom-memory-memory) is required.
* [maximum < initial throws a RangeError](http://webassembly.github.io/spec/js-api/#dom-memory-memory).
* [define Memory.buffer getter](http://webassembly.github.io/spec/js-api/#dom-memory-buffer).
* ["initial" in Table descriptor](http://webassembly.github.io/spec/js-api/#dom-table-table) is required.
* [Define ValueType enum](http://webassembly.github.io/spec/js-api/#enumdef-valuetype).
* Separate [run a host function](http://webassembly.github.io/spec/js-api/#run-a-host-function) from [create a host function](http://webassembly.github.io/spec/js-api/#create-a-host-function)
* [Added List of implementation-defined limits](http://webassembly.github.io/spec/js-api/#limits)
* [Added Security and Privacy section](http://webassembly.github.io/spec/js-api/#security-considerations)

# Requirements satisfied

N/A

# Dependencies met

Some changes to [WebAssembly core](https://github.com/w3c/transitions/issues/119).

# Wide Review

Reviewed with WebAssembly core specification, see list in https://github.com/w3c/transitions/issues/119.

# Issues Addressed

Issues are addressed on http://github.com/WebAssembly/spec. See, for example, the following issues related to this specification:

* https://github.com/WebAssembly/spec/issues/768
* https://github.com/WebAssembly/spec/issues/827
* https://github.com/WebAssembly/spec/issues/838
* https://github.com/WebAssembly/spec/issues/840
* https://github.com/WebAssembly/spec/issues/855
* https://github.com/WebAssembly/spec/issues/876
* https://github.com/WebAssembly/spec/issues/879
* https://github.com/WebAssembly/spec/issues/914
* https://github.com/WebAssembly/spec/issues/915
* https://github.com/WebAssembly/spec/issues/972

Open issues:
#810.  [js api: improve definition of error objects](https://github.com/WebAssembly/spec/issues/810) (editorial)
#741. [js-api] [Allow optional asynchronous steps after instantiation?](https://github.com/WebAssembly/spec/issues/741) (awaiting close by commenter)

# Formal Objections

None.

# Implementation

See results for 4 implementations at https://wpt.fyi/results/wasm/jsapi.

* `*.any.js` failures are an infrastructure bug.
* [one `grow.any.*` failure](https://wpt.fyi/results/wasm/jsapi/memory/grow.any.html) includes a test for a future feature which is not yet enabled by default.

# Patent disclosures

https://www.w3.org/2004/01/pp-impl/101196/status#current-disclosures

**Comment by binji** [comment]
@ericprud

**Comment by swickr** [comment]
Transition approved.

Looking forward to the resolution of [#1026](https://github.com/WebAssembly/spec/issues/1026) and the similar one for Object.

**Comment by plehegar** [comment]
Published
 https://www.w3.org/TR/2019/CR-wasm-js-api-1-20190718/
