### ISSUE TITLE
[WASM] CR transition for WebAssembly Web API

### ISSUE THREAD

**Issue by binji** [w3c/transitions#138]
# Document title, URIs, estimated publication date

target: https://www.w3.org/TR/2019/CR-wasm-web-api-1-20190516/
source: http://webassembly.github.io/spec/web-api/
to be published with: [Core](https://github.com/w3c/transitions/issues/119) and [JavaScript Interface](https://github.com/w3c/transitions/issues/137)

# Abstract

This document describes the integration of WebAssembly with the broader web platform.

Part of a collection of related documents: the Core WebAssembly Specification , the WebAssembly JS Interface , and the WebAssembly Web API .

# Status

Standard bikeshed SOTD; no expected changes to implementations.

# Decision to request transition

https://github.com/WebAssembly/meetings/blob/master/2019/WG-02-13.md#--request-that-we-move-forward-with-a-candidate-recommendation-cr

# Changes

* [compile a potential WebAssembly response](http://webassembly.github.io/spec/web-api/#compile-a-potential-webassembly-response) makes a copy of the bodyArrayBuffer before performing asynchronous compile (step 2.7.1).

# Requirements satisfied

N/A

# Dependencies met

Normative references to [WebAssembly JS API](https://github.com/w3c/transitions/issues/137) and [WebAssembly Core Specification](https://github.com/w3c/transitions/issues/119).

# Wide Review

Reviewed with WebAssembly core specification, see list in https://github.com/w3c/transitions/issues/119.

# Issues Addressed

Issues are addressed on http://github.com/WebAssembly/spec. See, for example, the following issues related to this specification:

* https://github.com/WebAssembly/spec/pull/711
* https://github.com/WebAssembly/spec/issues/757
* https://github.com/WebAssembly/spec/issues/793
* https://github.com/WebAssembly/spec/issues/806
* https://github.com/WebAssembly/spec/issues/821

# Formal Objections

None.

# Implementation

See results for 4 implementations at https://wpt.fyi/results/wasm/webapi.

* [`contenttype.any.*`](https://wpt.fyi/results/wasm/webapi/contenttype.any.html): some variants only pass on one implementation.

# Patent disclosures

https://www.w3.org/2004/01/pp-impl/101196/status#current-disclosures

**Comment by binji** [comment]
@ericprud

**Comment by swickr** [comment]
Transition approved.

**Comment by plehegar** [comment]
Published
 https://www.w3.org/TR/2019/CR-wasm-web-api-1-20190718/
