### ISSUE TITLE
[webappsec] FPWD request for fetch-metadata

### ISSUE THREAD

**Issue by mikewest** [w3c/transitions#139]
# Document title, URLs, estimated publication date

Fetch Metadata
https://mikewest.github.io/sec-metadata/
Whenever.

(I suppose we'll need to update this once it's moved to the webappsec repo and template. Should I have held off on this request until that happened?)

# Abstract

This document defines a set of Fetch metadata request headers that aim to provide servers with enough information to make _a priori_ decisions about whether or not to service a request based on the way it was made, and the context in which it will be used.

# Status

A Collection of Interesting Ideas

# Is it a delta specification intended to become a W3C Recommendation?

No.

# Link to group's decision to request transition

https://github.com/w3c/webappsec/issues/550#issuecomment-494274009

# Information about implementations known to the Working Group

Chrome has an implementation of all four headers defined in this document. Three are shipping in 76, one might not be necessary, but is implemented behind a flag.

**Comment by wseltzer** [comment]
Imported to the webappsec repos as https://github.com/w3c/webappsec-fetch-metadata

**Comment by mikewest** [comment]
@wseltzer, do you need me to do anything here? I'm happy to produce a FPWD-templated version of the document and commit it to the repo if that's helpful!

**Comment by wseltzer** [comment]
@mikewest yes, please

**Comment by mikewest** [comment]
https://github.com/w3c/webappsec-fetch-metadata/blob/master/FPWD.html / https://w3c.github.io/webappsec-fetch-metadata/FPWD.html

**Comment by samuelweiler** [comment]
Published:  https://www.w3.org/TR/fetch-metadata/
