### ISSUE TITLE
[CSSWG] FPWD request for css-overscroll

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#140]
# Document title, URLs, estimated publication date
CSS Overscroll Behavior Level 1
https://www.w3.org/TR/css-overscroll-1/
Next Thursday

# Abstract
This module defines overscroll-behavior to control the behavior when the scroll position of a scroll container reaches the edge of the scrollport. This allows content authors to hint that the boundary default actions, such as scroll chaining and overscroll, should not be triggered.

# Status
https://drafts.csswg.org/css-overscroll/#status

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://github.com/w3c/csswg-drafts/issues/3939#issuecomment-495701691

# Information about implementations known to the Working Group
https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior

**Comment by plehegar** [comment]
Approved.

**Comment by svgeesus** [comment]
One editor is from Facebook, but Facebook is not a [member of CSS WG](https://www.w3.org/2000/09/dbwg/details?group=32061). Per discussion with chairs, that editor removed (until Facebook joins).

Publication request sent 4 June, publication expected 6 June.

**Comment by svgeesus** [comment]
[Published 6 June](https://www.w3.org/TR/2019/WD-css-overscroll-1-20190606/)
