### ISSUE TITLE
[AudioWG] CR update for webaudio

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#146]
# Link to group's decision to request transition
RESOLUTION: request updated CR for Web Audio API 1.0
https://www.w3.org/2019/06/25-audio-minutes.html

# Link to previous Candidate Recommendation transition request
https://lists.w3.org/Archives/Member/chairs/2018JulSep/0115.html

# Substantive changes
https://webaudio.github.io/web-audio-api/#changestart1

# Any changes in normative references?
Media Capture and Streams is no longer a normative reference.

# Any changes in requirements?
None

# Wide Review of substantive changes
All changes were developed as issues on GitHub. The change appendix links to the respective issue for each change.

# Issues status
No open issues for V1
(actually 4 open, 471 closed; being worked on during today's f2f meeting, closed in next day or two)
https://github.com/WebAudio/web-audio-api/milestone/1

# Formal Objections
None

# Any changes in implementation information?
The major change is that Firefox has implemented most of Audio Worklet, which was the large technical change which held up the previous CR. Internal builds not pass most of the Chrome tests for Audio Worklet. Additional tests for edge cases are being developed by Mozilla and added to WPT. Full compliance is expected by the end of 2019.
Chromium implements almost all of Web Audio API. A few remaining things are being added by Google and Microsoft engineers.
The previous Microsoft implementation in Edge is now abandoned.
The Apple implementation remains unmaintained, with no updates for some years.

# Deadline for further comments
3 months

# Any changes in patent disclosures?
None

**Comment by swickr** [comment]
Some of the changes, such as issue 1802 (https://github.com/WebAudio/web-audio-api/issues/1802) should have privacy review.  Has PING been notified of these changes?

**Comment by plehegar** [comment]
This is blocked on https://github.com/WebAudio/web-audio-api/issues/2061

**Comment by svgeesus** [comment]
[Current status](https://github.com/WebAudio/web-audio-api/issues/2061#issuecomment-601644805)

**Comment by swickr** [comment]
Transition approved. (CR Update)

I note that the open privacy issues are not about the changes being made in this update.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/CR-webaudio-20200611/
