### ISSUE TITLE
[webperf] FPWD request for Timing Entry Names Registry

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#147]
# Document title, URLs, estimated publication date

Timing Entry Names Registry
https://w3c.github.io/timing-entrytypes-registry/?specStatus=FPWD;publishDate=2019-07-02

This is intended to become a Working Group Note.

# Abstract

This document provides a registry of PerformanceEntry.entryType used in Performance Timeline.

# Status

For updates, see Registration Entry Requirements and Update Process.

This document was published by the Web Performance Working Group as a First Public Working Draft.

GitHub Issues are preferred for discussion of this specification.

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. The group does not expect this document to become a W3C Recommendation. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 1 March 2019 W3C Process Document. 

# Is it a delta specification intended to become a W3C Recommendation?

no. This is not a delta spec, and this is not intended to become a W3C Recommendation.

# Link to group's decision to request transition

https://docs.google.com/document/d/13e3kHqur_Esp6ApUMA8fzBwsehFwLBQIvGcC9ZcyUgs/edit

This came from issue 117 raised against performance-timeline:
  https://github.com/w3c/performance-timeline/issues/117#issuecomment-493197882
 
# Information about implementations known to the Working Group

This reflects existing entry names from W3C Working Drafts. All of them are supported in some implementations.

cc @igrigorik , @yoavweiss, @toddreifsteck , @siusin

**Comment by swickr** [comment]
Transition approved.

With shortname "timing-entrytypes-registry/" as indicated in the editor's draft.

**Comment by plehegar** [comment]
Published https://www.w3.org/TR/2019/WD-timing-entrytypes-registry-20190723/
