### ISSUE TITLE
[WEBRTC] CR update for Media Capture and Streams

### ISSUE THREAD

**Issue by caribouW3** [w3c/transitions#148]
# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-webrtc/2019Jun/0030.html

# Link to previous Candidate Recommendation transition request
https://lists.w3.org/Archives/Member/chairs/2017JulSep/0148.html

# Substantive changes
A number of substantive changes have been made, as reflected in the diff:
https://www.w3.org/2019/06/mediacapture-diff.html
(e.g. applyConstraints algorithm moved off the main thread,
addition of section Feature Policy Integration, removal of originIdentifier,... )

# Any changes in normative references?
HTML52 -> WHATWG LS as recently requested for all specs.

# Any changes in requirements?
None

# Wide Review of substantive changes
Since the previous CR, 55 new GH issues were received

# Issues status
https://github.com/w3c/mediacapture-main/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc
Open issues at
https://github.com/w3c/mediacapture-main/issues

# Formal Objections
None

# Any changes in implementation information?
Partial implementations of the APIs are known to exist at least in Chrome, Firefox, MS Edge,
Safari.

# Deadline for further comments
september 30, 2019

# Any changes in patent disclosures?
None

**Comment by swickr** [comment]
Transition approved.

**Comment by swickr** [comment]
Please update your HTML reference.

**Comment by caribouW3** [comment]
The PR for that got approved by Dom, I think we're almost ready for publication next tuesday (we just need to snapshot with the right SOTD)

**Comment by caribouW3** [comment]
published
