### ISSUE TITLE
[ARIA] FPWD request for accname-1.2

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/transitions#150]
# Document title, URLs, estimated publication date
Accessible Name and Description Computation 1.2
Latest version URI: https://www.w3.org/TR/accname-1.2/
Editors' draft URI: https://w3c.github.io/accname/
Expected publication date: 16 July 2019

# Abstract
This document describes how user agents determine the names and descriptions of accessible objects from web content languages. This information is in turn exposed through accessibility APIs so that assistive technologies can identify these objects and present their names or descriptions to users. Documenting the algorithm through which names and descriptions are to be determined promotes interoperable exposure of these properties among different accessibility APIs and helps to ensure that this information appears in a manner consistent with author intent.

The accessible name and description computation specification defines support that applies across multiple content technologies. This includes accessible name and description provided by general-purpose WAI-ARIA [WAI-ARIA] roles, states, and properties as well as features specific to individual content languages.

This document updates and will eventually supersede the accessible name and description guidance in the Accessible Name and Description Computation 1.1 W3C Recommendation. It is part of the WAI-ARIA suite described in the WAI-ARIA Overview.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

This is a First Public Working Draft of Accessible Name and Description Computation (Accname) 1.2 by the Accessible Rich Internet Applications (ARIA) Working Group. Succeeding Accname 1.1 [ACCNAME-1.1], it refines the name and description model to address feedback from earlier versions, and will address any features needed for WAI-ARIA 1.2 [WAI-ARIA-1.2].

The Accessible Rich Internet Applications Working Group seeks feedback on any aspect of the specification. When submitting feedback, please consider issues in the context of the companion documents. To comment, file an issue in the W3C accname GitHub repository. If this is not feasible, send email to public-aria@w3.org (comment archive). In-progress updates to the document may be viewed in the publicly visible editors' draft.

This document was published by the Accessible Rich Internet Applications Working Group as a First Public Working Draft. This document is intended to become a W3C Recommendation.

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 1 March 2019 W3C Process Document. 

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-aria-admin/2019Jul/0000.html

# Information about implementations known to the Working Group
Implementation report will be at https://w3c.github.io/test-results/accname/ but has not been updated for 1.2 features, which so far do not impact testing. Informal testing, which informs input into the 1.2 version, is also conducted at https://github.com/WhatSock/w3c-alternative-text-computation.

**Comment by plehegar** [comment]
Approved. Go ahead and publish.

**Comment by plehegar** [comment]
@michael-n-cooper ping?

**Comment by michael-n-cooper** [comment]
@plehegar I'm not sure what I'm being pinged for, the document went up on 11 July 2019.

**Comment by plehegar** [comment]
Should checked that before pinging, sorry.
Published at
 https://www.w3.org/TR/2019/WD-accname-1.2-20190711/
