### ISSUE TITLE
[DTWG] CR update for Trace Context

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#156]
# Link to group's decision to request transition

https://github.com/w3c/distributed-tracing-wg/blob/master/meeting_notes/2019-07-30.md

# Link to previous Candidate Recommendation transition request

https://github.com/w3c/transitions/issues/133 (approved on April 26)

# Substantive changes

- lots of editorial improvements, including the description of header fields, processing model
- tweaks of id format
  https://github.com/w3c/trace-context/commit/428670ecbc71d307e1b1da5f7b25f19acbb4279f
- fixed substantive typo on what a tracing tool must set
  https://github.com/w3c/trace-context/commit/214a4df734b20b9829d3506882f4d6d0827dd539

Commits:
 https://github.com/w3c/trace-context/commits/master

Diff is at
https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Ftrace-context%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Ftrace-context%2F%3FspecStatus%3DWD%3BshortName%3Dtrace-context

# Any changes in normative references?

none

# Any changes in requirements?

none

# Wide Review of substantive changes

The substantive changes were tweaks in header grammars and fixing a typo, based on feedback from implementers.

# Issues status

https://github.com/w3c/trace-context/issues

The remaining issues are considered so far editorial and ongoing.

# Formal Objections

None

# Any changes in implementation information?

We're getting continuous feedback from implementers.

# Deadline for further comments

No change: still 8 September 2019.

# Any changes in patent disclosures?

None

(cc @nikmd23 @AloisReitbauer @mtwo )

**Comment by swickr** [comment]
Transition approved.
