### ISSUE TITLE
[VCWG] PR request for vc-data-model

### ISSUE THREAD

**Issue by burnburn** [w3c/transitions#158]
# Document title, URLs, estimated publication date

Document Title: Verifiable Credentials Data Model 1.0
Current document link:  https://w3c.github.io/vc-data-model/PR/2019-09-03/
Editor's draft: https://w3c.github.io/vc-data-model/
Latest version link: https://www.w3.org/TR/vc-data-model/
To be published to:  https://www.w3.org/TR/2019/PR-vc-data-model-20190903/
Implementation Report plan:  https://w3c.github.io/vc-test-suite/implementations/
Estimated publication date: 3 September 2019

# Abstract

Credentials are a part of our daily lives; driver's licenses are used to assert that we are capable of operating a motor vehicle, university degrees can be used to assert our level of education, and government-issued passports enable us to travel between countries. This specification provides a mechanism to express these sorts of credentials on the Web in a way that is cryptographically secure, privacy respecting, and machine-verifiable.

# Status

This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

The Working Group thanks the following individuals not only for their contributions toward the content of this document, but also for yeoman's work in this standards community that drove changes, discussion, and consensus among a sea of varied opinions: Matt Stone, Gregg Kellogg, Ted Thibodeau Jr, Oliver Terbu, Joe Andrieu, David I. Lehn, Matthew Collier, and Adrian Gropper.

Work on this specification has been supported by the Rebooting the Web of Trust community facilitated by Christopher Allen, Shannon Appelcline, Kiara Robles, Brian Weller, Betty Dhamers, Kaliya Young, Manu Sporny, Drummond Reed, Joe Andrieu, Heather Vescent, Kim Hamilton Duffy, Samantha Chase, and Andrew Hughes. The participants in the Internet Identity Workshop, facilitated by Phil Windley, Kaliya Young, Doc Searls, and Heidi Nobantu Saul, also supported the refinement of this work through numerous working sessions designed to educate about, debate on, and improve this specification.

The Working Group also thanks the Chairs, Dan Burnett and Matt Stone, as well as our W3C Staff Contact, Kazuyuki Ashimura, for their expert management and steady guidance of the group through the W3C standardization process.

Portions of the work on this specification have been funded by the United States Department of Homeland Security's Science and Technology Directorate under contract HSHQDC-17-C-00019. The content of this specification does not necessarily reflect the position or the policy of the U.S. Government and no official endorsement should be inferred.

Comments regarding this document are welcome by the W3C Advisory Committee, but readers should be aware that the Candidate Recommendation comment period regarding the rest of this document has ended and the Working Group is unlikley to make substantive modifications to the specification at this stage. Please file issues directly on GitHub, or send them to public-vc-comments@w3.org (subscribe, archives).

The Working Group has received implementation feedback showing that there are at least two implementations for each normative feature in the specification. The group has obtained reports from nine (9) implementations. For details, see the test suite and implementation report.

Changes since the last publication of this document include:

Non-normative insertion of an additional example and some minor editorial modifications to a few sentences in the specification.

This document was published by the Verifiable Claims Working Group as a Proposed Recommendation. This document is intended to become a W3C Recommendation.

GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-vc-comments@w3.org (archives).

The W3C Membership and other interested parties are invited to review the document and send comments to public-vc-comments@w3.org (subscribe, archives) through 01 October 2019. Advisory Committee Representatives should consult their WBS questionnaires. Note that substantive technical comments were expected during the Candidate Recommendation review period that ended 21 August 2019.

Please see the Working Group's implementation report.

Publication as a Proposed Recommendation does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 1 March 2019 W3C Process Document.

# Link to group's decision to request transition

https://www.w3.org/2019/08/20-vcwg-minutes.html#resolution06

# Changes

(See above in the Status section)

# Requirements satisfied

The working group does not maintain a direct analysis of requirements satisfied since this is a data model specification.  However, the primary ecosystem requirements motivating this work are given in the specification itself at https://w3c.github.io/vc-data-model/PR/2019-09-03/#use-cases-and-requirements

# Dependencies met (or not)

There are no known dependencies on other work.

# Wide Review

The specification has been discussed and reviewed extensively within its community via discussions at the W3C Credentials Community Group and multiple Rebooting the Web of Trust conferences.  Additionally, horizontal review was requested from relevant groups at W3C.  Issues and/or PRs for the latter can be found in the Working Group's GitHub repository at https://github.com/w3c/vc-data-model/issues?utf8=%E2%9C%93&q=label%3AHorizontalReview+ .

# Issues addressed

The GitHub repository for issues is at https://github.com/w3c/vc-data-model/issues .
All issues, regardless of source, have been addressed.
Issues received during the second CR review period: https://github.com/w3c/vc-data-model/issues?q=is%3Aissue+label%3ACR2-phase

The disposition of all issues received prior to this review period is available in the previous Transition Request:  https://github.com/w3c/transitions/issues/152

No substantially new issues required to be addressed in this version were raised during this time period.

# Formal Objections

None

# Implementation

The Working Group has obtained reports from nine (9) implementations, with at least two implementations of each feature.  See the implementation report at https://w3c.github.io/vc-test-suite/implementations/ .

# Patent disclosures

No disclosures to date:  https://www.w3.org/2004/01/pp-impl/98922/status

**Comment by swickr** [comment]
Checking into the status of JSON-LD 1.1 ...

**Comment by iherman** [comment]
The JSON-LD Working Group has just closed all its outstanding technical issues see:

- https://github.com/w3c/json-ld-syntax/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3Adefer-future-version
- https://github.com/w3c/json-ld-api/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3Adefer-future-version
- https://github.com/w3c/json-ld-framing/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3Adefer-future-version

and considers the technical work, in terms of features of the language, as closed.

The group is planning to work only on editorial and CR related issues  (test cases, reports, etc.) at the upcoming TPAC F2F and intends to issue a request for CR a few of weeks after TPAC.

I think we can safely say that the future Recommendation is ready as far as the VC work is concerned.

- Ivan Herman, staff contact for the JSON-LD WG

**Comment by swickr** [comment]
Transition approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2019/PR-vc-data-model-20190905/
