### ISSUE TITLE
Some feedback about publication request

### ISSUE THREAD

**Issue by xfq** [w3c/transitions#16]
In https://github.com/w3c/transitions/blob/4d964f2549a7a03ccc019a6761b5f6763f90803e/index.html#L487:

> Before sending the publication request, the Document Contact SHOULD install the document in its final location.

It might be useful to say that "install the document in its final location" means putting the document in the right directory under /TR/.

-----

And quoting an email between me and @dontcallmedom, as another feedback:

[[[
On 2017-08-21 22:17, Fuqiao Xue wrote:

> I don't quite understand the "install the document in its final
location" part. As far as I can see, if a documented is in TR/, it's
already published.

Not quite - what we consider to be a published TR document is one which
is linked from the TR page itself (https://www.w3.org/TR/), which is
something only the Webmaster can make happen.
]]]

**Comment by svgeesus** [comment]
Does this issue still need to be open, now we are clear that "publication" means "editing the /TR overview page to point to an already installed document" ?

**Comment by xfq** [comment]
I know what it means now, but I'm not sure if it's confusing for other people (either now, or in the future).

**Comment by plehegar** [comment]
the document says later "The Webmaster completes publication" so it should be clear that there is a step after installing the document in place. Following the link, it has "The Webmaster
publishes the document by updating the appropriate technical report
index and updating the latest version link". So it may be a case here of one has to read the document top to bottom understands implication.

**Comment by svgeesus** [comment]
I suggest closing this issue.

**Comment by xfq** [comment]
Fine with me. Closing.
