### ISSUE TITLE
[immersive-web] FPWD request for webxr-ar-module

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#161]
(final; cc @dontcallmedom , @AdaRoseCannon , @cwilso )

# Document title, URLs, estimated publication date

WebXR Augmented Reality Module - Level 1
https://immersive-web.github.io/webxr-ar-module/
Oct, 10 2019

# Abstract

https://immersive-web.github.io/webxr-ar-module/#abstract
> The WebXR Augmented Reality module expands the WebXR Device API with the functionality available on AR hardware.

# Status

https://immersive-web.github.io/webxr-ar-module/#status

# Is it a delta specification intended to become a W3C Recommendation?

No

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-immersive-web-wg/2019Sep/0011.html

# Information about implementations known to the Working Group

none yet

**Comment by plehegar** [comment]
Approved.

**Comment by himorin** [comment]
https://www.w3.org/TR/2019/WD-webxr-ar-module-1-20191010/
