### ISSUE TITLE
[immersive-web] FPWD request for webxr-gamepads-module

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#162]
(final; cc @dontcallmedom , @AdaRoseCannon , @cwilso )

# Document title, URLs, estimated publication date

WebXR Gamepads Module - Level 1
https://immersive-web.github.io/webxr-gamepads-module/
Oct, 10, 2019

# Abstract

https://immersive-web.github.io/webxr-gamepads-module/#abstract
> This specification module describes support for accessing button, trigger, thumbstick, and touchpad data associated with virtual reality (VR) and augmented reality (AR) devices on the Web.

# Status

https://immersive-web.github.io/webxr-gamepads-module/#status

# Is it a delta specification intended to become a W3C Recommendation?

No

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-immersive-web-wg/2019Sep/0011.html

# Information about implementations known to the Working Group

none yet

**Comment by plehegar** [comment]
Approved

**Comment by himorin** [comment]
https://www.w3.org/TR/2019/WD-webxr-gamepads-module-1-20191010/
