### ISSUE TITLE
[WASM] PR transition for WebAssembly Core Specification

### ISSUE THREAD

**Issue by ericprud** [w3c/transitions#163]
# Document title, URLs, estimated publication date
target: https://www.w3.org/TR/2019/CR-wasm-core-1-20190919/
source: [CR](https://www.w3.org/TR/2019/CR-wasm-core-1-20190718/) with manual edits.
to be published with: [JavaScript Interface](https://github.com/w3c/transitions/issues/164) and [WebAPI](https://github.com/w3c/transitions/issues/165)

# Abstract
This document describes version 1.0 of the core WebAssembly standard, a safe, portable, low-level code format designed for efficient execution and compact representation.

Part of a collection of related documents: the Core WebAssembly Specification, the WebAssembly JS Interface, and the WebAssembly Web API.

# Status
At the time of publication, the WebAssembly language was already fully supported in four major browsers. Progress can be monitored in the [Web Platform Tests](https://wpt.fyi/results/wasm). The [WebAssembly Community Group](https://www.w3.org/community/webassembly/) is continuing to add features to WebAssembly.

# Link to group's decision to request transition
https://hackmd.io/WTWiMvkRQJ2wkg06E1pywQ (should be echoed elsewhere, will locate)

# Changes
- Updated normative reference to [IEEE 754-2019](https://ieeexplore.ieee.org/document/8766229)

# Requirements satisfied
N/A

# Dependencies met (or not)
no changes to dependencies
normative reference to IEEE 754-2019 follows publication of that document

# Wide Review
Wide implementation and testing preceded publication as CR. See "Wide Review" in [CR transition](https://github.com/w3c/transitions/issues/119)

# Issues addressed
- The [latest js-api change](https://github.com/WebAssembly/spec/commit/666dc4cb8d4a81d386a7a716000bb85fbbbd06a2) is present in the CR document
- The [Upgrade to IEEE 754-2019 (#1050)](https://github.com/WebAssembly/spec/commit/a221f2574d7106e92cf8abaf05d5bb1131b19d76) just updates the IEE754 reference to the most recent spec -- doesn't change implementation

# Formal Objections
None since CR. See "Formal Objections" in [CR transition request](https://github.com/w3c/transitions/issues/119) for earlier disputes that did not result in an objection.

# Implementation
  exit criteria: 2+ impls of everything in [WPT/wasm])https://wpt.fyi/results/wasm) where an impl passes  all positive tests. As anticipated in the [CR status](https://www.w3.org/TR/wasm-core/#status), some impls result in different failures that those expected by negative tests.

# Patent disclosures
https://www.w3.org/2004/01/pp-impl/101196/status#current-disclosures

**Comment by swickr** [comment]
Transition approved.
