### ISSUE TITLE
PR transition for WebAssembly JavaScript Interface

### ISSUE THREAD

**Issue by ericprud** [w3c/transitions#164]
# Document title, URLs, estimated publication date
title: WebAssembly JavaScript Interface
title2: W3C Proposed Recommendation, 19 September 2019
target: https://www.w3.org/TR/2019/CR-wasm-js-api-1-20190919/
source: [CR](https://www.w3.org/TR/2019/CR-wasm-js-api-1-20190718/) with manual edits.
to be published with: [Core](https://github.com/w3c/transitions/issues/163) and [WebAPI](https://github.com/w3c/transitions/issues/165)

# Abstract
This document provides an explicit JavaScript API for interacting with WebAssembly.

# Rest...
see [core transition request](https://github.com/w3c/transitions/issues/163)

**Comment by swickr** [comment]
Transition approved.
