### ISSUE TITLE
PR transition for WebAssembly Web API

### ISSUE THREAD

**Issue by ericprud** [w3c/transitions#165]
# Document title, URLs, estimated publication date
title: WebAssembly Web API
title2: W3C Proposed Recommendation, 19 September 2019
target: https://www.w3.org/TR/2019/CR-wasm-web-api-1-20190919/
source: [CR](https://www.w3.org/TR/2019/CR-wasm-web-api-1-20190718/) with manual edits.
to be published with: [Core](https://github.com/w3c/transitions/issues/163) and [JS API](https://github.com/w3c/transitions/issues/164)

# Abstract
This document describes the integration of WebAssembly with the broader web platform.

# Rest...
see [core transition request](https://github.com/w3c/transitions/issues/163)

**Comment by swickr** [comment]
Transition approved.
