### ISSUE TITLE
[CWIG] FPWD request for mini-app-white-paper

### ISSUE THREAD

**Issue by xfq** [w3c/transitions#166]
# Document title, URLs, estimated publication date

Title: MiniApp Standardization White Paper

URL: https://w3c.github.io/mini-app-white-paper/?specStatus=FPWD;publishDate=2019-09-12

Expected publication date: 12 September 2019

# Abstract

This document introduces a new format for mobile application, named MiniApp, which is a very popular hybrid solution relies on Web technologies but also integrates with capabilities of Native Apps.

# Status

https://w3c.github.io/mini-app-white-paper/?specStatus=FPWD;publishDate=2019-09-12#sotd

This document is intended to be published as an Interest Group Note in the future.

# Is it a delta specification intended to become a W3C Recommendation?

No.

# Link to group's decision to request transition

https://lists.w3.org/Archives/Member/member-chinese-web/2019Sep/0001.html

# Information about implementations known to the Interest Group

Current implementations are briefly described in:

https://w3c.github.io/mini-app-white-paper/?specStatus=FPWD;publishDate=2019-09-12#miniapp-landscape

**Comment by plehegar** [comment]
Approved.

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2019/WD-mini-app-white-paper-20190912/
