### ISSUE TITLE
[CSSWG] FPWD request for CSS Containment Module Level 2

### ISSUE THREAD

**Issue by frivoal** [w3c/transitions#167]
# Document title, URLs, estimated publication date
CSS Containment Module Level 2
https://drafts.csswg.org/css-contain-2/
26 September 2019

# Abstract
https://drafts.csswg.org/css-contain-2/#abstract

# Status
https://drafts.csswg.org/css-contain-2/#status

# Is it a delta specification intended to become a W3C Recommendation?

No, this is a full spec, copying the content of level 1, but also including the at-risk feature that was dropped from there.

# Link to group's decision to request transition
https://logs.csswg.org/irc.w3.org/css/2019-09-15/#e1234939

# Information about implementations known to the Working Group
Chrome and Firefox both pass all features that were present in level 1 (see https://drafts.csswg.org/css-contain-1/implementation-report-2019-09)

**Comment by plehegar** [comment]
Approved.

**Comment by xfq** [comment]
Sorry for the delay. It's published: https://www.w3.org/TR/2019/WD-css-contain-2-20191015/
