### ISSUE TITLE
[CSSWG] PR request for CSS-CONTAIN-1

### ISSUE THREAD

**Issue by frivoal** [w3c/transitions#168]
# Document title, URLs, estimated publication date

CSS Containment Module Level 1
https://drafts.csswg.org/css-contain-1/
September 26 2019

# Abstract

https://drafts.csswg.org/css-contain-1/#abstract

# Status

https://drafts.csswg.org/css-contain-1/#status

# Link to group's decision to request transition

https://logs.csswg.org/irc.w3.org/css/2019-09-15/#e1234731

# Changes

https://drafts.csswg.org/css-contain-1/#2019-04-30-changes

# Requirements satisfied
N/A (no requirement document)

# Dependencies met (or not)

Met (no changes since CR, see https://github.com/w3c/transitions/issues/134)

# Wide Review + Issues addressed

Disposition of Comments: https://drafts.csswg.org/css-contain-1/issues-2019-cr.html

See also [last CR transition](https://github.com/w3c/transitions/issues/134)

# Formal Objections

None

# Implementation

https://drafts.csswg.org/css-contain-1/implementation-report-2019-09

# Patent disclosures

None (https://www.w3.org/2004/01/pp-impl/32061/status)

**Comment by swickr** [comment]
Transition approved.

**Comment by frivoal** [comment]
ping

**Comment by xfq** [comment]
Sorry for the delay. It's published: https://www.w3.org/TR/2019/PR-css-contain-1-20191015/
