### ISSUE TITLE
[DXWG] CR Request to DCAT v2

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#169]
Reference: [w3c/transitions](https://github.com/w3c/transitions)

# Document title, URLs, estimated publication date

Data Catalog Vocabulary (DCAT) - Version 2
* current ED : https://w3c.github.io/dxwg/dcat/
* current WD : https://www.w3.org/TR/vocab-dcat-2
* Proposed: https://w3c.github.io/dxwg/dcat/?specStatus=CR;crEnd=2019-10-31;publishDate=2019-10-03

# Abstract
https://www.w3.org/TR/vocab-dcat-2/#abstract

# Status
https://w3c.github.io/dxwg/dcat/?specStatus=CR;crEnd=2019-10-31;publishDate=2019-10-03#sotd

# Link to group's decision to request transition

https://www.w3.org/2019/09/24-dxwg-minutes.html#item01

# Changes

Diff
  https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fvocab-dcat-2%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fdxwg%2Fdcat%2F%3FspecStatus%3DCR%3BshortName%3Dvocab-dcat-2

* Namespaces sorted in normative/non-normative sets
* Marked at risk:
* * Catalog: dcat:service, dcat:catalog
* * Cataloged Resource: dcat:qualifiedRelation, prov:qualifiedAttribution
* * Dataset dcat:spatialResolutionInMeters, dcat:temporalResolution, prov:wasGeneratedBy
* * Distribution odrl:hasPolicy, dcat:accessService, dcat:packageFormat
* * Data Service dct:accessRights
* * Relationship dcat:Relationship, dcat:hadRole
* * Role dcat:Role
* * Period of Time dcat:startDate, dcat:endDate
* * Location dcat:bbox, dcat:centroid 
* Removed Location w3cgeo:lat, w3cgeo:long, w3cgeo:alt
* various minor clarifications, such as Cataloged Resource odrl:hasPolicy

See https://w3c.github.io/dxwg/dcat/#motivation.  DCAT version 2 represents a (backward compatible) revision of the existing 2014 DCAT (http://www.w3.org/TR/2014/REC-vocab-dcat-20140116/). A summary of the broad changes is included in https://www.w3.org/TR/vocab-dcat-2/#changes

# Requirements satisfied
https://www.w3.org/TR/2019/NOTE-dcat-ucr-20190117/.  DCAT Requirements are also represented in [github](https://github.com/w3c/dxwg) labelled as 'requirement' and 'DCAT'.  (24 closed, 19 open/deferred to future work)

# Dependencies met (or not)
No dependencies on new or modified standards or other WG deliverables. Process dependencies on other groups or organisations for feedback or wider review covered in appropriate section below.

# Wide Review

The wide review commenced at the end of May 2019 and included direct approaches to the Chairs of the following groups:
* W3C SHACL Community Group
* Research Data Alliance
* W3C Privacy Interest Group
* W3C ODRL Community Group
* EC ISA/Joinup programme
* W3C Schema.org Community Group
* W3C Internationalization Working Group
* W3C ShEx Community Group

This was associated with a W3C blog post about the DCAT version 2 work, contextualising it with the wider objectives of the DXWG working group - https://www.w3.org/blog/2019/06/dataset-exchange-working-group-is-making-progress/

The wide review did not discover any significant issues, though the Privacy Interest Group were keen to ensure that privacy and scope to remove personally-identifiable information from catalogues was considered in any primer that DXWG developed https://lists.w3.org/Archives/Public/public-privacy/2019AprJun/0076.html.  The Internationalization Working Group added the DCAT proposal to their Review Radar https://github.com/w3c/i18n-activity/issues/704

Comments from wide review were received via the comments mailing list https://lists.w3.org/Archives/Public/public-dxwg-comments/ or as github issues tagged as feedback - [here](https://github.com/w3c/dxwg/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Adcat+label%3Afeedback) which also tracks responses and discussion.  Where the feedback couldn't be addressed within the time available (and with agreement with the correspondent), the issue has been marked for future work.

# Issues addressed
Github is being used for issue tracking (even if original issue came via email). Of non-editorial issues, [more than a 100](https://github.com/w3c/dxwg/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Adcat+is%3Aclosed+-label%3Aeditorial) have been closed/resolved. Several remain open for future work or are editorial.

# Formal Objections
None

# Implementation
Implementation of DCAT 2 will be evidenced by showing use of the new properties/classes (or terms with equivalent meaning) in implementations of catalogs.  This information gathering is already under way, and gathered in a temporary working document at https://docs.google.com/spreadsheets/d/10-UIgM1xLQXNsaSgU6xRsPlsYo3jABreVNwjzciGPKM/edit#gid=1108132380

Some properties are abstract and are not expected to be used as-is.

# Exit criteria:
The exit criteria will focusing on v2 new features that replicate features that were included in application profiles of v1 as a way of remedying missing and necessary elements.  The exit criteria also include recent commitments by organisations such as EC Joinup to adopt the DCAT v2 model in their work - see  https://joinup.ec.europa.eu/solution/abr-specification-registry-registries/document/specification-registry-registries-version-meeting-september

# Patent disclosures
https://www.w3.org/2004/01/pp-impl/99375/status

@davebrowning @pwin @kcoyle

**Comment by aphillips** [comment]
I18N has three open issues against this spec (dcat/957, dcat/958, and dcat/959). We will review their status in our teleconference scheduled for 2019-09-26 (tomorrow). Our issues list is located [here](https://github.com/w3c/i18n-activity/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Adcat).

**Comment by swickr** [comment]
Thanks @aphillips for noting these.  It appears that dcat/957 and dcat/958 have been resolved for now.

**Comment by swickr** [comment]
Transition approved.

1. Please add to the SoTD the CR Exit criteria and a pointer to D.2 Features at Risk .  The paragraphs from "Implementation" and "Exit criteria" in this transition request are sufficient for the CR exit criteria, though if you can commit to showing at least one producer and one consumer of each new term that will be preferable.  For the terms from ODRL and PROV, I presume the intent is to demonstrate that implementations find those terms useful in conjunction with DCAT.

2. Please clarify in D.2 what your intention is if you conclude the feature does not have adequate implemention; e.g. will you drop it from the spec or might you retain it as informative.

3. Correct the link in D.2 for Distribution odrl:hasPolicy and confirm that the other links in that section are to the right sections.

4. I suggest that the links in 6.4.18 and 6.6.7 that refer to the prov namespace URIs be updated to cite the PROV Ontology spec directly.  However, if you already had a discussion about whether to cite the ns or the Recommendation then don't change yet but I'm interested in reading the records of that discussion.


Provided there are no objections raised prior to Thursday October 3, CR transition is approved.

Noting https://github.com/w3c/dxwg/issues/959 I encourage the WG to address this during CR.

**Comment by plehegar** [comment]
@davebrowning , can you make the corrections to the editors draft?

**Comment by plehegar** [comment]
@draggett , can you take care of publishing the document this Thursday? You'll need the draft from @davebrowing and also send a draft announcement to w3t-comm

**Comment by aphillips** [comment]
@swickr Thanks. That's correct. We have only one remaining open issue against this spec (w3c/dxwg#959)

**Comment by davebrowning** [comment]
@swickr - Thank you.  And yes, the intent on ODRL and PROV is as you say.

@plehegar, @draggett  - yes, will look to get these changes done Wednesday (as early as poss...)

**Comment by davebrowning** [comment]
Just to confirm - points 1 to 4 were addressed by [w3c/dxwg#1111](https://github.com/w3c/dxwg/issues/1111) (Indeed, point 4 motivated us to review our use of such links for consistency across and we found a few others linking to the namespace - in general now, such links always go to the recommendation or to the relevant chapter of the DCAT spec where this is appropriate)
