### ISSUE TITLE
Revised CR do not need new review forms

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/transitions#17]
https://www.w3.org/Guide/transitions?profile=CR&cr=substantive asks that
> The Team Contact builds a Candidate Recommendation review form that the Project Manager reviews for correctness.

But at least for "modern" CRs, this may not be needed, since there may already be such a review form that may just need to be extended.

**Comment by plehegar** [comment]
Proposing to exclude CR update for this requirement.

**Comment by svgeesus** [comment]
Process 2018 does not require an AC WBS form for entering CR, either. Too disruptive and confusing, plus we never managed to get rid of Proposed Rec either.

**Comment by plehegar** [comment]
This got removed when Process 2018 when into effect.
