### ISSUE TITLE
[Service Workers] CR Request for Service Workers 1

### ISSUE THREAD

**Issue by ylafon** [w3c/transitions#171]
# Document title, URLs, estimated publication date
Current WD: https://www.w3.org/TR/2019/WD-service-workers-1-20190813/
Current ED: https://w3c.github.io/ServiceWorker/v1/
Proposed CR: https://raw.githack.com/w3c/ServiceWorker/master/publish/service_worker_1/CR-service-workers-20191003/index.html

# Abstract
https://raw.githack.com/w3c/ServiceWorker/master/publish/service_worker_1/CR-service-workers-20191003/index.html#abstract

# Status
https://raw.githack.com/w3c/ServiceWorker/master/publish/service_worker_1/CR-service-workers-20191003/index.html#status

# Link to group's decision to request transition
https://github.com/w3c/ServiceWorker/issues/1458

# Changes
No changes since last WD apart from clarifications - editorial notes in the document - about the status of some issues.

# Requirements satisfied
There are no requirement document per se, but the initial goals outlined in the explainer are met, see https://github.com/w3c/ServiceWorker/blob/master/explainer.md

# Dependencies met (or not)
No known dependencies that could impact or being impacted by this specification.

# Wide Review
https://lists.w3.org/Archives/Public/www-tag/2015Sep/0071.html
This led mostly to further explanations (like during i18n review), no blocking issues were raised during that review.

# Issues addressed
https://github.com/w3c/ServiceWorker/milestone/2?closed=1&open=1

# Formal Objections
None.

# Implementation
See test results on wpt.fyi
https://wpt.fyi/results/service-workers
Note that those tests are for the latest editors' draft, this CR contains only a subset of them, thus the results need to be filtered to accurately represent the state of implementations.

# Patent disclosures
https://www.w3.org/2004/01/pp-impl/101220/status

**Comment by swickr** [comment]
Is https://github.com/w3c/i18n-activity/issues/28 resolved?
What are the CR Exit Criteria

**Comment by ylafon** [comment]
The CR exit criteria are defined in the group's [charter](https://www.w3.org/2017/08/sw-charter)

> In order to advance to Proposed Recommendation, each specification is expected to have at least two independent implementations of each feature defined in the specification.

I can amend the SoTD in order to reflect that if it is clearer.

**Comment by swickr** [comment]
The CR specification should state more precisely how the WG intends to demonstrate that those implementations exist.  For example, by showing the results of test suite runs and producing an implementation report.

**Comment by r12a** [comment]
> Is w3c/i18n-activity#28 resolved?

The correct URL for that comment is now https://github.com/w3c/ServiceWorker/issues/1483

**Comment by ylafon** [comment]
After discussing with Philippe, we would like to proceed even if w3c/ServiceWorker#1483 is not yet fully resolved. The impact of a potential issue would be limited by the fact that the worst case would mean that, for example, no match happened and data will be fetched from the network instead of from the service worker. This will be clarified during CR but it is a minor modification (based also on Jake Archibald's comment, and the already existing references to URL equivalence https://url.spec.whatwg.org/#concept-url-equals for cache operations).

**Comment by swickr** [comment]
I note @aphillips ' [comment in 1843](https://github.com/w3c/ServiceWorker/issues/1483#issuecomment-554349913) as well.

**Comment by swickr** [comment]
It appears that the [environment](https://w3c.github.io/ServiceWorker/v1/#ref-for-blob-url-entry-environment) citation from FileAPI could be to the HTML spec.  You might look at that during CR.

**Comment by swickr** [comment]
Transition approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2019/CR-service-workers-1-20191119/
