### ISSUE TITLE
FPWD Request for Scalable Video Coding (SVC) Extension for WebRTC

### ISSUE THREAD

**Issue by caribouW3** [w3c/transitions#174]
# Document title, URLs, estimated publication date
Scalable Video Coding (SVC) Extension for WebRTC
W3C First Public Working Draft 15 October 2019
https://www.w3.org/TR/2019/WD-webrtc-svc-20191015/

Ed draft at 
https://w3c.github.io/webrtc-svc/

# Abstract
This document defines a set of ECMAScript APIs in WebIDL to extend the WebRTC 1.0 API to enable user agents to support scalable video coding (SVC).

# Status
The API is based on preliminary work done in the W3C ORTC Community Group.
This document was published by the Web Real-Time Communications Working Group as a First Public Working Draft. This document is intended to become a W3C Recommendation.
Comments regarding this document are welcome. Please send them to public-webrtc@w3.org (archives).

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-webrtc/2019Oct/0020.html (CfC thread)

# Information about implementations known to the Working Group
https://wpt.fyi/results/webrtc-svc?label=experimental&label=master&aligned

**Comment by caribouW3** [comment]
CfC end declared by the chair: https://lists.w3.org/Archives/Public/public-webrtc/2019Oct/0050.html

Now aiming for a publication on Thursday, 17th.

**Comment by plehegar** [comment]
Approved. Go ahead and publish.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2019/WD-webrtc-svc-20191022/
