### ISSUE TITLE
PR Request for CSS-Writing-Modes Level 3

### ISSUE THREAD

**Issue by frivoal** [w3c/transitions#176]
# Document title, URLs, estimated publication date
CSS Writing Modes Level 3
https://www.w3.org/TR/css-writing-modes-3/
October 24 2019 

# Abstract
https://www.w3.org/TR/css-writing-modes-3/#abstract

# Status
https://www.w3.org/TR/css-writing-modes-3/#status

# Link to group's decision to request transition
https://logs.csswg.org/irc.w3.org/css/2019-09-16/#e1240793

# Changes
https://www.w3.org/TR/css-writing-modes-3/#changes

# Requirements satisfied
N/A (no requirement document)

# Dependencies met (or not)
Met.
All normative dependencies fall into one of:
* stable (>=CR) W3C specs:
    - CSS-CASCADE-4 (CR)
    - CSS-DISPLAY-3 (CR)
    - CSS-MASKING-1 (CR)
    - CSS-VALUES-3 (CR)
    - CSS2 (REC)
    - CSS3-BREAK (CR)
    - CSS3-IMAGES (CR)
    - CSS3-TEXT-DECOR (CR)
    - CSS3BG (CR)
    - SVG11 (REC)
* Stable non-W3C specs:
    - HTML (LS)
    - RFC2119
    - RFC6919
    - UAX11
    - UAX24
    - UAX50
    - UAX9
    - Unicode

* Newer specs used for more up to date versions of definitions and terminology covering concepts that preexist in older more mature specs:
    - CSS-BOX-3 (WD) for properties that exist in CSS2 (REC):
    - CSS-INLINE-3 (WD) for properties and modern vocabulary describing inline text layout mechanisms that exists in CSS2 (REC):
    - CSS-OVERFLOW-3 (WD) for new terminology to discuss parts of scrollable elements, which exists in CSS2 (REC)
    - CSS-SIZING-3] (WD) for new terminology to discuss sizing mechanisms that exist since CSS2 (REC)
    - CSS3PAGE (WD) for the term "page progression direction", which refers to a concept that preexists in CSS2 (REC)

* Other reasons
    - CSS-RUBY-1 (WD), to specify types of boxes that writing-modes **do not** apply to
   - CSS-WRITING-MODES-4 (CR) mentioned only in the change section and notes for at-risk features that were dropped from Level 3
    - CSS3COL (WD) referred to only to say that the behavior is undefined

# Wide Review + Issues addressed
Disposition of Comments on last CR: https://drafts.csswg.org/css-writing-modes-3/issues-cr-2019

No open issues: https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Acss-writing-modes-3

See also previous CR Transitions (#159, #153, #45)

# Formal Objections

None.

# Implementation

Implementation Report: https://drafts.csswg.org/css-writing-modes-3/implementation-report-2019-08

# Patent disclosures
None (https://www.w3.org/2004/01/pp-impl/32061/status)

**Comment by swickr** [comment]
Transition approved.

Please consider updating the HTML5 informative reference to use the WHATWG HTML LS URI in addition to or instead of the /TR URI.

Ok to publish as early as 22 Oct.

**Comment by frivoal** [comment]
> Please consider updating the HTML5 informative reference to use the WHATWG HTML LS URI in addition to or instead of the /TR URI.

Done in the ED.

**Comment by xfq** [comment]
The link to WHATWG HTML § 14.3.5 seems to be broken.

(https://html.spec.whatwg.org/multipage/#bidi-rendering should be https://html.spec.whatwg.org/multipage/rendering.html#bidi-rendering)

**Comment by frivoal** [comment]
Wouldn't call that broken, since the link without the chapter name (rendering.html) redirects to the one with the chapter name, and I thought that was a feature, allowing them more flexibility when refactoring the spec.

Anyway, I've adjusted it to your preference.

**Comment by xfq** [comment]
Hmm, not sure why it didn't redirect when I tried it (I'm aware of the JS redirects in WHATWG HTML, and I  also tried a few times in this case). In this case, I agree that linking without the chapter name makes more sense (at least when JS is enabled).

**Comment by frivoal** [comment]
If it can fail due to JS not loading/working, I using the full path directly can make more sense. Anyway, no strong preference from me.

Latest commit is with the chapter name, the one before that is without chapter name. Publish whichever one is OK by the W3C's rules.

**Comment by xfq** [comment]
OK. Published with the chapter name: https://www.w3.org/TR/2019/PR-css-writing-modes-3-20191024/
