### ISSUE TITLE
FPWD Request for IMSC 1.2

### ISSUE THREAD

**Issue by tmichel07** [w3c/transitions#180]
# Document title, URLs, estimated publication date
**TTML Profiles for Internet Media Subtitles and Captions 1.2**

https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/496.html

estimated publication date to 2019/Nov/28

# Abstract

https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/496.html#abstract

This specification defines two profiles of [ttml2]: a text-only profile and an image-only profile. These profiles are intended to be used across subtitle and caption delivery applications worldwide, thereby simplifying interoperability, consistent rendering and conversion to other subtitling and captioning formats.

This specification improves on [ttml-imsc1.1] by supporting contemporary practices, while retaining compatibility with [ttml-imsc1.1] documents. Relative to [ttml-imsc1.1], any addition or deprecation of features are summarized at Appendix § L. Summary of substantive changes.

It is feasible to create documents that simultaneously conform to both [ttml10-sdp-us] and the text-only profile.

The specification defines extensions to [ttml2], as well as incorporates extensions specified in [SMPTE2052-1] and [EBU-TT-D].

Both profiles are based on [SUBM].

# Status

https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/496.html#sotd

This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

This document was published by the Timed Text Working Group as a First Public Working Draft. This document is intended to become a W3C Recommendation.

GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-tt@w3.org (archives) with [imsc] at the start of your email's subject .

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 1 March 2019 W3C Process Document.

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
Concluded to go FPWD during 2019/Oct/10 call.
https://www.w3.org/2019/10/10-tt-minutes.html

# Information about implementations known to the Working Group
N/A

**Comment by himorin** [comment]
please hold on a bit, WG is about to conclude CfC to publish FPWD

**Comment by tmichel07** [comment]
My understanding is that the CfC started on October 10th as decided during the TTWG telecon on that day. The CfC is 10 working days. So it ended on Oct 25th. Therefore I have Request Transition on the 26th as there was no comments received during CFC to my knowledge.
But I do agree with you that this is fast, but I was required by PLH and PH to Request Transition. 
I also agree with you wee should put it on Hold for a few days .
Philippe Could you please put this TRansition Request on hold until we have a clear Green light from the TTWG and Chair, as suggested by Atsushi. Thanks

**Comment by himorin** [comment]
updated. and added 'Awaiting Director'
CfC ended without any comment/objection after issued during weekly WG call.

**Comment by plehegar** [comment]
(pending charter approval)

**Comment by plehegar** [comment]
To be clear: Approved as soon as the charter gets approved by the Director (scheduled for November 27)

**Comment by plehegar** [comment]
done
 https://www.w3.org/TR/2019/WD-ttml-imsc1.2-20191128/
