### ISSUE TITLE
FPWD Request for TTML Live Extensions Module v1

### ISSUE THREAD

**Issue by tmichel07** [w3c/transitions#181]
# Document title, URLs, estimated publication date
**TTML Live Extensions Module v1**

https://www.w3.org/TR/2019/WD-tt-live-1-20191107/
Latest published version:
https://www.w3.org/TR/tt-live-1/

Estimation date 07 Nov 2019

# Abstract
This specification defines constraints and extensions to TTML to support the contribution of real time streams of content, primarily subtitles and captions, from an authoring or playout system via a controlled network to an encoder whose output is intended for wider distribution. It also defines a system model including nodes, sequences and streams useful for modelling such systems. The primary use case is the transfer of live subtitles and captions within a broadcast or media preparation environment.

This document is derived from the [EBU-TT-Live-1-0] where some informative information has been removed, and the normative requirements have been re-based on [TTML1] where in the original they were based on the [EBU-TT-1-2] profile of TTML1.

The extensions and constraints defined in this specification are usable with both [TTML1] and [TTML2]. No constraints added to [TTML2] invalidate the extensions and constraints specified herein.

No requirement is presented here for any subtitle presentation device used by an audience member to behave differently in the presence of live subtitles compared to prepared subtitles: rather, it is envisaged that any processing required to manage the two cases, and the transitions between them, occurs in the broadcaster domain. However the use of SMPTE time code is not supported.

These extensions are based on [EBU-TT-Live-1-0] developed by EBU and benefit from technical consensus and implementation experience gathered there.

# Status
This document was published by the Timed Text Working Group as a First Public Working Draft. This document is intended to become a W3C Recommendation.

GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-tt@w3.org (archives) with [tt-live-1] at the start of your email's subject .
Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.
This document is governed by the 1 March 2019 W3C Process Document.

# Is it a delta specification intended to become a W3C Recommendation?
not a delta spec. But a spec to become a W3C Recommendation

# Link to group's decision to request transition
https://www.w3.org/2019/09/18-tt-minutes.html#x14

The resolution during this TTWG F2F meeting sept 18th was
"RESOLVED: go to FPWD for the Live extension module and the carriage mechanism after resolving current open issues"

There are 4 open issues from Glenn on sep 19th for editorial updates. 
These updates seem to be pending, and not yet incorporated in the current version dated September 3rd
https://github.com/w3c/tt-module-live/issues

These need to be resolved before publication.

# Information about implementations known to the Working Group

**Comment by tmichel07** [comment]
The draft is currently available at
https://w3c.github.io/tt-module-live/tt-live-1/spec/tt-live.html
It will be moved to final destination once finalized.

**Comment by tmichel07** [comment]
NOTE: You and P. Hoschka have requested to me to Request Transition for this FPWD.
As there are pending issues and the document is not yet finalized, I suggest to defer this Transition Request until:
- The issue are resolved
- The document is updated and finalized
- the CfC  of 10 working days per our Decison Policy is done

**Comment by himorin** [comment]
please hold on, WG is finishing a draft for FPWD

**Comment by tmichel07** [comment]
I fully agree with you Atsushi that this Request for Transition is too eralier, according to our Decision Policy for CfC and because the TTML Live Extensions Module draft is not yet finalize. This was indeed my above comment.
Therefore as Atsushi recommended, Philippe could you please put this Transition Request on hold until we have the publication Green light from the TTWG and from the Chair
