### ISSUE TITLE
FPWD Request for Decentralized Identifiers (DIDs) v1.0

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#184]
# Document title, URLs, estimated publication date

- Title: Decentralized Identifiers (DIDs) v1.0
- URL: https://w3c.github.io/did-core/FPWD/2019-11-07/
- Short name: did-core
- Estimated publication late: Thursday, 7 November, 2019

# Abstract

See: https://w3c.github.io/did-core/FPWD/2019-11-07/#abstract

# Status

See: https://w3c.github.io/did-core/FPWD/2019-11-07/#sotd

# Is it a delta specification intended to become a W3C Recommendation?

No

# Link to group's decision to request transition

See: https://www.w3.org/2019/did-wg/Meetings/Minutes/2019-10-29-did#resolution1

# Information about implementations known to the Working Group

There is a registry of provisional implementations based on the precursor document, namely the CG report that was used as an input for the current draft: https://w3c-ccg.github.io/did-method-registry/#the-registry

@burnburn @brentzundel @msporny @talltree @peacekeeper

**Comment by plehegar** [comment]
approved

**Comment by iherman** [comment]
Thanks @plehegar  

What is the protocol for closing the issue? Should I do it when the publication is out, or is it done automatically?

**Comment by plehegar** [comment]
when the publication is out.
and it's not automatic.

https://www.w3.org/TR/2019/WD-did-core-20191113/

**Comment by iherman** [comment]
Thanks @plehegar I will think of it next time!

**Comment by plehegar** [comment]
welcome. don't worry about cleaning up issues, I'm happy to do the clean-ups.
