### ISSUE TITLE
PR Request for Data Catalog Vocabulary (DCAT) - Version 2

### ISSUE THREAD

**Issue by pwin** [w3c/transitions#185]
Previous transition at
 https://github.com/w3c/transitions/issues/169

# Document title, URLs, estimated publication date

Data Catalog Vocabulary (DCAT) - Version 2

current ED : https://w3c.github.io/dxwg/dcat/
current CR : https://www.w3.org/TR/vocab-dcat-2
Proposed: https://w3c.github.io/dxwg/dcat/?specStatus=PR;crEnd=2019-10-31;prEnd=2019-12-12;publishDate=2019-11-14

# Abstract

https://www.w3.org/TR/vocab-dcat-2/#abstract

# Status

https://w3c.github.io/dxwg/dcat/?specStatus=PR;crEnd=2019-10-31;prEnd=2019-12-12;publishDate=2019-11-14#sotd

# Link to group's decision to request transition
https://www.w3.org/2002/09/wbs/99375/dcat-to-pr/results
https://www.w3.org/2019/11/05-dxwg-minutes.html

# Changes since CR

Diff:
https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fvocab-dcat-2%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fdxwg%2Fdcat%2F%3FspecStatus%3DPR%3BshortName%3Dvocab-dcat-2

Minor editorial changes have been made:
 - [PR 1125](https://github.com/w3c/dxwg/pull/1125) has updated the owl version in dcat.ttl;
 - [PR 1127](https://github.com/w3c/dxwg/pull/1127) has uniformed the use of blanks and punctuation in the literals included in dcat.ttl;
 - [PR 1135]([https://github.com/w3c/dxwg/pull/1135](https://github.com/w3c/dxwg/pull/1135)) has fixed coordinate order in ga-courts example;
 - [PR 1136](https://github.com/w3c/dxwg/pull/1136) has inserted a note in section DCAT History to clarify that DCAT 2 maintains the DCAT namespace as it preserves backward compatibility with DCAT;
 - [PR 1140](https://github.com/w3c/dxwg/pull/1140) has revised some class descriptions. It has removed descriptions of dcat:accessRights and dct:license for dcat:DataServices. These descriptions were redundant as they are already provided in the class dcat:Resource from which the two properties are inherited;
- [PR 1142](https://github.com/w3c/dxwg/pull/1142) has updated the acknowledgements;
 - [PR 1141](https://github.com/w3c/dxwg/pull/1141) and [PR 1143](https://github.com/w3c/dxwg/pull/1143) have updated the link to implementation report;

# Requirements satisfied

No changes since previous transition

# Dependencies met (or not)

No changes since previous transition

# Wide Review

There was some discussion about the use of "conforms to" (see https://github.com/w3c/dxwg/issues/1130 ) and this has been carried forward into future work that will perhaps be undertaken in a DCAT Primer document.

See also implementation report

# Issues addressed

Closed issues:
https://github.com/w3c/dxwg/issues?q=is%3Aissue+label%3Adcat+is%3Aclosed

Open issues:
https://github.com/w3c/dxwg/issues?q=is%3Aissue+label%3Adcat+is%3Aopen

No further issues will be addressed for DCAT version 2, but there are issues being held for future work - https://github.com/w3c/dxwg/labels/future-work

# Formal Objections

None

# Implementation
https://w3c.github.io/dxwg/dcat-implementation-report/

Please note that the proposed updates to European Union and Member State application profiles of DCAT and the incorporation of DCAT v2 into other developing standards such as the registry of base registrys (ABR standard) are committments that will only be ratified if the DCAT v2 concludes successfully the W3C Rec Track.

# Patent disclosures

No changes since previous transition

https://www.w3.org/2004/01/pp-impl/99375/status

**Comment by swickr** [comment]
[Appendix D.2](https://w3c.github.io/dxwg/dcat/?specStatus=PR;crEnd=2019-10-31;prEnd=2019-12-12;publishDate=2019-11-14#features-at-risk) of the draft Proposed Recommendation continues to use the At Risk text of the Candidate Recommendation.  As [the CR commitment](https://www.w3.org/TR/vocab-dcat-2/#features-at-risk) was to move those features to Informative status should they fail to "show adequate adoption", and the (implicit) expectation is that "adequate" is two implementations either existing or planned, it appears that several of those features now should have Informative status.

Please clarify what the WG believes are the status of each of those At Risk features.

**Comment by pwin** [comment]
No feature at risk got dropped. The Features At Risk section will be
removed before publication

**Comment by swickr** [comment]
Transition approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2019/PR-vocab-dcat-2-20191119/

**Comment by plehegar** [comment]
The document was published with the **wrong license**:
 https://lists.w3.org/Archives/Public/public-dxwg-wg/2019Dec/0074.html
