### ISSUE TITLE
PR Request for Trace Context

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#186]
# Document title, URLs, estimated publication date
  Trace Context
  W3C Proposed Recommendation 21 November 2019
  https://w3c.github.io/trace-context/?specStatus=PR;crEnd=2019-09-09;prEnd=2020-01-10;publishDate=2019-11-21
  https://www.w3.org/TR/trace-context/

# Abstract
 https://w3c.github.io/trace-context/?specStatus=PR;crEnd=2019-09-09;prEnd=2019-12-21;publishDate=2019-11-21#abstract

# Status

[[
This document was published by the Distributed Tracing Working Group as a Proposed Recommendation. This document is intended to become a W3C Recommendation.

It satisfies Distributed Tracing working group technical requirements. There are a few implementations of this specification available. We are gathering implementation experience and usage feedback. We recommend the wide deployment and use of this recommendation.

GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-trace-context@w3.org (archives) with trace-context at the start of your email's subject .

The W3C Membership and other interested parties are invited to review the document and send comments to public-trace-context@w3.org (subscribe, archives) through 10 January 2020. Advisory Committee Representatives should consult their WBS questionnaires. Note that substantive technical comments were expected during the Candidate Recommendation review period that ended 09 September 2019.

Please see the Working Group's implementation report.

Publication as a Proposed Recommendation does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress. 
]]

# Previous transition
  https://github.com/w3c/transitions/issues/156

# Link to group's decision to request transition
  https://github.com/w3c/trace-context/issues/336

# Changes
  - considerations for trace-id field field generation
  - clarifications on multiple tracestate headers fields and its propogation
  - clarifications on traceparent processing

None of the changes are considered to be substantive.

Diff: https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Ftrace-context%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Ftrace-context%2F%253FspecStatus%253DPR

# Requirements satisfied

No changes

# Dependencies met (or not)

No change

# Wide Review

We received clarification requests from various implementers.

https://github.com/w3c/trace-context/issues?q=is%3Aissue+is%3Aclosed

# Issues addressed

https://github.com/w3c/trace-context/issues?q=is%3Aissue+is%3Aclosed

Open issues:
  https://github.com/w3c/trace-context/issues?q=is%3Aopen+is%3Aissue
 Remaining issues will be addressed through future revisions

# Formal Objections

 None

# Implementation

https://github.com/w3c/trace-context/#reference-implementations

See also notes from today's meeting:
 https://docs.google.com/document/d/1Gr9QD6kt3_DcxRJSFpuoqWWMAJMRqCGd1kPcroNUyh8/edit#

We expect further adoption/deployment once the spec is final.

# Patent disclosures

None
https://www.w3.org/2004/01/pp-impl/108594/status

cc  @mtwo @SergeyKanzhelev @danielkhan

**Comment by swickr** [comment]
Transition approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2019/PR-trace-context-1-20191121/
