### ISSUE TITLE
[DID WG] FPWD Request for Use Cases and Requirements for Decentralized Identifiers

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#188]
# Document title, URLs, estimated publication date

Title: Use Cases and Requirements for Decentralized Identifiers
Estimated publication date: 2019-11-28

# Abstract

See https://w3c.github.io/did-use-cases/?specStatus=FPWD#abstract

# Status

See https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/did-use-cases/?specStatus=FPWD#sotd

# Is it a delta specification intended to become a W3C Recommendation?

No, it is a FPWD for a WG Note

# Link to group's decision to request transition

https://www.w3.org/2019/did-wg/Meetings/Minutes/2019-11-19-did#resolution1

# Information about implementations known to the Working Group

n/a

---

cc: @burnburn @brentzundel @jandrieu @philarcher

**Comment by plehegar** [comment]
Approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2019/WD-did-use-cases-20191128/
