### ISSUE TITLE
CR Request for sensor APIs

### ISSUE THREAD

**Issue by xfq** [w3c/transitions#189]
# Document title, URLs, estimated publication date

* Generic Sensor API - https://xfq.github.io/testing/generic-sensor-CR/Overview.html
* Accelerometer - https://xfq.github.io/testing/accelerometer-CR/Overview.html
* Gyroscope - https://xfq.github.io/testing/gyroscope-CR/Overview.html
* Orientation Sensor - https://xfq.github.io/testing/orientation-sensor-CR/Overview.html

# Abstract

* Generic Sensor API: https://xfq.github.io/testing/generic-sensor-CR/Overview.html#abstract
* Accelerometer: https://xfq.github.io/testing/accelerometer-CR/Overview.html#abstract
* Gyroscope: https://xfq.github.io/testing/gyroscope-CR/Overview.html#abstract
* Orientation Sensor: https://xfq.github.io/testing/orientation-sensor-CR/Overview.html#abstract

# Status

* Generic Sensor API - https://xfq.github.io/testing/generic-sensor-CR/Overview.html#sotd
* Accelerometer - https://xfq.github.io/testing/accelerometer-CR/Overview.html#sotd
* Gyroscope - https://xfq.github.io/testing/gyroscope-CR/Overview.html#sotd
* Orientation Sensor - https://xfq.github.io/testing/orientation-sensor-CR/Overview.html#sotd

The CR exit criterion is two interoperable deployed implementations of each feature.

# Link to group's decision to request transition

https://www.w3.org/2019/09/19-dap-minutes.html#x06

# Changes

The only substantial change since the last CR is the the addition of WebDriver extensions:

* Generic Sensor API: https://xfq.github.io/testing/generic-sensor-CR/Overview.html#automation
* Accelerometer: https://xfq.github.io/testing/accelerometer-CR/Overview.html#automation
* Gyroscope: https://xfq.github.io/testing/gyroscope-CR/Overview.html#automation
* Orientation Sensor: https://xfq.github.io/testing/orientation-sensor-CR/Overview.html#automation

# Requirements satisfied

The specifications meet the requirements set forth in the DAS WG Charter and satisfy [Sensor Use Cases](https://w3c.github.io/sensors/usecases) as demonstrated in [Motion Sensors Explainer](https://w3c.github.io/motion-sensors/).

# Dependencies met (or not)

New normative references since the last CR:

* Generic Sensor API: `[ACCELEROMETER]` `[AMBIENT-LIGHT]` `[GEOLOCATION-SENSOR]` `[GYROSCOPE]` `[MAGNETOMETER]` `[MAGNETOMETER]` `[WebDriver]`
* Accelerometer: none
* Gyroscope: none
* Orientation Sensor: none

# Wide Review

The specifications have received wide review: https://github.com/w3c/sensors/issues/299

# Issues addressed

No open issue for this version ("Level 1").

# Formal Objections

None.

# Implementation

Preliminary implementation reports:

* Generic Sensor API: n/a (an abstract base class)
* Accelerometer: https://wpt.fyi/accelerometer
* Gyroscope: https://wpt.fyi/gyroscope
* Orientation Sensor: https://wpt.fyi/orientation-sensor

# Patent disclosures

https://www.w3.org/2004/01/pp-impl/43696/status

None.

-----

/cc @anssiko @reillyeon

**Comment by swickr** [comment]
References to "since last CR" are actually "since last WD"; i.e. this request is indeed to enter CR.

**Comment by swickr** [comment]
@plehegar Please confirm with @snyderp whether [396](https://github.com/w3c/sensors/issues/396) and [397](https://github.com/w3c/sensors/issues/396) have been closed.

Please update all the normative references to cite /TR versions of W3C documents.  See, e.g., [SpecRef](https://www.specref.org/?q=hr-time) and the [W3C Manual of Style](https://w3c.github.io/manual-of-style/#ref-section)

**Comment by snyderp** [comment]
https://github.com/w3c/sensors/issues/396 is addresed, https://github.com/w3c/sensors/issues/397 is ongoing

**Comment by xfq** [comment]
> References to "since last CR" are actually "since last WD"; i.e. this request is indeed to enter CR.

Sorry about the lack of clarity.

I chose the [last CR](https://www.w3.org/TR/2018/CR-generic-sensor-20180320/) (instead of [last WD](https://www.w3.org/TR/2019/WD-generic-sensor-20190307/)) as the reference because the to-be-published CR is mostly the same as the WD.

**Comment by plehegar** [comment]
@anssiko @xfq  : waiting on https://github.com/w3c/sensors/issues/397 to settle

**Comment by plehegar** [comment]
unless I'm mistaken, this is ready to be looked by the Director again

**Comment by anssiko** [comment]
Once we have integrated https://github.com/w3c/sensors/issues/401 we have a publication-ready specification. We have consensus to land it, just pending sign-off from @xfq to ensure the PR complies with publication checkers.

**Comment by plehegar** [comment]
thanks. we won't look at it before tomorrow in any case.

**Comment by xfq** [comment]
I have merged https://github.com/w3c/sensors/pull/401 and updated the documents.

**Comment by swickr** [comment]
Please see https://github.com/w3c/sensors/issues/397#issuecomment-562733289

**Comment by swickr** [comment]
Transition approved after https://github.com/w3c/sensors/pull/402 is merged.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2019/CR-generic-sensor-20191212/
https://www.w3.org/TR/2019/CR-gyroscope-20191212/
https://www.w3.org/TR/2019/CR-accelerometer-20191212/
https://www.w3.org/TR/2019/CR-orientation-sensor-20191212/
