### ISSUE TITLE
[CSSWG] Publish Writing Modes L3 as CR / Writing Modes L4 as FPWD

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#19]
Summary:
  CSSWG wants to publish Writing Modes L3 as CR and Writing Modes L4 as FPWD (simultaneously).

[ Insert transition request FAQ / links to resolutions / DoC here ]

**Comment by plehegar** [comment]
CR got approved
 https://lists.w3.org/Archives/Member/chairs/2017OctDec/0142.html

**Comment by svgeesus** [comment]
Waiting since 21 November for editors answer to
https://lists.w3.org/Archives/Member/w3c-css-wg/2017OctDec/0133.html

**Comment by fantasai** [comment]
Fixed table markup error. Cannot duplicate duplicate-ID error by regenerating locally. Sent copies of locally-generated files over.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2017/CR-css-writing-modes-3-20171207/

**Comment by plehegar** [comment]
https://www.w3.org/TR/2017/WD-css-writing-modes-4-20171207/
