### ISSUE TITLE
[Publishing WG] CR Transition request for publication manifest and audiobooks

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#190]
## Document title, URLs, estimated publication date
- Publication Manifest
    - Editor's draft: https://w3c.github.io/pub-manifest/?specStatus=CR&publishDate=2019-12-05
    - Expected publication date: 2019-12-05
- Audiobooks
    - Editor's draft: https://w3c.github.io/audiobooks/?specStatus=CR&publishDate=2019-12-05
    - Expected publication date: 2019-12-05

## Abstract
- Publication Manifest: https://w3c.github.io/pub-manifest/?specStatus=CR&publishDate=2019-12-05#abstract
- Audiobooks: https://w3c.github.io/audiobooks/?specStatus=CR&publishDate=2019-12-05#abstract

## Status
- Publication Manifest: https://w3c.github.io/pub-manifest/?specStatus=CR&publishDate=2019-12-05#sotd
- Audiobooks: https://w3c.github.io/audiobooks/?specStatus=CR&publishDate=2019-12-05#sotd

## Link to the group's decision to request transition

Resolution at[1], based on a CfC by email, started at [2] 

1. https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-11-18-pwg.html#resolution3
2. https://lists.w3.org/Archives/Public/public-publ-wg/2019Nov/0009.html

## Changes
Major changes to Publication Manifest since FPWD include:

- removal of the "canonical manifest" as a json-ld representation, with focus now on the "internal representation" (emphasize that the internal representation can be in any language);
- addition/use of `language` and `direction` keywords in the JSON-LD context for expressing the global language and direction of manifest text (also for local overrides) - `inLanguage` now only identifies the language(s) of the content;
- clarifications to how the base URL for the manifest is obtained;
- a significant rewrite of the manifest processing algorithm to use the Infra specification language and data types;
- moved the WebIDL representation of the internal representation to an informative appendix, as it is a representation of the final data not a requirement to produce;
- addition of the `alternate` property to provide alternative media representations of resources;
- addition of the required `conformsTo` property to identify the profile a manifest conforms to;

A list of all changes to Publication Manifest since FPWD is available at: https://github.com/w3c/pub-manifest/commits/master

## Requirements Satisfied

The Publication Manifest specification partially meets the original objective of defining Web Publications. Work on Web Publications was suspended due to a lack of interest at this time from publishers, plus significant differences of opinion in terms of how they are expected to function on the web and in browsers. The group generally agreed on the manifest format for expressing information about publications, however, so driving Publication Manifest forward puts a stake in the ground for returning to Web Publications while also enabling the creation of other formats for which there is more interest (audiobooks). Defining a common manifest format also aids in future interoperability, which was another goal of Web Publications. The Publication Manifest format is also largely translatable to and from the EPUB 3 Package Document, so this provides a potential future pathway for the next iteration of EPUB. 

See also the [use case review](https://github.com/w3c/publ-wg/wiki/Publication-Manifest-Use-Case-Requirements-Review) for how the Publication Manifest specification matches up to the original requirements for Web Publications.

## Dependencies Met
JSON-LD 1.1 (on the `@direction` keyword usage). The latest JSON-LD 1.1 document (to be in CR soon) introduces this feature and the Publication Manifest depends on it.

## Wide Review

Practically all the work happened on GitHub, see the separate section on issues below. This included comments from outside of the Working Group.

### Horizontal Reviews

* TAG Review
    * Tag request: https://github.com/w3ctag/design-reviews/issues/344
    * Although it was never formally closed by the TAG, the issues raised during the discussions (mostly around the usage of WebIDL) were taken care of in the final version (essentially: the algorithms and terminology have been reshaped following the WHATWG Infra standard, and the WebIDL specification is just an illustrative, non-normative appendix, not used in the spec part)
* I18N Horizontal review
    * self review: https://github.com/w3c/pub-manifest/issues/38
    * closure: https://github.com/w3c/pub-manifest/issues/38#issuecomment-539143527
* A11y Horizontal review
    * APA review request: https://lists.w3.org/Archives/Public/public-apa/2019Aug/0078.html
    * closure: https://lists.w3.org/Archives/Public/public-apa/2019Oct/0023.html
* PING Review
    * self review: https://github.com/w3c/pub-manifest/issues/61
    * closure: https://lists.w3.org/Archives/Group/group-publ-wg-chairs/2019Oct/0020.html

## Issues Addressed
- Publication Manifest:
   - Open issues minus editorial or postponed: https://tinyurl.com/y38cxuhv
   - Same as above, but including closed issues: https://tinyurl.com/y378byy6
   
    Note: the Publication Manifest document was originally developed within a larger framework called "Web Publications". That line of work has been paused, but the manifest part of the document was re-used as the starting basis for Publication Manifest. The issues for Web Publications listed below are only for completeness, because they (partially) contributed to the development of the Publication Manifest (the relevant open issues were transferred to the pub-manifest repository):
   - Open issues minus editorial or postponed: https://tinyurl.com/yygspsdm
   - Same as above, but including closed issues: https://tinyurl.com/y2ohwaqm

- Audiobooks:
   - Open issues minus editorial, deferred, or transferred to best practices: https://tinyurl.com/y67bemer
   - Same as above, but including closed issues: https://tinyurl.com/yxfp7yz3

## Formal Objections
None.

### Testing Strategy for Publication Manifest and Audiobooks
Interested implementers for Publication Manifest and Audiobooks will be provided with a test suite using the Web Platform tests model. These specifications will be testing all MUST and SHOULD statements, and for Audiobooks, there will be additional manual User Agent Behavior tests. The Working Group will provide details for implementers on how to run the tests and assistance with any issues encountered. Implementers should log issues against the Github projects for visibility.

As Publication Manifest is largely a vocabulary of terms, a comparison of the vocabulary to the structures and metadata of the EPUB 3 Package Document will also be carried out. This comparison is intended to show that there is already real-world precedent in publishing for the information included in the manifest, and a pathway for translating EPUB content (and vice versa).

Additionally, implementations will need to show that they are capable of ingesting and transforming a manifest into an internal representation using the algorithm defined in the Publication Manifest document. These transforms ensure that any authoring conveniences used in the authored manifest are normalized and sanitized, and result in a predictable data structure.

### Exit Criteria
Publication Manifest and Audiobooks must have at least 2 passing tests for each feature in the specifications. For the Audiobooks User Agent Behaviors tests, all implementations should meet all of the behavior requirements that are applicable to them. 

### Potential Implementations

The following institutions have already expressed their interest in implementing an audiobook reader: Colibrio, EDRLab, Rakuten/Kobo, Google, Blackstone Publishing. Two out of those (Colibrio and EDRLab) already have a running prototype.

There are also two experimental implementations (one in [javascript](https://github.com/w3c/pub-manifest/tree/master/experiments/manifest-to-internal-processor) and the other in [typescript](https://github.com/iherman/PubManifest)) that have been used to "test" the specification. 

## Patent Disclosures
See https://www.w3.org/2004/01/pp-impl/100074/status

---

Cc @GarthConboy @mattgarrish @TzviyaSiegman @wareid

**Comment by swickr** [comment]
Transition approved.

I encourage the following editorial fixes prior to publication:

The citation in [bibo] times out; please check that URI and consider whether there is a better URI.

In [Manifest 4.2.5](https://w3c.github.io/pub-manifest/?specStatus=CR&publishDate=2019-12-05#value-url) there is a reference to a "note in the HTML5 spec", however the current HTML5 spec does not include that note.  Fine to simply drop the sentence.

In [Manifest 4.8.1.1](https://w3c.github.io/pub-manifest/?specStatus=CR&publishDate=2019-12-05#cover) there is a reference to WCAG 1.0 that looks it could just as well
be to WCAG 2.1 thereby eliminating the reference to the older WCAG spec.

**Comment by mattgarrish** [comment]
Thanks @swickr!

I've opened a [pull request](https://github.com/w3c/pub-manifest/pull/170) with the changes you've noted (I think that entire note can go).

I've also [updated the specref database](https://github.com/tobie/specref/pull/570) to get the bibo domain updated.

**Comment by plehegar** [comment]
one more nit:
[[
Consider using HTML and DOM LS

Update those links.

Found 16 references in this category

    https://www.w3.org/TR/html/dom.html
    https://www.w3.org/TR/html/editing.html
    https://www.w3.org/TR/html/grouping-content.html
    https://www.w3.org/TR/html/infrastructure.html
    https://www.w3.org/TR/html/sections.html
    https://www.w3.org/TR/html/textlevel-semantics.html
    https://www.w3.org/TR/html5/semantics-scripting.html
]]
https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fw3c.github.io%2Fpub-manifest%2F%3FspecStatus%3DCR%26publishDate%3D2019-12-05

**Comment by plehegar** [comment]
To be clear: we would like those links to be directly to the WHAT HTML LS (per WHATWG/W3C MOU)

**Comment by mattgarrish** [comment]
Sure, no problem. I'll get those fixed asap.

**Comment by iherman** [comment]
Published on 2019-12-05. Closing.
