### ISSUE TITLE
[Publishing WG] FPNote for Lightweight Packaging Format

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#191]
# Document title, URLs, estimated publication date

- Title: Lightweight Packaging Format (LPF)
- Editors draft: https://w3c.github.io/lpf/?specStatus=WG-NOTE&publishDate=2019-12-05
- Short name: lpf
- Estimated publication date: 2019-12-05

Note: the publication date should be synchronized with the publication of the CR for Publication Manifest and Audiobooks (subject to a separate transition request, issue https://github.com/w3c/transitions/issues/190)

# Abstract

See: https://w3c.github.io/lpf/?specStatus=WG-NOTE&publishDate=2019-12-05#abstract

# Status

See: https://w3c.github.io/lpf/?specStatus=WG-NOTE&publishDate=2019-12-05#sotd

# Is it a delta specification intended to become a W3C Recommendation?

No. It is to be published as a Working Group Note

# Link to group's decision to request transition

Resolution at[1], based on a CfC by email, started at [2]

1. https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-11-18-pwg.html#resolution2
2. https://lists.w3.org/Archives/Public/public-publ-wg/2019Nov/0009.html

# Information about implementations known to the Working Group

Planned implementations for the Publication Manifest and Audiobooks will probably implement this as well. See https://github.com/w3c/transitions/issues/190 for further details.

---

@llemeurfr @GarthConboy @wareid @TzviyaSiegman

**Comment by plehegar** [comment]
Approved. Please feel the form at IANA to request media type (either as final or provisional)

**Comment by iherman** [comment]
Published 2019-12-05
