### ISSUE TITLE
[JSON-LD WG]  CR Request for json ld11, json ld11 api, and json ld11 framing

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#194]
# Document title, URLs, estimated publication date
- JSON-LD 1.1
    - Editor's draft: https://w3c.github.io/json-ld-syntax/?specStatus=CR&publishDate=2019-12-10
    - Expected publication date: 2019-12-10
- JSON-LD 1.1 Processing Algorithms and API
    - Editor's draft: https://w3c.github.io/json-ld-api/?specStatus=CR&publishDate=2019-12-10
    - Expected publication date: 2019-12-10
- JSON-LD 1.1 Framing
    - Editor's draft: https://w3c.github.io/json-ld-framing/?specStatus=CR&publishDate=2019-12-10
    - Expected publication date: 2019-12-10

# Abstract
- JSON-LD 1.1: https://w3c.github.io/json-ld-syntax/?specStatus=CR&publishDate=2019-12-10#abstract
- JSON-LD 1.1 Processing Algorithms and API: https://w3c.github.io/json-ld-api/?specStatus=CR&publishDate=2019-12-10#abstract
- JSON-LD 1.1 Framing: https://w3c.github.io/json-ld-framing/?specStatus=CR&publishDate=2019-12-10#abstract

# Status
- JSON-LD 1.1: https://w3c.github.io/json-ld-syntax/?specStatus=CR&publishDate=2019-12-10#sotd
- JSON-LD 1.1 Processing Algorithms and API: https://w3c.github.io/json-ld-api/?specStatus=CR&publishDate=2019-12-10#sotd
- JSON-LD 1.1 Framing: https://w3c.github.io/json-ld-framing/?specStatus=CR&publishDate=2019-12-10#sotd

# Link to group's decision to request transition

- WG resolution on call: https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-11-22-json-ld#resolution2
- Based on CfC: https://lists.w3.org/Archives/Public/public-json-ld-wg/2019Nov/0017.html

# Changes

- Changes to JSON-LD Syntax [since 1.0](https://w3c.github.io/json-ld-syntax/#changes-from-10) and [since the CG final report](https://w3c.github.io/json-ld-syntax/#changes-from-cg). The exact changes in the text can also be highlighted (not done by default, but can be chosen by the reader using a button).
- Changes to JSON-LD API [since 1.0](https://w3c.github.io/json-ld-api/#changes-since-1-0-recommendation-of-16-january-2014) and [since the CG final report](https://w3c.github.io/json-ld-api/#changes-from-cg)
- Changes to JSON-LD Framing [since 1.0 draft](https://w3c.github.io/json-ld-framing/#changes-since-1-0-draft-of-30-august-2012) and [since the CG final report](https://w3c.github.io/json-ld-framing/#changes-from-cg)

# Requirements satisfied

We have tracked our requirements in Github using issues. 

- JSON-LD 1.1
  - Total: 179 issues, mostly editorial change tracking.
  - [21 Satisfied Requirements](https://github.com/w3c/json-ld-syntax/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Asatisfied)
  - [19 Rejected](https://github.com/w3c/json-ld-syntax/issues?q=is%3Aissue+sort%3Acreated-asc+label%3Aspec%3Awontfix) - These issues were invalid, out of scope for the work, or proposals that were discussed and rejected.
  - [3 Deferred for Future Work](https://github.com/w3c/json-ld-syntax/issues?q=is%3Aissue+sort%3Acreated-asc+defer+label%3Adefer-future-version)

- JSON-LD 1.1 API
  - Total: 71 Issues, mostly editorial change tracking
  - [12 Satisfied Requirements](https://github.com/w3c/json-ld-api/issues?q=is%3Aissue+is%3Aclosed+sort%3Acreated-asc+label%3Asatisfied)
  - [4 Won't Fix](https://github.com/w3c/json-ld-api/issues?q=is%3Aissue+sort%3Acreated-asc+label%3Awontfix)
  - [3 Deferred for Future Work](https://github.com/w3c/json-ld-api/issues?q=is%3Aissue+is%3Aopen+label%3Adefer-future-version)

- JSON-LD 1.1 Framing
  - Total: 30 issues, as always mostly editorial and questions
  - [9 Satisfied Requirements](https://github.com/w3c/json-ld-framing/issues?q=is%3Aissue+is%3Aclosed+sort%3Acreated-asc+label%3Asatisfied)
  - [2 Won't Fix](https://github.com/w3c/json-ld-framing/issues?q=is%3Aissue+is%3Aclosed+sort%3Acreated-asc+label%3Aspec%3Awontfix)
  - [3 Deferred for Future Work](https://github.com/w3c/json-ld-framing/issues?q=is%3Aissue+is%3Aopen+label%3Adefer-future-version)
 

# Dependencies met (or not)
None.

# Wide Review
All reviews, comments, etc, were tracked in Github issues, see below

# Issues addressed
- JSON-LD 1.1
   - Open issues minus editorial, deferred, or transferred to best practices: https://tinyurl.com/yyys74xg
   - Same as above, but included closed issues: https://tinyurl.com/y5tgxj2u
- JSON-LD 1.1 Processing Algorithms and API
   - Open issues minus editorial, deferred, or transferred to best practices: https://tinyurl.com/y67bemer
   - Same as above, but included closed issues: https://tinyurl.com/y3hssblp
- JSON-LD 1.1 Framing
   - Open issues minus editorial, deferred, or transferred to best practices: https://tinyurl.com/y32fltkb
   - Same as above, but included closed issues: https://tinyurl.com/y6djf6dt

# Formal Objections
None.

# Implementation

There is a (draft) [implementation report](https://w3c.github.io/json-ld-api/reports/) with pointers to all the tests (and instructions on how to submit implementation reports). Tests prepared for each feature of JSON-LD (some tests are covering more than one); see also the separate [test documentation](https://w3c.github.io/json-ld-api/tests/manifest). 

The exit criteria is that each feature (i.e., each test) must be passed by at least two, independent implementations. The WG intends to leave the CR duration open for a minimum of 3 months after the publication of the CR.

At the moment, members of the Working Groups are actively involved in different implementations in Ruby, Javascript, Python, and TypeScript (the latter is a streaming JSON-LD parser). The WG expects all four of them to submit test results. We also have contacts with an implementer active with a Java implementations. The group is also actively reaching out to implementers to find implementations in C/C++ and possibly Rust. 

Note that the test suite and the implementation aim to cover the _full_ JSON-LD 1.1, i.e., including the JSON-LD 1.0 features.

# Patent disclosures

See https://www.w3.org/2004/01/pp-impl/107714/status

---

@gkellogg @pchampin @dlongley @BigBlueHat @azaroth42

**Comment by plehegar** [comment]
(expects an answer around December 6 from the Director)

**Comment by swickr** [comment]
Might the WG wish to state something in the Abstracts about compatibility with JSON-LD 1.0; e.g. that 1.1 is a superset of 1.0?

**Comment by gkellogg** [comment]
Looking at similar updates, such as [SPARQL 1.1 Query](https://www.w3.org/TR/2013/REC-sparql11-query-20130321/) and [RDF 1.1 Concepts](https://www.w3.org/TR/rdf11-concepts/) for examples, I don't find any discussion there of the relationship to their respective 1.0 versions, other than in the "Changes Since ..." sections.

That said, it would be entirely appropriate for us to do something like this.

> This specification describes a superset of the features defined in JSON-LD 1.1 ( API ) and, except where noted, documents created using the 1.0 version of this specification remain compatible with JSON-LD 1.1.

In the case of the API, which is largely written for implementors, there are substantial algorithmic changes to allow accepting both 1.0 and 1.1 documents, and the algorithms describe the points of departure.

The Framing document never had a 1.0 recommendation, although it was used as a community standard. Changes are also noted there.

**Comment by iherman** [comment]
I would be in favour adding such remark. It is an important message to the community. I would not mind if we added this to the Frame document, too, which was used by the community, too.

**Comment by iherman** [comment]
@plehegar @swickr a small detail in the request. RDF issues...

- We intend to add the following terms to the RDF namespace: `rdf:JSON`[1], `rdf:CompoundLiteral` (class), `rdf:language` and `rdf:direction`[2]
- We intend to add a `https://www.w3.org/ns/i18n` namespace document to allow for terms like `https://www.w3.org/ns/i18n#ar-EG_rtl`[3]

Both are related to the direction setting issue.

cc: @gkellogg @pchampin @dlongley @BigBlueHat @azaroth42



1. https://www.w3.org/TR/json-ld11/#the-rdf-json-datatype
2. https://www.w3.org/TR/json-ld11/#the-rdf-compoundliteral-class-and-the-rdf-language-and-rdf-direction-properties
3. https://www.w3.org/TR/json-ld11/#the-i18n-namespace

**Comment by swickr** [comment]
@iherman 
> - We intend to add the following terms to the RDF namespace: rdf:JSON[1], rdf:CompoundLiteral (class), rdf:language and rdf:direction[2]
> - We intend to add a https://www.w3.org/ns/i18n namespace document to allow for terms like https://www.w3.org/ns/i18n#ar-EG_rtl[3]

Fine; let's coordinate on how to do this.  Do you have a new NS document staged somewhere?

**Comment by swickr** [comment]
Transition approved.

The [JSON-LD] entry in Syntax/Informative References is superflous; that ref is not
used in the spec.

Two of your RFC references in Syntax and API are using httpwg.org rather than ietf.org; you may want to fix these before Proposed Rec.

**Comment by gkellogg** [comment]
> Transition approved.
> 
> The [JSON-LD] entry in Syntax/Informative References is superflous; that ref is not
> used in the spec.

That gets generated because of ReSpec `data-cite` attribute, which I've attempted to quash before, I'll have another go.

> Two of your RFC references in Syntax and API are using httpwg.org rather than ietf.org; you may want to fix these before Proposed Rec.

+1

**Comment by iherman** [comment]
@swickr,

>@iherman 
>> - We intend to add the following terms to the RDF namespace: rdf:JSON[1], rdf:CompoundLiteral (class), rdf:language and rdf:direction[2]
>> - We intend to add a https://www.w3.org/ns/i18n namespace document to allow for terms like https://www.w3.org/ns/i18n#ar-EG_rtl[3]
>
> Fine; let's coordinate on how to do this.  Do you have a new NS document staged somewhere?

See https://github.com/w3c/json-ld-syntax/issues/263#issuecomment-562687010 (modulo some minor adjustment discussed in the issue). There is only one new document (`i18n`), the other part is an update on the good old rdf namespace file...

**Comment by iherman** [comment]
@swickr, while we are it...

I have prepared a document, after having seen some discussions on the semweb mailing list, which is, temporarily, at: https://www.w3.org/1999/02/rdf-syntax.html

I wonder whether we should turn this document into a bona fide https://www.w3.org/1999/02/rdf-syntax-ns.html with appropriate conneg (although the text has to be expanded a little bit with the new terms added by JSON-LD).

Of course, before doing that, we would have to send a mail to semweb mailing list to see if anybody sees any problems with it. (I guess such a mail should be sent out as an information of the new JSON-LD terms anyway.). WDYT?

Cc: @draggett

**Comment by iherman** [comment]
Documents have been published; closing.
