### ISSUE TITLE
FPWD Request for Pointer Events Level 3

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/transitions#201]
# Document title, URLs, estimated publication date
Pointer Events Level 3
https://github.com/w3c/pointerevents
https://w3c.github.io/pointerevents/

# Abstract
The features in this specification extend or modify those found in Pointer Events, a W3C Recommendation that describes events and related interfaces for handling hardware agnostic pointer input from devices including a mouse, pen, touchscreen, etc. For compatibility with existing mouse based content, this specification also describes a mapping to fire Mouse Events for other pointer device types.

# Status
This specification is an update to [PointerEvents2] which was shipped broadly by Google Chrome and Microsoft Edge and Mozilla Firefox. Level 3 includes editorial clarifications and new features that facilitate more use cases, in an effort to enable wider developer and browser adoption.

This document was published by the Pointer Events Working Group as an Editor's Draft.
GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-pointer-events@w3.org (archives).
Publication as an Editor's Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.
This document is governed by the 1 March 2019 W3C Process Document.

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://github.com/w3c/pointerevents/issues/312

# Information about implementations known to the Working Group
Direction-specific `touch-action` values, `getPredictedEvents`, `getCoalescedEvents` and `pointerrawupdate` all implemented in Chrome/Blink. In development in Firefox/Gecko

**Comment by plehegar** [comment]
Transition approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2019/WD-pointerevents3-20191212/

**Comment by patrickhlauke** [comment]
@plehegar image files are 404-ing, and there's an additional weird

```
Failed to load resource: the server responded with a status of 404 () https://www.w3.org/TR/tr-outdated-spec
```

error showing up in the console

**Comment by plehegar** [comment]
images fixed. The 404 is our fixup script trying to find if the doc is outdated or not, so it's expected. we catch the 404 in the script.

**Comment by plehegar** [comment]
See also https://github.com/w3c/tr-design/blob/gh-pages/src/fixup.js#L155

**Comment by patrickhlauke** [comment]
perfect, thank you @plehegar

**Comment by plehegar** [comment]
I'll set up the automatic publication before mid-January
