### ISSUE TITLE
PR Request for Web of Things (WoT) Architecture

### ISSUE THREAD

**Issue by mmccool** [w3c/transitions#202]
# Document title, URLs, estimated publication date
* **Document Title**: Web of Things (WoT) Architecture
* **Current Version:**: https://www.w3.org/TR/2019/CR-wot-architecture-20191106/
* **Editor's Draft**: https://w3c.github.io/wot-architecture/

# Abstract
The W3C Web of Things (WoT) is intended to enable interoperability across IoT platforms and application domains. Overall, the goal of the WoT is to preserve and complement existing IoT standards and solutions. In general, the W3C WoT architecture is designed to describe what exists rather than to prescribe what to implement.

This WoT Architecture specification describes the abstract architecture for the W3C Web of Things. This abstract architecture is based on a set of requirements that were derived from use cases for multiple application domains, both given in this document. A set of modular building blocks are also identified whose detailed specifications are given in other documents. This document describes how these building blocks are related and work together. The WoT abstract architecture defines a basic conceptual framework that can be mapped onto a variety of concrete deployment scenarios, several examples of which are given. However, the abstract architecture described in this specification does not itself define concrete mechanisms or prescribe any concrete implementation.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

his document describes an abstract architecture design. However, there is an Implementation Report that describes a set of concrete implementations based on the associated WoT Thing Description specification. These are implementations following the W3C Web of Things architecture.

This document was published by the Web of Things Working Group as an Editor's Draft.
GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-wot-wg@w3.org (archives).
Publication as an Editor's Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.
This document is governed by the 1 March 2019 W3C Process Document.

# Link to group's decision to request transition
https://www.w3.org/2019/12/11-wot-minutes.html#resolution02

# Changes
No significant changes to the body of the text since the second CR transition.  There
were however some minor changes:
* Expanded description of changes in the Change Log since the first CR transition.
* Updated references to point to newer versions of W3C publications published since the second CR transition.

# Requirements satisfied
This is an abstract architecture definition and includes a use case and requirements analysis
within it.   Therefore there is not a separate analysis of requirements satisfied.

# Dependencies met (or not)
There are no known dependencies on other work.

#  Wide Review
The specification has been discussed and reviewed extensively within its community via discussions at the W3C Interest Group and multiple Face-to-Face meetings. Additionally, horizontal review was requested from relevant groups at W3C. Issues and/or PRs for the latter can be found in the Working Group's GitHub repository at https://github.com/w3c/wot-architecture .

# Issues addressed
See
https://github.com/w3c/wot-architecture/issues
and in particular
https://github.com/w3c/wot-architecture/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22CR2+period%22

# Formal Objections
None.

# Implementation
No direct implementation since this is an abstract architecture document.
However, the related Web of Things (WoT) Thing Description's Implementation Report
does list several implementations in that context:
https://cdn.statically.io/gh/w3c/wot-thing-description/master/testing/report.html

# Patent disclosures
None

**Comment by plehegar** [comment]
HTML diff:
 https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2019%2FCR-wot-architecture-20191106%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fwot-architecture%2F

closed privacy issues:
 https://github.com/w3c/wot-architecture/issues?q=is%3Aissue+is%3Aclosed+label%3APrivacy

The informative reference to Server-Sent events needs to be updated to point to:
 https://html.spec.whatwg.org/multipage/server-sent-events.html

**Comment by plehegar** [comment]
References report: (nothing is surfacing there)
  https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fw3c.github.io%2Fwot-architecture%2F

**Comment by plehegar** [comment]
We need a transition call for this one.

**Comment by npdoty** [comment]
The link on the closed privacy issues included above doesn't show the issues in question. This list seems to be more descriptive: https://github.com/w3c/wot-architecture/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+privacy

**Comment by swickr** [comment]
Transition approved, with an update to the Server Sent Events reference to the HTML LS

**Comment by snyderp** [comment]
Re: https://w3c.github.io/wot-architecture/

PING is concerned about the Web of Things Architecture spec.  While this issue is not meant to block advancement, we'd like to register these concerns, in the hope that future specs from the Web of Things Working Group consider and address them.

First, we urge the WoT group to clearly delineate between which portion of specs are merely descriptive (i.e. describing what exists in practice today), and what is prescriptive (i.e. what future implementors should do). Clarity here will help PING better understand the privacy implications of the spec going forward.

Second, we urge the WoT group to group together documents with heavily-interrelated privacy aspects. For example, the Architecture document describes a great deal of how devices are expected to interact, but lacks precise details about how those interactions will be carried out, among which parties, carrying which values, and over what lifetime.  

While we appreciate that the WoT group expects more of these details to be fleshed out in future documents, PING worries that details specified in the Architecture document will constrain future decisions, and "lock in" privacy-negative aspects of the overall system being described. More generally, its difficult to impossible to assess the privacy aspects of large systems by looking at each piece in isolation. Going forward we urge the WG to more fully describe the entire proposed system(s), so that PING can better evaluate its overall privacy implications.

**Comment by swickr** [comment]
Transition approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/PR-wot-architecture-20200130/
