### ISSUE TITLE
PR Request for Web of Things (WoT) Thing Description

### ISSUE THREAD

**Issue by mmccool** [w3c/transitions#203]
# Document title, URLs, estimated publication date
* **Document Title**: Web of Things (WoT) Thing Description
* **Current Version:**: https://www.w3.org/TR/2019/CR-wot-thing-description-20191106/
* **Editor's Draft**: https://w3c.github.io/wot-thing-description/
* **Implementation Report:** https://cdn.statically.io/gh/w3c/wot-thing-description/master/testing/report.html

# Abstract
This document describes a formal model and a common representation for a Web of Things (WoT) Thing Description. A Thing Description describes the metadata and interfaces of Things, where a Thing is an abstraction of a physical or virtual entity that provides interactions to and participates in the Web of Things. Thing Descriptions provide a set of interactions based on a small vocabulary that makes it possible both to integrate diverse devices and to allow diverse applications to interoperate. Thing Descriptions, by default, are encoded in a JSON format that also allows JSON-LD processing. The latter provides a powerful foundation to represent knowledge about Things in a machine-understandable way. A Thing Description instance can be hosted by the Thing itself or hosted externally when a Thing has resource restrictions (e.g., limited memory space) or when a Web of Things-compatible legacy device is retrofitted with a Thing Description.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

This document was published by the Web of Things Working Group as an Editor's Draft.
GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-wot-wg@w3.org (archives).
Please see the Working Group's implementation report.

Publication as an Editor's Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.
This document is governed by the 1 March 2019 W3C Process Document.

# Link to group's decision to request transition
https://www.w3.org/2019/12/11-wot-minutes.html#resolution03

# Changes
Since the second CR publication, the following changes were made to informative content:
* At-risk features CertSecurityScheme, PublicSecurityScheme, PoPSecurityScheme as well as implicit, password and client flows in OAuth2SecurityScheme were removed.
* In section § 5.3.2 Data Schema Vocabulary Definitions, clarified the relationship between data schemas and content types.
* In section § 6.3.9 forms, clarified the expectations of Consumers and Things for operation types writemultipleproperties, readmultipleproperties and readallproperties.
* In section § 8.3.1 Protocol Binding based on HTTP, the contexts in which default values GET or PUT are used for vocabulary term htv:methodName were clarified.
* The example Thing Description in appendix section § A.2 MyIlluminanceSensor Example with MQTT Protocol Binding was improved to make a better example using MQTT.

# Requirements satisfied
Requirements are stated in the associated Web of Things (WoT) Architecture document 
(https://www.w3.org/TR/2019/CR-wot-architecture-20191106/)
and have been satisfied.

# Dependencies met (or not)
Specification dependencies are listed in the References section of the document.
Of particular note is the dependence on JSON-LD 1.1, which is still in progress.
However this document has been defined in such a way that it can stand alone (for now) and
we are coordinating with the JSON-LD 1.1 group so that they are aware of the dependency.

#  Wide Review
The specification has been discussed and reviewed extensively within its community via discussions at the W3C Interest Group and multiple Face-to-Face meetings. Additionally, horizontal review was requested from relevant groups at W3C. Issues and/or PRs for the latter can be found in the Working Group's GitHub repository at https://github.com/w3c/wot-thing-description .

# Issues addressed
See
https://github.com/w3c/wot-thing-description/issues
and in particular
https://github.com/w3c/wot-thing-description/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22CR2+period%22

# Formal Objections
None.

# Implementation
The Web of Things (WoT) Thing Description's Implementation Report
lists and describes several implementations:
https://cdn.statically.io/gh/w3c/wot-thing-description/master/testing/report.html

# Patent disclosures
None.

**Comment by plehegar** [comment]
See also #202  . Might as well do both at the same time.

**Comment by mmccool** [comment]
Original submission had an incomplete change log.  Now updated (and complete) both here and in the document.

**Comment by swickr** [comment]
Transition approved, with the update to the reference to the HTML LS for server sent events

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/PR-wot-thing-description-20200130/
