### ISSUE TITLE
FPWD Request for Web Share API

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/transitions#204]
# Document title, URLs, estimated publication date
Title: Web Share API
Estimated publication: 2019-12-17
https://w3c.github.io/web-share/?specStatus=FPWD&publishDate=2019-12-17

# Abstract
This specification defines an API for sharing text, links and other content to an arbitrary destination of the user's choice. The available share targets are not specified here; they are provided by the user agent. They could, for example, be apps, websites or contacts.

# Status
https://w3c.github.io/web-share/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
Yes

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-webapps/2019OctDec/0011.html

# Information about implementations known to the Working Group
Implemented in Chrome for Android, Safari IOS and MacOS, and in Gecko (but not shipped in a product).

**Comment by plehegar** [comment]
Assuming it is NOT a [delta specification](https://www.w3.org/2005/07/13-pubrules-about#delta), but it is intended to become a W3C Recommendation nevertheless.


Transition approved. Congratulations.

**Comment by marcoscaceres** [comment]
Oops about the delta.

**Comment by ylafon** [comment]
https://www.w3.org/TR/2019/WD-web-share-20191217/
