### ISSUE TITLE
CR Request for the 2019 DOM Standard Review Draft

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#206]
# Document title, URLs, estimated publication date
DOM
Review Draft — Published 24 December 2019 (if we couldn't make it on 24 Dec, then 31 Dec)
temp:
https://domspec-w3c-ready.herokuapp.com/
final:
https://www.w3.org/TR/dom/
https://dom.spec.whatwg.org/review-drafts/2019-12

# Abstract
DOM defines a platform-neutral model for events, aborting activities, and node trees.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

The following features are at-risk for the purpose of the W3C Candidate Recommendation:

AbstractRange (lacks two implementations in current engines)
document.origin (lacks two implementations in current engines)
The W3C HTML Working Group co-produced this document under the W3C Patent Policy and the 1 February 2018 W3C Process Document. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

# Link to group's decision to request transition
https://github.com/w3c/htmlwg/issues/6

# Changes
* Integration of custom elements; 
* shadow trees; 
* aborting ongoing activities; 
* StaticRange objects.
(detail changes can be found in the [commit log](https://github.com/whatwg/dom/commits))

# Requirements satisfied
Yes.

# Dependencies met (or not)
Some of the Normative References are still under development, but the group believe all the terms referenced by this review draft are valid and widely implemented.

# Wide Review
https://github.com/w3c/htmlwg/issues/4
The HTML WG have sent out the Call for Review to the A11y groups, the i18n WG, the Security mailing list, the Privacy IG and the TAG.
At the end of the review period no issues had been raised that block transition of the DOM Standard Review Draft to CR.

# Issues addressed
There are still open issues for DOM, but the editors believe this review draft is good enough to move to CR.

# Formal Objections
None.

# Implementation
The following features are at-risk for the purpose of the W3C Candidate Recommendation:
AbstractRange (lacks two implementations in current engines)
document.origin (lacks two implementations in current engines)

# Patent disclosures
https://www.w3.org/2004/01/pp-impl/44556/status

**Comment by plehegar** [comment]
since we're in a publication moratorium, this transition won't get looked at for the next 2 weeks.

**Comment by swickr** [comment]
The CFC was for the June Review Draft; please clarify the WG's intention as this CR draft is the December 2019 Review Draft.   To which Review Draft(s) do the changes listed in this CR request apply?

The first sentence of the last paragraph ("Do not attempt ...") of the yellow status box should be deleted for the purposes of a W3C CR; it was not agreed-to per the [sample document](https://www.w3.org/2019/01/whatwg-w3c-sample.html) in the [MoU](https://www.w3.org/2019/04/WHATWG-W3C-MOU.html).  The second and third sentences of that paragraph are ok;  we realize that the sample document test was not clear about references to CR and PR documents.

In the Status of This Document , please update the W3C Process Document reference to the 2019 Process.

cc: @sideshowbarker @LJWatson

**Comment by LJWatson** [comment]
Wide and horizontal review was done on the June 2019 review draft. Had 
there been only editorial updates to the DOM standard since then we 
might have been able to carry the review forward and publish the 
December 2019 review draft, but there have been a few [substantive 
updates](https://github.com/whatwg/dom/pulls?utf8=%E2%9C%93&q=is%3Apr+closed%3A%3E2019-06-20).

**Comment by LJWatson** [comment]
Wide and horizontal review was done on the June 2019 review draft. Had 
there been only editorial updates to the DOM standard since then we 
might have been able to carry the review forward and publish the 
December 2019 review draft, but there have been a few [substantive updates](https://github.com/whatwg/dom/pulls?utf8=%E2%9C%93&q=is%3Apr+closed%3A%3E2019-06-20).

**Comment by sideshowbarker** [comment]
> The first sentence of the last paragraph ("Do not attempt ...") of the yellow status box should be deleted for the purposes of a W3C CR

OK, removed

> In the Status of This Document , please update the W3C Process Document reference to the 2019 Process.

OK, changed

**Comment by swickr** [comment]
Thanks @LJWatson :

> Wide and horizontal review was done on the June 2019 review draft. Had
> there been only editorial updates to the DOM standard since then we
> might have been able to carry the review forward and publish the
> December 2019 review draft, but there have been a few [substantive updates](https://github.com/whatwg/dom/pulls?utf8=%E2%9C%93&q=is%3Apr+closed%3A%3E2019-06-20).

In this case, either the CfC should be repeated for the version of the Review Draft that is staged as the requested CR publication or the staged CR publication should be changed to the June 2019 Review Draft; whichever the Working Group feels is most appropriate.

**Comment by plehegar** [comment]
Awaiting on an updated draft for the June 2019 snapshot

**Comment by sideshowbarker** [comment]
https://domspec-w3c-ready.herokuapp.com/ is now updated — it’s now the June 2019 Review Draft

**Comment by swickr** [comment]
Thanks @sideshowbarker; this is nearly ready.  Once the following are done this is OK to publish.

W3C In the Recommendation Status section,

1. Fix the "This version" link to the 2019-06 Review Draft
2. Fix the W3C Version Mnemonic to "DOM 2019-06"
3. Update the "W3C HTML Working Group" link to https://www.w3.org/2019/html/ 
4. Correct the "patent disclosures" link to https://www.w3.org/2004/01/pp-impl/115520/status

**Comment by sideshowbarker** [comment]
> Once the following are done this is OK to publish.
> 
> W3C In the Recommendation Status section,
> 
> 1. Fix the "This version" link to the 2019-06 Review Draft
> 2. Fix the W3C Version Mnemonic to "DOM 2019-06"
> 3. Update the "W3C HTML Working Group" link to https://www.w3.org/2019/html/
> 4. Correct the "patent disclosures" link to https://www.w3.org/2004/01/pp-impl/115520/status

https://domspec-w3c-ready.herokuapp.com/#w3c-rec now has all those changes.

(Sorry for not replying to say so before now…)

**Comment by swickr** [comment]
Transition approved.

**Comment by sideshowbarker** [comment]
https://dom.spec.whatwg.org/review-drafts/2019-06/ now has the W3C CR draft
