### ISSUE TITLE
[TTWG] CR Request for ttml2

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#208]
# Document title, URLs, estimated publication date
Timed Text Markup Language 2 (TTML2) (2nd Edition)
https://w3c.github.io/ttml2/
estimated publication date at 28th Jan 2020

# Abstract
https://w3c.github.io/ttml2/#abstract

# Status
https://w3c.github.io/ttml2/#status

# Link to group's decision to request transition
https://www.w3.org/2020/01/09-tt-minutes.html#x08

# Changes
https://w3c.github.io/ttml2/ttml2-changes.html

# Requirements satisfied
No requirements document.

# Dependencies met (or not)
https://w3c.github.io/ttml2/#references

# Wide Review
Asked for HR at 18 Oct 2019, with 3mo period (as in charter).

- accessibility: requested at https://lists.w3.org/Archives/Public/public-tt/2019Oct/0049.html
- privacy: all labeled to be fixed by PR; review comment at https://lists.w3.org/Archives/Public/public-tt/2019Nov/0011.html, list of issues at https://github.com/w3cping/tracking-issues/issues/30
- security: requested at https://lists.w3.org/Archives/Public/public-tt/2019Oct/0038.html
- internationalization: draft comment at https://github.com/w3c/i18n-request/issues/86#issuecomment-576250508, all aim to next version of TTML https://www.w3.org/2020/01/23-i18n-minutes.html#item06

# Issues addressed
https://github.com/w3c/ttml2/issues/
most open issues were delayed to 3rd edition: https://github.com/w3c/ttml2/milestone/8

# Formal Objections
none

# Implementation
Implementation report will be prepared at TTWG wiki by exit the CR stage: https://www.w3.org/wiki/TimedText/TTML2SecondEditionImplementationReport

For this specification to exit the CR stage, at least 2 independent implementations of every feature defined in this specification need to be documented in the implementation report. The implementation report is based on implementer-provided test results for the test suite.

The Working Group has not identified features "at risk" for this specification.

# Patent disclosures
https://www.w3.org/2004/01/pp-impl/34314/status#current-disclosures

**Comment by swickr** [comment]
Transition approved once the HTML non-normative reference is updated to cite the WHATWG HTML LS.

Kudos for the links to the GH PRs in the change history; those are very helpful.

**Comment by himorin** [comment]
HTML non-normative references have been updated to WHATWG HTML LS by https://github.com/w3c/ttml2/pull/1193/commits/fe45478561d226f6b53895db4354841cfecd3d83

**Comment by plehegar** [comment]
go ahead and publish

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2020/CR-ttml2-20200128/
