### ISSUE TITLE
[CSSWG] FPWD Request for CSS Color Module Level 5

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#209]
# Document title, URLs, estimated publication date
CSS Color Module Level 5
https://drafts.csswg.org/css-color-5/
Thursday 30 Jan

# Abstract
https://drafts.csswg.org/css-color-5/#abstract

# Status
https://drafts.csswg.org/css-color-5/#status (as ED for now)

# Is it a delta specification intended to become a W3C Recommendation?
yes, right now
intended to merge in CSS Color 4 once that is a Proposed Rec, or when CSS Color 5 goes to CR, whichever is first.

# Link to group's decision to request transition
RESOLVED: publish first public working draft of color-5
https://www.w3.org/2020/01/23-css-irc.html#T14-48-08

# Information about implementations known to the Working Group
Not yet, but the underlying lab() and lch() functions on which this spec depends are being implemented now in Safari and in BFO PDF formatter.

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Blocked see https://github.com/w3c/transitions/issues/218#issuecomment-583799417

**Comment by svgeesus** [comment]
Publication requested 28 Feb, expected 3 March

**Comment by svgeesus** [comment]
[Published 3 March](https://www.w3.org/TR/2020/WD-css-color-5-20200303/)
