### ISSUE TITLE
[CSSWG] FPWD Request for Media Queries Level 5

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#210]
# Document title, URLs, estimated publication date

Media Queries Level 5
https://drafts.csswg.org/mediaqueries-5/
Thursday 30 Jan

# Abstract

https://drafts.csswg.org/mediaqueries-5/#abstract

# Status

https://drafts.csswg.org/mediaqueries-5/#status (as ED)

# Is it a delta specification intended to become a W3C Recommendation?

yes, for now

# Link to group's decision to request transition

RESOLVED: resolved to publish media-queries-5
https://www.w3.org/2020/01/23-css-irc.html#T14-50-13

# Information about implementations known to the Working Group

some features shipping in all browsers, some shipping in some, some not shipping yet

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Blocked see https://github.com/w3c/transitions/issues/218#issuecomment-583799417

**Comment by svgeesus** [comment]
Publication requested 28 Feb, expected 3 March

**Comment by svgeesus** [comment]
[Published 3 March](https://www.w3.org/TR/2020/WD-mediaqueries-5-20200303/)
