### ISSUE TITLE
[CSSWG] FPWD Request for CSS Transforms Module Level 2

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#211]
# Document title, URLs, estimated publication date

CSS Transforms Module Level 2
https://drafts.csswg.org/css-transforms-2/
Thurs 30 January

# Abstract
https://drafts.csswg.org/css-transforms-2/#abstract

# Status
https://drafts.csswg.org/css-transforms-2/#status (as ED)

# Is it a delta specification intended to become a W3C Recommendation?
yes

# Link to group's decision to request transition

RESOLUTION: publish FPWD of transforms-2
https://www.w3.org/2020/01/23-css-irc.html#T14-49-08

# Information about implementations known to the Working Group

being implemented now in some browsers

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Blocked see https://github.com/w3c/transitions/issues/218#issuecomment-583799417

**Comment by svgeesus** [comment]
Publication request sent 29 Feb, expected 3 March

**Comment by svgeesus** [comment]
[Published 3 March](https://www.w3.org/TR/2020/WD-css-transforms-2-20200303/)
