### ISSUE TITLE
FPWD Request for Picture-in-Picture

### ISSUE THREAD

**Issue by tidoust** [w3c/transitions#214]
# Document title, URLs, estimated publication date
* Title: Picture-in-Picture
* URL of ED to publish: https://w3c.github.io/picture-in-picture/
* GitHub: https://github.com/w3c/picture-in-picture/
* To be published at: https://www.w3.org/TR/picture-in-picture/ (does not exist yet)
* Estimated publication date: whenever possible. 30 January 2020?

# Abstract
This specification intends to provide APIs to allow websites to create a floating video window always on top of other windows so that users may continue consuming media while they interact with other content sites, or applications on their device.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at http://www.w3.org/TR/.

The Media Working Group maintains a list of all bug reports that the group has not yet addressed. This draft highlights some of the pending issues that are still to be discussed in the working group. No decision has been taken on the outcome of these issues including whether they are valid. Pull requests with proposed specification text for outstanding issues are strongly encouraged.

This document was published by the Media Working Group as a Working Draft. This document is intended to become a W3C Recommendation. 

This document is a First Public Working Draft. 

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress. 

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 1 March 2019 W3C Process Document. 

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://github.com/w3c/picture-in-picture/issues/173

# Information about implementations known to the Working Group
Shipped in Chrome. Safari ships a similar API (proprietary for now). Firefox supports picture-in-picture at the chrome level.

[Status text slightly updated on 2020-01-28 to match the one used by the Media WG]

**Comment by plehegar** [comment]
Approved

**Comment by tidoust** [comment]
Published at https://www.w3.org/TR/2020/WD-picture-in-picture-20200130/
