### ISSUE TITLE
[CSSWG] FPWD Request for Resize Observer

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#216]
# Document title, URLs, estimated publication date

Resize Observer
https://drafts.csswg.org/resize-observer-1/
Tues 4 Feb 2020

# Abstract
https://drafts.csswg.org/resize-observer-1/#abstract

# Status
https://drafts.csswg.org/resize-observer-1/#status (as ED)

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
14:57:02 [stantonm]
    RESOLVED: publish FPWD of resize-observer
https://www.w3.org/2020/01/23-css-irc.html#T14-57-02

# Information about implementations known to the Working Group
Not yet
Spec was incubated in WICG then transferred to CSS WG

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Publication request sent, expected publication 11 Feb

**Comment by svgeesus** [comment]
[published 11 Fen 2020](https://www.w3.org/TR/2020/WD-resize-observer-1-20200211/)
