### ISSUE TITLE
[CSSWG] FPWD Request for CSS Scroll Anchoring

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#217]
# Document title, URLs, estimated publication date

CSS Scroll Anchoring Module Level 1
https://drafts.csswg.org/css-scroll-anchoring-1/
Tues 4 Feb 2020

# Abstract
https://drafts.csswg.org/css-scroll-anchoring-1/#abstract

# Status
https://drafts.csswg.org/css-scroll-anchoring-1/#status (as ED)

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
15:02:13 [stantonm]
    heycam: maybe scroll anchoring
15:02:17 [jensimmons]
    jensimmons has joined #css
15:02:26 [stantonm]
    TabAtkins: I can own, and publish
15:02:44 [stantonm]
    RESOLVED: FPWD of scroll-anchoring level 1
https://www.w3.org/2020/01/23-css-irc.html#T15-02-13

# Information about implementations known to the Working Group
Not yet

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Publication request sent, expected Tues 11 Feb.

**Comment by svgeesus** [comment]
[published 11 Feb 2020](https://www.w3.org/TR/2020/WD-css-scroll-anchoring-1-20200211/)
