### ISSUE TITLE
[CSSWG] FPWD Request for CSS Conditional 4

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#218]
# Document title, URLs, estimated publication date

CSS Conditional Rules Module Level 4
https://drafts.csswg.org/css-conditional-4/
Tues 4 Feb 2020

# Abstract
https://drafts.csswg.org/css-conditional-4/#abstract

# Status
https://drafts.csswg.org/css-conditional-4/#status (as ED)

# Is it a delta specification intended to become a W3C Recommendation?
Yes

# Link to group's decision to request transition
14:57:16 [stantonm]
    fantasai: css-conditional level 4
14:57:37 [stantonm]
    RESOLVED: publish FPWD of css-conditional-4
https://www.w3.org/2020/01/23-css-irc.html#T14-57-16

# Information about implementations known to the Working Group
Too early

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Publication of this specification as FPWD is currently blocked on many broken links from Bikeshed. This is apparently by design: @tabatkins wants delta specs to auto-expand by a clever import mechanism, so the generated html is not a delta spec. Meanwhile, Bikeshed refuses to link from foo-n to foo(n-1). The clever import mechanism does not exist. Some spec editors may prefer to keep delta specs small, to focus review on the actual new parts.

@fantasai has a fork of Bikeshed that removes the restriction on links to earlier levels of the same spec. However, i can't get it to work on my machine.

The alternative is to generate the html and then laboriously fix up links with search and replace, one by one in the generated html. And then repeat that work, every time the spec is republished, until it stops being a delta spec (typically, when the earlier version is super stable and almoust ready to exit CR).

**Comment by svgeesus** [comment]
Publication request sent 29 Feb, expected 3 March

**Comment by svgeesus** [comment]
[Published 3 March](https://www.w3.org/TR/2020/WD-css-conditional-4-20200303/)
