### ISSUE TITLE
[CSSWG] CR Update Request for css-speech-1

### ISSUE THREAD

**Issue by xfq** [w3c/transitions#225]
# Document URLs

CSS Speech Module https://drafts.csswg.org/css-speech-1/

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/www-style/2017Feb/0069.html

# Link to previous Candidate Recommendation transition request

https://lists.w3.org/Archives/Member/chairs/2012JanMar/0059.html

# Substantive changes

https://drafts.csswg.org/css-speech-1/#changes

# Any changes in normative references?

None.

# Any changes in requirements?

None.

# Wide Review of substantive changes

This is a CR update after having made some minor fixes in response to horizontal review.

# Issues status

There are 3 open issues: https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Acss-speech-1

# Formal Objections

None.

# Any changes in implementation information?

None.

# Deadline for further comments

1 month after publication.

# Any changes in patent disclosures?

None.

# Note

This spec was erroneously published as a Note, but the group resolution was to publish it as an updated CR. (See https://github.com/w3c/tr-design/issues/180 for background.)

The shortname will be renamed from css3-speech to css-speech-1.

**Comment by plehegar** [comment]
Normative references:
 https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fdrafts.csswg.org%2Fcss-speech-1%2F

Diff (from previous CR in March 2012)
 https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2012%2FCR-css3-speech-20120320%2F&doc2=https%3A%2F%2Fdrafts.csswg.org%2Fcss-speech-1%2F

**Comment by swickr** [comment]
Transition approved.

It would  be a community service if the WG would give a realistic expectation about the future of this document.  Suggesting that the spec "will not become Proposed Recommendation before 5 March 2020" seems misleading based on the heartbeat the WG has given this work.

**Comment by svgeesus** [comment]
[Test suite results (on 7 tests!) 0/7](http://test.csswg.org/harness/results/css-speech-1_dev/grouped/) with no known implementations.

@plehegar [wrote](https://github.com/w3c/tr-design/issues/180#issuecomment-519255197)

> So, as far as I can tell, we got mixed up and should not have publish the document as a Note, but I could miss something.

It was published as a Note because I asked for republication as CR, in accordance with CSS WG resolution, and PLH told me that if there were no implementations and none on the horizon it should be published as a Note instead. And could always be republished as  CR if that changed.

**Comment by xfq** [comment]
@fantasai @frivoal Any text to add/change in the [Status section](https://drafts.csswg.org/css-speech-1/#status)?

**Comment by fantasai** [comment]
@xfq  I don't think so...

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/CR-css-speech-1-20200310/
