### ISSUE TITLE
FPWD Request for XR Accessibility User Requirements

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/transitions#227]
# Document title, URLs, estimated publication date
Title: XR Accessibility User Requirements
Editors' Draft: https://w3c.github.io/apa/xaur/
Anticipated Publication URI: https://www.w3.org/TR/WD-xaur-20200213/
Planned Publication Date: 13 February 2020

# Abstract
This document lists user needs and requirements for people with disabilities when using virtual reality or immersive environments, augmented or mixed reality and other related technologies (XR). It first introduces a definition of XR as used throughout the document, then briefly outlines some uses of XR. It outlines the complexity of understanding XR, introduces some accessibility challenges, and introduces accessibility multimodal support for a range of input and output devices, the importance of customization. Based on this information, it outlines accessibility user needs for XR and their related requirements, followed by information about related work that may be helpful to understand the complex technical architecture and processes behind how XR environments built and what may form the basis of a robust accessibility architecture for XR.

This document is most explicitly not a collection of baseline requirements. It is also important to note that some of the requirements may be implemented at a system or platform level, and some may be authoring requirements.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

This is a First Public Working Draft of XR Accessibility User Requirements by the Accessible Platform Architectures Working Group. It is developed by the Research Questions Task Force (RQTF) who work to identify accessibility knowledge gaps and barriers in emerging and future web technologies. The requirements outlined here come from research into user needs that then provide the basis for any technical requirements. This version is published to collect public feedback on the requirements prior to finalization as a Working Group Note.

To comment, file an issue in the W3C APA GitHub repository. If this is not feasible, send email to public-apa@w3.org (archives). Comments are requested by 7 April 2020. In-progress updates to the document may be viewed in the publicly visible editors' draft.

This document was published by the Accessible Platform Architectures Working Group as a First Public Working Draft.

Comments regarding this document are welcome. Please send them to public-apa@w3.org (archives).

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. The group does not expect this document to become a W3C Recommendation. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 1 March 2019 W3C Process Document. 

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-apa-admin/2020Jan/0033.html

# Information about implementations known to the Working Group
Note-track, no implementation

**Comment by plehegar** [comment]
Approved.

**Comment by michael-n-cooper** [comment]
Published to https://www.w3.org/TR/2020/WD-xaur-20200213/
