### ISSUE TITLE
CR Update Request for Time Ontology in OWL

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/transitions#228]
# Document URLs
Latest published version - https://www.w3.org/TR/owl-time/
Proposed update - https://w3c.github.io/sdw/time/

# Link to group's decision to request transition
Group no longer active. 
See discussion here: https://github.com/w3c/sdw/issues/1165 

# Link to previous Candidate Recommendation transition request
This is actually a request to update a Recommendation, but this appeared to be the closest matching transition request form. The most recent Transition Request for OWL-Time was https://lists.w3.org/Archives/Public/public-sdw-wg/2017Aug/0006.html 

# Substantive changes
Added IANA considerations https://w3c.github.io/sdw/time/#iana-links 
This copies existing material into the template usually used for IANA registrations. 
It does not change the content or underlying semantics. 

Note that IANA registration has already occurred - see https://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1. This new chapter would merely align the published version with the usual IANA registration expectations and allow readers to know about the IANA registration from within the W3C document. 

# Any changes in normative references?
No. 

# Any changes in requirements?
Not to vocabulary requirements - only to the documentation requirements for IANA registrations. 

# Wide Review of substantive changes
The chapter added was reviewed by IANA and deemed suitable - see https://github.com/link-relations/registry/issues/4#issuecomment-511254227 

This Transition is merely to finish the job on the W3C side. 

# Errata
Three errata are also processed in this version - see 
https://github.com/w3c/sdw/issues/1014 https://github.com/w3c/sdw/issues/1114 https://github.com/w3c/sdw/issues/1161

# Issues status
https://github.com/w3c/sdw/issues?q=is%3Aissue+label%3Atime

# Formal Objections

# Any changes in implementation information?
No. 

# Deadline for further comments

# Any changes in patent disclosures?
No.

**Comment by dr-shorthair** [comment]
@tguild I have done my best within the framework of the TR template.

**Comment by plehegar** [comment]
We require new Recommendations to link to a github repository for reporting errors. Any reason not to ask folks to raise issues at https://github.com/w3c/sdw/issues , in preference to the mailing list?

Issues status

https://github.com/w3c/sdw/issues?q=is%3Aissue+label%3Atime

I guess this transition addresses all of the issues marked as errata for owl-time:

https://github.com/w3c/sdw/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aerrata+label%3Atime+

**Comment by dr-shorthair** [comment]
Yes, it does (I just checked). I guess I should mention the other errata in the TR?

**Comment by swickr** [comment]
Looking for SDW IG resolution to publish per https://github.com/w3c/sdw/issues/1165#issuecomment-587099778

**Comment by plehegar** [comment]
please update here once there is a recorded IG decision.

**Comment by tguild** [comment]
IG decision as of 5 March - deadline on CfC

https://lists.w3.org/Archives/Public/public-sdwig/2020Feb/0035.html

**Comment by swickr** [comment]
Transition approved, but we still need a link to https://github.com/w3c/sdw/issues in the SoTD

**Comment by dr-shorthair** [comment]
Addressed in https://github.com/w3c/sdw/commit/89fe786338bc7102e12c09c88cdc0498a3a541dc#diff-07cc694b9b3fc636710fa08b6922c42b

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/CR-owl-time-20200326/
