### ISSUE TITLE
FPWD Request for WCAG 2.2

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/transitions#229]
# Document title, URLs, estimated publication date
Title: Web Content Accessibility Guidelines (WCAG) 2.2
Anticipated Publication URI: https://www.w3.org/TR/2020/WD-WCAG22-20200225/
Expected Publication Date: 25 February 2020

# Abstract
Web Content Accessibility Guidelines (WCAG) 2.2 covers a wide range of recommendations for making Web content more accessible. Following these guidelines will make content more accessible to a wider range of people with disabilities, including accommodations for blindness and low vision, deafness and hearing loss, limited movement, speech disabilities, photosensitivity, and combinations of these, and some accommodation for learning disabilities and cognitive limitations; but will not address every user need for people with these disabilities. These guidelines address accessibility of web content on desktops, laptops, tablets, and mobile devices. Following these guidelines will also often make Web content more usable to users in general.

WCAG 2.2 success criteria are written as testable statements that are not technology-specific. Guidance about satisfying the success criteria in specific technologies, as well as general information about interpreting the success criteria, is provided in separate documents. See Web Content Accessibility Guidelines (WCAG) Overview for an introduction and links to WCAG technical and educational material.

WCAG 2.2 extends Web Content Accessibility Guidelines 2.1 [WCAG21], which was published as a W3C Recommendation June 2018. Content that conforms to WCAG 2.2 also conforms to WCAG 2.0 and WCAG 2.1. The WG intends that for policies requiring conformance to WCAG 2.0 or WCAG 2.1, WCAG 2.2 can provide an alternate means of conformance. The publication of WCAG 2.2 does not deprecate or supersede WCAG 2.0 or WCAG 2.1. While WCAG 2.0 and WCAG 2.1 remain W3C Recommendations, the W3C advises the use of WCAG 2.2 to maximize future applicability of accessibility efforts. The W3C also encourages use of the most current version of WCAG when developing or updating Web accessibility policies.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

This is a First Public Working Draft of Web Content Accessibility Guidelines (WCAG) 2.2 by the Accessibility Guidelines Working Group. WCAG 2.2 continues the updates to Web Content Accessibility Guidelines from WCAG 2.1. This first draft includes 1 new Success Criterion, which is supported by Understanding and Techniques. Additional Success Criteria are being developed for future Working Drafts, all of which are expected to be in WCAG 2.2 by April 2020. Because of the rapid development, early review is critical.

To comment, file an issue in the W3C WCAG GitHub repository. The Working Group requests that public comments be filed as new issues, one issue per discrete comment. It is free to create a GitHub account to file issues. If filing issues in GitHub is not feasible, send email to public-agwg-comments@w3.org (comment archive). The Working Group request comments on this draft be filed by 23 March 2020. In-progress updates to the guidelines can be viewed in the public editors' draft.

This document was published by the Accessibility Guidelines Working Group as a First Public Working Draft. This document is intended to become a W3C Recommendation.

Comments regarding this document are welcome. Please send them to public-agwg-comments@w3.org (archives).

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 1 March 2019 W3C Process Document. 

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/w3c-wai-gl/2020JanMar/0204.html

# Information about implementations known to the Working Group
No implementation information at this time.

**Comment by plehegar** [comment]
Approved.

**Comment by michael-n-cooper** [comment]
Published to https://www.w3.org/TR/2020/WD-WCAG22-20200227/
