### ISSUE TITLE
[CSSWG] CR transition for css-counter-styles-3

### ISSUE THREAD

**Issue by tabatkins** [w3c/transitions#23]
# Document title, URLs, estimated publication date
* CSS Counter Styles Level 3
* https://drafts.csswg.org/css-counter-styles/
* Dec 12?

# Abstract
This module introduces the ''@counter-style'' rule, which allows authors to define their own custom counter styles for use with CSS list-marker and generated-content counters [[CSS3LIST]]. It also predefines a set of common counter styles, including the ones present in CSS2 and CSS2.1.

# Status
Updated CR

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/www-style/2017Nov/0017.html

# Changes
https://drafts.csswg.org/css-counter-styles-3/#changes

# Requirements satisfied
n/a

# Dependencies met (or not)
* All dependencies are WD or above.
* Normative dependencies on WDs can be replaced by 2.1 if necessary, when this moves to Rec.

# Wide Review
https://drafts.csswg.org/css-counter-styles-3/issues-cr-20150611

# Issues addressed
https://drafts.csswg.org/css-counter-styles-3/issues-cr-20150611

# Formal Objections
None

# Implementation
* Firefox

# Patent disclosures
None

**Comment by swickr** [comment]
Updated CR transition is approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2017/CR-css-counter-styles-3-20171214/
