### ISSUE TITLE
FPWD Request for <Explainer: Improving Spoken Presentation on the Web>

### ISSUE THREAD

**Issue by ruoxiran** [w3c/transitions#232]
# Document title, URLs, estimated publication date
[
*Document title: Explainer: Improving Spoken Presentation on the Web
*snapshot URL: [https://raw.githack.com/w3c/pronunciation/FPWD-explainer-gap-20200310/snapshots/explainer/Overview.html](https://raw.githack.com/w3c/pronunciation/FPWD-explainer-gap-20200310/snapshots/gap-analysis-and-use-cases/Overview.html)
*estimated publication date: 10 March, 2020
]

# Abstract
[The objective of the Pronunciation Task Force is to develop normative specifications and best practices guidance collaborating with other W3C groups as appropriate, to provide for proper pronunciation in HTML content when using text to speech (TTS) synthesis. This document presents the results of the Pronunciation Task Force work on an HTML standard. It includes an introduction with a historical perspective, an enumeration of the core requirements, a listing of approach use cases, and finally a gap analysis. Gaps are defined when a requirement does not have a corresponding use case approach by which it can be authored in HTML.]

# Status
[This is a First Public Working Draft of Pronunciation Explainer by the Accessible Platform Architectures Working Group. It was initially developed by the Pronunciation Task Force.

To comment, file an issue in the W3C pronunciation GitHub repository. If this is not feasible, send email to public-pronunciation@w3.org (subscribe, archives). Comments are requested by 14 April 2020. In-progress updates to the document may be viewed in the publicly visible editors' draft.

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. The group does not expect this document to become a W3C Recommendation. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 1 March 2019 W3C Process Document.  ]

# Is it a delta specification intended to become a W3C Recommendation?
[no]

# Link to group's decision to request transition
[[https://lists.w3.org/Archives/Public/public-apa-admin/2020Mar/0000.html](https://lists.w3.org/Archives/Public/public-apa-admin/2020Mar/0000.html)]

# Information about implementations known to the Working Group
[Note-track, no implementation]

**Comment by plehegar** [comment]
Approved.

**Comment by plehegar** [comment]
Actually, the two translation got mixed.

I believe this one was meant to refer to
 https://raw.githack.com/w3c/pronunciation/509f22a80f31b7072b45389092fe7b36544c93fb/explainer/index.html

which doesn't use the proper license. Please fix the transition request and the license first.

**Comment by ruoxiran** [comment]
> Actually, the two translation got mixed.
> 
> I believe this one was meant to refer to
> https://raw.githack.com/w3c/pronunciation/509f22a80f31b7072b45389092fe7b36544c93fb/explainer/index.html
> 
> which doesn't use the proper license. Please fix the transition request and the license first.

Fixed, thank you. https://github.com/w3c/pronunciation/commit/b466f387bfdb9c0c6d7ff5ab44790c1a7acb4837

**Comment by ruoxiran** [comment]
> > Actually, the two translation got mixed.
> > I believe this one was meant to refer to
> > https://raw.githack.com/w3c/pronunciation/509f22a80f31b7072b45389092fe7b36544c93fb/explainer/index.html
> > which doesn't use the proper license. Please fix the transition request and the license first.
> 
> Fixed, thank you. [w3c/pronunciation@b466f38](https://github.com/w3c/pronunciation/commit/b466f387bfdb9c0c6d7ff5ab44790c1a7acb4837)

Sorry, the right link should be: https://raw.githack.com/w3c/pronunciation/FPWD-explainer-gap-20200310/snapshots/explainer/Overview.html

**Comment by plehegar** [comment]
Approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/WD-pronunciation-explainer-20200310/
