### ISSUE TITLE
CR Request for ttml-imsc1.2

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#234]
# Document title, URLs, estimated publication date
TTML Profiles for Internet Media Subtitles and Captions 1.2
https://w3c.github.io/imsc/imsc1/spec/ttml-ww-profiles.html
estimated publication date at 19th March 2020

# Abstract
https://w3c.github.io/imsc/imsc1/spec/ttml-ww-profiles.html#abstract

# Status
https://w3c.github.io/imsc/imsc1/spec/ttml-ww-profiles.html#sotd

# Link to group's decision to request transition
https://www.w3.org/2020/03/12-tt-minutes.html#t09

# Changes
https://w3c.github.io/imsc/imsc1/spec/ttml-ww-profiles.html#substantive-changes-summary

# Requirements satisfied
No requirements document

# Dependencies met (or not)

- Requirements document: https://w3c.github.io/imsc-vnext-reqs/
- References: https://w3c.github.io/imsc/imsc1/spec/ttml-ww-profiles.html#references
- External groups
  - https://lists.w3.org/Archives/Member/member-tt/2020Jan/0000.html
  - https://lists.w3.org/Archives/Member/member-tt/2020Jan/0001.html
  - https://lists.w3.org/Archives/Member/member-tt/2020Jan/0002.html
  - https://lists.w3.org/Archives/Member/member-tt/2020Jan/0003.html
  - https://lists.w3.org/Archives/Member/member-tt/2020Jan/0004.html
  - https://lists.w3.org/Archives/Member/member-tt/2020Jan/0005.html
  - https://lists.w3.org/Archives/Member/member-tt/2020Jan/0006.html

# Wide Review
Asked for HR at 16 Oct 2019, with 3 mo period.

* a11y: [mail for request](https://lists.w3.org/Archives/Public/public-tt/2019Oct/0041.html), list of issues https://github.com/w3c/imsc/issues?q=is%3Aissue+label%3Aa11y-needs-resolution
* i18n: [mail for request](https://lists.w3.org/Archives/Public/public-tt/2019Oct/0040.html), no issue raised
* privacy: response from Jeffrey Yaskin at https://lists.w3.org/Archives/Public/public-tt/2019Nov/0011.html and from Nick Doty at https://lists.w3.org/Archives/Public/public-tt/2020Mar/0013.html
* security: https://lists.w3.org/Archives/Public/public-web-security/2020Feb/0002.html
* TAG: w3ctag/design-reviews#474

# Issues addressed
issues were addressed at:
https://github.com/w3c/imsc/issues?q=is%3Aissue+label%3Aimsc1.2

# Formal Objections
None

# Implementation
For this specification to exit the CR stage, at least 2 independent implementations of every feature defined in this specification but not already present in either [TTML2](https://www.w3.org/TR/ttml2/) or [ttml-imsc1.1](https://www.w3.org/TR/ttml-imsc1.1/) need to be documented in the implementation report. The Working Group does not require that implementations are publicly available but encourages them to be so.

The Working Group has not identified features "at risk" for this specification.

Preliminary implementation report at https://www.w3.org/wiki/TimedText/IMSC1_2_Implementation_Report

# Patent disclosures
None
https://www.w3.org/2004/01/pp-impl/34314/status

**Comment by nigelmegitt** [comment]
@himorin The action to request HR is at https://github.com/w3c/ttwg/issues/76

**Comment by himorin** [comment]
Completed form as current status

**Comment by plehegar** [comment]
Looking at [references](https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fw3c.github.io%2Fimsc%2Fimsc1%2Fspec%2Fttml-ww-profiles.html):

the HTML5 reference needs to be to [HTML] instead (WHATWG HTML LS).

**Comment by palemieux** [comment]
> a11y: mail for request, list of issues https://github.com/w3c/imsc/issues?q=is%3Aissue+label%3Aa11y-needs-resolution

Based on an initial review of the issues, it does not look like resolving them will result in substantive changes to the specification.

**Comment by swickr** [comment]
Regarding https://github.com/w3c/imsc/issues/530 which is currently labeled as requiring resolution; I suggested adding an editorial note in [8.5.3](https://w3c.github.io/imsc/imsc1/spec/ttml-ww-profiles.html#text-font-source) pointing to the (currently still open) https://github.com/w3c/csswg-drafts/issues/4055.

https://github.com/w3c/imsc/pull/525 needs to be merged to update the HTML5 reference.

It appears to me that [namespaceState] only needs to be informative; that would resolve the "still a Working Draft" procedural question.

The SoTD needs to include the "Implementation" paragraph above in the transition request; in particular the CR exit criteria and deadline for review comments.

Otherwise, Transition approved.

**Comment by palemieux** [comment]
> w3c/imsc#525 needs to be merged to update the HTML5 reference.

It was merged couple of days ago on the IMSC 1.2 branch: https://github.com/w3c/imsc/pull/525/commits/8c3ad6943557ecd586b7c38eec059024a5d92359

> I suggested adding an editorial note in 8.5.3 pointing to the (currently still open) w3c/csswg-drafts#4055.

It is still not clear to me that the attack vector indicated at w3c/csswg-drafts#4055 is relevant to IMSC. Specifically, as I understand it, the attack vector involves a script running on a malevolent website  and accessing the user's font list. Is that correct? If so, IMSC does not specify any such scripting capability and/or any API that would allow the user's font list to be accessed.

Can someone explain to me the issue in simple terms?

**Comment by himorin** [comment]
> > [w3c/imsc#525](https://github.com/w3c/imsc/pull/525) needs to be merged to update the HTML5 reference.
> 
> It was merged couple of days ago on the IMSC 1.2 branch: [w3c/imsc@8c3ad69](https://github.com/w3c/imsc/commit/8c3ad6943557ecd586b7c38eec059024a5d92359)

I've updated my local copy to branch HEAD after respec processing
https://ttml-w3c.himor.in/CR-ttml-imsc1.2-20200324/
and original copy from this branch is
https://ttml-w3c.himor.in/CR-ttml-imsc1.2-20200324/Overview_orig.html

**Comment by himorin** [comment]
editorial note was added for font-based fingerprinting, also reference was updated, I've did publication request sent out. (Implementation report is already configured in respec config, pointing to TTWG wiki on w3.org.)

**Comment by palemieux** [comment]
@himorin What is the CR end date?

**Comment by himorin** [comment]
from [days calculator](https://w3c.github.io/spec-releases/milestones/?cr=2020-03-24), daedline for comment is Apr/21, CfC in group is Apr/25, PR transition need to be prepared by May/5.
I'll add a PR to update spec timeline.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/CR-ttml-imsc1.2-20200324/
