### ISSUE TITLE
FPWD Request for RTC Accessibility User Requirements

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/transitions#235]
# Document title, URLs, estimated publication date
Title: RTC Accessibility User Requirements
Anticipated publication date: 19 March 2020
Latest version URI: https://www.w3.org/TR/raur/
Anticipated publication URI: https://www.w3.org/TR/2020/WD-raur-20200319/
Editors' draft URI: https://w3c.github.io/apa/raur/

# Abstract
This document outlines various accessibility related user needs, requirements and scenarios for Real-time communication (RTC). These user needs should drive accessibility requirements in various related specifications and the overall architecture that enables it. It first introduces a definition of RTC as used throughout the document and outlines how RTC accessibility can support the needs of people with disabilities. It defines the term user needs as used throughout the document and then goes on to list a range of these user needs and their related requirements. Following that some quality related scenarios are outlined and finally a data table that maps the user needs contained in this document to related use case requirements found in other technical specifications.

This document is most explicitly not a collection of baseline requirements. It is also important to note that some of the requirements may be implemented at a system or platform level, and some may be authoring requirements.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

This is a First Public Working Draft of RTC Accessibility User Requirements by the Accessible Platform Architectures Working Group. It is developed by the Research Questions Task Force (RQTF) who work to identify accessibility knowledge gaps and barriers in emerging and future web technologies. The requirements outlined here come from research into user needs that then provide the basis for any technical requirements. This version is published to collect public feedback on the requirements prior to finalization as a Working Group Note.

To comment, file an issue in the W3C APA GitHub repository adding the RAUR label. If this is not feasible, send email to public-apa@w3.org (archives). Comments are requested by 21 April 2020. In-progress updates to the document may be viewed in the publicly visible editors' draft.

This document was published by the Accessible Platform Architectures Working Group as a First Public Working Draft.

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. The group does not expect this document to become a W3C Recommendation. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 1 March 2019 W3C Process Document. 

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-apa-admin/2020Mar/0004.html

# Information about implementations known to the Working Group
Note-track, no implementations.

**Comment by plehegar** [comment]
Approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/WD-raur-20200319/
