### ISSUE TITLE
REC Request for WoT Architecture and WoT Thing Description

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#236]
# Link to internal transition

https://lists.w3.org/Archives/Team/w3t-comm/2020Mar/0159.html

# Link to previous transition

https://github.com/w3c/transitions/issues/202
https://github.com/w3c/transitions/issues/203

cc @ashimura

**Comment by swickr** [comment]
Transition approved.

**Comment by ashimura** [comment]
Thanks a lot, @swickr !

We're planning to wrap up the discussion on the Press Release during the next WoT Marketing call on April 2, and publish the REC on April 9 along with the Press Release :)

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/REC-wot-architecture-20200409/
https://www.w3.org/TR/2020/REC-wot-thing-description-20200409/
