### ISSUE TITLE
Supersede Selectors API

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#237]
# title, URL of the document to be superseded
[Selectors API Level 1](https://www.w3.org/TR/selectors-api/), W3C Recommendation 21 February 2013
[Selectors API Level 2](https://www.w3.org/TR/selectors-api2/), published as a WG Note

# title, URL of the newer version
DOM Review Draft — Published 18 June 2019
https://dom.spec.whatwg.org/review-drafts/2019-06/

# Link to group's decision to request superseding
https://lists.w3.org/Archives/Public/public-webapps/2020JanMar/0001.html

# Rationale
The Selectors API has been merged into WHATWG DOM.
https://github.com/w3c/webappswg/issues/21#issue-493689685

# Implementation
The Selectors API was published as a Rec in 2013 and has been widely implemented by the browser vendors.

**Comment by swickr** [comment]
Approved to go to AC Review.

**Comment by plehegar** [comment]
for Level 1, follow the example like:
  https://lists.w3.org/Archives/Member/w3c-ac-members/2018AprJun/0041.html

for Level 2, no Director invoilvement. just ask webmaster to retire WG Note. You may to update the SOTD of that Note as well.

**Comment by plehegar** [comment]
in AC review
