### ISSUE TITLE
[CSSWG] FPWD Request for CSS Box Model Module Level 4

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#238]
# Document title, URLs, estimated publication date
CSS Box Model Module Level 4
Proposed shortname: css-box-4
ED: https://drafts.csswg.org/css-box-4/

# Abstract
This specification describes the margin and padding properties, which create spacing in and around a CSS box.

# Status
https://drafts.csswg.org/css-box-4/#status

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/www-style/2020Feb/0011.html

# Information about implementations known to the Working Group
None for the new stuff, most of it is just copied off of CSS2.

**Comment by plehegar** [comment]
Approved

**Comment by fantasai** [comment]
Whoever publishes this, lmk, so I can push a copy of css-box-3 simultaneously. Basically all we did was copy over the latest draft of css-box-3 to css-box-4, and dropped all the new features from L3 so that it's just a pile of definitions and CSS2 stuff.

**Comment by svgeesus** [comment]
Publication request sent 20 April, expected publication 21 April

**Comment by svgeesus** [comment]
[Published 21 April 2020](https://www.w3.org/TR/2020/WD-css-box-4-20200421/)
