### ISSUE TITLE
[meta] CR Transition request headers are not self-explanatory

### ISSUE THREAD

**Issue by tabatkins** [w3c/transitions#24]
I'm filling out a new CR Transition request, and having to ask fantasai what several of the sections are asking for.

She says that this is addressed by <https://www.w3.org/Guide/transitions> (which is linked in the README), but I don't see any immediate mapping; I'd have to fully digest this document and hope that it does explain every heading (and skimming it now, it looks like it *doesn't*).

At minimum, the headings should have something like:

```
# Status
[TODO: whatever Status means]
```

Which we can then replace with whatever we're supposed to.

**Comment by plehegar** [comment]
Started to clarify tings: https://github.com/w3c/transitions/commit/a7eae19a3127645522bb0888caa817357f9adcda
Ideally, it would be better to have a transition request generator, to prefill a lot of the info.

**Comment by svgeesus** [comment]
Last few times I filled these in, the requested `[TODO: whatever] were all there.

Can this be closed as solved, @tabatkins ?

**Comment by tabatkins** [comment]
Yeah, the templates look good now. Thanks!
