### ISSUE TITLE
FPNote for JSON-LD-streaming

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#240]
# Document title, URLs, estimated publication date

- Streaming JSON-LD
- Editor's draft: https://w3c.github.io/json-ld-streaming/
- Estimated publication date: 2020-05-05. Note that the goal is to publish this note on the same day (and announce it in HPN) together with the JSON-LD PR publication, if that is accepted by the Director. See #239.
- Requested short name: json-ld11-streaming

# Abstract

- See https://w3c.github.io/json-ld-streaming/#abstract

# Status

- See https://w3c.github.io/json-ld-streaming/#sotd

# Link to group's decision to request transition

- https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-04-17-json-ld#resolution3

# Information about implementations known to the Working Group

- There is an implementation optimized for streaming for an RDF to JSON-LD 1.1 parser, as well as a JSON-LD 1.1 to RDF serializer. These are also part of the [JSON-LD 1.1 Implementation report](https://w3c.github.io/json-ld-api/reports/)

---

Cc: Cc: @gkellogg  @BigBlueHat @azaroth42 @rubensworks

**Comment by plehegar** [comment]
Approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/NOTE-json-ld11-streaming-20200507/
