### ISSUE TITLE
FPWD Request for Image Resource

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#242]
# Document title, URLs, estimated publication date
Image Resource
https://www.w3.org/TR/image-resource/
https://w3c.github.io/image-resource/?specStatus=FPWD
5 May 2020

# Abstract
This document defines the concept of an "image resource" and a corresponding WebIDL ImageResource dictionary. Web APIs can use the ImageResource dictionary to represent an image resource in contexts where an HTMLImageElement is not suitable or available (e.g., in a Worker).

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

This specification is not stable. Implementors who are not taking part in the discussions will find the specification changing out from under them in incompatible ways.

This document was published by the Web Applications Working Group as a First Public Working Draft. This document is intended to become a W3C Recommendation.

GitHub Issues are preferred for discussion of this specification.
Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.
This document is governed by the 1 March 2019 W3C Process Document.

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://github.com/w3c/image-resource/issues/17

# Information about implementations known to the Working Group
It was a spec extracted from the Web Manifest spec.

**Comment by plehegar** [comment]
Approved.

I note that this specification is missing a security and privacy considerations section. I would expect that, either:
* the document will contain such section by the time it reaches CR,
* or that there is a rational for not having it which got reviewed by the security and privacy folks.

**Comment by siusin** [comment]
Thanks @plehegar . The group planned to add the Priv/Sec section after FWPD.

**Comment by marcoscaceres** [comment]
Filed bug about Privacy/Sec section https://github.com/w3c/image-resource/issues/21

**Comment by siusin** [comment]
Spec was published on 07 May 2020.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/WD-image-resource-20200508/
