### ISSUE TITLE
PR Request for DOM Review Draft — Published 18 June 2019

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#243]
# Document title, URLs, estimated publication date
DOM
Review Draft — Published 18 June 2019
https://dom.spec.whatwg.org/review-drafts/2019-06/#w3c-rec
https://www.w3.org/TR/2020/PR-dom-20200512/
12 May 2020

# Abstract
DOM defines a platform-neutral model for events, aborting activities, and node trees.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

The following are non-normative for the purpose of the W3C Proposed Recommendation:

* `AbstractRange` (lacks two implementations in current engines)
* `document.origin` (lacks two implementations in current engines)

The W3C HTML Working Group co-produced this document under the W3C Patent Policy and the 01 March 2019 W3C Process Document. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

# Link to group's decision to request transition
https://github.com/w3c/htmlwg/issues/9

# Changes
None.

# Requirements satisfied
Yes.

# Dependencies met (or not)
Some of the Normative References (Service Workers 1, UIEvents) are still under development, but the group believe all the terms referenced by this review draft are valid and widely implemented.

# Wide Review
[w3c/htmlwg#4](https://github.com/w3c/htmlwg/issues/4)
The HTML WG have sent out the Call for Review to the A11y groups, the i18n WG, the Security mailing list, the Privacy IG and the TAG.
By the end of the review period no issues raised that would block this transition.

# Issues addressed
There are still open issues for DOM, but this review draft has already identified the non-normative features in the W3C Recommendation Status section.

# Formal Objections
None.

# Implementation
https://wpt.fyi/results/dom?label=experimental&label=master&aligned
Most of the test failures are because of corner cases or historical cases.
The group identified two non-normative features based on the follow test results:
AbstractRange (https://wpt.fyi/results/dom/idlharness.window.html%3Fexclude%3DNode?label=experimental&label=master&aligned)
document.origin ( https://wpt.fyi/results/dom/historical.html?label=experimental&label=master&aligned )

# Patent disclosures
https://www.w3.org/2004/01/pp-impl/44556/status

**Comment by plehegar** [comment]
For the SOTD, we should make sure to go through the list of requirements at
 https://www.w3.org/pubrules/doc/rules/?profile=PR#document-status
(such as WBS for AC and end date of review).

In addition, we should the following sentence:
 "This specification is intended to supersede DOM Level 1, DOM Level 2 (Core, Events, Traversal and Range, HTML), Element Traversal, DOM Level 3 Core, and DOM4 W3C Recommendations."

(please check that no Recommendation was wrongfully omitted from that sentence)

**Comment by plehegar** [comment]
Note that we will need to update or retire https://www.w3.org/DOM/DOMTR .

Conside also retiring  the DOM Requirements note

**Comment by swickr** [comment]
Transition approved.
Thanks for the great work.

**Comment by xfq** [comment]
> In addition, please add the following sentence:
> "This specification is intended to supersede DOM Level 1, DOM Level 2 (Core, Events, Traversal and Range, HTML), Element Traversal, DOM Level 3 Core, and DOM4 W3C Recommendations."
> 
> (please check that no Recommendation was wrongfully omitted from that sentence)

There may be other DOM L2/L3 RECs, and the Selectors API as well. But maybe not all of them are in the current DOM Review Draft (for example, some of them are in UI Events now). (I made a list in 2017: https://github.com/w3c/WebPlatformWG/issues/96#issuecomment-332071471 )

**Comment by plehegar** [comment]
I don't think the other L2s are applicables. Load/Save, Schemas, Validation, etc. aren't replaced by the new DOM REC and still fully applicable to implementations like Xerces. I restricted the scope to the functionalities include in the DOM snapshots. open for input here.
 
Good catch on Selectors API.

Views and Style are about CSSOM and CSSOM View. it's up to CSS to supersede them imho.

**Comment by sideshowbarker** [comment]
> In addition, please add the following sentence:
> "This specification is intended to supersede DOM Level 1, DOM Level 2 (Core, Events, Traversal and Range, HTML), Element Traversal, DOM Level 3 Core, and DOM4 W3C Recommendations."

While I don’t see any issues in principle with adding such as statement, I can’t find any similar statement in the https://www.w3.org/2019/01/whatwg-w3c-sample.html#w3c-rec *“Sample Jointly Published Document”* that’s part of the MoU.

Is there something I’m missing? Is the addition of such a statement covered or implied somewhere else in the MoU?

If not, I have to ask if it’s really OK for us to add it unilaterally at this point, or whether it’s something we need to give the WHATWG SG a heads-up about and get their explicit sign-off on.

Also, I note that https://dom.spec.whatwg.org/#goals already mentions a set of specifications which it implicitly supersedes:

> This specification standardizes the DOM. It does so as follows:
> 
> 1. By consolidating DOM Level 3 Core [DOM-Level-3-Core], Element Traversal [ELEMENTTRAVERSAL], Selectors API Level 2 [SELECTORS-API2], the "DOM Event Architecture" and "Basic Event Interfaces" chapters of DOM Level 3 Events [uievents-20031107] (specific types of events do not belong in the DOM Standard), and DOM Level 2 Traversal and Range [DOM-Level-2-Traversal-Range]…
> …
> 2. By defining a replacement for the "Mutation Events" and "Mutation Name Event Types" chapters of DOM Level 3 Events [uievents-20031107] as the old model was problematic.

Notably, that existing statement in the spec mentions parts of DOM Level 3 Events, while the proposed statement in https://github.com/w3c/transitions/issues/243#issuecomment-626008462 doesn’t mention DOM Level 3 Events at all.

So I’m uncertain how to proceed with this.

**Comment by plehegar** [comment]
It's meant to appear in the SOTD of the Proposed Recommendation and will be removed in the final Recommendation.

**Comment by hober** [comment]
I'm surprised to see the PR is not a redirect to the Review Draft on whatwg.org. I thought that was the plan?

**Comment by othermaciej** [comment]
Pointing to the whatwg.org copy is what is described in the Memorandum of Understanding between W3C and WHATWG. See section 5, "Format of jointly published documents".

https://www.w3.org/2019/04/WHATWG-W3C-MOU.html

**Comment by siusin** [comment]
@hober 
The document was published yesterday. It's a redirect to the June 2019 Review Draft PR snapshot:
https://www.w3.org/TR/2020/PR-dom-20200514/

Once DOM PR gets published:

> /TR/dom/              r> dom.spec.whatwg.org
> /TR/dom/latest/       r> PR-dom-20200514
> /TR/dom/upcoming/     r> dom.spec.whatwg.org
> /TR/dom/ed/           r> dom.spec.whatwg.org
> /TR/dom41/            p> NOTE-dom41-20200319
> /TR/DOM-Level-3-Core/ p> REC-DOM-Level-3-Core-20040407
> /TR/DOM-Level-2-Core/ p> REC-DOM-Level-2-Core-20001113
> /TR/REC-DOM-Level-1/  p> REC-DOM-Level-1-19981001
> /TR/dom/rec/          r> REC-dom-20151119
> PR-dom-20200514       r> dom.spec.whatwg.org/review-drafts/2019-06/

**Comment by hober** [comment]
> The document was published yesterday. It's a redirect to the June 2019 Review Draft PR snapshot:
> https://www.w3.org/TR/2020/PR-dom-20200514/

When I navigate to that URL, my browser is not redirected. The URL in the location bar remains the same.

**Comment by siusin** [comment]
@hober it may be a caching issue, could you refresh and try again? It works for me on Safari V13.1.

**Comment by hober** [comment]
> @hober it may be a caching issue, could you refresh and try again? It works for me in Safari v13.1.

I tried in two different browsers. One of them had never loaded the page before. Both do not redirect and remain at w3.org.

**Comment by deniak** [comment]
There was a mirroring issue on one of our server. It should now be fixed and it should redirect to the whatwg.org snapshot now:
```
$ curl -L -I https://www.w3.org/TR/2020/PR-dom-20200514/
HTTP/1.1 301 Moved Permanently
date: Tue, 19 May 2020 07:16:48 GMT
location: https://dom.spec.whatwg.org/review-drafts/2019-06/
cache-control: max-age=31536000
expires: Wed, 19 May 2021 07:16:48 GMT
content-type: text/html; charset=iso-8859-1
strict-transport-security: max-age=15552000; includeSubdomains; preload
content-security-policy: upgrade-insecure-requests

HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Tue, 19 May 2020 07:16:51 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 1504112
Last-Modified: Fri, 08 May 2020 12:32:59 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "5eb5517b-16f370"
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Accept-Ranges: bytes
```

**Comment by hober** [comment]
> There was a mirroring issue on one of our server. It should now be fixed and it should redirect to the whatwg.org snapshot now[…]

Yup, looks like it's working now. Thanks for fixing this!

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/PR-dom-20200514/
