### ISSUE TITLE
[CSSWG] FPWD Request for CSS Sizing Level 4

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#244]
# Document title, URLs, estimated publication date
CSS Box Sizing Module Level 4
https://drafts.csswg.org/css-sizing-4/

# Abstract
https://drafts.csswg.org/css-sizing-4/#abstract

# Status
https://drafts.csswg.org/css-sizing-4/#status

# Is it a delta specification intended to become a W3C Recommendation?
Yes, but we plan to merge the main text inline prior to CR.

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/www-style/2020May/0008.html

# Information about implementations known to the Working Group
Initial work has begun in Chrome for aspect-ratio and contain-intrinsic-size; several have at least implementations of 'stretch' and 'fit-content' behind a keyword.

**Comment by plehegar** [comment]
Approved

**Comment by xfq** [comment]
Reopening because it hasn't been published yet.

**Comment by xfq** [comment]
In the [References](https://drafts.csswg.org/css-sizing-4/#references) section, there is a link to `[CSS-ALIGN-4]`, which is a broken link. @fantasai Can you fix this?

**Comment by fantasai** [comment]
@xfq I think I figured it out, there was stale data in the spec database. Try rebuilding?

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2020/WD-css-sizing-4-20200526/
