### ISSUE TITLE
FPWD Request for Rules for Simple Placement of Japanese Ruby

### ISSUE THREAD

**Issue by r12a** [w3c/transitions#246]
# Document title, URLs, estimated publication date
Rules for Simple Placement of Japanese Ruby
https://www.w3.org/TR/2020/WD-simple-ruby-20200609/
for 9 Jun 2020

Not intended for Rec track.  Aiming for WG Note.

# Abstract
A simple set of rules for placement of Ruby text in Japanese typography.

# Status
https://www.w3.org/TR/2020/WD-simple-ruby-20200609/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://www.w3.org/2020/06/04-i18n-minutes.html#item05

# Information about implementations known to the Working Group
n/a

**Comment by plehegar** [comment]
approved

**Comment by r12a** [comment]
Draft announcement text:

> The Internationalization Working Group has published a First Public Working Draft of Rules for Simple Placement of Japanese Ruby. This document provides a simple set of rules for placement of Ruby text in Japanese typography that can be used as a minimum baseline for implementers and specification writers.

> Ruby is the name given to the small annotations in Japanese content that are rendered alongside base text, usually to provide a pronunciation guide, but sometimes to provide other information.

**Comment by aphillips** [comment]
Ruby isn't, of course, a strictly Japanese mechanism. The last paragraph implies that it is. Perhaps:

> Ruby is the name given to small annotations that are rendered alongside the primary (base) text in languages such as Japanese, usually to provide a pronunciation guide, but sometimes to provide other information.

**Comment by r12a** [comment]
It's true, but the CLReq folks don't refer to it as ruby – they call them annotations.  And the document is specific to how ruby is managed in Japanese, which is why we changed the document title to reflect that.   It doesn't cover chinese needs.

**Comment by aphillips** [comment]
We split the difference by calling them "ruby annotations" I guess? 😉 "Ruby" isn't the Japanese endonym for these annotations either. 

The first paragraph takes care of indicating that this is about *Japanese* ruby. My concern (and the reason I bothered to comment) is that I think we should take care to avoid perpetuating the myth that ruby annotation is strictly a Japanese concern.

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2020/WD-simple-ruby-20200609/

(We can move Addison's comment into an issue in the simple-ruby repo if needed.)
