### ISSUE TITLE
FPNote for DID Specification Registries

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#247]
# Document title, URLs, estimated publication date

- title: DID Specification Registries
- editors' version: https://w3c.github.io/did-spec-registries/
- editors' version of the FPWD: https://w3c.github.io/did-spec-registries/FPWD/2020-06-18/
- expected publication date: 2020-06-18
- expected URL with short name: https://www.w3.org/TR/did-spec-registries/
- expected Dated URI: https://www.w3.org/TR/2020/NOTE-did-spec-registries-20200618/

# Abstract

This document serves as an official registry for all known global parameters, properties, and values used by the Decentralized Identifier ecosystem.

# Status

See: https://w3c.github.io/did-spec-registries/#sotd

# Link to group's decision to request transition

https://www.w3.org/2019/did-wg/Meetings/Minutes/2020-06-09-did#resolution1

# Information about implementations known to the Working Group

n/a

Cc: @OR13, @msporny, @burnburn, @brentzundel

**Comment by plehegar** [comment]
Approved, including the funding paragraphs included in the SOTD. For future iterations, you should more explicit on who gets to approve pull requests for new entries in section 4.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/NOTE-did-spec-registries-20200618/
