### ISSUE TITLE
CR Request for the January 2020 HTML Standard Review Draft

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#248]
# Document title, URLs, estimated publication date
HTML
Review Draft — Published 29 January 2020
June 23 2020
https://html.spec.whatwg.org/review-drafts/2020-01/
https://www.w3.org/TR/html/

# Abstract
None.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

The following features are at-risk for the purpose of the W3C Candidate Recommendation:

OffscreenCanvas
scrollPathIntoView() method of CanvasRenderingContext2D
srcObject setter for HTMLMediaElement, with media provider other than MediaStream (that is, a MediaSource or Blob)
close() method of SharedWorkerGlobalScope
alternative style sheets
autocapitalization
theme-color
accessKeyLabel property of HTMLElement
:dir pseudo-class
"preload" link type
"modulepreload" link type
"prerender" link type
"dragexit" event
"cancel" event
"oncancel" event handler
The W3C HTML Working Group co-produced this document under the W3C Patent Policy and the 01 March 2019 W3C Process Document. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

# Link to group's decision to request transition
https://github.com/w3c/htmlwg/issues/12

# Changes
https://github.com/w3c/htmlwg/issues/8 contains a list of Pull Requests between Jul 2019 and Jan 2020.

# Requirements satisfied
None.

# Dependencies met (or not)
All the normative references of this version are lists in the [References](https://html.spec.whatwg.org/review-drafts/2020-01/#references) section. The group believes these references are stable and have been reviewed by the editors.

# Wide Review
https://github.com/w3c/htmlwg/issues/8
No substantive issues were raised during the wide and horizontal review.

# Issues addressed
There are still open issues for HTML, but the editors believe this review draft is good enough to move to CR.

# Formal Objections
None during the CfC.

# Implementation
The following features are at-risk for the purpose of the W3C Candidate Recommendation:

- OffscreenCanvas
- scrollPathIntoView() method of CanvasRenderingContext2D
- srcObject setter for HTMLMediaElement, with media provider other than MediaStream (that is, a MediaSource or Blob)
- close() method of SharedWorkerGlobalScope
- alternative style sheets
- autocapitalization
- theme-color
- accessKeyLabel property of HTMLElement
- :dir pseudo-class
- "preload" link type
- "modulepreload" link type
- "prerender" link type
- "dragexit" event
- "cancel" event
- "oncancel" event handler

# Patent disclosures
https://www.w3.org/2004/01/pp-impl/115520/status

**Comment by swickr** [comment]
The last two sentences in the yellow box must be removed.  See the [sample document](https://www.w3.org/2019/01/whatwg-w3c-sample.html#w3c-rec) from the MoU.  The variation in the first paragraph is OK.

Transition approved pending the change above.

Please add an expected duration of CR in the SoTD.
Please correct the patent disclosure link to https://www.w3.org/2004/01/pp-impl/115520/status

**Comment by siusin** [comment]
https://html.spec.whatwg.org/review-drafts/2020-01/ (updated by @sideshowbarker ) will be published as https://www.w3.org/TR/2020/CR-html-2020618/;

@deniak will also create the following redirects 
https://www.w3.org/TR/html/latest -> https://html.spec.whatwg.org/review-drafts/2020-01/
and https://www.w3.org/TR/html5/latest -> https://html.spec.whatwg.org/review-drafts/2020-01/;
https://www.w3.org/TR/html/ -> https://html.spec.whatwg.org/

Draft announcement:
https://lists.w3.org/Archives/Team/w3t-comm/2020Jun/0127.html

@swickr @plehegar could you review these links for the publication?

**Comment by plehegar** [comment]
should be https://www.w3.org/TR/2020/CR-html-20200618/ (you're missing a 0)

 https://www.w3.org/TR/html5/latest ->  https://www.w3.org/TR/latest 
(which will then redirect to https://html.spec.whatwg.org/review-drafts/2020-01/ )

 https://www.w3.org/TR/html/upcoming ->  https://html.spec.whatwg.org/

**Comment by plehegar** [comment]
note: before we publish the Proposed Recommendation, you'll need to come with a full list of documents to retire once HTML becomes a new REC. (you can start by looking at the MoU for that).

**Comment by siusin** [comment]
Ok, will do :)

**Comment by siusin** [comment]
Published: 
https://www.w3.org/TR/2020/CR-html-20200618/

**Comment by LJWatson** [comment]
If someone could give me a list of the specs to retire I'll put a CFC to the WG together. Sorry to ask someone else to do the hard work - I'm a bit pressed for time at present. Thanks!

**Comment by plehegar** [comment]
@LJWatson , just to be sure: most of the specs to retire are part of the MoU and therefore have already been decided by the Director. We should come back to your question once we have the list but let's make sure not to put a CfC that would revisite the MoU.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/CR-html-20200618/

**Comment by plehegar** [comment]
For the list of documents to retire: add DOM HTML.
