### ISSUE TITLE
FPWD Request for Dutch, Georgian, Greek, & Hungarian Gap-analysis (5 docs)

### ISSUE THREAD

**Issue by r12a** [w3c/transitions#249]
# Document title, URLs, estimated publication date
Estimated pub date for all 5 docs: 11 June 2020

Dutch Gap Analysis
https://www.w3.org/TR/2020/WD-latn-nl-gap-20200611/

Ethiopic Gap Analysis
https://www.w3.org/TR/2020/WD-elreq-gap-20200611/

Georgian Gap Analysis
https://www.w3.org/TR/2020/WD-geor-gap-20200611/

Greek Gap Analysis
https://www.w3.org/TR/2020/WD-grek-gap-20200611/

Hungarian Gap Analysis
https://www.w3.org/TR/2020/WD-latn-hu-gap-20200611/

# Abstract
This document describes and prioritises gaps for the support of Georgian on the Web and in eBooks. In particular, it is concerned with text layout. It checks that needed features are supported in W3C specifications, in particular HTML and CSS and those relating to digital publications. It also checks whether the features have been implemented in browsers and ereaders. This is a preliminary analysis.

(Same abstract for all docs, except for language name.)

# Status
https://www.w3.org/TR/2020/WD-latn-nl-gap-20200611/#sotd
https://www.w3.org/TR/2020/WD-elreq-gap-20200611/#sotd
https://www.w3.org/TR/2020/WD-geor-gap-20200611/#sotd
https://www.w3.org/TR/2020/WD-grek-gap-20200611/#sotd
https://www.w3.org/TR/2020/WD-latn-hu-gap-20200611/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://www.w3.org/2020/05/28-i18n-minutes.html#item07

# Information about implementations known to the Working Group
n/a

**Comment by xfq** [comment]
All published. Thanks @r12a @plehegar!

Closing.
