### ISSUE TITLE
FPWD Request for 16 gap-analysis & 3 layout docs

### ISSUE THREAD

**Issue by r12a** [w3c/transitions#250]
# Document title, URLs, estimated publication date

Proposed publication date: 16 Jun 2020

**Gap-analysis docs**

Arabic & Persian Gap Analysis
https://w3c.github.io/alreq/gap-analysis/
https://www.w3.org/TR/2020/WD-alreq-gap-20200616/

Chinese Layout Gap Analysis
https://w3c.github.io/clreq/gap-analysis/
https://www.w3.org/TR/2020/WD-clreq-gap-20200616/

Bengali Gap Analysis
https://w3c.github.io/iip/gap-analysis/beng-gap.html
https://www.w3.org/TR/2020/WD-beng-gap-20200616/

Devanagari Gap Analysis
https://w3c.github.io/iip/gap-analysis/deva-gap.html
https://www.w3.org/TR/2020/WD-deva-gap-20200616/

Gurmukhi Gap Analysis
https://w3c.github.io/iip/gap-analysis/guru-gap.html
https://www.w3.org/TR/2020/WD-guru-gap-20200616/

Gujarati Gap Analysis
https://w3c.github.io/iip/gap-analysis/gujr-gap.html
https://www.w3.org/TR/2020/WD-gujr-gap-20200616/

Tamil Gap Analysis
https://w3c.github.io/iip/gap-analysis/taml-gap.html
https://www.w3.org/TR/2020/WD-taml-gap-20200616/

Japanese Gap Analysis
https://w3c.github.io/jlreq/gap-analysis/
https://www.w3.org/TR/2020/WD-jpan-gap-20200616/

Inuktitut & Cree Gap Analysis
https://w3c.github.io/amlreq/gap-analysis/iu-cr-gap/
https://www.w3.org/TR/2020/WD-cans-iu-cr-gap-20200616/

Cherokee Gap Analysis
https://w3c.github.io/amlreq/gap-analysis/cher-gap/
https://www.w3.org/TR/2020/WD-cher-gap-20200616/

Lao Gap Analysis
https://w3c.github.io/sealreq/gap-analysis/laoo-gap.html
https://www.w3.org/TR/2020/WD-laoo-gap-20200616/

Khmer Gap Analysis
https://w3c.github.io/sealreq/gap-analysis/khmr-gap.html
https://www.w3.org/TR/2020/WD-khmr-gap-20200616/

Javanese Script Gap Analysis
https://w3c.github.io/sealreq/gap-analysis/java-gap.html
https://www.w3.org/TR/2020/WD-java-gap-20200616/

Thai Script Gap Analysis
https://w3c.github.io/sealreq/gap-analysis/thai-gap.html
https://www.w3.org/TR/2020/WD-thai-gap-20200616/

Mongolian Gap Analysis
https://w3c.github.io/mlreq/gap-analysis/
https://www.w3.org/TR/2020/WD-mong-gap-20200616/

Tibetan Gap Analysis
https://w3c.github.io/tlreq/gap-analysis/
https://www.w3.org/TR/2020/WD-tibt-gap-20200616/

**Layout requirements docs:**

Tamil Layout Requirements
https://w3c.github.io/iip/tamil/
https://www.w3.org/TR/2020/WD-ilreq-taml-20200616/

Mongolian Layout Requirements
https://w3c.github.io/mlreq/
https://www.w3.org/TR/2020/WD-mlreq-20200616/

Requirements for Tibetan Text Layout and Typography
https://w3c.github.io/tlreq/
https://www.w3.org/TR/2020/WD-tlreq-20200616/

# Abstract
_All GA docs have an abstract like this:_

This document describes and prioritises gaps for the support of languages using the Gujarati script on the Web and in eBooks. In particular, it is concerned with text layout. It checks that needed features are supported in W3C specifications, in particular HTML and CSS and those relating to digital publications. It also checks whether the features have been implemented in browsers and ereaders. This is a preliminary analysis.

_Layout requirements doc abstracts follow this pattern:_

This document describes requirements for the layout and presentation of text in languages that use the Mongolian script when they are used by Web standards and technologies, such as HTML, CSS, Mobile Web, Digital Publications, and Unicode.

# Status
See the links above.

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://www.w3.org/2020/05/28-i18n-minutes.html#item07

# Information about implementations known to the Working Group
n/a

**Comment by plehegar** [comment]
Approved.

Thank you for ensuring we can use the Web all around the world!

**Comment by plehegar** [comment]
All documents have been published.
