### ISSUE TITLE
FPNote for Extensions to the OWL-Time Ontology - temporal aggregates

### ISSUE THREAD

**Issue by tguild** [w3c/transitions#251]
# Document title, URLs, estimated publication date

Extensions to the OWL-Time Ontology - temporal aggregates
https://w3c.github.io/sdw/time-aggregates/
2020-07-07

# Abstract

OWL-Time [owl-time] is an ontology for temporal entities and relations between them. OWL-Time defines simple temporal entities (intervals and instants). This note adds one new class time:TemporalAggregate and two properties time:hasPart and its inverse time:isPartof to allow for the description of arbitrary aggregates of temporal entities. 

# Status

For OGC - This is a Public Draft of a document prepared by the Spatial Data on the Web Interest Group (SDWIG) — a joint W3C-OGC project (see charter). The document is prepared following W3C conventions. This document is not an OGC Standard. This document is distributed for review and comment. This document is subject to change without notice and may not be referred to as an OGC Standard. Recipients of this document are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation.

New classes and properties are introduced in this extension to OWL-Time. The new elements concern temporal entities which cannot be expressed in OWL-Time. The ontology document imports OWL-Time, and adds the new elements and axioms. IRIs denoting the new elements are placed in the OWL-Time namespace since it is expected that they could be added to the normative ontology in a future revision of OWL-Time.

This document was published by the Spatial Data on the Web Interest Group as an Interest Group Note.

 GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-sdwig@w3.org (archives).

Publication as an Interest Group Note does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

The group does not expect this document to become a W3C Recommendation. The disclosure obligations of the Participants of this group are described in the charter.

**SDWIG intends to recharter as a WG and will likely seek to put this document on REC track. As it will be a different group the above Respec generated statement is accurate.

This document is governed by the 1 March 2019 W3C Process Document. 

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-sdwig/2020Apr/0041.html

# Information about implementations known to the Working Group

Time Ontology in use as is this extension.

**Comment by plehegar** [comment]
approved.

**Comment by tguild** [comment]
Published
