### ISSUE TITLE
REC Request for DOM

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#253]
# Link to internal transition

https://lists.w3.org/Archives/Team/w3t-comm/2020Jul/0043.html

# Link to previous transition

  https://github.com/w3c/transitions/issues/243

cc @siusin @sideshowbarker @LJWatson @hober

**Comment by plehegar** [comment]
I lost my list of documents to supersede/retire for the publication of DOM 😒
So, here it is again an attempt to compile it:

From the MOU:
  https://www.w3.org/TR/2015/REC-dom-20151119/

From [/TR](https://www.w3.org/TR/?tag=dom):
  https://www.w3.org/TR/2004/NOTE-DOM-Requirements-20040226/
  https://www.w3.org/TR/2008/REC-ElementTraversal-20081222/
  https://www.w3.org/TR/2000/REC-DOM-Level-2-Core-20001113/
  https://www.w3.org/TR/2000/REC-DOM-Level-2-Traversal-Range-20001113/
  https://www.w3.org/TR/2000/REC-DOM-Level-2-Style-20001113/
  https://www.w3.org/TR/2000/REC-DOM-Level-2-Events-20001113/
  https://www.w3.org/TR/2003/REC-DOM-Level-2-HTML-20030109/
  https://www.w3.org/TR/2000/REC-DOM-Level-2-Views-20001113/
  https://www.w3.org/TR/2002/NOTE-DOM-Level-3-AS-20020725/
  https://www.w3.org/TR/2004/NOTE-DOM-Level-3-Views-20040226/
  https://www.w3.org/TR/2004/NOTE-DOM-Level-3-XPath-20040226/
  https://www.w3.org/TR/2013/REC-selectors-api-20130221/  

  

 I note that [Xerces](https://xerces.apache.org/news.html) keeps getting updated and references DOM Level 2 and Level 3 but hasn't received significant updates in the last 2 years. Can we retire most of Level 3? 🤔 (I chose to start with Level 2 at least).
 The DOM HTML modules can be retired once HTML becomes a REC.
For UIEvents, that's up to WebApps.

**Comment by sideshowbarker** [comment]
For the Recommendations in the https://github.com/w3c/transitions/issues/253#issuecomment-661077844 list, the following are ready for announcement/publication on November 3 —

* https://www.w3.org/TR/2020/SPSD-DOM-Level-2-Core-20201103/
* https://www.w3.org/TR/2020/SPSD-DOM-Level-2-Events-20201103/
* https://www.w3.org/TR/2020/SPSD-DOM-Level-2-HTML-20201103/
* https://www.w3.org/TR/2020/SPSD-DOM-Level-2-Style-20201103/
* https://www.w3.org/TR/2020/SPSD-DOM-Level-2-Traversal-Range-20201103/
* https://www.w3.org/TR/2020/SPSD-DOM-Level-2-Views-20201103/
* https://www.w3.org/TR/2020/SPSD-ElementTraversal-20201103/
* https://www.w3.org/TR/2020/SPSD-dom-20201103/
* https://www.w3.org/TR/2020/SPSD-selectors-api-20201103/

For the Notes in the https://github.com/w3c/transitions/issues/253#issuecomment-661077844 list, I’ll have equivalents in place by the end of the week (also for announcement/publication on November 3).

**Comment by sideshowbarker** [comment]
The following Retired Notes are ready for announcement/publication on November 3 —

* https://www.w3.org/TR/2020/NOTE-DOM-Level-3-AS-20201103/
* https://www.w3.org/TR/2020/NOTE-DOM-Level-3-Views-20201103/
* https://www.w3.org/TR/2020/NOTE-DOM-Level-3-XPath-20201103/
* https://www.w3.org/TR/2020/NOTE-DOM-Requirements-20201103/

**Comment by swickr** [comment]
Approved and [published](https://dom.spec.whatwg.org/review-drafts/2019-06/)
