### ISSUE TITLE
CR Update Request for Media Queries Level 4

### ISSUE THREAD

**Issue by frivoal** [w3c/transitions#255]
# Document URLs
Current CR: https://www.w3.org/TR/mediaqueries-4/
ED to be published: https://drafts.csswg.org/mediaqueries-4/

# Link to group's decision to request transition
https://logs.csswg.org/irc.w3.org/css/2020-07-15/#e1332610

# Link to previous Candidate Recommendation transition request
https://lists.w3.org/Archives/Member/w3c-css-wg/2017JulSep/0103.html

# Substantive changes
https://drafts.csswg.org/mediaqueries-4/#changes-2017-9

# Any changes in requirements?
None

# Wide Review of substantive changes
Disposition of comments:
 https://drafts.csswg.org/mediaqueries-4/issues-cr-2017-09-05

Calls for wide/horizontal review:
 - about 1.5 month ago: https://lists.w3.org/Archives/Public/public-review-announce/2020May/0008.html
 - Earlier in the document's lifecyle: https://lists.w3.org/Archives/Public/public-review-announce/2017May/0011.html

# Issues status
All closed as of today: https://github.com/w3c/csswg-drafts/labels/mediaqueries-4

# Formal Objections
None as of today

# Any changes in implementation information?
Most parts of the spec have some degree of implementation, the quality of which isn't fully known as the test suite is not completed yet. All normative changes since the previous CR do have tests in WPT though, and there are plans to write more.

The one feature which is know to lack implementations ([the update media feature](https://drafts.csswg.org/mediaqueries-4/#update)) is marked at risk

# Deadline for further comments
60 days

# Any changes in patent disclosures?
None

**Comment by swickr** [comment]
Transition approved.

You may wish to update the HTML reference in the [Introduction](https://drafts.csswg.org/mediaqueries-4/#intro) :)

**Comment by frivoal** [comment]
> Transition approved.

Thanks

> You may wish to update the HTML reference in the Introduction :)

That's a historic retrospective on how we got there, so speaking of HTML4 is appropirate. We might also want to have a section speaking of which specs refer back to MQ4, and HTML-LS would be among those (also cssom-view, css-conditionals-3…), but this kind of "used from" section is somewhat uncommon.

**Comment by frivoal** [comment]
The first date on HTML4.01 is 1999 https://www.w3.org/TR/1999/REC-html401-19991224/, so I think it's not wrong.

I think we could consider an editorial issue to re-write the intro before going to PR, but I'd rather not do that on the fly.

**Comment by svgeesus** [comment]
Publication requested 20 July, expected 21 July.

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2020/CR-mediaqueries-4-20200721/
