### ISSUE TITLE
FPWD Request for Web App Manifest - Application Information

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#256]
# Document title, URLs, estimated publication date
Web App Manifest - Application Information
W3C First Public Working Draft 30 July 2020
https://www.w3.org/TR/2020/WD-manifest-app-info-20200730/

# Abstract
This document is a registry of supplementary members for the Web App Manifest specification that provide additional metadata to an application manifest. This metadata can be used in a digital storefront or other surfaces where this web application may be marketed or distributed, or to enhance an installation dialog when installing a web application.

# Status
https://www.w3.org/TR/2020/WD-manifest-app-info-20200730/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
No.

# Link to group's decision to request transition
https://github.com/w3c/manifest-app-info/issues/13
7 Support, no FO.

# Information about implementations known to the Working Group
This spec is a supplement to the Web App Manifest spec, which has been widely accepted by the browser vendors.

**Comment by plehegar** [comment]
Approved.

**Comment by siusin** [comment]
@deniak reminded me we can publish a WG-Note directly. So here's the draft for tomorrow's publish:
  https://www.w3.org/TR/2020/NOTE-manifest-app-info-20200730/

**Comment by siusin** [comment]
We published a note last week -> https://www.w3.org/TR/2020/NOTE-manifest-app-info-20200730/
