### ISSUE TITLE
[CSSWG][css-grid-1] CR Update Request for CSS Grid Level 1

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#258]
# Document URLs
ED: https://drafts.csswg.org/css-grid-1/
TR: https://www.w3.org/TR/css-grid-1/

# Link to group's decision to request transition
https://www.w3.org/2020/07/31-css-minutes.html#item19

# Link to previous Candidate Recommendation transition request
https://github.com/w3c/transitions/issues/26

# Substantive changes
https://drafts.csswg.org/css-grid-1/#changes-2017

# Any changes in requirements?
No

# Wide Review of substantive changes
See https://drafts.csswg.org/css-grid-1/issues-cr-2017
(This is all slight adjustments to the layout algorithms, and a couple edge cases on valid property values, and should have no impact on horizontal review considerations.)

# Issues status
Disposition of Comments https://drafts.csswg.org/css-grid-1/issues-cr-2017

# Formal Objections
None

# Any changes in implementation information?
Implementations have improved. :)

# Deadline for further comments
CSSWG always accepts comments. Compat restricts what we can do about them. New feature requests are deferred to Level 3.

# Any changes in patent disclosures?
None

**Comment by swickr** [comment]
Transition approved.

**Comment by svgeesus** [comment]
The test suite could use some attention. I' seeing things like

> Harness status: Error

> ReferenceError: TestingUtils is not defined

> checkTrackSizes@https://test.csswg.org/suites/css-grid-1_dev/nightly-unstable/html/grid-flex-track-intrinsic-sizes-003.htm:43:3
> @https://test.csswg.org/suites/css-grid-1_dev/nightly-unstable/html/grid-flex-track-intrinsic-sizes-003.htm:50:16

> Found 0 tests

**Comment by fantasai** [comment]
@svgeesus That's a tooling issue: mismatched URL models between the old CSSWG test build system and modern WPT. It runs fine on wpt.live. (And also aren't bugs in the test suite irrelevant to publishing an updated spec?) http://wpt.live/css/css-grid/layout-algorithm/grid-flex-track-intrinsic-sizes-003.html

**Comment by svgeesus** [comment]
Publication request sent 13 Aug, expected 18 August

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2020/CR-css-grid-1-20200818/
