### ISSUE TITLE
[CSSWG][css-grid-2] CR Request for css-grid-2

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#259]
# Document title, URLs, estimated publication date
CSS Grid Layout Module Level 2
https://drafts.csswg.org/css-grid-2/

# Abstract
https://drafts.csswg.org/css-grid-2/#abstract

# Status
https://drafts.csswg.org/css-grid-2/#status

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/www-style/2019Nov/0007.html
(Delay was due to waiting for pending Grid 1 spec edits before merging in Level 1 contents into Level 2 in preparation for CR.)

# Changes
None since the previous WD, other than incorporation of the full text of Level 1. See https://drafts.csswg.org/css-grid-2/#changes

# Requirements satisfied
Has received WG review and much interest from web developers and designers. A few requests for improvement were reported and fixed in 2018-2019, but the spec has been almost static since then.

# Dependencies met (or not)
Same as Grid 1

# Wide Review
[Reviews solicited](https://lists.w3.org/Archives/Public/public-review-announce/2018Aug/0001.html)
No comments received outside of the CSSWG. No expectation of impact on topics relevant to horizontal review.

# Issues addressed
None since 2019 WD. A handful of issues addressed in 2019. Overall the spec is a fairly straightforward build on top of the CSS Grid Level 1 features, see most recent WD (diff spec, easier to compare levels): https://www.w3.org/TR/2019/WD-css-grid-2-20191203/

# Formal Objections
None

# Implementation
Firefox has been shipping since 2019

# Patent disclosures
None

**Comment by swickr** [comment]
Pending no blocking issues raised from the notice to the Chairs list by 12 August, Transition to CR is approved.

**Comment by svgeesus** [comment]
Publication request sent 13 Aug, expected 18 August

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2020/CR-css-grid-2-20200818/
