### ISSUE TITLE
CR Update Request for WebRTC 1.0: Real-time Communication Between Browsers webrtc

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/transitions#261]
# Document URLs
https://w3c.github.io/webrtc-pc/

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-webrtc/2020Aug/thread.html#msg5

# Link to previous Candidate Recommendation transition request
https://github.com/w3c/transitions/issues/199

# Substantive changes
[30 substantive pull requests were merged](https://github.com/w3c/webrtc-pc/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+-label%3AEditorial+merged%3A%3E%3D2019-12-13)

Highlights include:
* [resolving a portscanning issue](https://github.com/w3c/webrtc-pc/pull/2540)
* clean up of state machines when closing a peer connection
* marking voiceActivityFlag at risk (no clear implementation plans)
* removal of support for multiple DTLS certificate (remain of an older approach to certificate management)

# Any changes in requirements?
None

# Wide Review of substantive changes
Of the [54 non-editorial issues closed](https://github.com/w3c/webrtc-pc/issues?page=3&q=is%3Aissue+is%3Aclosed+-label%3AEditorial+closed%3A%3E%3D2019-12-13), we identified 4 as security-related and marked them with the security-tracker labels. The issues have been closed without further feedback from the security community.

The Working Group is not aware of impact of the other substantive changes on other groups in W3C and elsewhere.

# Issues status
The [2 remaining issues](https://github.com/w3c/webrtc-pc/issues?q=is%3Aissue+is%3Aopen+-label%3A%22WebRTC+Extensions%22+-label%3A%22Test+suite+issue%22+-label%3A%22No+specification+change+needed%22+-label%3A%22Editorial%22) are related to getCapabilities and its fingerprint impact; the Working Group has not determined yet whether they can be addressed in the timeframe of WebRTC 1.0 as it likely requires coordinated cross-group cross-spec mitigations to be meaningfully addressed.

# Formal Objections
None

# Any changes in implementation information?
The Working Group is tracking implementation progress in a [dedicated semi-automated implementation report](https://w3c.github.io/webrtc-interop-reports/webrtc-pc-report.html) built on top of wpt.fyi data.

# Deadline for further comments
1 month after publication

# Any changes in patent disclosures?
None

**Comment by xueyuanjia** [comment]
Draft transition approved.
