### ISSUE TITLE
Supersede JSON LD 1.0 and JSON LD 1.0 API

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#265]
# Title, URL of the document to be superseded

- JSON-LD 1.0
    - https://www.w3.org/TR/2014/REC-json-ld-20140116/
- JSON-LD 1.0 Processing Algorithms and API
    - https://www.w3.org/TR/2014/REC-json-ld-api-20140116/

# Title, URL of the newer version

- JSON-LD 1.1
    - https://www.w3.org/TR/json-ld11/
    - https://www.w3.org/TR/2020/REC-json-ld11-20200716/
- JSON-LD 1.1 Processing Algorithms and API
    - https://www.w3.org/TR/json-ld11-api/
    - https://www.w3.org/TR/2020/REC-json-ld11-api-20200716/

# Link to group's decision to request superseding
https://github.com/w3c/json-ld-wg/issues/154

# Rationale
See the rationale in https://github.com/w3c/json-ld-wg/issues/154

# Implementation

See the implementation report in https://w3c.github.io/json-ld-api/reports/

# Note

http://www.w3.org/TR/json-ld/, respectively http://www.w3.org/TR/json-ld-api/, are already redirected to https://www.w3.org/TR/json-ld11/, respectively https://www.w3.org/TR/json-ld11-api/.

Cc: @gkellogg, @pchampin, @BigBlueHat @plehegar

**Comment by swickr** [comment]
Approved to send for AC review.

**Comment by iherman** [comment]
WBS form sent to the AC:

https://www.w3.org/mid/35ca4c4d-b62c-a2db-33f0-4a5e9e5b8765@w3.org

Cc: @swickr @plehegar I am not sure whether a different label is necessary and/or whether this issue should simply be closed. Is it "Awaiting Publication" ?
