### ISSUE TITLE
PR Request for the Publication Manifest and the Audiobooks Specifications

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#266]
PR Request for the Publication Manifest and the Audiobooks Specifications

# Document title, URLs, estimated publication date

Title: Publication Manifest
URL: https://www.w3.org/TR/pub-manifest/
Editor's draft: https://w3c.github.io/pub-manifest/?specStatus=PR
Estimated publication date: 2020-09-29

Title: Audiobooks
URL: https://www.w3.org/TR/audiobooks/
Editor's draft: https://w3c.github.io/audiobooks/?specStatus=PR
Estimated publication date: 2020-09-29

# Abstract

See:

- https://w3c.github.io/pub-manifest/?specStatus=PR#abstract
- https://w3c.github.io/audiobooks/?specStatus=PR#abstract

# Status

- https://w3c.github.io/pub-manifest/?specStatus=PR#sotd
- https://w3c.github.io/audiobooks/?specStatus=PR#sotd 

# Link to group's decision to request transition

- https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2020/2020-09-14-pwg.html#resolution1
- https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2020/2020-09-14-pwg.html#resolution2

# Changes

- https://w3c.github.io/pub-manifest/?specStatus=PR#change-log-older
- https://w3c.github.io/audiobooks/?specStatus=PR#change-log-older

# Requirements satisfied

No changes since the CR Transition

# Dependencies met (or not)

No changes since the CR Transition; there was no external dependencies

# Wide Review

Review happened via github issues, see:

- https://github.com/w3c/pub-manifest/issues?q=is%3Aissue+
- https://github.com/w3c/audiobooks/issues?q=is%3Aissue+

# Issues addressed

See the changes section, that also refers to the issues leading to the changes:

- https://w3c.github.io/pub-manifest/?specStatus=PR#change-log-older
- https://w3c.github.io/audiobooks/?specStatus=PR#change-log-older

# Formal Objections

None.

# Implementation

All the reports are collected here:

- https://w3c.github.io/publ-tests/

The repository contains the test suite and test reports. The only normative part of the spec is the manifest processing sections in the two documents; the respective test reports are here:

- https://w3c.github.io/publ-tests/test_reports/manifest_processing/index.html

# Patent disclosures

See

- https://www.w3.org/2004/01/pp-impl/100074/status

**Comment by iherman** [comment]
Note: I was not sure what format we have to give to the request on keeping the Recommendation "editable" per the 2020 process. I hope the [2nd resolution above](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2020/2020-09-14-pwg.html#resolution2) makes that point clear.

Questions can also be addressed to the chairs and editors:

@TzviyaSiegman, @wareid, @GarthConboy, @mattgarrish

**Comment by fantasai** [comment]
@iherman A Recommendation is always editable per 2020 process. The question is whether you intend to add new features; if so that intention needs to be documented in the SOTD.

**Comment by iherman** [comment]
@fantasai,

> @iherman A Recommendation is always editable per 2020 process.

Ie, the [2nd WG resolution](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2020/2020-09-14-pwg.html#resolution2) concerning the PR transition was not necessary. But that is fine, no harm done.

> The question is whether you intend to add new features; if so that intention needs to be specifically documented in the SOTD.

O.k. I will have to familiarize myself with the respec changes; I hope this is generated, somehow, into the SOTD text.

**Comment by iherman** [comment]
@fantasai 

> A Recommendation is always editable per 2020 process. The question is whether you intend to add new features; if so that intention needs to be specifically documented in the SOTD.

Is there a standard wording for this? I looked in the respec sources to see if it is prepared for this, but I did not find anything (although I may have missed this).

Cc @plehegar

**Comment by plehegar** [comment]
It is not generated by default.

Recommended text is "Future updates to this specification may incorporate [new features](https://www.w3.org/2020/Process-20200915/#allow-new-features)."

**Comment by plehegar** [comment]
See also https://www.w3.org/pubrules/doc/rules/?profile=PR#newFeatures

**Comment by plehegar** [comment]
and pubrules will tell you about by the way:
 https://www.w3.org/pubrules/?url=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fpub-manifest%2F%3FspecStatus%3DPR&profile=PR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020
(ignore the stability paragraph error for now)

**Comment by iherman** [comment]
> It is not generated by default.
> 
> Recommended text is "Future updates to this specification may incorporate [new features](https://www.w3.org/2020/Process-20200915/#allow-new-features)."

Thanks @plehegar 

(Would be good if respec took care of this, eventually. At present, adding it manually to the sotd section means that line is added at the very first paragraph of that section followed by the generated part of the sotd which, editorially, is not ideal. Oh well...)

**Comment by plehegar** [comment]
@dontcallmedom , see the comment from Ivan above. I wonder if an option in respec/bikeshed would help (if it's not there already)

**Comment by dontcallmedom** [comment]
ReSpec takes care of it if you set `respecConfig.updateableRec` to `true`

**Comment by iherman** [comment]
> ReSpec takes care of it if you set `respecConfig.updateableRec` to `true`

I see it now in the respec code, but something goes wrong, see [a future PR](https://w3c.github.io/pub-manifest/?specStatus=PR). The relevant part is displayed as `[object Object]` :-(

Cc @mattgarish

(B.t.w., do we know when the respec manual will be updated?)

**Comment by mattgarrish** [comment]
> I see it now in the respec code, but something goes wrong, see [a future PR](https://w3c.github.io/pub-manifest/?specStatus=PR).

Odd, I only tested setting to REC and it came out, but I see what you mean.

**Comment by dontcallmedom** [comment]
I confirm there is a bug (which the above-linked respec PR should fix)

**Comment by swickr** [comment]
Transition approved.

@iherman when you draft the AC Review email for Comm, please make explicit mention of the
>Future updates to this specification may incorporate new features.

sentence as this is the first time the AC will be seeing that use.  @plehegar will be happy to help you with the phrasing.

@r12a please close https://github.com/w3c/i18n-activity/issues/699

**Comment by r12a** [comment]
> @r12a please close w3c/i18n-activity#699

Done.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/PR-audiobooks-20201001/
https://www.w3.org/TR/2020/PR-pub-manifest-20201001/
