### ISSUE TITLE
Update next step page for Process 2020

### ISSUE THREAD

**Issue by xfq** [w3c/transitions#269]
The [transition guide](https://www.w3.org/Guide/transitions) has been updated, but the useful [next step](https://w3c.github.io/transitions/nextstep.html) page is still the old one. It would be great to get it updated too.

**Comment by plehegar** [comment]
This was implemented:

https://w3c.github.io/transitions/nextstep.html?shortname=webauthn-2
https://w3c.github.io/transitions/nextstep.html?shortname=hr-time-2

**Comment by xfq** [comment]
Thank you @plehegar. The page still says "2019 Process", though.
