### ISSUE TITLE
FPNote for How EMVCo, FIDO, and W3C Technologies Relate

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/transitions#270]
# Document title, URLs, estimated publication date

- title: How EMVCo, FIDO, and W3C Technologies Relate

The document is currently at:
 https://www.w3.org/2020/07/htr/index.html

In addition to requesting approval by the W3C Director, we are seeking approval by the EMVCo Board and the FIDO Board. Until we have all three approvals the document must remain NON PUBLIC.
We plan for the Webmaster to make it public upon completion of TR page publication.

- expected publication date: 2020-11-05
- expected URL with short name: https://www.w3.org/TR/htr/
- expected Dated URI: https://www.w3.org/TR/2020/NOTE-htr-20201105/

# Abstract

Because the document is not public, please see the document directly.

# Status

Because the document is not public, please see the document directly.

# Link to group's decision to request transition

https://lists.w3.org/Archives/Member/member-wpsig/2020Sep/0012.html

# Information about implementations known to the Working Group

N/A

**Comment by plehegar** [comment]
Approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/NOTE-htr-20201105/
