### ISSUE TITLE
FPWD Request for Baggage specification

### ISSUE THREAD

**Issue by caribouW3** [w3c/transitions#271]
# Document title, URLs, estimated publication date

Propagation format for distributed trace context: Baggage

Requested shortname: https://www.w3.org/TR/baggage

Editors' draft
https://w3c.github.io/baggage/

Estimated publication: October 8th or 13th

# Abstract

Distributed tracing is a set of tools and practices to monitor the health and reliability of a distributed application. A distributed application is an application that consists of multiple components that are deployed and operated separately. It is also known as micro-service.

The main concept behind distributed tracing is event correlation. Event correlation is a way to correlate events from one component to the events from another. It allows to find the cause-and-effect relationship between these events. For instance – find which user action in a browser caused a failure in the business logic layer.

To correlate events between components, these components need to exchange and store a piece of information called context. Typically context consists of an originating event identifier, an originating component identity and other event properties. Context has two parts. The first part is a trace context. Trace context consists of properties crucial for event correlation. The second part is baggage. Baggage carries user-defined properties. These properties may be helpful for correlation scenarios. But they are not required and components may choose to not carry or store them.

Unifying the format of distributed tracing context as well as aligning on semantic meaning of the values is the main objective of this working group. The goal is to share this with the community so that various tracing and diagnostics products can operate together.

# Status

This is the First Public Working Draft (FPWD). There are a few implementations of this protocol available. Experimental interoperability scenarios were run and have demonstrated promising results. The specification will be progressed into Candidate Recommendation stage after that, drafts for binary, AMQP and MQTT protocols will be written to make sure the concepts and structure defined in this specification can be ported to other protocols.

GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-trace-context@w3.org (archives) with baggage at the start of your email's subject .

# Is it a delta specification intended to become a W3C Recommendation?

no

# Link to group's decision to request transition

https://github.com/w3c/baggage/issues/36

# Information about implementations known to the Working Group

See SOTD.

**Comment by plehegar** [comment]
This document will need a Security and Privacy considerations section before doing the wide review.

Respec config needs to be [updated](https://lists.w3.org/Archives/Public/spec-prod/2020JulSep/0026.html).

Approved as FPWD.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/WD-baggage-20201020/
