### ISSUE TITLE
CR Snapshot Update Request for Web Authentication: An API for Accessing Public Key Credentials Level 2

### ISSUE THREAD

**Issue by YubicoDemo** [w3c/transitions#276]
# Document URLs
Title: Web Authentication: An API For Accessing Public Key Credentials; Level 2
https://www.w3.org/TR/2020/WD-webauthn-2-20201216/

# Link to group's decision to request transition
https://www.w3.org/2020/10/07-webauthn-minutes.html

# Link to previous Candidate Recommendation transition or update request
https://lists.w3.org/Archives/Member/chairs/2018JanMar/0096.html

# Substantive changes
- Added new method to allow Discoverable/Resident Credentials Preferred
- New methods added for Attestation Objects
- Added Enterprise Attestation, Apple Attestation
- Added Large Blob storage and credential properties

DIFF: https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fwebauthn%2F&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2F2020%2FWD-webauthn-2-20201216%2F

# Any changes in requirements?
None

# Wide Review of substantive changes
**Web Payments WG**
 “The Web Authentication WG and the Web Payments WG launched a joint task force in October 2019 to help ensure that  payments use cases can be addressed by Web Authentication. Although this collaboration has not involved formal review of Web Authentication Level 2, it has involved usage of the specification and led to a number of feature proposals, including:
   1) The ability to call Web Authentication get() from within an iframe. This is a common coding pattern in the payment industry, where the payment service provider code runs in an iframe in the merchant page.
   2) Secure Payment Confirmation (SPC), which “marries” Web Authentication and Payment Request API to
       improve the user experience. This work is motivated in particular by regulatory requirements in Europe (PSD2) involving both strong customer authentication (SCA) and transaction confirmation (“dynamic linking”).
In short, the Web Payments Working Group is an active consumer of Web Authentication and has engaged payments industry stakeholders around the adoption of Web Authentication."

**PING**
[issues addressed](https://github.com/w3c/webauthn/issues?q=is%3Aissue+label%3Aprivacy-needs-resolution)

**Security**
[Security Review Request for WebAuthn Level 2](https://lists.w3.org/Archives/Public/public-webauthn/2020Oct/0074.html) (Monday, 19 October) -- no issues

**i18n**
[Review Requested](https://github.com/w3c/i18n-request/issues/132) and [Editorial issues filed](        https://github.com/w3c/webauthn/issues?q=is%3Aissue+label%3Ai18n-needs-resolution)

**APA WG**
 [Accessibility Review Request for WebAuthn Level 2](https://lists.w3.org/Archives/Public/public-webauthn/2020Oct/0076.html) (Monday, 19 October)

# Issues status
Only Editorial remaining; move to L3. All technical issues closed

# Formal Objections
None

# Any changes in implementation information?
Google and MSFT; preliminary feedback in form of issues and PRs. 

# Deadline for further comments
28 days after publication of CR request.

# Any changes in patent disclosures?
None

See [Requirements for updating a Candidate Recommendation Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot) for further information.

# CR Test Plan
Run the WD-04 Editor's version through the Level 2 test harness

# CR Exit Criteria
Show two browser implementations supporting the new features and extensions.

# Relationship between Level 2 and Level 1?
Web Authentication Level 2 will supersede Web Authentication Level 1

**Comment by swickr** [comment]
We're not seeing evidence of [horizontal review](https://www.w3.org/Guide/documentreview/#how_to_get_horizontal_review); has the horizontal review been completed?

What is your CR test plan?  What are you proposing as [CR Exit criteria](https://www.w3.org/2020/Process-20200915/#adequate-implementation)?

What is the relationship between Level 2 and Level 1?  For example, if this specification becomes a Recommendation will it [supersede](https://www.w3.org/2020/Process-20200915/#maturity-levels) the Level 1 Recommendation?

Before moving to Proposed Recommendation, please consider this as we prefer to include this in the AC Review of a Proposed Recommendation.

**Comment by wseltzer** [comment]
Issue edited to add review links (Privacy, Security, i18n, APA)

**Comment by wseltzer** [comment]
Group agreed that upon CR transition, the unadorned "webauthn" should point to level 2 (as well as webauthn-2), while webauthn-1 points to level 1. https://www.w3.org/2020/12/16-webauthn-minutes.html

**Comment by plehegar** [comment]
Horizontal comments:
 https://www.w3.org/PM/horizontal/?repo=w3c/i18n-activity#webauthn
 https://www.w3.org/PM/horizontal/?repo=w3c/security-review#webauthn
 https://www.w3.org/PM/horizontal/?repo=w3cping/tracking-issues#webauthn

**Comment by swickr** [comment]
Transition approved.

(This is a transition from WD to CR, not a CR Update)

Please document the CR test criteria and CR exit criteria in the SoTD.

I see the [completion of the CfC on 14 Oct](https://lists.w3.org/Archives/Public/public-webauthn/2020Oct/0059.html)

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/CR-webauthn-2-20201222/
