### ISSUE TITLE
FPWD Request for CSS Custom Highlight API 

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#277]
# Document title, URLs, estimated publication date
CSS Custom Highlight API Module Level 1
https://drafts.csswg.org/css-highlight-api-1/
after TPAC

# Abstract
This CSS module describes a mechanism for styling arbitrary ranges of a document identified by script.
CSS is a language for describing the rendering of structured documents (such as HTML and XML) on screen, on paper, etc. 

# Status
https://drafts.csswg.org/css-highlight-api-1/#status (as ED)

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
RESOLUTION: publish highlight-api
https://www.w3.org/2020/10/19-css-minutes.html#resolution02

# Information about implementations known to the Working Group
Implementer interest

**Comment by plehegar** [comment]
Approved

**Comment by frivoal** [comment]
The list of editors needed to be updated before publication, and that's now done, so you can publish away.

**Comment by svgeesus** [comment]
Hmm  on drafts.csswg.org I'm still seeing

>     Florian Rivoal (On behalf of Bloomberg) 
>    Sanket Joshi (Microsoft Corporation) 
>    Theresa O'Connor (Apple Inc.) 

But I also see https://github.com/w3c/csswg-drafts/commit/42d0b592c58bb44f696247e7c4432495eb17f153 so kay, /TR will be correct

**Comment by svgeesus** [comment]
Publication requested 20 Oct, expected 22 Oct just before the publishing moratorium.

**Comment by svgeesus** [comment]
[Published 22 Oct 2020](https://www.w3.org/TR/2020/WD-css-highlight-api-1-20201022/)
