### ISSUE TITLE
Supersede JSON LD 1.0 and JSON LD 1.0 API

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#278]
# Link to internal transition

  https://lists.w3.org/Archives/Team/w3t-archive/2020Oct/0077.html

# Link to previous transition

  https://github.com/w3c/transitions/issues/265

cc @iherman

**Comment by swickr** [comment]
Transition approved.

**Comment by iherman** [comment]
Pulication requests sent for the 3rd of November.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/SPSD-json-ld-20201103/
https://www.w3.org/TR/2020/SPSD-json-ld-api-20201103/
