### ISSUE TITLE
[FONTWG] PR request for WOFF2

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#28]
# Document title, URLs, estimated publication date
WOFF File Format 2.0 
https://dev.w3.org/webfonts/WOFF2/spec/
First Tuesday or Thursday after moratorium and after successful transition

# Abstract

Based on experience with WOFF 1.0, which is widely deployed, this specification was developed to provide improved compression and thus lower use of network bandwidth, while still allowing fast decompression even on mobile devices. This is achieved by combining a content-aware preprocessing step and improved entropy coding, compared to the Flate compression used in WOFF 1.0.

# Status

https://dev.w3.org/webfonts/WOFF2/spec/#status (as CR)

# Link to group's decision to request transition

https://www.w3.org/2017/12/13-webfonts-minutes.html

# Changes

[Changes since CR](https://w3c.github.io/woff/woff2/#changes-since-CR)
* Two references (Brotli, and Font Top Level type) were updated from Internet Drafts to RFCs: RFC 7932, Informational, and RFC 8081, IETF Proposed Standard respectively.
* The Internet Media Type Registration appendix was updated so that fragment identifiers conform to RFC 8081

# Requirements satisfied

See WOFF 2.0 Evaluation Report 
https://www.w3.org/TR/WOFF20ER/

# Dependencies met (or not)

All normative references are mature (W3C Recommendation, IETF RFC, etc).

# Wide Review

This specification is implemented in recent shipping versions of all major browsers, is supported by font foundries, and font authoring tools.

# Issues addressed

No issues raised since publication of the 15 March 2016 Candidate Recommendation

# Formal Objections

None

# Implementation

* [CanIUse](https://caniuse.com/#feat=woff2)
* [Implementation report](https://www.w3.org/Fonts/WG/WOFF2/Implementation.html)
* [Decoder results](https://www.w3.org/Fonts/WG/WOFF2/Decoder_results.html)
* [User Agent results](http://test.csswg.org/harness/results/woff2_dev/grouped/)
* [Encoder results](https://www.w3.org/Fonts/WG/WOFF2/Encoder_results.html)

# Patent disclosures

https://www.w3.org/2004/01/pp-impl/44556/status

**Comment by swickr** [comment]
I have reviewed the implementation report for WOFF File Format 2.0 
Candidate Recommendation.  In doing so two items surfaced:

1. The reference to CSS3 Fonts should be normative as it is used 
normatively in section 2.

2. Per the implementation report, while there are two tested 
implementations of encoding and decoding of font collections no user 
agent is yet shown to use them after decoding.  Please add a sentence to 
the SoTD indicating that the browser support is expected to improve.

With that, I am satisfied that WOFF File Format 2.0 may advance to 
Proposed Recommendation and approve this transition request on behalf of 
the Director.

**Comment by svgeesus** [comment]
PR published
https://www.w3.org/TR/2018/PR-WOFF2-20180111/
