### ISSUE TITLE
CR Request for WAI-ARIA 1.2

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/transitions#280]
# Document title, URLs, estimated publication date
[Accessible Rich Internet Applications (WAI-ARIA) 1.2 editors' draft](https://w3c.github.io/aria/), modulo CR boilerplate, hoped to be published 2020-11-03.

# Abstract
Accessibility of web content requires semantic information about widgets, structures, and behaviors, in order to allow assistive technologies to convey appropriate information to persons with disabilities. This specification provides an ontology of roles, states, and properties that define accessible user interface elements and can be used to improve the accessibility and interoperability of web content and applications. These semantics are designed to allow an author to properly convey user interface behaviors and structural information to assistive technologies in document-level markup. This version adds features new since WAI-ARIA 1.1 [wai-aria-1.1] to improve interoperability with assistive technologies to form a more consistent accessibility model for [HTML] and [SVG2]. This specification complements both [HTML] and [SVG2].

This document is part of the WAI-ARIA suite described in the WAI-ARIA Overview.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

This is a Candidate Recommendation of WAI-ARIA 1.2 by the Accessible Rich Internet Applications Working Group of the Web Accessibility Initiative. This is a Call for Implementations; the Accessible Rich Internet Applications Working Group requests that initial implementations be submitted by 31 January 2021. The Working Group targets February 2020 to complete the testing process and produce the implementation report. A history of changes to WAI-ARIA 1.2 is available in the appendix. Some features are marked as "at risk" due to concerns around implementation and testing challenges, and could be removed if testing does not document sufficient implementation. The Working Group plans to advance past Candidate Recommendation when the Candidate Recommendation Exit Criteria have been met.

The Accessible Rich Internet Applications Working Group seeks feedback on any aspect of the specification. When submitting feedback, please consider issues in the context of the companion documents. To comment, file an issue in the W3C ARIA GitHub repository. If this is not feasible, send email to public-aria@w3.org (comment archive). Comments are requested by 31 January 2021. In-progress updates to the document may be viewed in the publicly visible editors' draft.

This document was published by the Accessible Rich Internet Applications Working Group as a Candidate Recommendation. This document is intended to become a W3C Recommendation.

GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-aria@w3.org (archives).

W3C publishes a Candidate Recommendation to indicate that the document is believed to be stable and to encourage implementation by the developer community. This Candidate Recommendation is expected to advance to Proposed Recommendation no earlier than 31 January 2021.

Please see the Working Group's implementation report.

Publication as a Candidate Recommendation does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 1 March 2019 W3C Process Document. 

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-aria-admin/2020Oct/0015.html

# Changes
https://w3c.github.io/aria/#changelog

# Requirements satisfied
The ARIA WG has used a [workflow](https://www.w3.org/WAI/ARIA/workflow) that involves annual releases. Features to add in these annual releases are described in the [roadmap](https://www.w3.org/WAI/ARIA/roadmap) and this version represents incremental progress towards that.

# Dependencies met (or not)
While there are many normative *references*, the primary *dependency* is on Core Accessibility API Mappings, which maps 1:1 with the features of Accessible Rich Internet Applications, and will soon enter CR itself.

# Wide Review
https://lists.w3.org/Archives/Public/public-review-announce/2019Dec/0015.html

# Issues addressed
https://github.com/w3c/aria/issues?q=is%3Aissue+label%3A%22ARIA+1.2%22

# Formal Objections
None

# Implementation
The draft [implementation report](https://w3c.github.io/test-results/core-aam-1.2/) contains implementation information. CR is expected to last 3 months. Exit criteria are:

WAI-ARIA 1.2 defines a technology that can be used in multiple host languages and exposes features to various device platforms. Specific implementation guidance for these languages and platforms is provided in a set of Accessibility API Mappings (AAMs), including at time of publication Core AAM, Accessible Name and Description AAM, HTML AAM, Graphics AAM, SVG AAM, and Digital Publishing AAM. Testing WAI-ARIA relies on the guidance in those auxiliary specifications. For each WAI-ARIA feature, successful test results in any two implementations mapping any of the accessibility APIs referenced in any of the AAMs using any host language will be considered sufficient for the purpose of determining implementability and interoperability of WAI-ARIA. It is not an expectation that the AAMs themselves be at Candidate Recommendation or later stage in order to support WAI-ARIA testing.

WAI-ARIA 1.2 builds upon WAI-ARIA 1.1, which met its implementation requirements in November 2017. Only features that are new or changed in WAI-ARIA 1.2 need be tested, as the WAI-ARIA implementation report provides implementatibility and interoperability evidence for the remaining features. Features that will be tested for WAI-ARIA are the new and changed features listed in the change log.

The Accessible Rich Internet Applications Working Group intends to submit this document for consideration as a W3C Proposed Recommendation as soon as the following conditions are met:

* Define test cases: Identify a set of unit tests, feature tests, dynamic tests, and any additional tests needed to cover all ARIA normative requirements;
* Prepare test files: Prepare test files consisting of HTML content enhanced with WAI-ARIA, to cover all the test cases;
* Test implementations: Perform these tests on multiple separate combinations of user agent plus operating system plus accessibility API;
* Evaluate test results: Examine results in accessibility APIs as defined by the WAI-ARIA User Agent Implementation Guide;
* Verify interoperable results: Find at least two implementations of each normative requirement where the defined behavior for the respective accessibility API is observed.

The WAI-ARIA 1.2 Implementations page contains further explanation of the terms and expectations above. It also contains up-to-date information about the test suite, test harness, user agents being examined, and interim test results in the draft implementation report. Implementers who wish to include their tools in the test process will find instructions to submit their implementation for consideration.

# Patent disclosures
https://www.w3.org/2004/01/pp-impl/83726/status

**Comment by swickr** [comment]
We found a [Privacy review request](https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0024.html) dated 27 October.  Is this CR Transition request premature?

I'm guessing that "February 2020" in the SoTD is a typo, too.

**Comment by michael-n-cooper** [comment]
We are aware that the CR request comes before horizontal review is complete. I apologize for this, it continues to be difficult to remember to solicit horizontal review months before an expected CR. We have planned a 3-month CR, which would allow a 3-month horizontal review to take place. In the best (and expected) case, horizontal review will identify no normative changes for the 1.2 version, so the spec would progress to PR on schedule. In the worst case, normative changes are identified and we have to use the process to re-issue a CR. We are aware of that risk, but considering that is an unlikely reason for delay, whereas delaying another three months prior to entering CR is a certain delay, we prefer to take that approach. We can own the horizontal review issue in messaging so horizontal review groups aren't taken by surprise.

**Comment by swickr** [comment]
I'm not aware of special circumstances that would warrant this but I'm willing to meet with you to discuss.

**Comment by plehegar** [comment]
@michael-n-cooper , any update on this front?

**Comment by michael-n-cooper** [comment]
Horizontal reviews are complete.

* [Privacy](https://github.com/w3c/aria/issues/1371) agreed to hold a discussion with the ARIA WG with goal of taking further steps in ARIA 1.3, nothing for 1.2.
* [Internationalization](https://github.com/w3c/i18n-request/issues/134) acknowledged review request but did not complete.
* [TAG](https://github.com/w3ctag/design-reviews/issues/586) ok with current state.
* [Security](https://lists.w3.org/Archives/Group/group-aria-chairs/2021Feb/0001.html) will not review.
* [Accessibility](https://lists.w3.org/Archives/Public/public-aria/2020Nov/0011.html) will not review.

**Comment by swickr** [comment]
Transition approved.

Thank you, Michael and WG.

**Comment by michael-n-cooper** [comment]
Aiming to publish 23 Feb 2021 after going through WAI announcement bureaucracy.
