### ISSUE TITLE
FPNote for Web Platform Design Principles

### ISSUE THREAD

**Issue by ylafon** [w3c/transitions#286]
# Document title, URLs, estimated publication date
- Title: Web Platform Design Principles
URL: https://www.w3.org/2001/tag/2020/staging/design-principle.html

- Expected pub date: 2020-11-10
- Short name: design-principles

# Abstract

This document contains a set of design principles to be used when designing Web Platform technologies. These principles have been collected during the Technical Architecture Group’s discussions in reviewing developing specifications. We encourage specification designers to read this document and use it as a resource when making design decisions.

# Status

This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index.

This document was published by the W3C Technical Architecture Group (TAG) as a W3C Working Group Note. Publication as a W3C Working Group Note does not imply endorsement by the W3C Membership.

This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document is expected to updated frequently during the year.

The nomenclature "Working Group Note" for this document is intended only to convey the level of consensus around this document. The participants in the W3C Technical Architecture Group are elected by the W3C Membership to document and build consensus around principles of Web architecture, to interpret and clarify these principles when necessary, to resolve issues involving general Web architecture brought to the TAG, and to help coordinate cross-technology architecture developments inside and outside W3C.

Feedback and comments on this specification are welcome. Please file an issue in this document’s GitHub repository.

This document is governed by the 15 September 2020 W3C Process Document.

# Link to group's decision to request transition

https://github.com/w3ctag/meetings/blob/gh-pages/2020/telcons/11-02-minutes.md

# Information about implementations known to the Working Group
n/a

**Comment by plehegar** [comment]
Approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/NOTE-design-principles-20201110/
