### ISSUE TITLE
FPNote for The MerchantValidationEvent interface

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/transitions#288]
# Document title, URLs, estimated publication date

The MerchantValidationEvent interface
https://w3c.github.io/merchant-validation/?specStatus=WG-NOTE
(Note: Any respec errors will be resolved prior to formal publication.)

Estimated publication date: 2020-12-03 (perhaps along with the Payment Request API).

# Abstract

Merchant validation is the process by which a payment handler validates the identity of a merchant against some value (usually some cryptographic challenge response). Validated merchants are allowed to interface with a payment handler. Details of how actual validation is performed is outside the scope of this specification. 

This feature was removed from Payment Request API 1.0 due to lack of interoperable support. 

# Status

(We expect template information here for a FPIG Note).

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-payments-wg/2020Oct/0012.html

# Information about implementations known to the Working Group

This may be supported in Webkit's implementation of Payment Request API.

**Comment by plehegar** [comment]
Approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/NOTE-merchant-validation-20201208/
