### ISSUE TITLE
[immersive-web] FPWD Request for WebXR Layers API Level 1

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#289]
# Document title, URLs, estimated publication date
WebXR Layers API Level 1
https://immersive-web.github.io/layers/
1 Dec 2020 (for approval at 27 Nov)

# Abstract
https://immersive-web.github.io/layers/#abstract
This specification describes support for various layer types used in a WebXR session.

# Status
https://immersive-web.github.io/layers/#status

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
Decision: https://lists.w3.org/Archives/Public/public-immersive-web-wg/2020Nov/0010.html
CfC: https://lists.w3.org/Archives/Public/public-immersive-web-wg/2020Nov/0007.html

initial github issue: https://github.com/immersive-web/layers/issues/202

# Information about implementations known to the Working Group
none yet

(/cc @cabanier as editor, @AdaRoseCannon as chair handling)

**Comment by himorin** [comment]
updated per decision / resolution for CfC, asking approval.

**Comment by plehegar** [comment]
Approved.

**Comment by himorin** [comment]
setting target date of publication as next slot at Dec 3rd (Thu), at TR/2020/WD-webxrlayers-1-20201203

**Comment by himorin** [comment]
published.
