### ISSUE TITLE
[CSSWG] CR request for selectors-3

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#29]
# Document title, URLs, estimated publication date

Selectors Level 3
ED at https://drafts.csswg.org/selectors-3/
REC at https://www.w3.org/TR/css3-selectors/

# Abstract

Selectors are patterns that match against elements in a tree, and as such form one of several technologies that can be used to select nodes in an XML document. Selectors have been optimized for use with HTML and XML, and are designed to be usable in performance-critical code. 

# Status

REC

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/www-style/2017May/0032.html

# Changes

https://drafts.csswg.org/selectors-3/#changes

# Requirements satisfied

N/A

# Dependencies met (or not)

All met

# Wide Review

See previous publications

# Issues addressed

Just the one erratum. Other issues have been forwarded to Selectors Level 4.

# Formal Objections

None

# Implementation

At least Gecko and Blink.

# Patent disclosures

None

**Comment by plehegar** [comment]
@svgeesus @fantasai 

You can't request a PR for a document with substantive changes. You can request a CR however with a short CR phase if you can demonstrate implementation already. I didn't find a CR document for selectors-3 (the latest one is 2011 REC) so I'm assuming you need a CR. For the substantive change, I also assume you mean that the test case in the spec is passed by Gecko and Blink.

**Comment by plehegar** [comment]
one more question: the spec links to HTML401. Seems odd to publish a REC in 2018 that still links to that. How much work would it be to upgrade the spec to the latest version of HTML5?

**Comment by plehegar** [comment]
same question for DOM-Level-3-Core.

**Comment by plehegar** [comment]
(note that both references are informative)

**Comment by svgeesus** [comment]
Agree this obviously should have been a CR request, it starts from a Rec and folds in errata; it is intended for Edited Recommendation, as clearly documented at
https://www.w3.org/2017/Process-20170301/#revised-rec
Title updated.

There are two informative references to HTML 4.01. One says that the HTML spec defines the syntax for HTML; the other says HTML has a `lang` attribute. Clearly these can be trivially updated to point to HTML 5.

Similarly the references to DOM 3 Core can be updated, they merely point out the existence of "text nodes, CDATA nodes, and entity references" and suchlike non-version-specific language.

Test suite and implementation report links in the ED are stale. Test suite is here
https://test.csswg.org/harness/suite/selectors-3_dev/
Implementation report here
https://test.csswg.org/harness/results/selectors-3_dev/grouped/

There are four tests with insufficient passes
https://test.csswg.org/harness/results/selectors-3_dev/grouped/filter/1/

**Comment by svgeesus** [comment]
https://github.com/w3c/csswg-drafts/issues/2189

**Comment by svgeesus** [comment]
Class selectors in Selectors-3 need updating for HTML 5

https://github.com/w3c/csswg-drafts/issues/2190

**Comment by svgeesus** [comment]
Erratum test case is not in WPT

https://github.com/w3c/csswg-drafts/issues/2192

**Comment by plehegar** [comment]
imho, the test failures shouldn't be blocker here if the text wasn't touched since the REC.

**Comment by svgeesus** [comment]
https://github.com/w3c/csswg-drafts/commit/e2fccb2145dbebcf7f276ba46011f59ba11660ec#diff-315c5cf0aab839f336caea6522d16d67
https://github.com/w3c/csswg-drafts/commit/91e1f383ada3975c44d1998875138c4e4286aacb#diff-315c5cf0aab839f336caea6522d16d67
https://github.com/w3c/csswg-drafts/commit/a5278b182f557f0cb1ac5ab7e24b2cbd2d4a9e06#diff-315c5cf0aab839f336caea6522d16d67

**Comment by svgeesus** [comment]
> imho, the test failures shouldn't be blocker here if the text wasn't touched since the REC.

Good to know. Suspect some may be mis-labelled Selectors 4 tests.

**Comment by fantasai** [comment]
I'd prefer not to update all the informative references here, since they are not wrong, and just leave the changes from the previous REC as the minimal set necessary to fold in the erratum. Selectors 4 is current; this is historical. Let me know if that's unacceptable and I'll update the references.

**Comment by svgeesus** [comment]
I will leave the question of references to the Director; if the Director agrees with @fantasai then my edits to the .src.html are easy to revert.
The test still needs to be submitted to WPT
The CR transition request still needs to be sent to chairs mailing list to start the 7-day clock.

**Comment by swickr** [comment]
I think it will look peculiar to publish an Edited Recommendation dated 2018 that cites (even informatively) HTML4 and DOM 3.  However, this does not feel critical and therefore I defer to the editor's preference.  Chris, you may revert these changes; thanks for doing them none-the-less.

**Comment by plehegar** [comment]
test case is at https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=5188

**Comment by fantasai** [comment]
@svgeesus I don't have a very strong preference, so your call on the references if you've already made the edits.

**Comment by svgeesus** [comment]
Test case is now properly committed to WT with an actual spec link to a testable assertion
http://test.csswg.org/harness/test/selectors-3_dev/single/selector-structural-pseudo-root/

Results
http://test.csswg.org/harness/details/selectors-3_dev/selector-structural-pseudo-root/

**Comment by svgeesus** [comment]
Publication request sent for 30 Jan (first date that is 7 days after the (updated for CR) transition request.

**Comment by svgeesus** [comment]
[Published](https://www.w3.org/TR/2018/CR-selectors-3-20180130/)
