### ISSUE TITLE
CR Snapshot Update Request for CSS Conditional 3

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#291]
# Document URLs
[ED](https://drafts.csswg.org/css-conditional-3/)

# Link to group's decision to request transition
[Minutes of TPAC F2F 2020-10-22](https://lists.w3.org/Archives/Public/www-style/2020Nov/0003.html)

# Link to previous Candidate Recommendation transition or update request
[Transition request: css3-conditional to CR](https://lists.w3.org/Archives/Member/chairs/2013JanMar/0130.html) (2013)!

# Substantive changes
[Changes](https://drafts.csswg.org/css-conditional-3/#changes)

# Any changes in requirements?
None

# Wide Review of substantive changes
[Wide Review status](https://github.com/w3c/csswg-drafts/issues/5569)

# Issues status
[Issues list](https://drafts.csswg.org/css-conditional-3/issues-cr-2013.html)

# Formal Objections
None

# Any changes in implementation information?
[Implementation report](https://test.csswg.org/harness/results/css-conditional-3_dev/grouped/)
[wpt.fyi](https://wpt.fyi/results/css/css-conditional?label=master&label=experimental&aligned)
The [API section](https://drafts.csswg.org/css-conditional-3/#apis) of this specification is [under-tested](https://wpt.fyi/results/css/css-conditional/js?label=master&label=experimental&aligned) and requires further tests to be made.

# Deadline for further comments
3 months

# Any changes in patent disclosures?
None

See [Requirements for updating a Candidate Recommendation Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot) for further information.

**Comment by swickr** [comment]
Transition approved.

(CR Update.)

**Comment by svgeesus** [comment]
Publication requested & Dec, expected 8 Dec.

**Comment by svgeesus** [comment]
[Published 8 Dec 2020](https://www.w3.org/TR/2020/CR-css-conditional-3-20201208/)
