### ISSUE TITLE
CR Snapshot Update Request for Web Audio API 1.0

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#292]
# Document URLs
[ED](https://webaudio.github.io/web-audio-api/)

# Link to group's decision to request transition
[minutes, 3 Dec 2020 telcon](https://lists.w3.org/Archives/Public/public-audio/2020OctDec/0024.html)

# Link to previous Candidate Recommendation transition or update request
[June 2020 CR](https://github.com/w3c/transitions/issues/146)

# Substantive changes
[Since Candidate Recommendation of 11 June 2020](https://webaudio.github.io/web-audio-api/#changes-2020-06-11)

# Any changes in requirements?
None

# Wide Review of substantive changes
* [Security review requested Sept 2020, no response yet](https://github.com/WebAudio/web-audio-api/issues/2254)
* [Privacy issues all closed](https://github.com/WebAudio/web-audio-api/issues?q=is%3Aissue++privacy+)
* [No A11y issues raised](https://github.com/WebAudio/web-audio-api/issues?q=is%3Aissue+label%3Aa11y-needs-resolution+)
* [No new I18n issues](https://github.com/WebAudio/web-audio-api/issues?q=is%3Aissue+label%3Ai18n-needs-resolution)
* No new features added; changes are in response to bug reports

# Issues status
[13 open, 1,268 closed issues](https://github.com/WebAudio/web-audio-api/issues)

# Formal Objections
None

# Any changes in implementation information?
Continued improvements in pass rate for Chrome and Firefox. Safari recently greatly improved, too.
[Implementation report](https://webaudio.github.io/web-audio-api/implementation-report.html)
[Detailed analysis of test failures](https://webaudio.github.io/web-audio-api/test-report.html) primarily edge cases
No change to exit criteria. 

# Deadline for further comments
One month (we are close to exiting CR)

# Any changes in patent disclosures?
None

See [Requirements for updating a Candidate Recommendation Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot) for further information.

**Comment by swickr** [comment]
Transition approved.

(CR Update)

**Comment by svgeesus** [comment]
Stalled due to [specberus bug](https://github.com/w3c/specberus/issues/1081)

**Comment by svgeesus** [comment]
Publication requested 13 Jan, expected 14 Jan

**Comment by svgeesus** [comment]
[Published 14 Jan 2021](https://www.w3.org/TR/2021/CR-webaudio-20210114/)
