### ISSUE TITLE
FPWD Request for EPUB 3.3.

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#293]
# Document title, URLs, estimated publication date

- EPUB 3.3
    - https://w3c.github.io/epub-specs/epub33/core/
- EPUB 3.3 Reading Systems 
    - https://w3c.github.io/epub-specs/epub33/rs/

Publications are planned beginning of January 2021.

# Abstract

- https://w3c.github.io/epub-specs/epub33/core/#abstract
- https://w3c.github.io/epub-specs/epub33/rs/#abstract

# Status

- https://w3c.github.io/epub-specs/epub33/core/#sotd
- https://w3c.github.io/epub-specs/epub33/rs/#sotd

# Is it a delta specification intended to become a W3C Recommendation?

no

# Link to group's decision to request transition

- https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-11-20-epub#resolution1

# Information about implementations known to the Working Group

The technical differences between this upcoming version of EPUB 3 and the previous public specification (EPUB 3.2) are minimal. EPUB 3.2 is widely implemented in epub readers.

Cc: @wareid @mattgarrish @shiestyle

**Comment by plehegar** [comment]
Some considerations for future updates: For EPUB 3.3, in "relationship to Other specifications", it would be good to say how it relates to previous versions of EPUB. A few normative references will need to be evaluated before moving in later stages (WebP, GIF, ZIP, etc.).

Both documents are approved for publication.

**Comment by jennyliang220** [comment]
Currently **/TR** doesn't have any EPUB publications, or document with shortname `epub`. The publication of `epub-33` will create new series starting with level 3.3. Is that what is expected?
cc @deniak

**Comment by iherman** [comment]
> Currently /TR doesn't have any EPUB publications, or document with shortname epub. The publication of epub-33 will create new series starting with level 3.3. Is that what is expected?

That is correct. EPUB has a complex history:

- versions < 3.2 were published by the IDPF under idpf.org URL-s
- version = 3.2 was published as a W3C CG report under https://www.w3.org/publishing/epub/ (and also https://www.w3.org/publishing/epub32/
- version > 3.2 is now Rec track by a WG, and hence it is on /TR

At some point the community will have to decide to redirect https://www.w3.org/publishing/epub/ to the EPUB 3.3 line, but that is down the line.

At this point I believe it would be premature to introduce a /TR/epub/ line, it would create confusion in the community. Again, we may introduce that versionless URL line later, when EPUB 3.3 is in PR or Rec.

**Comment by deniak** [comment]
> > Currently /TR doesn't have any EPUB publications, or document with shortname epub. The publication of epub-33 will create new series starting with level 3.3. Is that what is expected?
> 
> At this point I believe it would be premature to introduce a /TR/epub/ line, it would create confusion in the community. Again, we may introduce that versionless URL line later, when EPUB 3.3 is in PR or Rec.

Our current process will recreate the versionless URL as soon as the `epub-33` is published. This is how people can easily find the spec if they don't know the version and that's something we rely on in the TR redesign project. So I'm afraid, this part is not optional.

**Comment by iherman** [comment]
You mean /TR/epub/ will automatically exist?

O.k., but we should not give too much publicity to this. It may be a major source of confusion out there.

@dauwhe @wareid @TzviyaSiegman @shiestyle @mattgarrish

**Comment by deniak** [comment]
> You mean /TR/epub/ will automatically exist?

Correct.

> 
> O.k., but we should not give too much publicity to this. It may be a major source of confusion out there.
> 
> @dauwhe @wareid @TzviyaSiegman @shiestyle @mattgarrish

At the moment, we don't really advertise these versionless shortlinks. However, this is probably something we will rely more on in the future as people are often unaware of the different levels and statuses. Note that we are also thinking about giving the WG the possibility to provide a description of the different levels.

**Comment by iherman** [comment]
> Note that we are also thinking about giving the WG the possibility to provide a description of the different levels.

Ah. That would go a long way in alleviating the issues: making it clear to everyone in EPUB production that this version is still not production ready. 

The publishing community is more conservative than the Web Developer community insofar as using not-yet-final features, and is also bound to the usage of epubcheck as a central tool, whose evolution is not in our control...

Thanks @deniak

**Comment by plehegar** [comment]
https://www.w3.org/TR/2021/WD-epub-33-20210112/
