### ISSUE TITLE
FPNote for EPUB 3.3 Notes

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#294]
# Document title, URLs, estimated publication date

- EPUB 3.3
    - https://w3c.github.io/epub-specs/epub33/core/
- EPUB 3.3 Reading Systems 
    - https://w3c.github.io/epub-specs/epub33/rs/

Publications are planned beginning of January 2021.

# Abstract

- https://w3c.github.io/epub-specs/epub33/overview/#abstract
- https://w3c.github.io/epub-specs/epub33/multi-rend/#abstract

# Status
- https://w3c.github.io/epub-specs/epub33/overview/#sotd
- https://w3c.github.io/epub-specs/epub33/multi-rend/#sotd

# Link to group's decision to request transition

- https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-12-11-epub#resolution3
- https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-12-11-epub#resolution2

# Information about implementations known to the Working Group

The technical differences between this upcoming version of EPUB 3 and the previous public specification (EPUB 3.2) are minimal. EPUB 3.2 is widely implemented in epub readers.

Cc: @wareid @mattgarrish @shiestyle

**Comment by plehegar** [comment]
I believe the documents asked here are actually:
[[
EPUB 3 Overview
  https://w3c.github.io/epub-specs/epub33/overview/
EPUB Multiple-Rendition Publications 1.1
  https://w3c.github.io/epub-specs/epub33/multi-rend/
]]

With that mind, the publication are approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2021/NOTE-epub-overview-33-20210112/
https://www.w3.org/TR/2021/WD-epub-rs-33-20210112/
