### ISSUE TITLE
FPWD Request for screen-fold

### ISSUE THREAD

**Issue by xfq** [w3c/transitions#295]
# Document title, URLs, estimated publication date
The Screen Fold API
https://xfq.github.io/testing/screen-fold-WD/Overview.html
First Tuesday/Thursday after approval.

# Abstract
https://xfq.github.io/testing/screen-fold-WD/Overview.html#abstract

# Status
https://xfq.github.io/testing/screen-fold-WD/Overview.html#sotd

# Is it a delta specification intended to become a W3C Recommendation?
No.

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-device-apis/2020Dec/0004.html

# Information about implementations known to the Working Group
Polyfill: https://w3c.github.io/screen-fold/polyfill/demo.html

**Comment by plehegar** [comment]
Approved.

For later transitions, we should take a look again at https://github.com/w3c/dap-charter/issues/103#issuecomment-744446928 and see the level of reviews received for this document, especially TAG, CSS and PING.

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2020/WD-screen-fold-20201217/
