### ISSUE TITLE
FPWD Request for Data Catalog Vocabulary (DCAT) - Version 3

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#296]
# Document title, URLs, estimated publication date

Data Catalog Vocabulary (DCAT) - Version 3
https://w3c.github.io/dxwg/dcat/?specStatus=FPWD&publishDate=2020-12-17
17 December 2020

# Abstract

DCAT is an RDF vocabulary designed to facilitate interoperability between data catalogs published on the Web. This document defines the schema and provides examples for its use.

DCAT enables a publisher to describe datasets and data services in a catalog using a standard model and vocabulary that facilitates the consumption and aggregation of metadata from multiple catalogs. This can increase the discoverability of datasets and data services. It also makes it possible to have a decentralized approach to publishing data catalogs and makes federated search for datasets across catalogs in multiple sites possible using the same query mechanism and structure. Aggregated DCAT metadata can serve as a manifest file as part of the digital preservation process.

The namespace for DCAT terms is http://www.w3.org/ns/dcat#

The suggested prefix for the DCAT namespace is dcat

# Status

https://w3c.github.io/dxwg/dcat/?specStatus=FPWD&publishDate=2020-12-17#sotd

# Is it a delta specification intended to become a W3C Recommendation?

no

# Link to group's decision to request transition

https://www.w3.org/2020/12/01-dxwg-minutes.html

# Information about implementations known to the Working Group

None at this time.

cc @riccardoAlbertoni @pwin

**Comment by swickr** [comment]
Transition approved.

FPWD

**Comment by plehegar** [comment]
https://www.w3.org/TR/2020/WD-vocab-dcat-3-20201217/
