### ISSUE TITLE
PR Request for the January 2020 HTML Standard Review Draft

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#297]
# Document title, URLs, estimated publication date
HTML
Review Draft — Published 29 January 2020
December 21 2020
https://html.spec.whatwg.org/review-drafts/2020-01/
https://www.w3.org/TR/html/

# Abstract
None.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

The following features are non-normative for the purpose of the W3C Proposed Recommendation:

OffscreenCanvas
scrollPathIntoView() method of CanvasRenderingContext2D
srcObject setter for HTMLMediaElement, with media provider other than MediaStream (that is, a MediaSource or Blob)
close() method of SharedWorkerGlobalScope
alternative style sheets
autocapitalization
theme-color
accessKeyLabel property of HTMLElement
:dir pseudo-class
"preload" link type
"modulepreload" link type
"prerender" link type
"dragexit" event
"cancel" event
"oncancel" event handler
The W3C HTML Working Group co-produced this document under the W3C Patent Policy and the 15 September 2020 W3C Process Document. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy

# Link to group's decision to request transition
[HTMLWG/issue/#15](https://github.com/w3c/htmlwg/issues/15), no objection.

# Changes
None.

# Requirements satisfied
None.

# Dependencies met (or not)
All the normative references of this version are lists in the [References](https://html.spec.whatwg.org/review-drafts/2020-01/#references) section. The group believes these references are stable and have been reviewed by the editors.

# Wide Review
[w3c/htmlwg#8](https://github.com/w3c/htmlwg/issues/8)
No substantive issues were raised during the wide and horizontal review.

# Issues addressed
[w3c/htmlwg#13](https://github.com/w3c/htmlwg/issues/13), 1 issue raised during the CR period, non-normative.

# Formal Objections
None.

# Implementation
The group would like to use the [MDN BCD data of HTML](https://w3c.github.io/mdn-spec-links/less-than-2.html?spec=html) to prove adequate implementation experience.

# Patent disclosures
https://www.w3.org/2004/01/pp-impl/115520/status, note that the group has switched to Patent Policy 2020.

**Comment by siusin** [comment]
cc @plehegar @sideshowbarker

**Comment by plehegar** [comment]
Links to horizontal comments:
 https://www.w3.org/PM/horizontal/?repo=w3c/a11y-review#html
 https://www.w3.org/PM/horizontal/?repo=w3c/i18n-activity#html
 https://www.w3.org/PM/horizontal/?repo=w3c/security-review#html
 https://www.w3.org/PM/horizontal/?repo=w3cping/tracking-issues#html

**Comment by swickr** [comment]
Transition approved.

We note that any *-needs-resolution issues should be escalated to the WG if the horizontal group wishes them to be considered in Transition reviews.  We do not see any such escalations currently.

**Comment by siusin** [comment]
Spec Published on [22 Dec](https://www.w3.org/TR/2020/PR-html-20201222/).

AC Review: https://www.w3.org/2002/09/wbs/33280/html-2020-review-draft-pr/
