### ISSUE TITLE
FPNote for CSS 2020

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#298]
# Document title, URLs, estimated publication date
CSS Snapshot 2020
https://drafts.csswg.org/CSS-2020/
Tuesday **22 December 2020** just before the moratorium :) while it is still 2020

# Abstract
This document collects together into one definition all the specs that together form the current state of Cascading Style Sheets (CSS) as of 2020. The primary audience is CSS implementers, not CSS authors, as this definition includes modules by specification stability, not Web browser adoption rate.

# Status
https://drafts.csswg.org/CSS-2020/#status

# Link to group's decision to request transition
> RESOLVED: Publish snapshot 2020 as a note
https://www.w3.org/2020/12/16-css-irc#T17-30-49

# Information about implementations known to the Working Group

Everything listed here is widely implemented, unless explicitly noted as "broadly implemented" or "stable, but needs more testing"

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Publication requested 17 Dec, expected 22 Dec

**Comment by svgeesus** [comment]
[published 22 Dec](https://www.w3.org/TR/2020/NOTE-css-2020-20201222/)
