### ISSUE TITLE
[CSSWG] CR Request for CSS Text Level 3

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#299]
# Document title, URLs, estimated publication date
CSS Text Module Level 3
https://www.w3.org/TR/css-text-3/
Tuesday 21 December 2020

# Abstract
This CSS module defines properties for text manipulation and specifies their processing model. It covers line breaking, justification and alignment, white space handling, and text transformation.

# Status
https://www.w3.org/TR/css-text-3/#status

# Link to group's decision to request transition
https://www.w3.org/2020/12/16-css-minutes.html#t01
See https://lists.w3.org/Archives/Member/w3c-css-wg/2020OctDec/0099.html for context.

# Changes
https://drafts.csswg.org/css-text-3/#changes

# Requirements satisfied
AFAICT, aside from a few points that had to be marked undefined in this level.

# Dependencies met (or not)
Primary dependency is CSS2.

# Wide Review
LCWD 2013 and many comments since then.
a11y signoff https://lists.w3.org/Archives/Public/public-apa/2020Oct/0006.html
i18n signoff https://github.com/w3c/i18n-request/issues/146#issuecomment-742670641
TAG signoff https://github.com/w3ctag/design-reviews/issues/581#issuecomment-744686536
Privacy Review requested 6 October 2020, but no issues filed other than a question https://github.com/w3c/csswg-drafts/issues/5630
Security Review requested 6 October 2020, but no response
[CSSWG does not expect css-text-3 to raise any security or privacy issues other than the fingerprintability of line-breaking and hyphenation dictionaries (which is expected to track with the information already part of the UA string and/or accept-language headers).]

# Issues addressed
https://drafts.csswg.org/css-text-3/issues-lc-2013

# Formal Objections
None

# Implementation
Many parts of this spec have been implemented. There are many details that aren't quite right yet, though.
There's a draft test coverage report at https://drafts.csswg.org/css-text-3/test-coverage

# Patent disclosures
None

**Comment by plehegar** [comment]
Diff:
 https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fcss-text-3%2F&doc2=https%3A%2F%2Fdrafts.csswg.org%2Fcss-text-3%2F

Horizontal comments:
  https://www.w3.org/PM/horizontal/?repo=w3c/a11y-review#css-text
  https://www.w3.org/PM/horizontal/?repo=w3c/i18n-activity#css-text

Normative references:
 https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fdrafts.csswg.org%2Fcss-text-3%2F

**Comment by swickr** [comment]
Transition approved.

We presume the usual CR exit criteria for CSS will be used.

**Comment by svgeesus** [comment]
Publication requested 19 Dec, expected 22 Dec

**Comment by svgeesus** [comment]
[Published 22 Dec](https://www.w3.org/TR/2020/CR-css-text-3-20201222/)
