### ISSUE TITLE
[CSSWG] CR Request for CSS Box Model Level 3

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#300]
# Document title, URLs, estimated publication date
CSS Box Model Level 3
https://www.w3.org/TR/css-box-3/
Tuesday 21 December 2020

# Abstract
This specification specifies the CSS box model which defines margin, padding, and border areas for each box, and defines the margin and padding properties which create spacing in and around a CSS box.
It has no new features since CSS2, only updated terminology.

# Status
https://www.w3.org/TR/css-box-3/#status

# Link to group's decision to request transition
https://www.w3.org/2020/12/16-css-minutes.html#r07
See https://lists.w3.org/Archives/Member/w3c-css-wg/2020OctDec/0106.html for context.

# Changes
https://drafts.csswg.org/css-box-3/#changes

# Requirements satisfied
Yes

# Dependencies met (or not)
Only depends on CSS2.

# Wide Review
i18n signed off; other reviews were solicited as a formality but really, there's nothing new here to review.

# Issues addressed
Miscellaneous mostly editorial stuff. Nothing interesting except one about defining the SVG term "viewport", which was reviewed by Amelia.

# Formal Objections
None

# Implementation
This entire module has been fully implemented for probably a couple decades now.

# Patent disclosures
None

**Comment by plehegar** [comment]
Diff:
  https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fcss-box-3%2F&doc2=https%3A%2F%2Fdrafts.csswg.org%2Fcss-box-3%2F

Horizontal comments:
  https://www.w3.org/PM/horizontal/?repo=w3c/i18n-activity#css-box

Normative references:
 https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fdrafts.csswg.org%2Fcss-box-3%2F

**Comment by swickr** [comment]
Transition approved.

We presume the usual CR exit criteria for CSS will be used.

**Comment by svgeesus** [comment]
Publication requested 21 Dec, expected 22 Dec

**Comment by svgeesus** [comment]
[Published 22 Dec](https://www.w3.org/TR/2020/CR-css-box-3-20201222/)
