### ISSUE TITLE
CR Snapshot Update Request for CSS Backgrounds and Borders Level 3

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#301]
# Document URLs
CSS Backgrounds and Borders Level 3
https://www.w3.org/TR/css-backgrounds-3/
Tuesday 21 December 2020

# Link to group's decision to request transition
https://www.w3.org/2020/12/16-css-minutes.html#r08

# Link to previous Candidate Recommendation transition or update request
https://lists.w3.org/Archives/Member/chairs/2017OctDec/0000.html

# Substantive changes
https://drafts.csswg.org/css-backgrounds-3/#changes

# Any changes in requirements?
None

# Wide Review of substantive changes
Only very minor details were updated; these have all been reviewed by the CSSWG and its members.

# Issues status
Nothing substantive is open. (We have a request to add more referenceable terms, but this is editorial and we don't yet have good names.)
https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+label%3Acss-backgrounds-3+

# Formal Objections

None.

# Any changes in implementation information?
Nothing exciting. Most of the module is implemented, a few details not quite there yet.

# Deadline for further comments
None. I suppose we can pick a random date in the future, like 30 June 2021 or something.

# Any changes in patent disclosures?
None

See [Requirements for updating a Candidate Recommendation Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot) for further information.

**Comment by plehegar** [comment]
Diff:
 https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2017%2FCR-css-backgrounds-3-20171017%2F&doc2=https%3A%2F%2Fdrafts.csswg.org%2Fcss-backgrounds-3%2F

Horizontal comments:
 (none)

Normative references:
  https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fdrafts.csswg.org%2Fcss-backgrounds-3%2F

**Comment by swickr** [comment]
Transition approved.

(CR Update)

**Comment by svgeesus** [comment]
Publication requested 21 Dec, expected 22 Dec

**Comment by svgeesus** [comment]
[Published 22 Dec](https://www.w3.org/TR/2020/CR-css-backgrounds-3-20201222/)
