### ISSUE TITLE
FP IG Note for The Responsible Use of Spatial Data

### ISSUE THREAD

**Issue by tguild** [w3c/transitions#302]
# Document title, URLs, estimated publication date

The Responsible Use of Spatial Data 
https://w3c.github.io/sdw/responsible-use/ 
22 December 2020

# Abstract

This note highlights some of the unique characteristics of spatial data within the broader realm of ethical use of data. A brief analysis of the relationship between law and ethics explains that responsible use is not mandatory. Nevertheless, both legal and ethical frameworks play an important role in shaping what can be considered “responsible”. As do the perspectives of those who interact closely with spatial data: the developers, the users and the regulators. Therefore this note not only provides an insight into the relevant legislation and ethics guidelines, but also considers the principles of ethical data sharing from each of these three perspectives. The principles are made practical by providing concrete communication guidelines and showing examples of good practice. 

# Status

FPWD

#Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-sdwig/2020Dec/0021.html

# Information about implementations known to the Group (if relevant)

N/A

**Comment by tguild** [comment]
Requested a less generic shortname and will update URI when we rename the file.

**Comment by plehegar** [comment]
(awaiting for the shortname update)

**Comment by tguild** [comment]
responsible-use-spatial

https://github.com/w3c/sdw/issues/1232

**Comment by plehegar** [comment]
Approved.

**Comment by tguild** [comment]
Thanks @plehegar

**Comment by tguild** [comment]
https://www.w3.org/TR/2021/NOTE-responsible-use-spatial-20210119/

published
