### ISSUE TITLE
FPWD Request for CSS Cascading and Inheritance Level 5

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#304]
# Document title, URLs, estimated publication date
CSS Cascading and Inheritance Module Level 5
https://drafts.csswg.org/css-cascade-5/
Tuesday 12 January 2021

# Abstract
This CSS module describes how to collate style rules and assign values to all properties on all elements. By way of cascading and inheritance, values are propagated for all properties on all elements. New in this level is cascade layers.

# Status
https://drafts.csswg.org/css-cascade-5/#status

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/www-style/2021Jan/0001.html

# Information about implementations known to the Working Group
none

**Comment by plehegar** [comment]
Approved

**Comment by fantasai** [comment]
@xfq @svgeesus Document should be in a buildable state for FPWD, so whenever you and webreq are ready.

**Comment by svgeesus** [comment]
Publication request sent 18 Jan, expected 19 Jan

**Comment by svgeesus** [comment]
[Published 19 Jan 2021](https://www.w3.org/TR/2021/WD-css-cascade-5-20210119/)
