### ISSUE TITLE
FPWD Request for Requirements for WCAG 3.0

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/transitions#305]
# Document title, URLs, estimated publication date
Title: Requirements for WCAG 3.0
Editors' draft URI: https://w3c.github.io/silver/requirements/
Anticipated publication URI: https://www.w3.org/TR/2020/WD-wcag-3.0-requirements-20200119/
Desired publication date: 19 January 2021

# Abstract
The Requirements for WCAG 3.0 document is the next phase in the development of the next major upgrade to accessibility guidelines that will be the successor to Web Content Accessibility Guidelines (WCAG) 2 series. The Silver Task Force of the Accessibility Guidelines Working Group and the W3C Silver Community group have partnered to incubate the needs, requirements, and structure for the new accessibility guidance. To date, the group has:

    Researched accessibility guidance needs
    Developed problem statements and opportunities to improve accessibility guidance
    Received input from industry leaders for directions to proceed
    Drafted these high-level requirements for the next phase of the project, the prototyping and public input.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

This is a First Public Working Draft of Requirements for WCAG 3.0 by the Accessibility Guidelines Working Group, with primary development in the Silver Task Force and Silver Community Group. It is published alongside and in support of the First Public Working Draft of W3C Accessibility Guidelines (WCAG) 3.0. These requirements define goals and approaches for WCAG 3 to have a different scope, structure, and conformance model from WCAG 2. These requirements will be updated periodically as experience grows with WCAG 3, in order to define clear goals that remain achievable.

To comment, file an issue in the W3C silver GitHub repository. The Working Group requests that public comments be filed as new issues, one issue per discrete comment. It is free to create a GitHub account to file issues. If filing issues in GitHub is not feasible, send email to public-agwg-comments@w3.org (comment archive). The Working Group requests comments on this draft be sent by 26 February 2021. In-progress updates to the guidelines can be viewed in the public editors' draft.

This document was published by the Accessibility Guidelines Working Group as a First Public Working Draft.

GitHub Issues are preferred for discussion of this specification.

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership.

This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the 1 August 2017 W3C Patent Policy. The group does not expect this document to become a W3C Recommendation. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 15 September 2020 W3C Process Document. 

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/w3c-wai-gl/2020OctDec/0023.html

# Information about implementations known to the Working Group
No implementations

# Extra

* This document is Note track.
* This document is intended to be co-published with WCAG 3.0, whose Transition Request is #303.

**Comment by plehegar** [comment]
Approved.

**Comment by jennyliang220** [comment]
Hi @plehegar @michael-n-cooper, same as [#303](https://github.com/w3c/transitions/issues/303#issuecomment-763745577), WCAG 3.0 Requirement is using different [shortname strategy](https://github.com/w3c/manual-of-style/pull/13#issuecomment-756587936) from WCAG 2 requirement.

Anticipated Publication URI: https://www.w3.org/TR/wcag-3.0-requirements/

For WCAG2 requirement, it's: https://www.w3.org/TR/wcag2-req/

**Comment by plehegar** [comment]
https://www.w3.org/TR/2021/WD-wcag-3.0-requirements-20210121/
