### ISSUE TITLE
REC Request for WebRTC 1.0

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/transitions#307]
# Link to internal transition

https://lists.w3.org/Archives/Team/w3t-comm/2021Jan/0170.html

# Link to previous transition
https://github.com/w3c/transitions/issues/290

**Comment by swickr** [comment]
Process 2001 requires a record of the Working Group's decision [[6.2.10](https://www.w3.org/2020/Process-20200915/#transition-rec) -> [6.2.3](https://www.w3.org/2020/Process-20200915/#transition-reqs)].  Where may we find that record?

Not a showstopper for this transition, but it feels odd to me to have closed #2620 rather than labeling it for consideration in a future version.

Adobe had suggested an editorial change to the implementation report.  Was this addressed?

May I please see the proposed custom SoTD paragraph and the statement of where errata will be tracked.

**Comment by dontcallmedom** [comment]
My interpretation of the process is that for the 1st Recommendation, the WG decision to move to Proposed Recommendation serves as the logical WG decision to move to Rec (since the WG loses most of its agency in the PR->Rec phase); I can see why separate WG decisions would be useful to updated Recs, but I don't think they would mean anything for a 1st Rec. If a separate WG decision is needed for a 1st Rec, then that isn't available.

I've re-opened and transfered the former issue 2620 to https://github.com/w3c/webrtc-extensions/issues/65 in case it benefits from being revisited in the next iteration.

The editorial change to the implementation report [was implemented](https://github.com/w3c/webrtc-interop-reports/commit/117ae459b806e6e9f66e3ab873036921bc6e02e1) and copied in the snapshot linked from the PR.

The errata will be tracked in https://w3c.github.io/webrtc-pc/errata.html

SOTD:
> This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.
>
> The API is based on preliminary work done in the WHATWG.
>
>Its associated test suite is used to build an implementation report of the API.
>
>This document was published by the Web Real-Time Communications Working Group as a Recommendation.
>
>GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-webrtc@w3.org (archives).
>
>A W3C Recommendation is a specification that, after extensive consensus-building, has received the endorsement of the W3C and its Members. W3C recommends the wide deployment of this specification as a standard for the Web. Future updates to this Recommendation may incorporate new features.
>
>This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.
>
>This document is governed by the 15 September 2020 W3C Process Document.

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2021/REC-webrtc-20210126/

Can we close this now?

**Comment by dontcallmedom** [comment]
🎉
