### ISSUE TITLE
FPWD Request for 6 gap-analysis documents

### ISSUE THREAD

**Issue by r12a** [w3c/transitions#310]
# Document title, URLs, estimated publication date

Adlam Gap Analysis, estimated publication date 4 feb 2021
https://www.w3.org/TR/WD-adlm-gap-20210204/

Hebrew Gap Analysis, estimated publication date 4 feb 2021
https://www.w3.org/TR/WD-hebr-gap-20210204/

German Gap Analysis, estimated publication date 4 feb 2021
https://www.w3.org/TR/WD-latn-de-gap-20210204/

French Gap Analysis, estimated publication date 4 feb 2021
https://www.w3.org/TR/WD-latn-fr-gap-20210204/

N'Ko Gap Analysis, estimated publication date 4 feb 2021
https://www.w3.org/TR/WD-nkoo-gap-20210204/

Osage Gap Analysis, estimated publication date 4 feb 2021
https://www.w3.org/TR/WD-osge-osa-gap-20210204/

# Abstract
This document describes and prioritises gaps for the support of <language> on the Web and in eBooks. In particular, it is concerned with text layout. It checks that needed features are supported in W3C specifications, in particular HTML and CSS and those relating to digital publications. It also checks whether the features have been implemented in browsers and ereaders. This is a preliminary analysis.

# Status
See links above.

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://www.w3.org/2021/01/28-i18n-minutes.html#t05

# Information about implementations known to the Working Group
n/a

**Comment by xfq** [comment]
These links are all 404 for me... Have you uploaded them to CVS, @r12a?

**Comment by jennyliang220** [comment]
Hi @r12a @xfq, I just installed the documents. The links are:

- https://www.w3.org/TR/2021/WD-adlm-gap-20210204/
- https://www.w3.org/TR/2021/WD-hebr-gap-20210204/
- https://www.w3.org/TR/2021/WD-latn-de-gap-20210204/
- https://www.w3.org/TR/2021/WD-latn-fr-gap-20210204/
- https://www.w3.org/TR/2021/WD-nkoo-gap-20210204/
- https://www.w3.org/TR/2021/WD-osge-osa-gap-20210204/

**Comment by xfq** [comment]
Thanks @jennyliang220! They look good to me :)

**Comment by plehegar** [comment]
Approved.

**Comment by xfq** [comment]
Published. Closing.
