### ISSUE TITLE
Amended REC update for XSLT 2.0

### ISSUE THREAD

**Issue by caribouW3** [w3c/transitions#312]
# Document title, URLs, estimated publication date
https://www.w3.org/TR/xslt20

from the PER:
https://www.w3.org/TR/2009/PER-xslt20-20090421/

# Abstract
This specification defines the syntax and semantics of XSLT 2.0, a language for transforming XML documents into other XML documents.

XSLT 2.0 is a revised version of the XSLT 1.0 Recommendation [XSLT 1.0] published on 16 November 1999.

XSLT 2.0 is designed to be used in conjunction with XPath 2.0, which is defined in [XPath 2.0]. XSLT shares the same data model as XPath 2.0, which is defined in [Data Model], and it uses the library of functions and operators defined in [Functions and Operators].

XSLT 2.0 also includes optional facilities to serialize the results of a transformation, by means of an interface to the serialization component described in [XSLT and XQuery Serialization].

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

This document is governed by the 15 september 2020 W3C Process Document.

This is one document in a set of eight documents that have being progressed to Edited Recommendation together (XPath 2.0, XQuery 1.0, XQueryX 1.0, XSLT 2.0, Data Model (XDM), Functions and Operators, Formal Semantics, Serialization). 

The Proposed Edited Recommendation of XSLT 2.0 was published on 21 April 2009. The second edition is not a new version of this specification; its purpose is to clarify a number of issues that have become apparent since the first edition was published. All of these clarifications (excepting trivial editorial fixes) have been published in a separate errata document.

The W3C Team publishes the XSLT 2.0 Recommentation (2nd Edition), following the [Amended Recommendation process]
(https://www.w3.org/2020/Process-20200915/#rec-amended)

Please report errors in and submit comments on this document using <a href="https://github.com/w3c/qtspecs">https://github.com/w3c/qtspecs</a>. You may send your comments to the W3C XSLT/XPath/XQuery public comments mailing list, public-qt-comments@w3.org. It will be very helpful if you include the string "[XSLT 2.0]" in the subject line of your report, whether made in GitHub or in email. Each GH issue and email message should contain only one error report.

This document was produced by groups operating under the 5 February 2004 W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the XML Query Working Group and also maintains a public list of any patent disclosures made in connection with the deliverables of the XSL Working Group; those pages also include instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

# Link to decision to request transition
N/A

# Changes
None since https://www.w3.org/TR/2009/PER-xslt20-20090421/

# Wide Review
N/A

# Formal Objections
None raised during PER AC review in 2009.

# Any changes in patent disclosures?
N/A

**Comment by swickr** [comment]
PLH and I are studying the history of this document.  It was one of 8 documents in an AC [Call for Review issued on 21 April 2009](https://lists.w3.org/Archives/Member/w3c-ac-members/2009AprJun/0020.html).  The other 7 documents [advanced to Recommendation in December 2010.](https://lists.w3.org/Archives/Member/w3c-ac-members/2010OctDec/0064.html)

**Comment by swickr** [comment]
[XSLT 3.0 advanced to Recommendation](https://lists.w3.org/Archives/Member/w3c-ac-members/2017AprJun/0054.html) in June 2017.

**Comment by swickr** [comment]
Please find citable records of the reasons for not including this document in the December 2010 announcement.   It is apparently related to completion of XSLT 3.0 work; e.g. if the WG asked the Director in 2010 to hold on this document.

I am not comfortable proceeding until we can cite a record of what the WG requested of the Director in 2010.

**Comment by caribouW3** [comment]
Mostly a testing issue, the XQuery WG had successfully finished 2.0 2nd testing, whereas XSLT 2.0 second implementation report was missing. Situation continued, even though 3.0 got a double implementation testing.
(member-only pointers:
Test plan in https://lists.w3.org/Archives/Member/w3c-xsl-wg/2010Dec/0063.html, then 
https://lists.w3.org/Archives/Member/w3c-xsl-wg/2011Feb/0027.html )

**Comment by swickr** [comment]
Thanks for these pointers, Carine.  Noting @michaelhkay's [comment in February 2011](https://lists.w3.org/Archives/Member/w3c-xsl-wg/2011Feb/0026.html) in particular that "nearly" all the changes are clarifications, and the community has has several years now to review at the PER it should advance to Recommendation.

Transition approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2021/REC-xslt20-20210330/
