### ISSUE TITLE
FPNote for EPUB Accessibility Techniques 1.1

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#313]
# Document title, URLs, estimated publication date

- EPUB Accessibility Techniques 1.1
    - https://w3c.github.io/epub-specs/epub33/a11y-tech/
    - short name: epub-a11y-tech-11

Publications are planned beginning of 23 February 2021.

# Abstract

- https://w3c.github.io/epub-specs/epub33/a11y-tech/#abstract

# Status

- https://w3c.github.io/epub-specs/epub33/a11y-tech/#sotd

# Is it a delta specification intended to become a W3C Recommendation?

no

# Link to group's decision to request transition

- https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-12-epub#resolution1

# Information about implementations known to the Working Group

This document is based of an earlier, IDPF document which is widely used by the industry already

Cc: @wareid @mattgarrish @shiestyle @avneeshsingh

**Comment by plehegar** [comment]
Approved

**Comment by iherman** [comment]
Published on 2021.02.23:

https://www.w3.org/blog/news/archives/8923
