### ISSUE TITLE
CR Snapshot Update Request for css-scroll-snap [CSSWG]

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#317]
# Document URLs
ED https://drafts.csswg.org/css-scroll-snap-1/
TR https://www.w3.org/TR/css-scroll-snap-1/

# Link to group's decision to request transition
https://www.w3.org/2021/02/24-css-minutes.html#r03

# Link to previous Candidate Recommendation transition or update request
https://github.com/w3c/transitions/issues/114

# Substantive changes
https://drafts.csswg.org/css-scroll-snap-1/#changes

# Any changes in requirements?
Nope

# Wide Review of substantive changes
https://drafts.csswg.org/css-scroll-snap-1/issues-cr-2019

# Issues status
https://drafts.csswg.org/css-scroll-snap-1/issues-cr-2019

# Formal Objections
None

# Any changes in implementation information?
Widely, but incompletely, implemented.

# Deadline for further comments
N/A

# Any changes in patent disclosures?
None

See [Requirements for updating a Candidate Recommendation Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot) for further information.

**Comment by plehegar** [comment]
No needs-resolution issues: https://www.w3.org/PM/horizontal/

No i18n horizontal review request in:
   https://github.com/w3c/i18n-request/issues
No APA review request:
   https://www.w3.org/Search/Mail/Public/search?keywords=css-scroll-snap&index-type=t&type-index=public-apa
No Privacy review request:
   https://www.w3.org/Search/Mail/Public/search?keywords=css-scroll-snap&index-type=t&type-index=public-privacy
No Security review request:
   https://www.w3.org/Search/Mail/Public/search?keywords=css-scroll-snap&index-type=t&type-index=public-web-security
No TAG review request:
    https://github.com/w3ctag/design-reviews/issues?q=is%3Aissue+%22css-snap-scroll%22+

**Comment by swickr** [comment]
Transition approved.

(CR Update)
When was the last time this spec received Horizontal Review?

**Comment by plehegar** [comment]
Normative references:
 https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fdrafts.csswg.org%2Fcss-scroll-snap-1%2F

**Comment by fantasai** [comment]
@swickr Prior to the CR transition, which was in 2016. It hasn't changed much since then, other than a few i18n issues which we've been in contact with i18n on.

**Comment by plehegar** [comment]
fyi, here is a new view:
 https://www.w3.org/PM/horizontal/review.html?shortname=css-scroll-snap

**Comment by plehegar** [comment]
and APA: https://www.w3.org/WAI/APA/wiki/CSS_Scroll_Snap_Module_Level_1

**Comment by plehegar** [comment]
https://www.w3.org/TR/2021/CR-css-scroll-snap-1-20210311/
