### ISSUE TITLE
FPWD Request for Indexed Database API 3.0

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/transitions#318]
# Document title, URLs, estimated publication date
Indexed Database API 3.0
https://w3c.github.io/IndexedDB/
11 March 2021

# Abstract
This document defines APIs for a database of records holding simple values and hierarchical objects. Each record consists of a key and some value. Moreover, the database maintains indexes over records it stores. An application developer directly uses an API to locate records either by their key or by using an index. A query language can be layered on this API. An indexed database can be implemented using a persistent B-tree data structure.

# Status
https://w3c.github.io/IndexedDB/#status

# Is it a delta specification intended to become a W3C Recommendation?
Unsure

# Link to group's decision to request transition
CFC ends 9th of March
https://lists.w3.org/Archives/Public/public-webapps/2021JanMar/0008.html

# Information about implementations known to the Working Group
https://github.com/w3c/IndexedDB/issues/348#issuecomment-784664331

**Comment by plehegar** [comment]
Approved.

The spec should explain its relationship with previous version if it intends to supersede them.

We have 2 RECs for IndexedDB on /TR and I'm not sure this is needed:
  https://www.w3.org/TR/?title=indexed

**Comment by plehegar** [comment]
Btw, this is not a delta specification. It includes (all?) parts from the previous version and is a standalone spec.

**Comment by siusin** [comment]
@plehegar there is a [Revision history](https://w3c.github.io/IndexedDB/#revision-history) section in the spec, is this good enough to clarify its relationship with the 2.0?

**Comment by plehegar** [comment]
Nope. The spec should stated whether it's meant to replace IDB 2 or something different.

For example, the status could say" IDB 3.0 is intended to supersede IDB 2.0".

**Comment by marcoscaceres** [comment]
Ok, will follow up with the spec Editor...

**Comment by plehegar** [comment]
https://www.w3.org/TR/2021/WD-IndexedDB-3-20210311/
