### ISSUE TITLE
CR Request for WebRTC Priority Control API

### ISSUE THREAD

**Issue by caribouW3** [w3c/transitions#319]
Hi, 
This is a request to advance WebRTC Priority Control API to Candidate Rec status.

# Document title, URLs, estimated publication date
https://www.w3.org/TR/webrtc-priority/

ed draft https://w3c.github.io/webrtc-priority/
No publication date anticipated, flexible.

# Abstract
This API defines a control surface for manipulating the network control bits (DSCP bits) of outgoing WebRTC packets, and the queueing priority of outgoing WebRTC packets under congestion.

# Status
https://w3c.github.io/webrtc-priority/#sotd

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-webrtc/2021Feb/0042.html

# Changes
Links to most recent IETF specs in References
otherwise no change.

# Requirements satisfied
N/A

# Dependencies met (or not)
None

# Wide Review
https://github.com/w3c/webrtc-priority/issues/16

# Issues addressed
https://github.com/w3c/webrtc-priority/issues/

# Formal Objections
None

# Implementation
Transition to PR and REC will be requested as soon as there are 2 implementations.

# Patent disclosures
https://www.w3.org/2004/01/pp-impl/47318/status

**Comment by plehegar** [comment]
[Diff between WD and ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fwebrtc-priority%2F&doc2=https%3A%2F%2Fw3c.github.io%2Fwebrtc-priority%2F)
 
[Normative references](https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fw3c.github.io%2Fwebrtc-priority%2F)

Reviews: [i18n](https://github.com/w3c/i18n-request/issues/131), [APA](https://lists.w3.org/Archives/Public/public-apa/2020Sep/0016.html), [Privacy](https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0026.html), [Security](https://lists.w3.org/Archives/Public/public-web-security/2020Sep/0002.html), [TAG](https://github.com/w3ctag/design-reviews/issues/560)

[Horizontal comment tracker](https://www.w3.org/PM/horizontal/review.html?shortname=webrtc-priority)

**Comment by swickr** [comment]
Transition approved.

Please add your CR exit criteria in the SoTD.  I presume the statement under "implementation" in this transition request is what you intend; i.e. 2 implementations that pass the test suite, as started in https://github.com/w3c/webrtc-priority/issues/11

There is a new section "[Conformant Algorithms](https://w3c.github.io/webrtc-priority/#w3c-conformant-algorithms)" that appears to have been added by bikeshed.  Were you aware of this?  Do you feel it is appropriate for this spec?

**Comment by caribouW3** [comment]
I was not aware of that part of boilerplate that bikeshed adds. Since it's easy to overwrite (locally or in the bikeshed repo boilerplates), I removed it.
