### ISSUE TITLE
FPWD Request for Open Screen Protocol

### ISSUE THREAD

**Issue by tidoust** [w3c/transitions#322]
# Document title, URLs, estimated publication date
- Title: Open Screen Protocol
- URL: https://w3c.github.io/openscreenprotocol/
- Shortname: openscreenprotocol
- Estimated publication date: Tuesday 16 March or Thursday 18 March

# Abstract
The Open Screen Protocol is a suite of network protocols that allow user agents to implement the [Presentation API](https://www.w3.org/TR/presentation-api/) and the [Remote Playback API](https://www.w3.org/TR/remote-playback/) in an interoperable fashion.

# Status
 This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

This document was published by the Second Screen Working Group as a Working Draft. This document is intended to become a W3C Recommendation.

The Second Screen Working Group maintains a list of all bug reports that the group has not yet addressed. This draft highlights some of the pending issues that are still to be discussed in the working group. No decision has been taken on the outcome of these issues including whether they are valid. Pull requests with proposed specification text for outstanding issues are strongly encouraged.

This document is a First Public Working Draft.

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 15 September 2020 W3C Process Document. 

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-secondscreen/2021Mar/0008.html

# Information about implementations known to the Working Group
Google develops an open source [Open Screen Library](https://chromium.googlesource.com/openscreen/).

**Comment by plehegar** [comment]
Approved. Congratulations on getting the spec to move forward!

**Comment by tidoust** [comment]
FPWD published:
https://www.w3.org/TR/2021/WD-openscreenprotocol-20210318/
https://www.w3.org/TR/openscreenprotocol/

Publication announced to chairs and [public-transition-announce](https://lists.w3.org/Archives/Public/public-transition-announce/2021Mar/0003.html). I'm not expecting further announcements.

**Comment by tidoust** [comment]
> I'm not expecting further announcements.

Well, except the one on the home page, that is, which was done as well :)
https://www.w3.org/blog/news/archives/8973
