### ISSUE TITLE
FPWD Request for WebCodecs + companion registry and AVC (H.264) WebCodecs registration

### ISSUE THREAD

**Issue by tidoust** [w3c/transitions#323]
# Document title, URLs, estimated publication date

* [WebCodecs](https://w3c.github.io/webcodecs/) - Shortname: `webcodecs`
* [WebCodecs Codec Registry](https://w3c.github.io/webcodecs/codec_registry.html) - Shortname: `webcodecs-codec-registry`
* [AVC (H.264) WebCodecs Registration](https://w3c.github.io/webcodecs/avc_codec_registration.html) - Shortname: `webcodecs-avc-codec-registration`

Plan is to publish the registry and registration specs as non-normative Working Group Notes, as was done for the MSE/EME registries and registrations.

Estimated publication date: Thursday 8 April 2021.

# Abstract

* [Abstract for WebCodecs](https://w3c.github.io/webcodecs/#abstract)
* [Abstract for WebCodecs Codec Registry](https://w3c.github.io/webcodecs/codec_registry.html#abstract)
* [Abstract for AVC (H.264) WebCodecs Registration](https://w3c.github.io/webcodecs/avc_codec_registration.html#abstract)

# Status for WebCodecs

This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index</a> at https://www.w3.org/TR/.

The Media Working Group maintains a list of all bug reports that the group has not yet addressed. This draft highlights some of the pending issues that are still to be discussed in the working group. No decision has been taken on the outcome of these issues including whether they are valid. Pull requests with proposed specification text for outstanding issues are strongly encouraged.

This document was published by the Media Working Group as a Working Draft. This document is intended to become a W3C Recommendation.

This document is a First Public Working Draft.

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 15 September 2020 W3C Process Document.

# Status for Registry and AVC registration

Same as above with "This document is intended to become a W3C Recommendation" replaced by "This document is intended to become a W3C Working Group Note".

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
See [outcome of the CfC](https://lists.w3.org/Archives/Public/public-media-wg/2021Mar/0004.html) and [update after the split](https://lists.w3.org/Archives/Public/public-media-wg/2021Mar/0006.html).

# Information about implementations known to the Working Group
[Original trial in Chrome](https://www.chromestatus.com/feature/5669293909868544)

**Comment by plehegar** [comment]
The Process CG is working a new [process for registries](https://www.w3.org/Consortium/Process/Drafts/#registries). [6.4.1. Registry Definitions](https://www.w3.org/Consortium/Process/Drafts/#reg-def) mentions the need to identify the custodian of the registry tables (sections 3 and 4 of this draft) and, more importantly, the method and criteria by which to these tables 
 changes are proposed, approved, and incorporated. Please consider, for future updates, expanding on the 5th bullet in [Registration Entry Requirements](https://w3c.github.io/webcodecs/codec_registry.html#registration-entry-requirements), since it only mentions how to propose but doesn't say how propose changes get approved.

For the registration document, please make sure to change "This document is intended to become a W3C Recommendation. ".

All 3 documents approved for publication.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2021/WD-webcodecs-avc-codec-registration-20210408/
https://www.w3.org/TR/2021/WD-webcodecs-20210408/
https://www.w3.org/TR/2021/WD-webcodecs-codec-registry-20210408/
