### ISSUE TITLE
REC Request for Web AUthn Level 2

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#324]
# Link to internal transition

https://lists.w3.org/Archives/Team/w3t-comm/2021Apr/0030.html

# Link to previous transition

https://github.com/w3c/transitions/issues/315

Updated implementation report:
  https://www.w3.org/2020/12/webauthn-report.html

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2021/REC-webauthn-2-20210408/

**Comment by swickr** [comment]
Transition approved (yesterday).
