### ISSUE TITLE
FPWD Request for MiniApp Manifest

### ISSUE THREAD

**Issue by xfq** [w3c/transitions#327]
# Document title, URLs, estimated publication date
MiniApp Manifest
https://xfq.github.io/testing/miniapp-manifest-WD/Overview.html
proposed publication 11 May 2021

# Abstract
https://xfq.github.io/testing/miniapp-manifest-WD/Overview.html#abstract

# Status
https://xfq.github.io/testing/miniapp-manifest-WD/Overview.html#sotd

# Is it a delta specification intended to become a W3C Recommendation?
No.

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-miniapps-wg/2021Apr/0001.html

# Information about implementations known to the Working Group
Various MiniApp platforms support some kind of JSON-based file format to put metadata associated with a MiniApp.

**Comment by xfq** [comment]
cc @zhangyongjing

**Comment by xfq** [comment]
I would like to have a look at https://github.com/w3c/miniapp-manifest/pull/16 before publishing FPWD.

Removing `Awaiting Director` for now.

**Comment by zhangyongjing** [comment]
That's what I expected. Thanks @xfq .

**Comment by xfq** [comment]
https://github.com/w3c/miniapp-manifest/pull/16 has been merged.

Adding `Awaiting Director` to get Director's approval.

**Comment by plehegar** [comment]
Approved
