### ISSUE TITLE
PR Request for Web Audio API

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#328]
# Document title, URLs, estimated publication date

Web Audio API
https://webaudio.github.io/web-audio-api/
Tues 4 May (after AC publishing moratorium)

# Abstract

[Abstract](https://webaudio.github.io/web-audio-api/#abstract)

# Status

[Status as ED](https://webaudio.github.io/web-audio-api/#sotd)

# Link to group's decision to request transition

[Minutes of Thurs Apr 1 telcon](https://lists.w3.org/Archives/Public/public-audio/2021AprJun/0000.html)

# Changes
[Changes since Candidate Recommendation Snapshot, 14 January 2021](https://webaudio.github.io/web-audio-api/#changes-2021-01-14)

# Requirements satisfied

No change since CR snapshot

# Dependencies met (or not)

No change since CR snapshot

# Wide Review

No new features added; changes are clarifications and corrections in response to bug reports and are backed by the implementers

# Issues addressed

[7 open, 1289 closed issues]()
5 administrative, one new minor editorial, one still hoping for security review request to be responded to.

# Formal Objections

None

# Implementation

[Implementation report](https://webaudio.github.io/web-audio-api/implementation-report.html) and [detailed report on test failures](https://webaudio.github.io/web-audio-api/test-report.html) shows the vast majority of the 7,600 tests are passed.

# Patent disclosures

[Disclosures for Audio WG](https://www.w3.org/2004/01/pp-impl/46884/status)

**Comment by plehegar** [comment]
(scheduled for Director's attention on April 30?)

**Comment by svgeesus** [comment]
Magic wording for living standard

```html      
Future updates to this Recommendation may incorporate
 <a href="https://www.w3.org/2020/Process-20200915/#allow-new-features">new 
features</a>.
```

**Comment by svgeesus** [comment]
[Static snapshot of wpt results](https://lists.w3.org/Archives/Public/www-archive/2021Apr/0001.html) (25MB PDF)

**Comment by swickr** [comment]
Transition approved.

We noticed a /TR/HTML50 reference that should be updated to the WHATWG LS in "named processorerror using ErrorEvent at nodeReference."
We noticed several gitub.io references that should be updated to w3.org references.
Add MIMEsniff to normative refs.

**Comment by svgeesus** [comment]
Publication requested 5 May, expected 6 May.

**Comment by svgeesus** [comment]
{Published 6 May](https://www.w3.org/TR/2021/PR-webaudio-20210506/)
