### ISSUE TITLE
FPWD Request for WebTransport

### ISSUE THREAD

**Issue by ylafon** [w3c/transitions#329]
# Document title, URLs, estimated publication date
Title: WebTransport
URL: https://w3c.github.io/webtransport/
(currently, only the edcopy is available due to bikeshed not knowing WebTransport WG yet, PR sent).
Estimated Publication Date: Thursday 22 April 2020

# Abstract
This document defines a set of ECMAScript APIs in WebIDL to allow data to be sent and received between a browser and server, utilizing [WEB-TRANSPORT-HTTP3]. This specification is being developed in conjunction with a protocol specification developed by the IETF WEBTRANS Working Group.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

This document was published by the WebTransport Working Group as a Working Draft. This document is intended to become a W3C Recommendation.

Feedback and comments on this document are welcome. Please file an issue in this document’s GitHub repository.

This document is a First Public Working Draft.

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 15 September 2020 W3C Process Document.

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-webtransport/2021Apr/0000.html

# Information about implementations known to the Working Group

**Comment by plehegar** [comment]
Approved for publication.

This specification should have security/privacy reviews *as soon as possible*.

TAG review of the original proposal at https://github.com/w3ctag/design-reviews/issues/389 .

**Comment by ylafon** [comment]
See https://www.w3.org/TR/2021/WD-webtransport-20210504/
