### ISSUE TITLE
FPNote for WoT Use Cases and Requirements Note (by the WoT IG)

### ISSUE THREAD

**Issue by ashimura** [w3c/transitions#330]
# Document title, URLs, estimated publication date

## Title
Web of Things (WoT): Use Cases and Requirements

## URL
https://w3c.github.io/wot-usecases/index.html

### Proposed shortname
wot-usecases

Note:
The group uses "wot-usecases" as the shortname for the GitHub repository, but uses "wot-use-cases-requirements" as the shortname for www.w3.org. So I've checked with the group and clarified we'd like to use "wot-usecases" as shortname for publication.

## Estimated publication date
6 May 2021

# Abstract
https://w3c.github.io/wot-usecases/index.html#abstract

# Status
https://w3c.github.io/wot-usecases/index.html#sotd

# Link to group's decision to request transition
https://www.w3.org/2021/04/14-wot-minutes.html#t10

# Information about implementations known to the Group (if relevant)
There are already several existing implementaitons for the version 1.0 WoT specs, e.g., WoT Architecture 1.0 and WoT Thing Description 1.0, as shown by the [Implementation report](https://w3c.github.io/wot-thing-description/testing/report.html) and the [Press Release](https://www.w3.org/2020/04/pressrelease-wot-rec.html).

We expect updates for those existing implementations and some more additional implementations for new features of the version 1.1 WoT specs, e.g., WoT Architecture 1.1 and WoT Thing Description 1.1, based on the newly defined Use Cases and Requirements in this Note.

**Comment by plehegar** [comment]
Approved

**Comment by ashimura** [comment]
Thanks!
and working on the publication.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2021/NOTE-wot-usecases-20210518/
