### ISSUE TITLE
CR Snapshot Update Request for Page Visibility Level 2  page-visibility-2

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/transitions#332]
# Document URLs

https://w3c.github.io/page-visibility/?specStatus=CR&crEnd=2021-06-18&previousMaturity=PR&previousPublishDate=2017-10-17

# Link to group's decision to request transition
https://github.com/w3c/page-visibility/issues/65

# Link to previous Candidate Recommendation transition or update request
https://github.com/w3c/transitions/issues/5

# Substantive changes

 * Rewrite to operate on browsing contexts 
 * Add external hooks to now {visible,hidden} algorithms 
 * Allow a user agent to return hidden when obscured
 * Removes prerender

# Any changes in requirements?
None

# Wide Review of substantive changes
None

# Issues status
https://github.com/w3c/page-visibility/issues

# Formal Objections
none

# Any changes in implementation information?
 * "prerender" was dropped from various engines

# Deadline for further comments
2021-06-18

# Any changes in patent disclosures?
None 

See [Requirements for updating a Candidate Recommendation Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot) for further information.

**Comment by swickr** [comment]
Transition approved.

A full horizontal review, particularly from Privacy, will be needed before exiting CR.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2021/CR-page-visibility-2-20210518/
