### ISSUE TITLE
FPNote for Cookbook formulae for audio equalizer biquad filter coefficients

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#335]
# Document title, URLs, estimated publication date

Cookbook formulae for audio equalizer biquad filter coefficients
https://webaudio.github.io/Audio-EQ-Cookbook/audio-eq-cookbook.html
Tues 18 May 2021

# Abstract

This note describes audio filter transfer functions. They were derived from analog prototypes, and have  been digitized using the Bilinear Transform (BLT). Adapted from Audio-EQ-Cookbook.txt, by Robert Bristow-Johnson, with permission.

# Status

(not converted to Note yet)

# Link to group's decision to request transition

As discussed on 10 May virtual f2f, and as requested on Web Audio PR transition call.

> [Resolved: publish cookbook as a Note](https://docs.google.com/document/d/1zUY0fOgtzGk5Hv0RFcC8gIgPyfW63b445Kp8TcPs1Rs/edit)

# Information about implementations known to the Group (if relevant)

Web Audio uses these formulae.

**Comment by svgeesus** [comment]
Plan is to switch the link in the Web Audio Proposed Rec, which goes to a github.io address, to this Note for Rec.

**Comment by plehegar** [comment]
I can't access the Google doc link for the decision. If that link contains minutes, can the Group make their minutes public?

**Comment by rtoy** [comment]
Sorry about that.  You can also find the minutes at https://lists.w3.org/Archives/Public/public-audio/2021AprJun/0020.html, just before we start talking about WebMIDI.

**Comment by plehegar** [comment]
Thank you @rtoy .

Approved for publication.

**Comment by svgeesus** [comment]
Publication requested 7 June, expected 8 June

**Comment by svgeesus** [comment]
[Published 8 June 2021](https://www.w3.org/TR/2021/NOTE-audio-eq-cookbook-20210608/)
