### ISSUE TITLE
FPWD Request for <Specification for Spoken Presentation in HTML>

### ISSUE THREAD

**Issue by ruoxiran** [w3c/transitions#336]
# Document title, URLs, estimated publication date
[
Document title: Specification for Spoken Presentation in HTML
URLs: [Snapshot prepared for publication](https://raw.githack.com/w3c/pronunciation/FPWD-technical-approach/snapshot/Overview.html)
short name: spoken-html
estimated publication date: 18 May 2021.
]

# Abstract
[[Abstract](https://raw.githack.com/w3c/pronunciation/FPWD-technical-approach/snapshot/Overview.html#abstract)]

# Status
[[Status](https://raw.githack.com/w3c/pronunciation/FPWD-technical-approach/snapshot/Overview.html#sotd)]

# Is it a delta specification intended to become a W3C Recommendation?
[yes]

# Link to group's decision to request transition
[[APA WG decision](https://lists.w3.org/Archives/Public/public-apa-admin/2021May/0027.html)]

# Information about implementations known to the Working Group
[Texthelp had some implementations for this technical approach, and TF is seeking more for this.]

**Comment by plehegar** [comment]
Approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2021/WD-spoken-html-20210518/
