### ISSUE TITLE
CR Request for User Timing  --  shortname: user-timing

### ISSUE THREAD

**Issue by caribouW3** [w3c/transitions#338]
# Document title, URLs, estimated publication date

Spec Title: User Timing
Note that it was previously "User Timing Level 3", the WG has decided to drop levels 
and use the process2020 model. That implies a reuse of the user-timing shortname.

https://w3c.github.io/user-timing//?specStatus=CR&crEnd=2021-06-18&previousMaturity=WD&previousPublishDate=2021-03-08&implementationReportURI=https://wpt.fyi/results/user-timing

# Abstract
This specification defines an interface to help web developers measure the performance of their applications by giving them access to high precision timestamps.

# Status
This specification of User Timing is intended to supersede [USER-TIMING-2] and includes:

Ability to execute marks and measures across arbitrary timestamps.
Support for reporting arbitrary metadata along with marks and measures.
This document was published by the Web Performance Working Group as a Candidate Recommendation Snapshot. This document is intended to become a W3C Recommendation.

GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-web-perf@w3.org (subscribe, archives) with [UserTiming] at the start of your email's subject.

Publication as a Candidate Recommendation does not imply endorsement by the W3C Membership. A Candidate Recommendation Snapshot has received wide review and is intended to gather implementation experience.

This Candidate Recommendation is not expected to advance to Proposed Recommendation any earlier than 18 June 2021.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 15 September 2020 W3C Process Document.

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-web-perf/2021May/0002.html

# Changes
Ability to execute marks and measures across arbitrary timestamps.
Support for reporting arbitrary metadata along with marks and measures.

# Wide Review
No new call for wide review since Level 2.
https://lists.w3.org/Archives/Public/public-review-announce/2016Nov/0004.html

# Issues addressed
https://github.com/w3c/user-timing/issues

# Formal Objections
None

# Implementation
https://wpt.fyi/results/user-timing?label=experimental&label=master&aligned

**Comment by swickr** [comment]
The Call for Wide Review of Level 2 was issued in 2016.  The [publication history](https://www.w3.org/standards/history/user-timing-3) shows the FPWD for this spec was published in 2019.  Given the time that has elapsed we should have little confidence that reviews done on Level 2 still apply.  Our confidence should be less due to changes in the Working Drafts over the intervening time, due to additional understandings in the horizontal review areas, due to side-effects of subsequent work in other area, and possibly other factors.

Therefore, a CR Transition for this specification is not approved until the Working Group re-requests another wide review and requests explicit confirmation of horizontal reviews.

**Comment by caribouW3** [comment]
Hi. The Wide review has been started a long time ago, apparently it's time to declare a timeout on the security feedback.

**Comment by plehegar** [comment]
Pinging the i18n folks to close the loop  on https://github.com/w3c/i18n-activity/issues/1392

**Comment by plehegar** [comment]
https://github.com/w3c/i18n-activity/issues/1392 is now closed

**Comment by swickr** [comment]
Transition approved.

We'll put more effort into finding security reviewers before exiting CR.
