### ISSUE TITLE
CR Request for Performance Timeline -- shortname: performance-timeline

### ISSUE THREAD

**Issue by caribouW3** [w3c/transitions#339]
# Document title, URLs, estimated publication date

Performance Timeline
Note that it was previously "Performance Timeline Level 2", the WG has decided to drop levels
and use the process2020 model. That implies a reuse of the performance-timeline shortname.

https://w3c.github.io/performance-timeline/?specStatus=CR&crEnd=2021-06-18&previousMaturity=WD&previousPublishDate=2019-10-24&publishDate=2021-05-17&implementationReportURI=https://wpt.fyi/results/performance-timeline

# Abstract
This specification extends the High Resolution Time specification [HR-TIME-2] by providing methods to store and retrieve high resolution performance metric data.

# Status
This specification of Performance Timeline is intended to replace the first version of [PERFORMANCE-TIMELINE] and includes:

Extends the base definition of the Performance interface defined by [HR-TIME-2];
Exposes PerformanceEntry in Web Workers [WORKERS];
Adds support for performance observers.
This document was published by the Web Performance Working Group as a Candidate Recommendation Snapshot. This document is intended to become a W3C Recommendation.

GitHub Issues are preferred for discussion of this specification.

Publication as a Candidate Recommendation does not imply endorsement by the W3C Membership. A Candidate Recommendation Snapshot has received wide review and is intended to gather implementation experience.

This Candidate Recommendation is not expected to advance to Proposed Recommendation any earlier than 18 June 2021.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 15 September 2020 W3C Process Document.

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-web-perf/2021May/0002.html

# Changes
Extends the base definition of the Performance interface defined by [HR-TIME-2];
Exposes PerformanceEntry in Web Workers [WORKERS];
Adds support for performance observers.

# Dependencies met (or not)
WG-internal dependencies

# Wide Review
https://lists.w3.org/Archives/Public/public-review-announce/2016Oct/0015.html
Previous publication as WD is labeled as wide review draft.

# Issues addressed
https://github.com/w3c/performance-timeline/issues

# Formal Objections
None

# Implementation
https://wpt.fyi/results/performance-timeline

**Comment by swickr** [comment]
The Call for Wide Review was issued in October 2016. The [publication history](https://www.w3.org/standards/history/performance-timeline-2) shows the spec having received substantive change since that time. Given that, we should have little confidence that reviews done several years ago still apply. Our confidence should be less due to changes in the Working Drafts over the intervening time, due to additional understandings in the horizontal review areas, due to side-effects of subsequent work in other area, and possibly other factors.

Therefore, a CR Transition for this specification is not approved until the Working Group re-requests another wide review and requests explicit confirmation of horizontal reviews.

**Comment by plehegar** [comment]
Checking on closing   https://github.com/w3c/i18n-request/issues/156

**Comment by plehegar** [comment]
https://github.com/w3c/i18n-request/issues/156 is now closed

**Comment by swickr** [comment]
Transition approved.

We'll put more effort into finding security reviewers before CR exit.
