### ISSUE TITLE
Request for update of Note Responsible Use of Spatial Data

### ISSUE THREAD

**Issue by lvdbrink** [w3c/transitions#341]
First - apologies. I'm co-chair of the SDWIG and we are without a W3C team contact at the moment, but want to publish a new version of a Note. Hopefully it can be done by posting an issue here. If not, please accept my apologies. 

# Document title, URLs, estimated publication date

The Responsible Use of Spatial Data

https://www.w3.org/TR/responsible-use-spatial/

Publication date: as soon as possible. If there is anything to fix in the document @jabhay can help.

# Abstract
This note highlights some of the unique characteristics of spatial data within the broader realm of ethical use of data. A brief analysis of the relationship between law and ethics explains that responsible use is not mandatory. Nevertheless, both legal and ethical frameworks play an important role in shaping what can be considered “responsible”. As do the perspectives of those who interact closely with spatial data: the developers, the users and the regulators. Therefore this note not only provides an insight into the relevant legislation and ethics guidelines, but also considers the principles of ethical data sharing from each of these three perspectives. The principles are made practical by providing concrete communication guidelines and showing examples of good practice.

# Status
Interest group Note

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-sdwig/2021May/0038.html

**Comment by plehegar** [comment]
@lvdbrink , I'll take4 care of the publication. Give the unusual style, I'll need to work with the webmaster so expect publication this Thursday.

**Comment by plehegar** [comment]
https://w3c.github.io/sdw/responsible-use/?specStatus=IG-NOTE&publishDate=2021-05-27 looks right for the publication?

**Comment by plehegar** [comment]
fyi @wseltzer

**Comment by lvdbrink** [comment]
> https://w3c.github.io/sdw/responsible-use/?specStatus=IG-NOTE&publishDate=2021-05-27 looks right for the publication?

Yes, thank you @plehegar !

**Comment by plehegar** [comment]
@lvdbrink one minor question: the website for OGC. Is it http://www.opengeospatial.org/ or https://www.ogc.org/ ? I'm guessing the latter and the source needs a tweak.

**Comment by plehegar** [comment]
fyi, unless something comes up, this document is good to go on Thursday.

**Comment by lvdbrink** [comment]
> @lvdbrink one minor question: the website for OGC. Is it http://www.opengeospatial.org/ or https://www.ogc.org/ ? I'm guessing the latter and the source needs a tweak.

The first URL is redirected to the second. You are right, the latter is best to use.

**Comment by plehegar** [comment]
@lvdbrink , bummer, something did come up...

@wseltzer , the charter of the IG has expired so the Group is not allowed to publish. Can we extend it?

**Comment by wseltzer** [comment]
It was extended, just not announced. @plehegar

**Comment by plehegar** [comment]
ok. The charter extension will be announced tomorrow as well, so we're back in business.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2021/NOTE-responsible-use-spatial-20210527/
