### ISSUE TITLE
REC Request for Web Audio 1.0

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#342]
# Link to internal transition

https://lists.w3.org/Archives/Team/w3t-comm/2021Jun/0034.html

# Link to previous transition

https://github.com/w3c/transitions/issues/328

**Comment by plehegar** [comment]
ACTION: @eplehegar to run the normative-references checker once it's back online

**Comment by swickr** [comment]
In [8. Security and Privacy Considerations](https://webaudio.github.io/web-audio-api/#priv-sec) there are two editorial fixes needed:

The High-Resolution Time §7 Privacy and Security link should be updated to the /TR version.

"Fingerprining" should be correctly spelled.

**Comment by svgeesus** [comment]
> In 8. Security and Privacy Considerations there are two editorial fixes needed:

Please don't look at the ED. The Rec will be generated from the Proposed Rec, as usual.

But yes, will update link and "Fingerprining" is there as well.

**Comment by plehegar** [comment]
https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FPR-webaudio-20210506%2F
worked

Nothing else to report.

**Comment by svgeesus** [comment]
Publication requested 7 June, expected 10 June

Requested corrections re links and spelling have been made

**Comment by svgeesus** [comment]
Publication requested 9 June, now expected 17 June

**Comment by jennyliang220** [comment]
Hi @swickr , just to make sure, is this publication approved for 17 June?

**Comment by plehegar** [comment]
https://www.w3.org/TR/2021/REC-webaudio-20210617/
