### ISSUE TITLE
FPWD Request for MiniApp Lifecycle

### ISSUE THREAD

**Issue by xfq** [w3c/transitions#344]
# Document title, URLs, estimated publication date
MiniApp Lifecycle
https://xfq.github.io/testing/miniapp-lifecycle-WD/Overview.html
proposed publication 15 June 2021

# Abstract
https://xfq.github.io/testing/miniapp-lifecycle-WD/Overview.html#abstract

# Status
https://xfq.github.io/testing/miniapp-lifecycle-WD/Overview.html#sotd

# Is it a delta specification intended to become a W3C Recommendation?
No.

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-miniapps-wg/2021May/0007.html

# Information about implementations known to the Working Group
Various MiniApp platforms support some lifecycle events and a process to manage the whole MiniApp and each page's lifecycle.

**Comment by plehegar** [comment]
Approved

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2021/WD-miniapp-lifecycle-20210615/
