### ISSUE TITLE
FPWD Request for Web Neural Network API

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/transitions#345]
# Document title, URLs, estimated publication date
Web Neural Network API
Publication date: June 22nd (or 24th depending on when approval comes in)
https://webmachinelearning.github.io/webnn/
proposed shortname: webnn

# Abstract
This document describes a dedicated low-level API for neural network inference hardware acceleration.

# Status
 This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

The Web Machine Learning Working Group maintains a list of all bug reports that the group has not yet addressed. Pull requests with proposed specification text for outstanding issues are strongly encouraged.

This document was published by the Web Machine Learning Working Group as a Working Draft. This document is intended to become a W3C Recommendation.

This document is a First Public Working Draft.

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 15 September 2020 W3C Process Document. 

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-webmachinelearning-wg/2021Jun/0010.html

# Information about implementations known to the Working Group
Experimental implementations in non-shipping Chromium, and polyfill available

cc @anssiko

**Comment by plehegar** [comment]
Approved

**Comment by dontcallmedom** [comment]
published at https://www.w3.org/TR/2021/WD-webnn-20210622/
