### ISSUE TITLE
CR Snapshot Update Request for Payment Request API

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/transitions#346]
We are returning to CR snapshot after removing features that were not marked at-risk. 

# Document URLs
https://w3c.github.io/payment-request/

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-payments-wg/2021Jun/0013.html

Note: In response to the same Call for Consensus, we recorded a decision to advance to PR
if there are no substantive changes during CR.

# Link to previous Candidate Recommendation transition or update request
https://github.com/w3c/transitions/issues/287

# Substantive changes
* Improvements based on privacy reviews
   * Removed API support for shipping address, billing address, and contact information.
   * Clarified specification role in facilitating communication between top-level contexts.

* Improvements based on Internationalization review:
  * Recommended that payment UI matches document language
  * Clarified use of currency codes and currency symbols

# Any changes in requirements?
None.

# Wide Review of substantive changes

* We resolved a previous issue raised by Sam Weiler by removing features from the specification:
   https://github.com/w3c/payment-request/issues/842#issuecomment-843187200

* We addressed a number of issues raised during I18N review to the satisfaction of the reviewer:
   https://github.com/w3c/payment-request/issues/952#issuecomment-827192916
   https://github.com/w3c/payment-request/issues/950
   https://github.com/w3c/payment-request/issues/949#issuecomment-823454515
   https://github.com/w3c/payment-request/issues/946#issuecomment-845243625

* We addressed a one I18N issue by removing features related to contact and shipping info:
   https://github.com/w3c/payment-request/issues/434   

* And after discussion with I18N folks, there was agreement to postpone some additional changes
   to after recommendation. Although we resolved this by phone and in a meeting, we still hope that
   @aphillips will sign off on GitHub:
   https://github.com/w3c/payment-request/issues/951#issuecomment-844667750
   https://github.com/w3c/payment-request/issues/948#issuecomment-844667820

For the full list of specification changes, see:
 https://github.com/w3c/payment-request/commits/gh-pages

# Issues status
There are no remaining open issues related to Payment Request API version 1.

# Formal Objections

We provided substantive replies to 2 formal objections raised in our previous CfC to advance to Proposed Recommendation. We did not satisfy the objectors. 

* FO from Anders Rundgren:
  https://lists.w3.org/Archives/Public/public-payments-wg/2021Jan/0008.html

  Adrian Hope-Bailie reply:
  https://lists.w3.org/Archives/Public/public-payments-wg/2021Jan/0009.html

* FO from Tom Jones:
  https://lists.w3.org/Archives/Public/public-payments-wg/2021Jan/0020.html

   Multiple replies:
   https://lists.w3.org/Archives/Public/public-payments-wg/2021Jan/0021.html
   https://lists.w3.org/Archives/Public/public-payments-wg/2021Jan/0022.html

# Any changes in implementation information?
* We have updated the test suite based on the removed features
* We have registered bugs in three code bases regarding the removed features
* We plan to have an updated implementation report when we request to advance to PR

# Deadline for further comments
2021-07-06

# Any changes in patent disclosures?

We organized a PAG to address a 2021-02-04 disclosure. The PAG recommended that the Web Payments Working Group continue to work on Payment Request API. See the report:
 https://www.w3.org/2021/01/wpwg-pag/report.html

See [Requirements for updating a Candidate Recommendation Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot) for further information.

**Comment by swickr** [comment]
Publication of CR Snapshot Update approved.

Please extend the deadline for comments to a minimum of 28 days after the date of publication per [Process section 6.2.8.1](https://www.w3.org/2020/Process-20200915/#publishing-crrs).

**Comment by plehegar** [comment]
https://www.w3.org/TR/2021/CRD-payment-request-20210629/
