### ISSUE TITLE
FPNote for EPUB Accessibility - EU Accessibility Act Mapping

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#347]
# Document title, URLs, estimated publication date

- title: EPUB Accessibility - EU Accessibility Act Mapping
- Editor's draft: https://w3c.github.io/epub-specs/epub33/epub-a11y-eaa-mapping/
- Requested short name: epub-a11y-eaa-mapping
- Estimated publication date: 2021-06-29
- Planned dated URI: https://www.w3.org/TR/2021/NOTE-epub-a11y-eaa-mapping-20210629/
- Planned undated URI: https://www.w3.org/TR/epub-a11y-eaa-mapping/

# Abstract

The European Accessibility Act (EAA) is an EU directive that establishes binding accessibility targets that must be met by many different types of products and services to strengthen the rights of people with disabilities to access goods and services, including ebooks, dedicated reading software, ereading devices, and ecommerce.

The EAA has been approved on 27 June 2019, should be implemented by EU Member States within 28 June 2022 and will enter in force from 28 June 2025.

This note aims to demonstrate that the technical requirements of the European Accessibility Act related to ebooks are met by the EPUB standard.

The methodology used is mapping the requirements of the EU Accessibility Act related to ebooks to the EPUB Accessibility specification.

# Status

https://w3c.github.io/epub-specs/epub33/epub-a11y-eaa-mapping/#sotd

# Link to group's decision to request transition

https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-06-18-epub#resolution2

# Information about implementations known to the Group (if relevant)

n/a

Cc: @dauwhe @gregoriopellegrino @wareid @shiestyle @mattgarrish

**Comment by plehegar** [comment]
cc @brewerj  @michael-n-cooper

**Comment by plehegar** [comment]
cc @avneeshsingh

**Comment by plehegar** [comment]
Approved

**Comment by iherman** [comment]
Publication done, closing.
