### ISSUE TITLE
FPWD Request for CSS Fonts 5

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#349]
# Document title, URLs, estimated publication date
CSS Fonts Module Level 5
https://drafts.csswg.org/css-fonts-5/
Tues 29 June

# Abstract
This specification defines modifications to the existing CSS Fonts 4 specification along with additional features.

# Status
https://drafts.csswg.org/css-fonts-5/#status (as ED)

# Is it a delta specification intended to become a W3C Recommendation?
yes, currently; no, eventually

# Link to group's decision to request transition
RESOLVED: css-fonts-5 to FPWD
https://www.w3.org/2021/06/23-css-irc#T16-13-09-58

# Information about implementations known to the Working Group
Initial implementation experiments in Blink and Gecko

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Publication requested 25 June, expected 29 June

**Comment by svgeesus** [comment]
Published [29 June](https://www.w3.org/TR/2021/WD-css-fonts-5-20210629/)
