### ISSUE TITLE
CR Request for ARIA in HTML

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#350]
# Document title, URLs, estimated publication date
ARIA in HTML
https://www.w3.org/TR/html-aria/
W3C Candidate Recommendation Snapshot 06 July 2021

# Abstract
This specification defines the authoring rules (author conformance requirements) for the use of Accessible Rich Internet Applications (WAI-ARIA) 1.1 and Digital Publishing WAI-ARIA Module 1.0 attributes on [HTML] elements. This specification's primary objective is to define requirements for use with conformance checking tools used by authors (i.e., web developers). These requirements will aid authors in their development of web content, including custom interfaces/widgets, that makes use of ARIA to complement or extend the features of the host language [HTML].

# Status
ARIA in HTML is an [HTML] specification module. Any HTML features, conformance requirements, or terms that this specification module makes reference to, but does not explicitly define, are defined in the HTML specification.

This document was published by the Web Applications Working Group as a Candidate Recommendation Snapshot. This document is intended to become a W3C Recommendation.

GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-webapps@w3.org (subscribe, archives).
Publication as a Candidate Recommendation does not imply endorsement by the W3C Membership. A Candidate Recommendation Snapshot has received wide review and is intended to gather implementation experience.

This Candidate Recommendation is not expected to advance to Proposed Recommendation any earlier than 28 June 2021.
This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.
This document is governed by the 15 September 2020 W3C Process Document.

# Link to group's decision to request transition
https://github.com/w3c/html-aria/issues/326
8 people supported.

# Changes
None.

# Requirements satisfied
None.

# Dependencies met (or not)
HTML Accessibility API Mappings 1.0 and SVG Accessibility API Mappings are in WD status, the group believe these features will become stable and widely implemented when ARIA in HTML moves to REC.

# Wide Review
The horizontal review result were tracked in [#273](https://github.com/w3c/html-aria/issues/273), and there are no outstanding issues

# Issues addressed
No open issues for 1.0. See issues with [the label To Do for 1.0](https://github.com/w3c/html-aria/labels/To%20Do%20for%201.0)

# Formal Objections
None.

# Implementation
The editors confirmed that the number of features at risk is now zero. An [implementation report](https://w3c.github.io/html-aria/results/implementation-results.html) is also available

# Patent disclosures
https://www.w3.org/groups/wg/webapps/ipr

**Comment by plehegar** [comment]
cc @brewerj @michael-n-cooper

**Comment by plehegar** [comment]
Additional information (correct if any are wrong):

* The Snapshot will be based on the [editor's draft](https://w3c.github.io/html-aria/). If so, here is the [proposed publication](https://w3c.github.io/html-aria/?specStatus=CR&implementationReportURI=https://w3c.github.io/html-aria/results/implementation-results.html&publishDate=2021-07-06&crEnd=2021-08-03&previousMaturity=WD&previousPublishDate=2021-06-28). modulo the mention of no feature at-risk in the SOTD.
* [Normative references](https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fw3c.github.io%2Fhtml-aria%2F) seem fine. (The checker incorrectly flag /TR/html-aam/ and /TR/html-aria/)
* The date of the CR review period is missing. It must be 28 days or longer. Given that we have no issues and we have implementation, any reason to put to use something than August 3? cc @scottaohara 
* Note that the work on the SVG Accessibility API Mapping is [stalled](https://github.com/w3c/strategy/issues/272) at the moment. Not a stopper for the transition however.
*  The [horizontal board](https://www.w3.org/PM/horizontal/review.html?shortname=html-aria) reports no `needs-resolution` horizontal issues.

**Comment by swickr** [comment]
Note that both the HTML and SVG Accessibility API Mappings are currently in Working Draft state.

In the case of the SVG AAM mapping, the reference is to a definition and the usage in ARIA in HTML looks stable independent of the specifics of that definition.

For the HTML AAM mapping, there is a stronger dependency but the WG seems to be actively working on this so it can manage the CR exit timeline.

**Comment by swickr** [comment]
Transition approved.

**Comment by siusin** [comment]
Published -> https://www.w3.org/TR/2021/CR-html-aria-20210706/
