### ISSUE TITLE
REC Request for WOFF2

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#351]
# Link to internal transition

https://lists.w3.org/Archives/Team/w3t-comm/2021Jun/0258.html

# Link to previous transition

[PR](https://github.com/w3c/transitions/issues/28)
[REC](https://lists.w3.org/Archives/Team/webreq/2018Feb/0050.html)

**Comment by plehegar** [comment]
The document only contains candidate changes and does not need Director's approval. See also
 https://www.w3.org/Guide/transitions?profile=REC&rec=candidate-corrections

**Comment by plehegar** [comment]
Candidate changes: see complete changes list
https://w3c.github.io/woff/woff2/#changes
   (No other changes)

**Comment by plehegar** [comment]
To be clear: No AC Review nor Call for Exclusions get triggered due to this publication. Once the candidate changes become proposed changes, follow
 https://www.w3.org/Guide/transitions?profile=REC&rec=substantive

**Comment by svgeesus** [comment]
Thanks @plehegar for confirming that no Director's approval is needed, and that the only changes here are Candidate Corrections.

**Comment by svgeesus** [comment]
[Published 6 July](https://www.w3.org/TR/2021/REC-WOFF2-20210706/)
