### ISSUE TITLE
FPWD Request for Internationalization Glossary

### ISSUE THREAD

**Issue by r12a** [w3c/transitions#352]
# Document title, URLs, estimated publication date
Internationalization Glossary
https://www.w3.org/TR/2021/WD-i18n-glossary-20210708/
pub date: 8 July

# Abstract
This document provides definitions for various terms related to W3C internationalization.

# Status
https://www.w3.org/TR/2021/WD-i18n-glossary-20210708/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://www.w3.org/2021/06/24-i18n-minutes.html#t08

# Information about implementations known to the Working Group
n/a

**Comment by plehegar** [comment]
I'd like to understand the relationship with https://infra.spec.whatwg.org/ .

For example, code point is defined in https://infra.spec.whatwg.org/ . And again it's defined in this new one. Was there any discussion with @domenic and @annevk ? It seems that this spec has the potential to create confusion in the community.

**Comment by aphillips** [comment]
The I18N Glossary is not the **source** of *any* terminology, at least at present. It is a compendium of terminology found elsewhere in the I18N Activity's docs plus selected external sources (which already includes Infra). The `Unicode code point` definition in i18n-glossary is from Charmod-Norm. The `code point` definition is from Charmod (Fundamentals) and is actually the generic definition of a code point in a character encoding scheme.

I agree that there can be conflicts, but my tendency would be let I18N make judgement calls here. Infra and others can sometimes make locally-relevant decisions about their definitions which may not be suitable in all cases as "the definition" of one or another thing. 

We certainly would welcome input from others (especially @annevk and @domenic) and we want to ensure that our glossary is harmonious with usage at W3C and WHATWG. One good potential outcome of this effort would be to provide quotable definitions for other specifications--along with pointers to the original (source) definitions. This is a FPWD to give ourselves a place to work on the style, structure, and processes involved.

**Comment by r12a** [comment]
@aphillips explains this perfectly.  

Note that this is only the first draft and we expect going forward to add links to other places where things are defined, such as infra or Unicode Standard, and, where needed, explanations about why definitions differ in different places (if they do).  For example, the infra spec has a slightly narrower definition of `code point` than we have because it is specific to Unicode characters and the terminology needs of the HTML spec.  Our definition points to the fact that in the industry the term doesn't have to be Unicode-specific – non-Unicode code pages also have code points.

We also need to check the consistency of definitions across our own publications, and gathering the terms here is a good way to start working on that, not least because it enables us to actually remember when we have defined something by centralising the location of those definitions.  That helps to reduce inconsistencies and confusion.

**Comment by plehegar** [comment]
Thank you @aphillips @r12a .

Approved for publication. I'm looking forward to see refinements in the document about the relationship in future publications.

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2021/WD-i18n-glossary-20210708/
