### ISSUE TITLE
FPWD Request for VISS version 2 Core and VISS version 2 Transport

### ISSUE THREAD

**Issue by caribouW3** [w3c/transitions#354]
# Document title, URLs, estimated publication date
VISS version 2 - Core
VISS version 2 - Transport
21 July 2021
https://w3c.github.io/automotive/spec/VISSv2_Core.html?specStatus=FPWD&publishDate=2021-07-21
https://w3c.github.io/automotive/spec/VISSv2_Transport.html?specStatus=FPWD&publishDate=2021-07-21

# Abstract
https://w3c.github.io/automotive/spec/VISSv2_Core.html?specStatus=FPWD&publishDate=2021-07-21#abstract
https://w3c.github.io/automotive/spec/VISSv2_Transport.html?specStatus=FPWD&publishDate=2021-07-21#abstract

# Status
https://w3c.github.io/automotive/spec/VISSv2_Core.html?specStatus=FPWD&publishDate=2021-07-21#sotd
https://w3c.github.io/automotive/spec/VISSv2_Transport.html?specStatus=FPWD&publishDate=2021-07-21#sotd

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
CfC https://lists.w3.org/Archives/Public/public-automotive/2021Jun/0014.html

# Information about implementations known to the Working Group
[TODO: add any preliminary information that you might have]
none for V2.

**Comment by plehegar** [comment]
Any reason not to use VISS2 or VISS-2, instead of VISSv2 in the shortname? Otherwise, "v2" introduces a new convention that have never been used in our links, if I'm not mistaken.

Before moving to CR, please add:
- a description on how it relates to https://www.w3.org/TR/vehicle-information-service/
- a security and privacy consideration section.

**Comment by caribouW3** [comment]
Hi,
We might actually use vehicle-information-service-2 to match the 1st version shortname. I'll check with the editors and chair.

**Comment by caribouW3** [comment]
BTW, Security & Privacy are already in section 6 of the Core document:
https://w3c.github.io/automotive/spec/VISSv2_Core.html?specStatus=FPWD&publishDate=2021-07-21#security

**Comment by caribouW3** [comment]
The shortnames will be viss2-core and viss2-transport  (otherwise it's not really a short name)

**Comment by plehegar** [comment]
Approved
