### ISSUE TITLE
FPWD Request for MathML Core

### ISSUE THREAD

**Issue by bert-github** [w3c/transitions#355]
# Document title, URLs, estimated publication date
Title: MathML Core
Editors' draft: https://w3c.github.io/mathml-core/
Proposed URL: https://www.w3.org/TR/mathml-core/
Estimated publication date: end of July

# Abstract
This specification defines a core subset of Mathematical Markup Language, or MathML, that is suitable for browser implementation. MathML is a markup language for describing mathematical notation and capturing both its structure and content. The goal of MathML is to enable mathematics to be served, received, and processed on the World Wide Web, just as HTML has enabled this functionality for text.

# Status
https://w3c.github.io/mathml-core/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://www.w3.org/mid/CAESRWkBQqMQGM4xJoHFq8JeSVQo13fS7wJgj0sVGxkLAybh88Q@mail.gmail.com
where it says: ‘NS [=Neil Soiffer]: we have agreed to publish the first fpwd. People have until June 23 to submit changes to the fpwd. Please send corrections to DC.’

# Information about implementations known to the Working Group
The spec is inspired by the existing implementations of MathML3, but there is no information yet about implementations of this spec.

**Comment by plehegar** [comment]
Approved

**Comment by bert-github** [comment]
Published: https://www.w3.org/TR/2021/WD-mathml-core-20210810/
