### ISSUE TITLE
FPNote for EPUB 3 Text-to-Speech Enhancements 1.0

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#356]
# Document title, URLs, estimated publication date

- title: EPUB 3 Text-to-Speech Enhancements 1.0
- Editor's draft: https://w3c.github.io/epub-specs/epub33/tts/
- Requested short name: epub-tts-10
- Estimated publication date: 2021-08-03
- Planned dated URI: https://www.w3.org/TR/2021/NOTE-epub-tts-10-20210803/
- Planned undated URI: https://www.w3.org/TR/epub-tts-10/

# Abstract

This document describes authoring features and reading system support for improving the voicing of EPUB 3 publications.

# Status

https://www.w3.org/TR/2021/NOTE-epub-tts-10-20210803/#sotd

# Link to group's decision to request transition

https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-07-08-epub#resolution3

# Information about implementations known to the Group (if relevant)

Only a few and incomplete at the moment.

@dauwhe @mattgarrish @wareid @shiestyle

**Comment by plehegar** [comment]
Approved

**Comment by iherman** [comment]
Sent:

- official publication request
- draft HPN

**Comment by iherman** [comment]
Document has been published; closing.
