### ISSUE TITLE
PR Request for DOM Review Draft — Published 15 June 2020 -- shortname: DOM

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#357]
# Document title, URLs, estimated publication date
DOM Review Draft — Published 15 June 2020
https://www.w3.org/TR/2021/PR-DOM-20210803/

# Abstract
DOM defines a platform-neutral model for events, aborting activities, and node trees.

# Status
This Living Standard is also endorsed as a W3C Candidate Recommendation under the terms of the Memorandum of Understanding. For those purposes, it contains the following metadata:

Canonical version / latest Living Standard:
https://dom.spec.whatwg.org/
This version:
https://dom.spec.whatwg.org/review-drafts/2020-06/
W3C Version Mnemonic:
DOM 2020-06

Status of This Document
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

The W3C HTML Working Group co-produced this document under the W3C Patent Policy and the 15 September 2020 W3C Process Document. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

# Link to group's decision to request transition
https://github.com/w3c/htmlwg/issues/18

# Changes
None.

# Requirements satisfied
None.

# Dependencies met (or not)
None.

# Wide Review
w3c/htmlwg#14
No substantive issues.

# Issues addressed
There are still open issues for DOM, but the editors believe this review draft is good enough to move to PR.

# Formal Objections
None.

# Implementation
No at-risk features for this version.

# Patent disclosures
https://www.w3.org/groups/wg/htmlwg/ipr

**Comment by siusin** [comment]
@sideshowbarker @plehegar 
Any advice on the superseded DOM specs?

**Comment by sideshowbarker** [comment]
From the list at https://www.w3.org/TR/?title=dom I believe the only spec we can supersede is the Document Object Model (DOM) Level 3 Core Specification at https://www.w3.org/TR/2004/REC-DOM-Level-3-Core-20040407/

**Comment by sideshowbarker** [comment]
Well, https://www.w3.org/TR/dom40/ also — though it’s not listed on https://www.w3.org/TR/?title=dom (why not?…)

**Comment by swickr** [comment]
I believe the W3C Candidate Recommendation is from the [2020-06 DOM Review Draft](https://dom.spec.whatwg.org/review-drafts/2020-06/) via https://www.w3.org/TR/2021/CR-dom-20210608/

**Comment by plehegar** [comment]
https://www.w3.org/TR/2015/REC-dom-20151119/ is outdated. /TR/dom40 needs to redirect to /TR/dom/ .

**Comment by plehegar** [comment]
Implementation report is at https://wpt.fyi/results/dom?label=experimental&label=master&aligned

**Comment by plehegar** [comment]
WPT snapshot is https://www.w3.org/2021/04/wpt-fyi-snapshot.html?filter=dom&date=2021-08-01

**Comment by swickr** [comment]
Transition approved.  DOM 3 Core to be retired and the DOM4 shortname link to be fixed so the script shows it as (already) retired.

**Comment by siusin** [comment]
... also action to @sideshowbarker to modify https://dom.spec.whatwg.org/review-drafts/2020-06/ from CR to PR.

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2021/PR-DOM-20210805/
