### ISSUE TITLE
PR Request for Decentralized Identifiers (DIDs) v1.0

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#358]
# PR Transition Request DID WG

# Document title, URLs, estimated publication date
- Title: Decentralized Identifiers (DIDs) v1.0
- Document on TR: https://www.w3.org/TR/2021/PR-did-core-20210803/
- Editor's draft: https://w3c.github.io/did-core/
- Static version of the editors' draft: https://w3c.github.io/did-core/PR/2021-08-03/
- Expected publication date: 2021-08-03

# Abstract
See: https://w3c.github.io/did-core/PR/2021-08-03/#abstract

# Status
See: https://w3c.github.io/did-core/PR/2021-08-03/#sotd

# Link to group's decision to request transition
See: https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-07-20-did#resolution1

# Changes
The document has changed minimally since the most recent Candidate Recommendation Snapshot. All changes were editorial.

For a detailed list of changes, see:  
https://w3c.github.io/did-core/PR/2021-08-03/#revision-history

# Requirements satisfied
The working group believes we have enabled the core use cases described in this document:  
https://www.w3.org/TR/did-use-cases/

The chairs also believe that this document is one of the best of its kind and should be offered as an example to other groups.

# Dependencies met (or not)
N/A

# Wide Review
Requests for review were sent out to the relevant communities in the space, including

- W3C Credentials Community Group (CCG)
- Decentralized Identity Foundation (DIF)
- Hyperledger Indy and Aries

Additionally, required horizontal reviews were provided by:

- PING:  https://github.com/w3c/did-core/issues/291#issuecomment-785439265
- Security: https://github.com/w3c/did-core/issues/291#issuecomment-786722078
- WAI: Horizontal Review: https://github.com/w3c/did-core/issues/105#issuecomment-655616261
- I18N: Horizontal Review: https://github.com/w3c/did-core/issues/104#issuecomment-649187234
- TAG: Horizontal Review: https://github.com/w3c/did-core/issues/119#issuecomment-763945275

All reviews, comments, etc., from all sources, were tracked as Github issues; see below.

# Issues addressed
The following is the status at the time of submission of this transition request.

The GitHub repository for issues is at: https://github.com/w3c/did-core/issues  
All issues blocking PR entry, regardless of source, have been addressed.

A disposition of all Candidate Recommendation comments can be found here:  
https://lists.w3.org/Archives/Public/public-did-wg/2021Jul/att-0025/01-part

See also a summary in:  
https://lists.w3.org/Archives/Public/public-did-wg/2021Jul/0025.html

The following categories of issues remain open:

- Issues that are deferred to a future version of the specification:  
https://github.com/w3c/did-core/issues?q=is%3Aissue+is%3Aopen+label%3Adefer-v2
- Other issues that came in after the WG froze the document for PR vote: None
  
# Formal Objections
None

# Implementation
From the SOTD: "At the time of publication, there existed [103 experimental DID Method specifications](https://w3c.github.io/did-spec-registries/#did-methods), 32 experimental DID Method driver implementations, a [test suite](https://w3c.github.io/did-test-suite/) that determines whether or not a given implementation is conformant with this specification and 46 implementations submitted to the conformance test suite. At the time of publication, no additional substantive issues, changes, or modifications are expected."

Implementation Report: https://w3c.github.io/did-test-suite/#implementation-report

Test Suite Repository: https://github.com/w3c/did-test-suite

# Patent disclosures
None

---

Cc: @msporny @burnburn @brentzundel

**Comment by plehegar** [comment]
[HTML diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FCR-did-core-20210615%2F&doc2=https%3A%2F%2Fw3c.github.io%2Fdid-core%2FPR%2F2021-08-03%2F)

**Comment by plehegar** [comment]
[Normative references](https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fw3c.github.io%2Fdid-core%2FPR%2F2021-08-03%2F)

**Comment by msporny** [comment]
@plehegar -- standing by if you need anything.

**Comment by plehegar** [comment]
[[
Decentralized Identifiers (DIDs) v1.0
Call for exclusion started on 2021-06-15, opportunity until 2021-08-14
]]
https://www.w3.org/groups/wg/did/ipr

We'll need to check again the IPR status before to REC.

**Comment by plehegar** [comment]
@msporny 
The sentence
"<p>Future updates to this specification may incorporate <a href="https://www.w3.org/2020/Process-20200915/#allow-new-features">new features<a>.</p>"

does NOT appear in the SOTD of the Proposed Recommendation. Is that intentional?

Without it, the WG won't be allowed to revise the REC with new features (will have to publish a new FPWD instead).

**Comment by plehegar** [comment]
For the implementation report, please use the 'base' profile instead of 'ed': https://w3c.github.io/did-test-suite/?specStatus=base

**Comment by swickr** [comment]
Transition approved.

Please update the first citation in DID-SPEC-REGISTRIES to use the /TR URI.
Please make a snapshot of the implementation report in its current state (in GitHub is fine).

If you want to allow new features, add that sentence to the SoTD.

Reminder to self: re-check the IPR status before the next Transition.

**Comment by msporny** [comment]
> @msporny
> The sentence
> "
> 
> Future updates to this specification may incorporate [new features](https://www.w3.org/2020/Process-20200915/#allow-new-features).
> 
> "
> does NOT appear in the SOTD of the Proposed Recommendation. Is that intentional?
> Without it, the WG won't be allowed to revise the REC with new features (will have to publish a new FPWD instead).

Yes, that is intentional.

Unfortunately the WG decided that they did not want to support the "allow new features" option. :(

https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-07-20-did#section3

**Comment by msporny** [comment]
> For the implementation report, please use the 'base' profile instead of 'ed': https://w3c.github.io/did-test-suite/?specStatus=base

Done in https://github.com/w3c/did-spec-registries/commit/63d3966141b01f5eadf4f67d9bd52c8d90f94e00.

> Please make a snapshot of the implementation report in its current state (in GitHub is fine).

Done in https://github.com/w3c/did-test-suite/commit/abf8d0f308259ebc2e7f2b1e8dd67dfdfefb5631

**Comment by msporny** [comment]
> Please update the first citation in DID-SPEC-REGISTRIES to use the /TR URI.

Fixed in https://github.com/w3c/did-core/commit/c407bfcdfa0600917c554f424cdd210dbc0b381b

@iherman I updated the static copy of the Proposed Rec to reflect the changes that @swickr requested here:

https://github.com/w3c/did-core/commit/c672e55d09abc3669f517bf612a37dc47649e06e

I believe that addresses all of the concerns raised during the transition request.

**Comment by brentzundel** [comment]
Thank you Manu

**Comment by iherman** [comment]
> @iherman please remember to move the newest Proposed Rec document located here to TR space:
> 
> https://github.com/w3c/did-core/blob/main/PR/2021-08-03/index.html

Done.

**Comment by iherman** [comment]
Sent:

- official publication request
- draft AC announcement text
- draft HPN news

**Comment by iherman** [comment]
Document has been [published](https://www.w3.org/TR/2021/PR-did-core-20210803/), [AC notified](https://lists.w3.org/Archives/Member/w3c-ac-members/2021JulSep/0018.html), [PR Vote](https://www.w3.org/2002/09/wbs/33280/did-core-pr/) started.

Closing.
