### ISSUE TITLE
FPWD Request for CSS Nesting 1

### ISSUE THREAD

**Issue by argyleink** [w3c/transitions#359]
# Document title, URLs, estimated publication date
CSS Nesting Module
https://drafts.csswg.org/css-nesting-1/
Date Aug 27 2021

# Abstract
This module introduces the ability to nest one style rule inside another, with the selector of the child rule relative to the selector of the parent rule. This increases the modularity and maintainability of CSS stylesheets.

CSS is a language for describing the rendering of structured documents (such as HTML and XML) on screen, on paper, etc.

# Status
This is a public copy of the editors’ draft. It is provided for discussion only and may change at any moment. Its publication here does not imply endorsement of its contents by W3C. Don’t cite this document other than as work in progress.

Please send feedback by filing issues in GitHub (preferred), including the spec code “css-nesting” in the title, like this: “[css-nesting] …summary of comment…”. All issues and comments are archived. Alternately, feedback can be sent to the (archived) public mailing list www-style@w3.org.

This document is governed by the 15 September 2020 W3C Process Document.

# Is it a delta specification intended to become a W3C Recommendation?
no?

# Link to group's decision to request transition
[https://www.w3.org/2021/07/27-css-minutes.html#t13](https://www.w3.org/2021/07/27-css-minutes.html#t13)

# Information about implementations known to the Working Group
_n/a_

cc @tabatkins

**Comment by argyleink** [comment]
FWPD request was made last week to the CSSWG and this request is intended to place hold and show intent as we make any last minute changes after hearing feedback. Changes like https://github.com/w3c/csswg-drafts/pull/6483 which we'd like to present to the CSSWG before specifying a publish date. Hope that's ok! 🙂

**Comment by plehegar** [comment]
Approved for publication. Looks like a very useful syntax improvement.

**Comment by plehegar** [comment]
CSS WG decision record: https://www.w3.org/2021/07/27-css-minutes.html#t13

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2021/WD-css-nesting-1-20210831/
