### ISSUE TITLE
Update document "How to Organize a TR"

### ISSUE THREAD

**Issue by jennyliang220** [w3c/transitions#360]
1. value="editorial" only apply to Recommendations [now](https://github.com/w3c/transitions/blob/fb240b2d40c56f636f4a1aa702bad5d87fa11a28/index.html#L294). Remove CR+editorial documents like: `<li data-profile="CR" data-cr="editorial">`
2. Add webreq@w3.org publication request template. Including a checklist for team contacts.

**Comment by plehegar** [comment]
I don't see an option to do CR+editorial in our [transition document](https://www.w3.org/Guide/transitions?profile=CR). The line pointed to is about REC+editorial.
The publication template should try to get some of the information automatically, ie if you just request a WD publication, there is no need to ask for a Comm announcement.

**Comment by jennyliang220** [comment]
> I don't see an option to do CR+editorial in our transition document.

Hi @plehegar , In the source code, there is: 
https://github.com/w3c/transitions/blob/fb240b2d40c56f636f4a1aa702bad5d87fa11a28/index.html#L1321-L1322

So I delete this link in the PR [#361 here](https://github.com/w3c/transitions/pull/361/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L1321).

---

> if you just request a WD publication, there is no need to ask for a Comm announcement. 

You're right, I'll give Comm announcement when needed.

**Comment by xueyuanjia** [comment]
> > if you just request a WD publication, there is no need to ask for a Comm announcement.

As a reminder @jennyliang220: regular revised WD does not require a Comm announcement, WD (returned from CR/PR) needs Comm announcement as described in [Guidebook transition](https://www.w3.org/Guide/transitions?profile=WD&returning=true).
> 
> You're right, I'll give Comm announcement when needed.

Any change to the current practice? E.g., Comm pings Team Contacts for announcements.

**Comment by jennyliang220** [comment]
> Any change to the current practice? E.g., Comm pings Team Contacts for announcements.

@xueyuanjia, announcements' link/mockup are encouraged to be sent with the publication request (optional in the information). So if you see them in the request, there's no need to ping.  It could reduce the comm's work.

**Comment by xueyuanjia** [comment]
Hi @jennyliang220, does it mean the [publicaion request] sent to webreq will include an item of "announcement", where I can check whether the Team Contact did/will send a draft announcement to w3t-comm? E.g., these two requets [[1](https://lists.w3.org/Archives/Team/webreq/2021Dec/0015.html)] & [[2](https://lists.w3.org/Archives/Team/webreq/2021Dec/0008.html)] didn't include any info about announcement, while [1] sent a draft to Comm separately and [2] didn't. I am wondering... how to find out in [publication request] if the Team Contact will/when to send a draft...

**Comment by jennyliang220** [comment]
@xueyuanjia , you'll still find the request in the email to comm. The webreq comm information is not mandatory, it's just a reminder for team contacts to draft announcements. You can use it when it's there, but please don't totally relay on this.

So almost nothing has changed.
