### ISSUE TITLE
FPWD Request for Propagation format for distributed trace context: Baggage

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#364]
# Document title, URLs, estimated publication date

Propagation format for distributed trace context: Baggage
W3C First Public Working Draft 17 August 2021
https://w3c.github.io/baggage/?specStatus=FPWD&publishDate=2021-08-17

# Abstract

This specification defines a standard for representing and propagating a set of user-defined properties associated with a distributed request.

# Status

This is the First Public Working Draft (FPWD). There are a few implementations of this protocol available. Experimental interoperability scenarios were run and have demonstrated promising results. The specification will be progressed into Candidate Recommendation stage after that, drafts for binary, AMQP and MQTT protocols will be written to make sure the concepts and structure defined in this specification can be ported to other protocols.

This document was published by the Distributed Tracing Working Group as a First Public Working Draft. This document is intended to become a W3C Recommendation.

GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-trace-context@w3.org (subscribe, archives) with baggage at the start of your email's subject.
Publication as a First Public Working Draft does not imply endorsement by the W3C Membership.
This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.
This document was produced by a group operating under the 1 August 2017 W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.
This document is governed by the 15 September 2020 W3C Process Document.

# Is it a delta specification intended to become a W3C Recommendation?

no

# Link to group's decision to request transition

https://github.com/w3c/baggage/issues/75

and
[[
Sergey: create an issue to make FPWD
]]
https://docs.google.com/document/d/12AAIbnkt_AH1YjZwUwxirX_7WA7aWOSXpDweCgfqIiQ/edit#heading=h.qkgn3vl7kqbc

# Information about implementations known to the Working Group

from https://github.com/w3c/baggage/#known-implementations

OpenTelemetry provides an implementation of the baggage specification. You can find details at OpenTelemetry API. OpenTelemetry SDK ships a BaggagePropagator and enables it by default. For example, the .NET version of it is here and it is documented here.

Another system that supports the baggage concept is .NET. It supports it as part of the System.Diagnostics.Activity class and it is documented here. However, it is not a strict reference implementation: for example, it doesn't enforce the same character set or limits.

cc @SergeyKanzhelev @kalyanaj

**Comment by plehegar** [comment]
as a side note, there is an ongoing TAG review: https://github.com/w3ctag/design-reviews/issues/650

**Comment by swickr** [comment]
Transition approved.  (FPWD)

**Comment by plehegar** [comment]
published
