### ISSUE TITLE
FPWD Request for VirtualKeyboard API

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#368]
# Document title, URLs, estimated publication date
VirtualKeyboard API
https://w3c.github.io/editing/docs/virtualkeyboard/
https://www.w3.org/TR/virtualKeyboard/
24 August 2021

# Abstract
The VirtualKeyboard API provides authors with greater control over the visibility of the virtual keyboard (VK), and greater ability to adapt the layout of web pages when VK visibility changes.

# Status
This document was published by the Web Editing Working Group as a First Public Working Draft. This document is intended to become a W3C Recommendation.

GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-editing-tf@w3.org (subscribe, archives).
Publication as a First Public Working Draft does not imply endorsement by the W3C Membership.
This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.
This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.
This document is governed by the 15 September 2020 W3C Process Document.

# Is it a delta specification intended to become a W3C Recommendation?
no.

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-editing-tf/2021Aug/0002.html

# Information about implementations known to the Working Group
- [x] [Chromium](https://groups.google.com/a/chromium.org/g/blink-dev/c/EF9fJTfqoGI/m/a8CbytZrAwAJ)
- [ ] [Gecko](https://github.com/mozilla/standards-positions/issues/531)
- [ ] [WebKit](https://lists.webkit.org/pipermail/webkit-dev/2021-June/thread.html#31878)

**Comment by plehegar** [comment]
may I propose to use https://www.w3.org/TR/virtual-keyboard/ instead? We don't really capitalize words in /TR shortnames.

**Comment by siusin** [comment]
https://www.w3.org/TR/2021/WD-virtual-keyboard-20210824/

@plehegar could you confirm the change and approve this trans-request?

**Comment by plehegar** [comment]
Thank you for making the change.

Approved.

**Comment by siusin** [comment]
Published on 24 Aug.
