### ISSUE TITLE
FPWD Request for Secure Payment Confirmation

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/transitions#372]
# Document title, URLs, estimated publication date
https://w3c.github.io/secure-payment-confirmation/

Estimated publication: 31 August

Note: The only real difference between the editor's draft (link above) and the FPWD will be in the status section, and that text is going to be 100% boilerplate. Let me know if you'd like to see a mockup of the actual FPWD.

# Abstract
https://w3c.github.io/secure-payment-confirmation/#abstract

# Status
https://w3c.github.io/secure-payment-confirmation/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
No.

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-payments-wg/2021Aug/0033.html

# Information about implementations known to the Working Group
For Chrome, see:
  https://www.chromestatus.com/features/5702310124584960
  https://github.com/w3c/secure-payment-confirmation/blob/main/developer-guide.md

We also have these signals of industry interest:

 * Summary of Stripe experiment with SPC (Dec 2020-Jan 2021):
    http://www.w3.org/2021/Talks/spc-pilot-202103.pdf
 * Two more experiments are underway or about to start (Adyen + Airbnb; Stripe)
 * EMVCo has indicated publicly that they anticipate including support for SPC in EMV® 3-D Secure in Q3 or Q4 of this year.

# More stuff!

* TAG review requested: https://github.com/w3ctag/design-reviews/issues/544
* Explainer: https://github.com/w3c/secure-payment-confirmation/blob/main/explainer.md
* Use cases: https://github.com/w3c/secure-payment-confirmation/blob/main/scope.md
* Requirements: https://github.com/w3c/secure-payment-confirmation/blob/main/requirements.md

**Comment by deniak** [comment]
Discussing this with @ianbjacobs on IRC, I understand the transition is indeed approved.
/cc @jennyliang220

**Comment by ianbjacobs** [comment]
@swickr indicated I should proceed. Thanks!

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2021/WD-secure-payment-confirmation-20210831/
