### ISSUE TITLE
FPWD Request for Incremental Font Transfer

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#374]
# Document title, URLs, estimated publication date
Incremental Font Transfer
https://w3c.github.io/IFT/Overview.html
Tuesday 7 Sept 2021
Shortname: IFT

# Abstract
This specification defines two methods to incrementally transfer fonts from server to client. Incremental transfer allows clients to load only the portions of the font they actually need which speeds up font loads and reduces data transfer needed to load the fonts. A font can be loaded over multiple requests where each request incrementally adds additional data.

# Status
https://w3c.github.io/IFT/Overview.html#sotd (as ED)

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
[Resolution: Publish FPWD of Incremental Font Transfer](https://www.w3.org/2021/08/31-webfonts-minutes.html) Minutes, 31 Aug 2021

# Information about implementations known to the Working Group
A [preliminary client and server implementation](https://github.com/w3c/patch-subset-incxfer) of the patch subset method is being developed, and will be used to test and refine the specification.

**Comment by svgeesus** [comment]
Ah, I see @plehegar is on vacation all week so approval this week is unlikely.
Re-targetting for Tues 7 Sept.

**Comment by svgeesus** [comment]
Publication requested 01 Sept, expected 07 Sept

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
[published 7 Sept](https://www.w3.org/TR/2021/WD-IFT-20210907/)
