### ISSUE TITLE
[immersive-web] FPWD Request for WebXR lighting estimation

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#375]
# Document title, URLs, estimated publication date
WebXR Lighting Estimation API Level 1
https://immersive-web.github.io/lighting-estimation/
7 Sep 2021 (for approval on 3 Sep)

# Abstract
https://immersive-web.github.io/lighting-estimation/#abstract
This specification describes support for exposing estimates of environmental lighting conditions to WebXR sessions.

# Status
https://immersive-web.github.io/lighting-estimation/#status
(will be updated to align with WG ED, https://github.com/immersive-web/lighting-estimation/pull/51)

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
cfc: https://lists.w3.org/Archives/Public/public-immersive-web-wg/2021Aug/0004.html
resolution: https://lists.w3.org/Archives/Public/public-immersive-web-wg/2021Aug/0029.html

# Information about implementations known to the Working Group
none yet

**Comment by plehegar** [comment]
Approved

**Comment by himorin** [comment]
published: https://www.w3.org/TR/2021/WD-webxr-lighting-estimation-1-20210909/
