### ISSUE TITLE
FPWD Request for WebRTC Encoded Transform

### ISSUE THREAD

**Issue by caribouW3** [w3c/transitions#376]
# Document title, URLs, estimated publication date
WebRTC Encoded Transform
Ed draft:
https://w3c.github.io/webrtc-encoded-transform/
Shortname expected to be webrtc-encoded-transform
Publication date as soon as approved.

# Abstract
https://w3c.github.io/webrtc-encoded-transform/#abstract

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

This is the First Public Working Draft of the WebRTC Encoded Transform. Publication as a First Public Working Draft does not imply endorsement by the W3C Membership.
This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress. 

If you wish to make comments regarding this document, please send them to public-webrtc@w3.org (subscribe, archives). When sending e-mail, please put the text “webrtc-encoded-transform” in the subject, preferably like this: “[webrtc-encoded-transform] …summary of comment…”. All comments are welcome.

This document was produced by the Web Real-Time Communications Working Group. This document is intended to become a W3C Recommendation. 

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 15 September 2020 W3C Process Document.

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
CfC conlusion:
https://lists.w3.org/Archives/Public/public-webrtc/2021Sep/0000.html

# Information about implementations known to the Working Group
Experiments already exist.

**Comment by plehegar** [comment]
Approved

**Comment by caribouW3** [comment]
Published on Sept. 21
