### ISSUE TITLE
PR Request for Payment Request and Payment Method Identifiers

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/transitions#377]
# Document title, URLs, estimated publication date

Payment Request API
https://w3c.github.io/payment-request/

Payment Method Identifiers
https://w3c.github.io/payment-method-id/

Estimated publication date: 21 September 2021

# Abstract
https://w3c.github.io/payment-request/#abstract
https://w3c.github.io/payment-method-id/#abstract

# Status
https://w3c.github.io/payment-request/#sotd
https://w3c.github.io/payment-method-id/#sotd

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-payments-wg/2021Jun/0013.html

Note: The decision does not mention Payment Method Identifiers by name, which is a bug. The group's
expectation for years has been to advance these documents together; see, for example:
https://lists.w3.org/Archives/Public/public-payments-wg/2017Jul/0020.html

Because PMI has not changed in a long time (other than to remove "basic card" as a standardized
payment method identifier), the staff contact neglected to mention it in the call for consensus to
advance to PR. 

# Changes
https://w3c.github.io/payment-request/#changelog
https://github.com/w3c/payment-method-id/commits/

# Requirements satisfied
The specification has been published for multiple years and has converged 
around an interoperable set of features.

# Dependencies met (or not)
Yes.

# Wide Review

PR API has been reviewed over many years, with most recent changes being to remove features.

There was I18N review during this CR period:
https://github.com/w3c/payment-request/issues?q=is%3Aissue+is%3Aclosed+label%3Ai18n-needs-resolution+

There was also privacy review, leading to removal of features related to addresses.
https://github.com/w3c/payment-request/issues/842#issuecomment-843187200

# Issues addressed
https://github.com/w3c/payment-request/issues?q=is%3Aissue+is%3Aclosed
https://github.com/w3c/payment-method-id/issues?q=is%3Aissue+is%3Aclosed

# Formal Objections

No new Formal Objections since the previous transition.

# Implementation

Payment Request API is implemented in Chrome and Webkit.
https://caniuse.com/payment-request

Payment request implementation report:
https://w3c.github.io/test-results/payment-request/all.html

Payment method identifiers implementation report:
https://w3c.github.io/test-results/payment-method-id/all.html

# Patent disclosures
https://www.w3.org/groups/wg/payments/ipr

**Comment by ianbjacobs** [comment]
Update: I wrote to the WG about my omission of PMI and asked for feedback by 10 September at noon ET:
https://lists.w3.org/Archives/Public/public-payments-wg/2021Sep/0002.html

**Comment by plehegar** [comment]
Previous transition: https://github.com/w3c/transitions/issues/346
Payment Request API horizontal comments: https://www.w3.org/PM/horizontal/review.html?shortname=payment-request
Payment Method Identifiers comments: https://www.w3.org/PM/horizontal/review.html?shortname=payment-method-id

**Comment by plehegar** [comment]
Payment Request API diff: https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FCRD-payment-request-20210629%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fpayment-request%2F%3FspecStatus%3DPR%26shortName%3Dpayment-request

**Comment by plehegar** [comment]
For the record: "A Proposed Recommendation may identify itself as intending to allow new features (class 4 changes) after its initial publication as a Recommendation,"

I don't see any of that in the proposed SOTD. Is it intentional?

**Comment by ianbjacobs** [comment]
I would not say that it's intentional because we did not discuss it. Therefore I would say it's ok this way because nobody has suggested it.

**Comment by plehegar** [comment]
Note: i18n WG is still pondering https://github.com/w3c/payment-request/issues/948

**Comment by plehegar** [comment]
@ianbjacobs if it's not too late, I strongly encourage you to ask the WG regarding the mention in the SOTD since it will affect how the future Rec can be revised. cc @marcoscaceres . While knowing the outcome of that discussion is not a blocker for the Director, you should solve this before the actual PR publication.

**Comment by ianbjacobs** [comment]
@plehegar, do you have an example of a spec that does this?

**Comment by plehegar** [comment]
[Pubrules](https://www.w3.org/pubrules/doc/rules/?profile=PR) recommends:
```
<p>Future updates to this specification may incorporate <a href="https://www.w3.org/2020/Process-20200915/#allow-new-features">new features<a>.</p>
```

For an example, see the [sotd of WebRTC 1.0](https://www.w3.org/TR/2020/PR-webrtc-20201215/#sotd).

**Comment by ianbjacobs** [comment]
Our proposed charter sets and expectation that we will not add new features to PR API during the next charter period. Would it make sense to include that sentence in the spec ("just in case") but still set an expectation that we don't plan to add features in this version of the charter?

**Comment by marcoscaceres** [comment]
Hmmm… I think we should add this. Specially as SPC builds on PR API, which may bring unexpected feature requests. 

Ps: we don’t need to add it manually. ReSpec supports setting a class attribute on the sotd section.

**Comment by swickr** [comment]
> Note: i18n WG is still pondering [w3c/payment-request#948](https://github.com/w3c/payment-request/issues/948)

Thanks for flagging this, @plehegar 

It does appear that the label property defined in [8. PaymentItem dictionary](https://w3c.github.io/payment-request/#paymentitem-dictionary) is not covered by the note added by [#944](https://github.com/w3c/payment-request/pull/944) since the property cannot reasonably be translated by the user agent nor the API. For this property, shouldn't the spec note that it is the responsibility of the Web application to provide a language appropriate item description?

**Comment by ianbjacobs** [comment]
@swickr,
I don't think a note in the spec will be of much use; we are presuming that if the user has been interacting with the site up to this point, the site will provide something usable as input.

The need is for the site to label the text direction and language. The spec does not provide a mechanism and implementations don't provide a mechanism.

**Comment by marcoscaceres** [comment]
@swickr, I found a reference to ISO 3166-2 that was not used in the document, so I removed it.

**Comment by swickr** [comment]
Transition approved.

@plehegar has pinged i18n a couple of times on https://github.com/w3c/payment-request/issues/948.  This can proceed.

**Comment by ianbjacobs** [comment]
Thank you!

**Comment by plehegar** [comment]
https://www.w3.org/TR/2021/PR-payment-request-20210930/
https://www.w3.org/TR/2021/PR-payment-method-id-20210930/
