### ISSUE TITLE
REC Request for DOM Review Draft — Published 15 June 2020 as W3C Recommendation 

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#378]
# Link to internal transition

https://lists.w3.org/Archives/Team/w3t-comm/2021Sep/0092.html

# Link to previous transition
[PR](https://github.com/w3c/transitions/issues/357)
[CR](https://github.com/w3c/transitions/issues/340)

This specification is intended to supersede Document Object Model (DOM) 
Level 3 Core Specification Version 1.0, W3C Recommendation 07 April 2004.

/cc @sideshowbarker

**Comment by swickr** [comment]
Transition to W3C Recommendation is approved.

**Comment by siusin** [comment]
The REC and the SPSD [were published](https://lists.w3.org/Archives/Member/w3c-ac-members/2021JulSep/0047.html) on 2021-09-28.
