### ISSUE TITLE
CR Request for CSS Multi-column Layout Level 1

### ISSUE THREAD

**Issue by rachelandrew** [w3c/transitions#379]
# Document title, URLs, estimated publication date

Title: CSS Multi-column Layout Level 1
Editor's Draft: https://drafts.csswg.org/css-multicol/
Publication date: as soon as approved.

# Abstract

This specification describes multi-column layouts in CSS, a style sheet language for the web. Using functionality described in the specification, content can be flowed into multiple columns with a gap and a rule between them.

# Status

https://drafts.csswg.org/css-multicol/#status (as ED)

_Note that this is a return to CR status for this document which was returned to Working Draft status in October 2017 (https://www.w3.org/TR/2017/WD-css-multicol-1-20171005/) due to the number of unresolved issues. These issues and more have now been resolved._

# Link to group's decision to request transition

https://github.com/w3c/csswg-drafts/issues/6612#issuecomment-920189454

# Changes

All changes from the 2011 Candidate Recommendation to date can be found in the draft at  [https://drafts.csswg.org/css-multicol/#changes](https://drafts.csswg.org/css-multicol/#changes). The majority of changes were clarifications and adding specification text where the only indication of behavior was in an example. 

- The breaking properties are now defined in [CSS Fragmentation](https://www.w3.org/TR/css-break-3/).
- The `column-gap` property is now defined in [CSS Box Alignment](https://www.w3.org/TR/css-align-3/).
- The section “The Multi-Column model” was largely rewritten with the help of Morten Stenshorne and Elika J. Etemad. 

# Requirements satisfied

Working group requirements satisfied.

# Dependencies met (or not)

Multicol relies on properties and behavior now defined in [CSS Fragmentation Level 3]((https://www.w3.org/TR/css-break-3/)), this spec is a CR. 

# Wide Review

https://github.com/w3c/csswg-drafts/issues/6103 

All groups have reviewed other than Security, review was requested on 12 May 2021.

Updates were made on the request of the Accessibility and Internationalization Groups. 

# Issues addressed

Disposition of comments: https://drafts.csswg.org/css-multicol/issues.html

There are no outstanding issues that require edits to this document.

# Formal Objections

None.

# Implementation

[Implementation report](https://test.csswg.org/harness/results/css-multicol-1_dev/grouped/)

All properties of this specification already have multiple, interoperable implementations.

With the exception of `column-span` (implemented in Firefox in version 71), all properties can be found from the following browser versions:

- Chromium 50
- Edge 12
- Firefox 52
- Internet Explorer 10
- Safari 9

In addition to web user-agents, multicol is widely implemented by print user-agents.

# Patent disclosures

https://www.w3.org/groups/wg/css/ipr

**Comment by svgeesus** [comment]
The Security & Privacy section will need to be split into two separate sections (this is a new requirement from [W3C Wide Review](https://www.w3.org/Guide/documentreview/)

**Comment by rachelandrew** [comment]
> The Security & Privacy section will need to be split into two separate sections (this is a new requirement from [W3C Wide Review](https://www.w3.org/Guide/documentreview/))

thanks @svgeesus I have made it so.

**Comment by swickr** [comment]
Transition approved.

Note that there are much more recent browser implementations than you cited in the Implementation section :)

**Comment by svgeesus** [comment]
> Note that there are much more recent browser implementations than you cited in the Implementation section :)

Yes, hence the **from** version xx which was the first version to support it..
