### ISSUE TITLE
FPWD Request for Natural Language Interface Accessibility User Requirements

### ISSUE THREAD

**Issue by RealJoshue108** [w3c/transitions#384]
# Document title, URLs, estimated publication date
Publish to: https://www.w3.org/TR/naur/
Pubrules checked file available at: http://raw.githack.com/w3c/apa/naur-fpwd/naur/Overview.html
Requested Publication date: 12th October 2021

# Abstract
This document outlines accessibility user needs, requirements and scenarios, for natural language interfaces. These user needs should influence accessibility requirements in related specifications, and be considered in the design of applications that include natural language interfaces.

This document is most explicitly not a collection of baseline requirements. It is also important to note that some of the requirements may be implemented at a system or platform level, and some may be authoring requirements for development of applications.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

This document was published by the Accessible Platform Architectures Working Group as a First Public Working Draft.

To comment, file an issue in the W3C APA GitHub repository. If this is not feasible, send email to public-apa@w3.org (subscribe, archives). Comments are requested by 12th November 2021.

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership.

This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. The group does not expect this document to become a W3C Recommendation. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 15 September 2020 W3C Process Document. 

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-apa/2021Oct/0004.html

# Information about implementations known to the Working Group
N/A

**Comment by plehegar** [comment]
Approved
