### ISSUE TITLE
FPWD Request for Accessibility of Remote Meetings

### ISSUE THREAD

**Issue by RealJoshue108** [w3c/transitions#385]
# Document title, URLs, estimated publication date
Publish to: https://www.w3.org/TR/remote-meetings/
Pubrules checked file available at: https://raw.githack.com/w3c/apa/accessible-meetings/remote-meetings/Overview.html
Requested Publication date: 14th October

# Abstract
This document summarizes considerations of accessibility that arise in the conduct of remote and hybrid meetings. Such meetings are mediated, for some or all participants, by real-time communication software typically built upon Web technologies. Issues of software selection, and the roles of meeting hosts and participants in providing access are explained. Relevant W3C documents are referred to, where applicable, as sources of more detailed and in some instances normative guidance.

Whereas the RTC Accessibility User Requirements [raur] address the design of the underlying technologies and software, the present document examines the accessibility of remote and hybrid meetings from a larger perspective. It is recognized that the accessibility of a meeting experience to participants with disabilities depends on a variety of conditions, only some of which are ensured by the design of the software used. Further conditions need to be put in place as part of the process of organizing and conducting the meeting itself, including the appropriate application of features offered by the meeting software as well as the creation of accessible content.

# Status
This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

This document was published by the Accessible Platform Architectures Working Group as a First Public Working Draft.

To comment, file an issue in the W3C APA GitHub repository. If this is not feasible, send email to public-apa@w3.org (subscribe, archives). Comments are requested by 19th November 2021.

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership.

This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. The group does not expect this document to become a W3C Recommendation. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 15 September 2020 W3C Process Document. 

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-apa/2021Oct/0005.html

# Information about implementations known to the Working Group
N/A

**Comment by plehegar** [comment]
Approved
