### ISSUE TITLE
FPWD Request for MiniApp Packaging

### ISSUE THREAD

**Issue by xfq** [w3c/transitions#386]
# Document title, URLs, estimated publication date
MiniApp Packaging
https://raw.githack.com/xfq/testing/main/miniapp-packaging-WD/Overview.html
proposed publication 12 October 2021

# Abstract
https://raw.githack.com/xfq/testing/main/miniapp-packaging-WD/Overview.html#abstract

# Status
https://raw.githack.com/xfq/testing/main/miniapp-packaging-WD/Overview.html#sotd

# Is it a delta specification intended to become a W3C Recommendation?
No.

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-miniapps-wg/2021Sep/0003.html

# Information about implementations known to the Working Group
Various MiniApp platforms support some kind of package format. We hope to create a unified package format through this document.

**Comment by plehegar** [comment]
HTML5 normative reference needs to be removed. Use HTML instead.


Other than that, approved.

**Comment by xfq** [comment]
Further issues tracked in https://github.com/w3c/respec/issues/3861 and https://github.com/w3c/miniapp-packaging/pull/39

**Comment by xfq** [comment]
All issues resolved. Will send a publication request to the Webmaster.

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2021/WD-miniapp-packaging-20211130/
