### ISSUE TITLE
FPWD Request for IMSC Hypothetical Render Model (Timed-Text WG)

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#388]
# Document title, URLs, estimated publication date
IMSC Hypothetical Render Model
https://w3c.github.io/imsc-hrm/spec/imsc-hrm.html
propose publication at 2nd Nov 2021

# Abstract
https://w3c.github.io/imsc-hrm/spec/imsc-hrm.html#abstract

# Status
https://w3c.github.io/imsc-hrm/spec/imsc-hrm.html#sotd

# Is it a delta specification intended to become a W3C Recommendation?
no
but this document is a cut-out of [section 11. Hypothetical Render Model](https://www.w3.org/TR/ttml-imsc/#hypothetical-render-model) from IMSC 1.2, and could be counted as a delta specification to update the section.

# Link to group's decision to request transition
CfC: https://lists.w3.org/Archives/Public/public-tt/2021Oct/0001.html
resolution: https://lists.w3.org/Archives/Public/public-tt/2021Oct/0005.html

# Information about implementations known to the Working Group
This document is started from one section in IMSC spec, and some implementation uses this HRM as validation model.

/cc @nigelmegitt @pchampin @gkatsev

**Comment by plehegar** [comment]
Approved

**Comment by himorin** [comment]
published as https://www.w3.org/TR/2021/WD-imsc-hrm-20211109/
