### ISSUE TITLE
[CSSWG] PR request for CSS Color 3

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#39]
# Document title, URLs, estimated publication date

CSS Color Module Level 3
https://www.w3.org/TR/2017/CR-css-color-3-20171130/ (CR rolling in errata)
https://drafts.csswg.org/css-color-3/ (ED)
First Tues or Thurs after transition decision

This will be a Proposed Rec for an eventual Edited Recommendation.

# Abstract

https://www.w3.org/TR/2017/CR-css-color-3-20171130/#abstract

# Status

https://www.w3.org/TR/2017/CR-css-color-3-20171130/#status (as CR)

# Link to group's decision to request transition

RESOLUTION: Request a transition to PR for CSS Color 3
[Minutes, 7 Mar 2018 telcon](https://www.w3.org/2018/03/07-css-minutes.html#item01)

# Changes

No substantive changes. A typo ( a spurious trailing semicolon) [was reported](https://github.com/w3c/csswg-drafts/issues/2401) and will be removed n the Proposed Rec.

# Requirements satisfied

No change

# Dependencies met (or not)

No change

# Wide Review

One non-substantive comment on the CR of 30 November 2017. 

# Issues addressed

No substantive issues

# Formal Objections

None

# Implementation

No change. The one test for the rolled-in substantive erratum was already passed when we entered CR.

# Patent disclosures

None

**Comment by swickr** [comment]
Approved

**Comment by svgeesus** [comment]
Publication request sent, expected Thurs 15 March.

**Comment by svgeesus** [comment]
[Published 15 March](https://www.w3.org/TR/2018/PR-css-color-3-20180315/)
