### ISSUE TITLE
FPWD Request for Digital Publishing Accessibility API Mappings 1.1

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/transitions#391]
# Document title, URLs, estimated publication date
title: Digital Publishing Accessibility API Mappings 1.1
editors' draft: https://w3c.github.io/dpub-aam/
expected latest version uri: https://www.w3.org/TR/dpub-aam-1.1/
desired publication date: 30 November 2021

# Abstract
 The Digital Publishing Accessibility API Mappings (DPub-AAM) defines how user agents map the Digital Publishing WAI-ARIA Module [dpub-aria-1.1] markup to platform accessibility APIs. It is intended for user agent developers responsible for accessibility in their user agent so that they can support the accessibility content produced for digital publishing.

The implementation of this specification in user agents enables authors to produce more accessible e-books, by conveying structural book constructs used by the digital publishing industry to assistive technologies. It does this by extending the Core Accessibility API Mappings 1.1 [CORE-AAM-1.1] and the Accessible Name and Description: Computation and API Mappings 1.1 [ACCNAME-AAM-1.1] specifications for user agents. It provides Accessibility API Mapping guidance for the roles defined in the Digital Publish WAI-ARIA Module.

The DPub-AAM is part of the WAI-ARIA suite described in the WAI-ARIA Overview. 

# Status
This section describes the status of this document at the time of its publication. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

DPub-AAM 1.1 provides updated mappings to support Digital Publishing WAI-ARIA Module 1.1 [dpub-aria-1.1]. For a complete list of changes addressed in this revision, please refer to the change log.

This document was published by the Accessible Rich Internet Applications Working Group as a First Public Working Draft using the Recommendation track.

Publication as a First Public Working Draft does not imply endorsement by W3C and its Members.

This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the 1 August 2017 W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 2 November 2021 W3C Process Document. 

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-aria-admin/2021Oct/0007.html

# Information about implementations known to the Working Group
none yet

**Comment by plehegar** [comment]
Approved

**Comment by michael-n-cooper** [comment]
[Publication request](https://lists.w3.org/Archives/Team/webreq/2021Nov/0052.html)
~~Transition announcement draft~~[Request for clarification on requirements for a transition announcement](https://lists.w3.org/Archives/Team/w3t-comm/2021Nov/0147.html)

**Comment by plehegar** [comment]
https://www.w3.org/TR/2021/WD-dpub-aam-1.1-20211130/
