### ISSUE TITLE
REC Request for ARIA in HTML

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#392]
# Link to internal transition
https://lists.w3.org/Archives/Team/w3t-comm/2021Nov/0134.html

# Link to previous transition
[PR](https://github.com/w3c/transitions/issues/380)
[CR](https://github.com/w3c/transitions/issues/350)

**Comment by plehegar** [comment]
Added: Future updates to this specification may incorporate new 
features.

per
 https://lists.w3.org/Archives/Member/w3c-ac-members/2021OctDec/0022.html 

 So, even if the PR does not contain the proper wording, this Recommendation will be allowed to have proposed additions in it.

**Comment by swickr** [comment]
Recommendation announced 9-Dec: [[Member announcement](https://lists.w3.org/Archives/Member/w3c-ac-members/2021OctDec/0043.html)] and [[Public announcement](https://www.w3.org/blog/news/archives/9367)].
