### ISSUE TITLE
CR Request for CSS Scrollbars Styling Module Level 1

### ISSUE THREAD

**Issue by frivoal** [w3c/transitions#395]
# Document title, URLs, estimated publication date
CSS Scrollbars Styling Module Level 1
https://www.w3.org/TR/css-scrollbars-1/
Expected publication date: as soon as the Team can approve the transition and publish the document

# Abstract
https://www.w3.org/TR/css-scrollbars-1/#abstract

# Status
https://www.w3.org/TR/css-scrollbars-1/#status

# Link to group's decision to request transition
https://logs.csswg.org/irc.w3.org/css/2021-12-01/#e1449786

# Changes
https://www.w3.org/TR/css-scrollbars-1/#changes

# Requirements satisfied
No specific requirements document

# Dependencies met (or not)
Normative references are:
* CSS-COLOR-4: WD, only used to refer to the generic concept of a `<color>` ->OK
* CSS-COLOR-ADJUST-1*: WD, only used to refer to the color-scheme property as something that UAs *may* take into account ->OK
* CSS-OVERFLOW-3: WD, only normatively used to refer to the very stable concept of a "scroll container". -> OK
* CSS-VALUES-3: CR -> OK
* CSS-VALUES-4: WD, only used for things are already in level 3 as well (bikeshed is a bit agressive at picking the newest spec), like the notion of "css-wide keywords" or the syntax to define property values.  ->OK
* CSS2: REC -> OK
* RFC2119: -> OK

# Wide Review
Horizontal review: https://github.com/w3c/csswg-drafts/issues/6550
Blog announcement of a "last call": https://www.w3.org/blog/CSS/2021/08/27/css-scrollbars-lcwd/

# Issues addressed
https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+label%3Acss-scrollbars-1+is%3Aclosed

# Formal Objections
None

# Implementation
No formal implementation report yet, but so far, it is implemented and shipping in Firefox (since 64), and [under development in Blink](https://www.chromestatus.com/features/5665308343795712)

# Patent disclosures
None to date on this specification: https://www.w3.org/groups/wg/css/ipr#disclosures

cc: @svgeesus @tantek @atanassov @astearns @fantasai

**Comment by plehegar** [comment]
No 'needs-resolution' issues listed in https://www.w3.org/PM/horizontal/review.html?shortname=css-scrollbars

**Comment by swickr** [comment]
Transition approved.

**Comment by svgeesus** [comment]
Apparently a Director's Exception is needed, because there is a bug in the pubrules checker and it can't find the link to the Implementation Report even though it is clearly present. [Specberus bug report](https://github.com/w3c/specberus/issues/1463)

**Comment by svgeesus** [comment]
Publication requested 2021-12-06 expected 2021-12-07

**Comment by svgeesus** [comment]
Publication bumped to Thursday because of pubrules
