### ISSUE TITLE
CR Request for CSS Cascading and Inheritance Level 4 [CSSWG][css-cascade-4]

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#396]
# Document title, URLs, estimated publication date
CSS Cascading and Inheritance Level 4
https://www.w3.org/TR/css-cascade-4/
Soon? :)

# Abstract
https://www.w3.org/TR/css-cascade-4/#abstract

# Status
https://www.w3.org/TR/css-cascade-4/#status

This specification was pulled from CR to WD to
* defer scoping (now being explored in L6)
* define integration with Shadow DOM (which was shipping at the time, but not defined in the correct spec)

We also took the opportunity to
* define CSS's aliasing mechanism for properties and values
* fix various other minor issues

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/www-style/2021Dec/0003.html

# Changes
https://www.w3.org/TR/css-cascade-4/#changes

# Requirements satisfied
yes, afaict

# Dependencies met (or not)
Actual normative dependencies are CSS2 (REC), URL (LS), Fetch (LS), Mediaqueries L3 (REC), CSS Conditional Rules L3 (CR), Values and Units L3 (CR), RFC2119 (RFC)

Bikeshed seems to be autolinking to stuff mentioned in examples, so need to clean that up...

# Wide Review
Previous transition request: https://github.com/w3c/transitions/issues/82
Horizontal Review: https://github.com/w3c/csswg-drafts/issues/6120

# Issues addressed
Closed: https://github.com/w3c/csswg-drafts/issues?page=1&q=is%3Aissue+label%3Acss-cascade-4+is%3Aclosed

Open: https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+label%3Acss-cascade-4+is%3Aopen

Two issues are open about proper integration with the new Fetch specification, but it's taking awhile to get these sorted and we don't think it should block the transition back to CR. We plan to fix them during CR, once it becomes clearer what edits are necessary on our end.

# Formal Objections
None

# Implementation
This specification is fully implemented and shipping in all three major browser engine, minus bugs.

# Patent disclosures
None

**Comment by plehegar** [comment]
fyi, the document is referencing some of drafts.csswg.org and /TR/css-218/

https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fwww.w3.org%2FTR%2Fcss-cascade-4%2F

Not sure if it's intended in the published /TR version

**Comment by swickr** [comment]
Transition approved.

**Comment by svgeesus** [comment]
> fyi, the document is referencing some of drafts.csswg.org and /TR/css-218/

Fixed using bikeshed link defaults - it now references css-2021

**Comment by svgeesus** [comment]
Publication requested 11 Jan, expected 13 Jan

**Comment by svgeesus** [comment]
[Published 13 Jan 2022](https://www.w3.org/TR/2022/CR-css-cascade-4-20220113/)
