### ISSUE TITLE
CR Request for CSS Cascading and Inheritance Level 5 [CSSWG][css-cascade-5]

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#397]
# Document title, URLs, estimated publication date
CSS Cascading and Inheritance Level 5
https://www.w3.org/TR/css-cascade-5/
Soon? :)

# Abstract
https://www.w3.org/TR/css-cascade-5/#abstract

# Status
https://www.w3.org/TR/css-cascade-5/#status

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/www-style/2021Dec/0003.html

# Changes
https://www.w3.org/TR/css-cascade-5/#changes

# Requirements satisfied
As far as we can tell.

# Dependencies met (or not)
Same as Cascade L4

# Wide Review
Horizontal review: https://github.com/w3c/csswg-drafts/issues/6120
There has been a lot of discussion about the new layers feature in the authoring community, and Miriam and Jen Simmons have been passing through feedback.
The recently-added “Layers API” section hasn't gone through formal horizontal review, but it was just filling in routine stuff for representing the @layer rule in the CSSOM, and doesn't seem particularly relevant to any HRG concerns.

# Issues addressed
Closed issues: https://github.com/w3c/csswg-drafts/issues?q=label%3Acss-cascade-5+is%3Aclosed
Open issues: https://github.com/w3c/csswg-drafts/labels/css-cascade-5
Two feature requests were deferred. Nobody seems to be upset about anything.

# Formal Objections
None

# Implementation
In progress in all three browser engines.

# Patent disclosures
None

**Comment by swickr** [comment]
Transition approved.

**Comment by svgeesus** [comment]
Publication requested 11 Jan, expected 13 Jan

**Comment by svgeesus** [comment]
[Published 13 Jan 2022](https://www.w3.org/TR/2022/CR-css-cascade-5-20220113/)
