### ISSUE TITLE
First Note request for additional WebCodecs codec registrations

### ISSUE THREAD

**Issue by tidoust** [w3c/transitions#398]
# Document title, URLs, estimated publication date

The Media Working Group would like to publish a number of entries for the WebCodecs codec registry. These documents are to be published as Draft Notes:
* [AAC WebCodecs Registration](https://w3c.github.io/webcodecs/aac_codec_registration.html)
* [A-law PCM WebCodecs Registration](https://w3c.github.io/webcodecs/alaw_codec_registration.html)
* [AV1 WebCodecs Registration](https://w3c.github.io/webcodecs/av1_codec_registration.html)
* [FLAC WebCodecs Registration](https://w3c.github.io/webcodecs/flac_codec_registration.html)
* [MP3 WebCodecs Registration](https://w3c.github.io/webcodecs/mp3_codec_registration.html)
* [Opus WebCodecs Registration](https://w3c.github.io/webcodecs/opus_codec_registration.html)
* [Linear PCM WebCodecs Registration](https://w3c.github.io/webcodecs/pcm_codec_registration.html)
* [u-law PCM WebCodecs Registration](https://w3c.github.io/webcodecs/ulaw_codec_registration.html)
* [Vorbis WebCodecs Registration](https://w3c.github.io/webcodecs/vorbis_codec_registration.html)
* [VP8 WebCodecs Registration](https://w3c.github.io/webcodecs/vp8_codec_registration.html)
* [VP9 WebCodecs Registration](https://w3c.github.io/webcodecs/vp9_codec_registration.html)

No particular hurry for the publication date. Whenever convenient.

# Abstract

* [Abstract of AAC WebCodecs Registration](https://w3c.github.io/webcodecs/aac_codec_registration.html#abstract)
* [Abstract of A-law PCM WebCodecs Registration](https://w3c.github.io/webcodecs/alaw_codec_registration.html#abstract)
* [Abstract of AV1 WebCodecs Registration](https://w3c.github.io/webcodecs/av1_codec_registration.html#abstract)
* [Abstract of FLAC WebCodecs Registration](https://w3c.github.io/webcodecs/flac_codec_registration.html#abstract)
* [Abstract of MP3 WebCodecs Registration](https://w3c.github.io/webcodecs/mp3_codec_registration.html#abstract)
* [Abstract of Opus WebCodecs Registration](https://w3c.github.io/webcodecs/opus_codec_registration.html#abstract)
* [Abstract of Linear PCM WebCodecs Registration](https://w3c.github.io/webcodecs/pcm_codec_registration.html#abstract)
* [Abstract of u-law PCM WebCodecs Registration](https://w3c.github.io/webcodecs/ulaw_codec_registration.html#abstract)
* [Abstract of Vorbis WebCodecs Registration](https://w3c.github.io/webcodecs/vorbis_codec_registration.html#abstract)
* [Abstract of VP8 WebCodecs Registration](https://w3c.github.io/webcodecs/vp8_codec_registration.html#abstract)
* [Abstract of VP9 WebCodecs Registration](https://w3c.github.io/webcodecs/vp9_codec_registration.html#abstract)

# Status of the Document

See e.g. [SOTD of the VP9 WebCodecs Registration ED](https://w3c.github.io/webcodecs/vp9_codec_registration.html#status). I'm still fine-tuning the boilerplate in Bikeshed to meet DNOTE pubrules.

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-media-wg/2021Dec/0001.html

# Is it intended to be a W3C Statement?

No

**Comment by swickr** [comment]
I strongly encourage the Working Group to move [WebCodecs Codec Registry](https://www.w3.org/TR/webcodecs-codec-registry/) to the Registry Track.  As @tidoust observed in [email to the Working Group](https://lists.w3.org/Archives/Public/public-media-wg/2021Nov/0005.html) there would be formal review of the [registry definition](https://www.w3.org/2021/Process-20211102/#registry-definition) however updates to the [registry data](https://www.w3.org/2021/Process-20211102/#registry-table) would be governed (only) by the change policy described in that definition.

Though if the registry definition requires each registry entry to have an associated Note then First Note publication requests such as this will still be expected.

**Comment by tidoust** [comment]
Yes, I believe that publishing the WebCodecs Codec Registry to the Registry Track is still planned. The group just prefers to address that separately. Cc @chrisn, @jernoble

**Comment by plehegar** [comment]
Approved

**Comment by tidoust** [comment]
All [draft notes](https://www.w3.org/TR/?title=webcodecs&status=DNOTE) published last week.
The transition to the Registry track for the WebCodecs registry should be decided early 2022.
