### ISSUE TITLE
FPWD Request for CSS Cascading and Inheritance Level 6 [CSSWG][css-cascade-6]

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/transitions#400]
# Document title, URLs, estimated publication date

- CSS Cascading and Inheritance Level 6
- https://drafts.csswg.org/css-cascade-6/
- Friday, 10 December 2021 

# Abstract

https://drafts.csswg.org/css-cascade-6/#abstract

# Status

https://drafts.csswg.org/css-cascade-6/#status

# Is it a delta specification intended to become a W3C Recommendation?

It will be de-delta-fied prior to the CR transition. It's delta for now to focus review on what's new.

# Link to group's decision to request transition

https://github.com/w3c/csswg-drafts/issues/6865#issuecomment-989060825

# Information about implementations known to the Working Group

none

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Publication requested 16 Dec expected 21 Dec

**Comment by svgeesus** [comment]
[FPWD of Cascade 6](https://www.w3.org/TR/2021/WD-css-cascade-6-20211221/) 21 Dec 2021
