### ISSUE TITLE
FPWD Request for CSS Containment Level 3 [CSSWG][css-contain-3]

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/transitions#401]
# Document title, URLs, estimated publication date

- CSS Containment Level 3
- https://drafts.csswg.org/css-contain-3/
- Friday, 10 December 2021 

# Abstract

https://drafts.csswg.org/css-contain-3/#abstract

# Status

https://drafts.csswg.org/css-contain-3/#status

# Is it a delta specification intended to become a W3C Recommendation?

It will be de-delta-fied prior to the CR transition.

# Link to group's decision to request transition

https://github.com/w3c/csswg-drafts/issues/6426#issuecomment-988998375

# Information about implementations known to the Working Group

Chrome has a prototype implementation, behind a feature flag. There are no other known implementations.

**Comment by plehegar** [comment]
Approved.

**Comment by svgeesus** [comment]
Publication requested 16 Dec, expected 21 Dec

**Comment by svgeesus** [comment]
[FPWD of CSS Contain 3](https://www.w3.org/TR/2021/WD-css-contain-3-20211221/) 21 Dec 2021
