### ISSUE TITLE
First Note request for CSS Snapshot 2021

### ISSUE THREAD

**Issue by frivoal** [w3c/transitions#402]
# Document title, URLs, estimated publication date

Title: CSS Snapshot 2021
ED URL: https://drafts.csswg.org/css-2021/
Desired URL: https://www.w3.org/TR/css-2021/
Estimated publication date: I don't know, whenever you can (preferably within 2021, given what the document is about).

Once published, https://www.w3.org/TR/css/ (without a year in the shortname) should be made to point to this instead of last year's version.

# Abstract
https://drafts.csswg.org/css-2021/#abstract

# Status of the Document
https://drafts.csswg.org/css-2021/#sotd

# Link to group's decision to request transition
https://github.com/w3c/csswg-drafts/issues/6243#issuecomment-988962809

# Is it intended to be a W3C Statement?
No.

**Comment by svgeesus** [comment]
@frivoal I started to set this up for publication on Tuesday, assuming that approval from @plehegar would come swiftly.

Bikeshed generated an empty SotD (except for the custom paragraph), which I fixed manually. But I am still getting two errors, both of which look like Specberus bugs, so I guess I will push publication to Thursday or whenever those bugs are either fixed, or I get told that I can ignore them.

- [Bug in rule “sotd.supersedable”: No "status of this document"](https://github.com/w3c/specberus/issues/1477)
- [Bug in rule “sotd.publish”: The homepage https://www.w3.org/groups/wg/css should appear](https://github.com/w3c/specberus/issues/1478)

**Comment by frivoal** [comment]
Thanks for dealing with this. There seems to be an annoying number of new things specberus rejects recently, and every new publication seems to trip it up.

**Comment by svgeesus** [comment]
> There seems to be an annoying number of new things specberus rejects recently, and every new publication seems to trip it up.

Agreed.

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Publication requested 19 Dec, expected 21 Dec

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2021/NOTE-css-2021-20211230/
