### ISSUE TITLE
FPWD Request for CSS Conditional Rules Level 5 [CSSWG]

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#403]
# Document title, URLs, estimated publication date
CSS Conditional Rules Level 5
https://www.w3.org/TR/css-conditional-5/
https://drafts.csswg.org/css-conditional-5/
ASAP

# Abstract
https://drafts.csswg.org/css-conditional-5/#abstract

# Status
https://drafts.csswg.org/css-conditional-5/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
Delta now, will undeltaify before CR.

# Link to group's decision to request transition
https://www.w3.org/2021/12/15-css-minutes.html#t10

# Information about implementations known to the Working Group
font-tech() is in development in Blink and positive signal from WebKit.
Has had TAG review.

**Comment by svgeesus** [comment]
Publication requested **ahead of FPWD approval** 17 Dec, expected Tues 21 Dec.

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Publication requested 17 Dec expected 21 Dec

**Comment by svgeesus** [comment]
[Published 21 Dec 2021](https://www.w3.org/TR/2021/WD-css-conditional-5-20211221/)
