### ISSUE TITLE
CR Snapshot Update Request for CSS Conditional Rules Level 3

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#404]
# Document URLs
CSS Conditional Rules Level 3
https://drafts.csswg.org/css-conditional-3/
https://www.w3.org/TR/css-conditional-3/

# Link to group's decision to request transition
https://www.w3.org/2021/12/15-css-minutes.html#t10

# Link to previous Candidate Recommendation transition or update request
https://github.com/w3c/transitions/issues/291

# Substantive changes
https://drafts.csswg.org/css-conditional-3/#changes

# Any changes in requirements?
None

# Wide Review of substantive changes
There was only one substantive change, which doesn't seem to impact wide review: https://github.com/w3c/csswg-drafts/issues/6175

# Issues status
https://github.com/w3c/csswg-drafts/labels/css-conditional-3

# Formal Objections
None

# Any changes in implementation information?
Test suite has been completed, we have Firefox passing almost all tests, and Blink or Chrome passing most of them. We're two bugfixes away from REC, basically.

# Deadline for further comments
CSSWG will accept further comments always, just changes will be increasingly constrained by compat.

# Any changes in patent disclosures?
None

See [Requirements for updating a Candidate Recommendation Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot) for further information.

**Comment by swickr** [comment]
Transition approved.

**Comment by plehegar** [comment]
I see https://www.w3.org/TR/2021/CRD-css-conditional-3-20211223/ but that's a CRD, not a CRS. @svgeesus , is that intended?

**Comment by plehegar** [comment]
AH, I see that Dec 23 wasn't a webmaster publishing day so this goes pushed, ie the CRS publication is still pending.

**Comment by svgeesus** [comment]
Publication as CR Snapshot requested 11 Jan expected 13 Jan

**Comment by svgeesus** [comment]
[published 13 Jan 2022](https://www.w3.org/TR/2022/CR-css-conditional-3-20220113/)
