### ISSUE TITLE
FPWD Request for EditContext API

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#405]
# Document title, URLs, estimated publication date
EditContext API
W3C First Public Working Draft 21 December 2021
https://www.w3.org/TR/EditContext/

# Abstract
The EditContext is a new API that allows authors to more directly participate in the text input process. 

# Status
 This document was published by the Web Editing Working Group as a First Public Working Draft using the Recommendation track.

Publication as a First Public Working Draft does not imply endorsement by W3C and its Members.

This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 2 November 2021 W3C Process Document. 

# Is it a delta specification intended to become a W3C Recommendation?
No.

# Link to group's decision to request transition
https://github.com/w3c/editing/issues/366

# Information about implementations known to the Working Group
There is currently an experimental implementation using Chromium, and the WG are expecting flagless shipping in all major browsers eventually.

**Comment by plehegar** [comment]
Approved

**Comment by siusin** [comment]
Is it too late to request using the short name `edit-context` to publish the spec?

**Comment by swickr** [comment]
shortname edit-context is ok

**Comment by siusin** [comment]
published -> https://www.w3.org/TR/2021/WD-edit-context-20211221/
