### ISSUE TITLE
No issue template for: Update a Recommendation to add Proposed Amendments

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#408]
The [new issues chooser](https://github.com/w3c/transitions/issues/new/choose) has options for:

-  **Recommendation Track - Recommendation**
    Point to the internal REC transition for tracking purposes (Proposed Recommendation -> Recommendation)

-  **Recommendation Track - Update a Recommendation**
    Request Director's Approval to incorporate Proposed Amendments into a Recommendation (Recommendation -> Recommendation)

but is missing the one for

-  **Recommendation Track - Update a Recommendation to add Proposed Amendments**
    Request Director's Approval to incorporate Candidate Amendments into a Recommendation with Proposed Amendments (Recommendation -> Recommendation)

So the steps in the [Transitions Guide](https://www.w3.org/Guide/transitions?profile=REC&rec=substantive) for "Incorporating candidate corrections (substantive changes) into an existing Recommendation" cannot be followed, as there is no template to make the update request:

> The Document Contact issue an update request in w3c/transitions, if there are substantive changes other than to remove features explicitly identified as at risk. 

(I'm likely to make such an update request this week, which is how I noticed)

**Comment by svgeesus** [comment]
See [Requirements for updating a Recommendation](https://www.w3.org/Guide/transitions?profile=REC&rec=substantive#adv-reqs)

**Comment by svgeesus** [comment]
This is now blocking two of my specifications from moving forward.

**Comment by svgeesus** [comment]
@plehegar is this being worked on near-term or should I tell WGs that this is likely to be held up for a while?

**Comment by svgeesus** [comment]
ping @plehegar

**Comment by plehegar** [comment]
Only the action of incorporating proposed amendments into the recommendation requires a Director's approval. Thus, the other steps, ie adding candidate or proposed amendments) are not represented here.

I revised the [guide transitions page](https://www.w3.org/Guide/transitions?profile=REC) to make things clearer. Let me know if it's not and raise issues into the Guide repo as needed.
