### ISSUE TITLE
REC Request for Payment Request API and Payment Method Identifiers

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/transitions#411]
---

# Document title, URLs, estimated publication date

* [Payment Request API](https://w3c.github.io/payment-request/)
* [Payment Method Identifiers](https://w3c.github.io/payment-method-id/)

Estimated publication date: None, due to time expected to handle Formal Objections.

# Abstract

* [Payment Request abstract](https://w3c.github.io/payment-request/#abstract)
* [Payment Method Identifiers abstract](https://w3c.github.io/payment-method-id/#abstract)

# Status

* [Payment Request status](https://w3c.github.io/payment-request/#sotd)
* [Payment Method Identifiers status](https://w3c.github.io/payment-method-id/#sotd)

# Link to group's decision to request transition

* [Working Group decision to request to advance to Rec](https://lists.w3.org/Archives/Public/public-payments-wg/2022Feb/0003.html)

# Wide Review

The specification includes [informative changes](https://github.com/w3c/payment-request/pull/971) to satisfy concerns raised by the Internationalization Working Group after approval to advance to Proposed Recommendation.

# Dependencies

No changes since Proposed Recommendation.

# Changes

Since the 30 September 2021 Proposed Recommendation:

* [Changes to address aspects of one Formal Objection](https://github.com/w3c/payment-request/pull/978).
* [Informative changes](https://github.com/w3c/payment-request/pull/971) to satisfy concerns raised by the Internationalization Working Group.
* [An informative change](https://github.com/w3c/payment-request/issues/969) due to a change in terminology in the URL specification.
* A small number of editorial changes to fix bugs.

For the full commit history, see:

* [Payment Request commit history](https://github.com/w3c/payment-request/commits/gh-pages)
* [Payment Method Identifiers commit history](https://github.com/w3c/payment-method-id/commits/gh-pages)

# Link to internal AC Review results

* [AC Review results](https://www.w3.org/2002/09/wbs/33280/payments-pr-2021/results) (Member-only)

# Formal Objections

Proposed Recommendation review resulted in two Formal Objections to Payment Request; 
see the [public documentation](https://www.w3.org/2021/12/prapi-objs.html).
  
The Working Group satisfied 3 of the 4 elements of the Formal Objection from Criteo by adopting [non-substantive changes to the document](https://github.com/w3c/payment-request/pull/978).
 
The Working Group requests that the Director:

* Permit the specification to advance to Recommendation with no further changes to address the disintermediation concern expressed by Criteo. See more on [post-AC Review activities to address the objection](https://www.w3.org/2021/12/prapi-objs.html#post-ac-review)
* Overrule the Formal Objection from 51Degrees, for whom no changes would satisfy the Formal Objection.

For more detailed responses to claims and comments from reviewers, see the [public documentation](https://www.w3.org/2021/12/prapi-objs.html).

**Comment by plehegar** [comment]
See https://www.w3.org/Member/wiki/DirectorFOdashboard#Payment_Request_1.0_and_Payment_Method_Identifiers_proposed_recommendations

**Comment by marcoscaceres** [comment]
Hi 👋 any update on this (or anything we can do to move this along)? We have a bunch of pending pull requests that we'd like to merge into the Payment Request spec. However, we are currently blocked because the REC is not on TR yet 😢

**Comment by ianbjacobs** [comment]
Hi @marcoscaceres, we are awaiting handling of the formal objection. I don't yet have a schedule but things are in the pipe.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/REC-payment-method-id-20220908/
https://www.w3.org/TR/2022/REC-payment-request-20220908/
