### ISSUE TITLE
FPWD Request for MediaStreamTrack Insertable Media Processing using Streams

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/transitions#412]
# Document title, URLs, estimated publication date
* MediaStreamTrack Insertable Media Processing using Streams
* https://w3c.github.io/mediacapture-transform/
* publication date: Feb 10 (if approved in time)
* proposed TR shortname: mediacapture-transform

# Abstract
> This API defines an API surface for manipulating the bits on [MediaStreamTrack](https://www.w3.org/TR/mediacapture-streams/#mediastreamtrack)s carrying raw data.

# Status
>  This section describes the status of this document at the time of its publication. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.
> 
> This document was published by the Web Real-Time Communications Working Group as a Working Draft using the Recommendation track. This document is intended to become a W3C Recommendation.
> 
> If you wish to make comments regarding this document, please raise issues in the github repository, or alternatively send them to public-webrtc@w3.org (subscribe, archives). All comments are welcome.
> 
> This document is a First Public Working Draft.
> 
> Publication as a First Public Working Draft does not imply endorsement by W3C and its Members. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.
> 
> This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.
> 
> This document is governed by the 2 November 2021 W3C Process Document. 

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-webrtc/2022Feb/0024.html

# Information about implementations known to the Working Group
Chromium ships an earlier iteration of this specification: https://chromestatus.com/feature/5499415634640896

**Comment by dontcallmedom** [comment]
@plehegar I was hoping to get this published today, any chance you could review it in time for that?

**Comment by plehegar** [comment]
Approved

**Comment by dontcallmedom** [comment]
published on Feb 10 https://www.w3.org/TR/2022/WD-mediacapture-transform-20220210/
