### ISSUE TITLE
FPWD Request for VSSo: Vehicle Signal Specification Ontology

### ISSUE THREAD

**Issue by caribouW3** [w3c/transitions#413]
# Document title, URLs, estimated publication date
VSSo: Vehicle Signal Specification Ontology
https://www.w3.org/TR/vsso/

VSSo Core: Vehicle Signal Specification Core Ontology
https://www.w3.org/TR/vsso-core/

Publication date: tuesday, Feb 22nd.

# Abstract
https://www.w3.org/2022/auto/staging/WD-vsso-20220222.html#abstract
https://www.w3.org/2022/auto/staging/WD-vsso-core-20220222.html#abstract

# Status
https://www.w3.org/2022/auto/staging/WD-vsso-20220222.html#sotd
https://www.w3.org/2022/auto/staging/WD-vsso-core-20220222.html#sotd

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://www.w3.org/2022/02/15-auto-minutes#t01

# Information about implementations known to the Working Group
An extension of the VSS tools already exists (see https://github.com/danielwilms/vsso-demo)

**Comment by plehegar** [comment]
https://github.com/w3c/vsso-core# and https://github.com/w3c/vsso#  in [1.1 Normative namespaces](https://www.w3.org/2022/auto/staging/WD-vsso-core-20220222.html#normative-namespaces) and [1.1 Normative namespaces](https://www.w3.org/2022/auto/staging/WD-vsso-20220222.html#normative-namespaces).

Before you publish, you ought to use instead:
*  ``https://www.w3.org/ns/vsso-core#``
*  ``https://www.w3.org/ns/vsso#``

and install appropriate schemas or HTML files at those URLs.

eg. https://www.w3.org/ns/dx/prof/

**Comment by plehegar** [comment]
(waiting for confirmation for the change before approving publication)

**Comment by plehegar** [comment]
See also https://github.com/w3c/vsso/issues/25

**Comment by caribouW3** [comment]
Those ns are now in place, the spec will be edited accordingly.

**Comment by plehegar** [comment]
Approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/WD-vsso-core-20220303/
