### ISSUE TITLE
First Draft Note request for MiniApp Addressing

### ISSUE THREAD

**Issue by xfq** [w3c/transitions#415]
# Document title, URLs, estimated publication date
MiniApp Addressing
https://xfq.github.io/testing/miniapp-addressing-DNOTE/Overview.html
The first Tuesday or Thursday after approval

# Abstract
https://xfq.github.io/testing/miniapp-addressing-DNOTE/Overview.html#abstract

# Status of the Document
https://xfq.github.io/testing/miniapp-addressing-DNOTE/Overview.html#sotd

# Link to group's decision to request transition
https://www.w3.org/2022/01/20-miniapp-minutes.html#r01

# Is it intended to be a W3C Statement?
No.

**Comment by plehegar** [comment]
If my understanding is correct, the SOTD should say something along:
[[
The Working Group is publishing this specification as a Draft Note to encourage early review. This specification is not yet on the W3C standards track.
]]

Assuming this gets added to the SOTD, this publication is approved.

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2022/DNOTE-miniapp-addressing-20220310/
