### ISSUE TITLE
First Note request for MiniApp Widget Requirements

### ISSUE THREAD

**Issue by xfq** [w3c/transitions#416]
# Document title, URLs, estimated publication date
MiniApp Widget Requirements
https://xfq.github.io/testing/miniapp-widget-req-NOTE/Overview.html
The first Tuesday or Thursday after approval

# Abstract
https://xfq.github.io/testing/miniapp-widget-req-NOTE/Overview.html#abstract

# Status of the Document
https://xfq.github.io/testing/miniapp-widget-req-NOTE/Overview.html#sotd

# Link to group's decision to request transition
https://www.w3.org/2022/01/20-miniapp-minutes.html#r02

# Is it intended to be a W3C Statement?
No.

**Comment by plehegar** [comment]
Approved

**Comment by xfq** [comment]
Blocked on https://github.com/w3c/respec/issues/4064

**Comment by xfq** [comment]
I will manually fix the link and send a publication request while the ReSpec bug is being fixed.

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2022/NOTE-miniapp-widget-req-20220308/
