### ISSUE TITLE
PR Request for Geolocation API

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/transitions#417]
# Document title, URLs, estimated publication date
Geolocation API
April 5 2022
Ed: https://w3c.github.io/geolocation-api/
TR: https://www.w3.org/TR/geolocation/

# Abstract
https://w3c.github.io/geolocation-api/#abstract

# Status
https://www.w3.org/TR/geolocation/#sotd

# Will new features be allowed to be incorporated in the Recommendation?
Yes

# Link to group's decision to request transition
https://github.com/w3c/geolocation-api/issues/121

# Changes
None. 

# Requirements satisfied

Yes.

# Dependencies met (or not)

Yes.

# Wide Review
Done in CR. 

# Issues addressed
None. 

# Formal Objections
None (...so far). 

# Implementation
Gecko, WebKit, and Chromium. 
Report: https://wpt.fyi/geolocation-API

There is an unrelated bug in Chrome that is preventing Geolocation permission from being "granted". This is making it look like there are more failures than there actually are. 

Similarly, the Web Driven API the tests depend on is not implemented in Firefox or Safari (thus they show up as failures).

However, running the tests manually, the tests pass. We can also provide links to patches that show that everything is implemented per spec.  

# Patent disclosures
None.

**Comment by anssiko** [comment]
For your consideration:

The WG is aware of an issue related to test automation that complicates satisfying the "must show adequate implementation experience" requirement. Please refer to the CfC for details:

https://lists.w3.org/Archives/Public/public-device-apis/2022Mar/0005.html

We remain positive in that we can find a path forward with this transition despite these impediments.

**Comment by plehegar** [comment]
(feel free to set the label and assign back to Ralph as soon as the CfC is approved.)

**Comment by plehegar** [comment]
(CfC runs until March 23)

**Comment by plehegar** [comment]
(@marcoscaceres  will provide more details on the test results)

**Comment by marcoscaceres** [comment]
Here is the implementation report: 
https://w3c.github.io/geolocation-api/reports/PR_imp_report.html

It explains what was tested, and what couldn't be tested (and why).

Hope that helps!

**Comment by marcoscaceres** [comment]
I've updated the spec to also now point to this new implementation report.

**Comment by anssiko** [comment]
CfC passed: https://lists.w3.org/Archives/Public/public-device-apis/2022Mar/0008.html

**Comment by plehegar** [comment]
I installed everything for April 7 publication.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/PR-geolocation-20220407/
