### ISSUE TITLE
First Note request for Fonts for the Web: Rationale

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#419]
# Document title, URLs, estimated publication date
**Fonts for the Web: Rationale**
https://www.w3.org/Fonts/Group/WD-font-rationale-960701.html (as Member-only WD, from 1996)
Tuesday 15 March 2022
shortname would be font-rationale

# Abstract
The goal of the W3C working group on fonts is to produce recommendations for open font solutions for the web. Issues to be resolved include, but are not limited to: style sheet notation, client-server request structure, font matching and synthesis information, and font location.

This document describes the [goals](https://www.w3.org/Fonts/Group/WD-font-rationale-960701.html#goals) of the W3C Font Working Group so that the design philosophy is clear. It includes examples of different [scenarios](https://www.w3.org/Fonts/Group/WD-font-rationale-960701.html#scenarios) where fonts might be used on the Web, and also has a [glossary of terms](https://www.w3.org/Fonts/Group/WD-font-rationale-960701.html#gloss).

Another document describes the abstract information needed to [describe fonts](https://www.w3.org/Fonts/Group/WD-font-desc) for matching, synthesis, or requesting a font over the Web. A third document binds font descriptions to [HTML and CSS-1](https://www.w3.org/Fonts/Group/WD-font-html). Bindings to other media, for example to VRML, to CGM, or to Java, are also possible.

# Status of the Document
(no current status section, will be published as WG Note explaining the historical significance)
See also https://lists.w3.org/Archives/Public/public-webfonts-wg/2022Mar/0005.html

# Link to group's decision to request transition
RESOLUTION: publish 1996 web fonts requirement document.
https://www.w3.org/2022/03/08-webfonts-minutes.html#t01

# Is it intended to be a W3C Statement?
No

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
[Published 14 April 2022](https://www.w3.org/TR/2022/NOTE-font-rationale-20220414/)
