### ISSUE TITLE
CR Request for WebXR Device API

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#420]
# Document title, URLs, estimated publication date
WebXR Device API
https://www.w3.org/TR/webxr/

estimated publication date: 29-March-2022 (as the nearest one)

# Abstract
https://www.w3.org/TR/webxr/#abstract
This specification describes support for accessing virtual reality (VR) and augmented reality (AR) devices, including sensors and head-mounted displays, on the Web.

# Status
https://www.w3.org/TR/webxr/#sotd

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-immersive-web-wg/2022Feb/0005.html

# Changes
https://www.w3.org/TR/webxr/#changes

[changes from last request of HRs](https://www.w3.org/TR/webxr/#changes-from-20200724) are [minor or for resolving issues raised from horizontal reviews](https://www.w3.org/2022/03/22-immersive-web-minutes.html#t01).

# Requirements satisfied
yes

# Dependencies met (or not)
yes

# Wide Review

* [TAG](https://github.com/w3ctag/design-reviews/issues/545)
* [I18N](https://github.com/w3c/i18n-request/issues/127)
* [Privacy](https://lists.w3.org/Archives/Public/public-privacy/2020JulSep/0016.html), [issues](https://github.com/immersive-web/webxr/issues?q=label%3Aprivacy-needs-resolution+is%3Aclosed)
* [accessibility](https://lists.w3.org/Archives/Public/public-apa/2020Sep/0012.html), [APA action](https://www.w3.org/WAI/APA/track/actions/2268)
* [security](https://lists.w3.org/Archives/Public/public-web-security/2020Aug/0001.html)

# Issues addressed
https://github.com/immersive-web/webxr/issues

# Formal Objections
none

# Implementation
https://wpt.fyi/results/webxr?label=experimental&label=master&aligned

# Patent disclosures
https://www.w3.org/groups/wg/immersive-web/ipr

**Comment by plehegar** [comment]
* [diff from July 2020](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2020%2FWD-webxr-20200724%2F&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2F2022%2FWD-webxr-20220314%2F)
* [Horizontal reviews board](https://www.w3.org/PM/horizontal/review.html?shortname=webxr)
* [Normative references](https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2022%2FWD-webxr-20220314%2F)

**Comment by swickr** [comment]
The normative dependency on a CG Report [Requesting Permissions](https://wicg.github.io/permissions-request/) is a concern.

Please update the WebXr Layers normative reference to the /TR version.

In a future update before exiting CR, please update all the inline references to w3c.github.io documents (e.g. permissions).

**Comment by himorin** [comment]
Thank you for pointing on github.io links. I've squashed at some recent point and worked fine, but it seems bikeshed (both local and via GHaction) is picking github.io URL instead of /TR/. I'll try to replace these by hand.

**Comment by swickr** [comment]
Transition approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/CR-webxr-20220331/
