### ISSUE TITLE
First Note request for 2 i18n gap-analysis docs

### ISSUE THREAD

**Issue by r12a** [w3c/transitions#421]
Document titles:
Perso-arabic Kashmiri Gap Analysis
Uighur Gap Analysis

URIs
https://w3c.github.io/alreq/gap-analysis/arab-ks-gap.html
https://w3c.github.io/alreq/gap-analysis/arab-ug-gap.html

Estimated pub date:
Tues 29 Mar

Abstracts:
This document describes and prioritises gaps for the support of Kashmiri language using the Perso-arabic orthography on the Web and in eBooks. In particular, it is concerned with text layout. It checks that needed features are supported in W3C specifications, in particular HTML and CSS and those relating to digital publications. It also checks whether the features have been implemented in browsers and ereaders.

This document describes and prioritises gaps for the support of Uighur on the Web and in eBooks. In particular, it is concerned with text layout. It checks that needed features are supported in W3C specifications, in particular HTML and CSS and those relating to digital publications. It also checks whether the features have been implemented in browsers and ereaders.

SOTD:
https://w3c.github.io/alreq/gap-analysis/arab-ug-gap.html#sotd
https://w3c.github.io/alreq/gap-analysis/arab-ks-gap.html#sotd

Group sign off:
https://www.w3.org/2022/03/24-i18n-minutes.html#t05

# Is it intended to be a W3C Statement?
No

**Comment by plehegar** [comment]
Approved.

**Comment by xfq** [comment]
Should "Perso-**a**rabic Kashmiri" be "Perso-**A**rabic Kashmiri"?

**Comment by plehegar** [comment]
> Should "Perso-**a**rabic Kashmiri" be "Perso-**A**rabic Kashmiri"?

SGTM

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/DNOTE-arab-ks-gap-20220329/
https://www.w3.org/TR/2022/DNOTE-arab-ug-gap-20220329/
