### ISSUE TITLE
FPWD Request for Region Capture

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/transitions#422]
# Document title, URLs, estimated publication date
Title: Region Capture 
URL: https://w3c.github.io/mediacapture-region/
Target TR URL: https://www.w3.org/TR/mediacapture-region/
Target publication date: April 5 2022

# Abstract
This document introduces an API for cropping a video track derived from display-capture of the current [browsing context](https://html.spec.whatwg.org/multipage/browsers.html#browsing-context).

# Status
This section describes the status of this document at the time of its publication. A list of current W3C publications and the latest revision of this technical report can be found in the [W3C technical reports index](https://www.w3.org/TR/) at https://www.w3.org/TR/.

This document was published by the Web Real-Time Communications Working Group as a First Public Working Draft using the [Recommendation track](https://www.w3.org/2021/Process-20211102/#recs-and-notes).

This First Public Working Draft represents the direction the Web Real-Time Communications Working Group intends to explore to solve the use case of partial capture of browsing contexts. The Working Group is particularly interested in feedback on how well this direction matches the said use case from potential adopters of the API.

Publication as a First Public Working Draft does not imply endorsement by W3C and its Members.

This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a [public list of any patent disclosures](https://www.w3.org/groups/wg/webrtc/ipr) made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains [Essential Claim(s)](https://www.w3.org/Consortium/Patent-Policy/#def-essential) must disclose the information in accordance with [section 6 of the W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy/#sec-Disclosure).

This document is governed by the [2 November 2021 W3C Process Document](https://www.w3.org/2021/Process-20211102/).

This document is governed by the [2 November 2021 W3C Process Document](https://www.w3.org/2021/Process-20211102/).

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-webrtc/2022Apr/0002.html

# Information about implementations known to the Working Group
[Origin Trial in Chromium](https://chromestatus.com/feature/5712447794053120)

**Comment by plehegar** [comment]
Approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/WD-mediacapture-region-20220405/
