### ISSUE TITLE
FPWD Request for WebAssembly [Core, JavaScript Interface, Web API]

### ISSUE THREAD

**Issue by ericprud** [w3c/transitions#428]
# Document title, URLs, estimated publication date
WebAssembly Core Specification
  http://www.w3.org/TR/2022/WD-wasm-core-2-20220414

WebAssembly JavaScript Interface
  http://www.w3.org/TR/2022/WD-wasm-js-api-2-20220414

WebAssembly Web API
  http://www.w3.org/TR/2022/WD-wasm-js-api-2-20220414

# Abstract
http://www.w3.org/TR/2022/WD-wasm-core-2-20220414/#abstract
http://www.w3.org/TR/2022/WD-wasm-js-api-2-20220414/#abstract
http://www.w3.org/TR/2022/WD-wasm-web-api-2-20220414/#abstract

# Status
[TODO: copy the status of the document or link to it]
http://www.w3.org/TR/2022/WD-wasm-core-2-20220414/#sotd
http://www.w3.org/TR/2022/WD-wasm-js-api-2-20220414/#sotd
http://www.w3.org/TR/2022/WD-wasm-web-api-2-20220414/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
yes (via evergreen)

# Link to group's decision to request transition
WG meeting 2022-04-13 with plh. will update with link when minutes are published

# Information about implementations known to the Working Group
All major web browsers implement this spec.

**Comment by plehegar** [comment]
Approved

**Comment by plehegar** [comment]
Due to various scheduling and complexity, we're ok with the WASM Group using LateX for their first working drafts. However, the expectation is that those documents would switch to use MathML in a Working Draft before attempting to move to CR.

**Comment by ericprud** [comment]
Can this be closed now?

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/WD-wasm-core-2-20220419/
https://www.w3.org/TR/2022/WD-wasm-js-api-2-20220419/
https://www.w3.org/TR/2022/WD-wasm-web-api-2-20220419/
