### ISSUE TITLE
FPWD Request for Largest Contentful Paint

### ISSUE THREAD

**Issue by caribouW3** [w3c/transitions#432]
# Document title, URLs, estimated publication date
Title: Largest Contentful Paint
Expected URI 
https://www.w3.org/TR/largest-contentful-paint/

Editors draft at:
https://w3c.github.io/largest-contentful-paint/

publication ASAP.

# Abstract
This document defines an API that enables monitoring the largest paint an element triggered on screen.

# Status
This section describes the status of this document at the time of its publication. A list of current W3C publications and the latest revision of this technical report can be found in the [W3C technical reports index](https://www.w3.org/TR/) at https://www.w3.org/TR/.

This document is published by the Web Performance Working Group as a First Public Working Draft using the Recommendation track.

Publication as a First Public Working Draft does not imply endorsement by W3C and its Members.

This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 2 November 2021 W3C Process Document.

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-web-perf/2022Apr/0005.html

# Information about implementations known to the Working Group
Implementation information in chromium:
https://chromium.googlesource.com/chromium/src/+/main/docs/speed/metrics_changelog/lcp.md

**Comment by plehegar** [comment]
Group decision: https://lists.w3.org/Archives/Public/public-web-perf/2022May/0001.html

Approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/WD-largest-contentful-paint-20220524/
