### ISSUE TITLE
First Draft Note request for Ethical Web Principles

### ISSUE THREAD

**Issue by ylafon** [w3c/transitions#433]
# Document title, URLs, estimated publication date
Title: W3C TAG Ethical Web Principles
URL: https://w3ctag.github.io/ethical-web-principles/
Estimated publication date: 20220512
short name: ethical-web-principles
 
# Abstract

The web should be a platform that helps people and provides a positive social benefit. As we continue to evolve the web platform, we must therefore consider the consequences of our work. The following document sets out ethical principles that will drive the W3C's continuing work in this direction.

# Status of the Document

This section describes the status of this document at the time of its publication. A list of current W3C publications and the latest revision of this technical report can be found in the [W3C technical reports index](https://www.w3.org/TR/) at https://www.w3.org/TR/.

This document reflects the consensus of the TAG at the time of publication. It will continue to evolve and the TAG will issue updates as often as needed. The intent is for this document to become a W3C Statement.

This document was published by the Technical Architecture Group as a Group Draft Note using the Note track.

Group Draft Notes are not endorsed by W3C nor its Members.

This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

The W3C Patent Policy does not carry any licensing requirements or commitments on this document.

This document is governed by the 2 November 2021 W3C Process Document.

# Link to group's decision to request transition

https://github.com/w3ctag/meetings/blob/gh-pages/2022/telcons/05-02-minutes.md#ewp-intro-edits

# Is it intended to be a W3C Statement?

Yes

**Comment by plehegar** [comment]
Approved

**Comment by ylafon** [comment]
https://www.w3.org/TR/2022/DNOTE-ethical-web-principles-20220512/
