### ISSUE TITLE
CR Snapshot Update Request for CSS Custom Properties for Cascading Variables Module Level 1

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#434]
# Document URLs
https://www.w3.org/TR/2021/CRD-css-variables-1-20211111/

# Link to group's decision to request transition
[RESOLVED: Move CSS Variables 1 to CR Snapshot after May 9](https://lists.w3.org/Archives/Public/www-style/2022May/0002.html)

# Link to previous Candidate Recommendation transition or update request
[9 Nov 2015](https://lists.w3.org/Archives/Member/chairs/2015OctDec/0094.html)

# Substantive changes
[Changes Since the 03 December 2015 CR](https://www.w3.org/TR/2021/CRD-css-variables-1-20211111/#changes-20151203)
[Changes since the 11 Nov 2021 CR Draft](https://drafts.csswg.org/css-variables/#changes-20211111)

# Any changes in requirements?
None

# Wide Review of substantive changes
[[css-variables-1] Horizontal Review](https://github.com/w3c/csswg-drafts/issues/6808)

# Issues status
[2 open, 49 closed](https://github.com/w3c/csswg-drafts/labels/css-variables-1)

# Formal Objections
None

# Any changes in implementation information?
[Web Platform Tests](https://wpt.fyi/results/css/css-variables?label=experimental&label=master&aligned) 
generally excellent results on 223 tests (642 subtests)
[Can I Use CSS Variables](https://caniuse.com/css-variables)
has been implemented in all modern browsers for years
widely deployed in the wild

# Deadline for further comments
3 months

# Any changes in patent disclosures?
None

See [Requirements for updating a Candidate Recommendation Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot) for further information.

**Comment by plehegar** [comment]
* [Normative references](https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FCRD-css-variables-1-20211111%2F)
* [Horizontal review](https://www.w3.org/PM/horizontal/review.html?shortname=css-variables)
* [diff between 2021 and ED](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FCRD-css-variables-1-20211111%2F&doc2=https%3A%2F%2Fdrafts.csswg.org%2Fcss-variables%2F)

**Comment by swickr** [comment]
Transition approved.

I noticed that [Section 3.1](https://drafts.csswg.org/css-variables/#invalid-variables) and [Section 5.2](https://drafts.csswg.org/css-variables/#changes-20151203) have in-line links to the editors' draft for CSS Properties and Values API.  Please update those in-line links to the /TR version at some point before the next transition.

**Comment by svgeesus** [comment]
[Published](https://www.w3.org/TR/2022/CR-css-variables-1-20220616/)
