### ISSUE TITLE
FPWD Request for Viewport Capture

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/transitions#435]
# Document title, URLs, estimated publication date
Title: Viewport Capture
URL: https://w3c.github.io/mediacapture-viewport/

# Abstract
> This document defines how a browser viewport can be used as the source of a media stream using getViewportMedia, an extension to the Screen Capture API.

# Status
> This section describes the status of this document at the time of its publication. A list of current W3C publications and the latest revision of this technical report can be found in the [W3C technical reports index](https://www.w3.org/TR/) at https://www.w3.org/TR/.
>
> This document is not complete.
>
> This document was published by the [Web Real-Time Communications Working Group](https://www.w3.org/groups/wg/webrtc) as a First Public Working Draft using the [Recommendation track](https://www.w3.org/2021/Process-20211102/#recs-and-notes).
>
> Publication as a First Public Working Draft does not imply endorsement by W3C and its Members.
>
> This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.
>
> This document was produced by a group operating under the [W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy/). W3C maintains a [public list of any patent disclosures](https://www.w3.org/groups/wg/webrtc/ipr) made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains [Essential Claim(s)](https://www.w3.org/Consortium/Patent-Policy/#def-essential) must disclose the information in accordance with [section 6 of the W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy/#sec-Disclosure).
>
> This document is governed by the [2 November 2021 W3C Process Document](https://www.w3.org/2021/Process-20211102/).

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-webrtc/2022May/0042.html

# Information about implementations known to the Working Group
N/A

**Comment by plehegar** [comment]
Approved.

**Comment by dontcallmedom** [comment]
@caribouW3 any chance you could take care of preparing the FPWD publication?

**Comment by dontcallmedom** [comment]
published https://www.w3.org/TR/2022/WD-mediacapture-viewport-20220524/
