### ISSUE TITLE
CR Request for CSS Color Module Level 4

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#436]
# Document title, URLs, estimated publication date
CSS Color Module Level 4
https://drafts.csswg.org/css-color-4/
https://www.w3.org/TR/css-color-4/
asap after transition approval

# Abstract
This specification describes CSS [<color>](https://www.w3.org/TR/css-color-4/#typedef-color) values and properties for foreground color and group opacity.
[CSS](https://www.w3.org/TR/CSS/) is a language for describing the rendering of structured documents (such as HTML and XML) on screen, on paper, etc.

# Status
https://www.w3.org/TR/css-color-4/#status
(as WD; usual CSS WG status for CR)

# Link to group's decision to request transition
RESOLUTION: Color 4 to CR when timing permits
https://www.w3.org/2022/06/22-css-minutes.html#t01

# Changes
https://drafts.csswg.org/css-color-4/#changes-from-20220428

# Requirements satisfied
No requirements document

# Dependencies met (or not)
Referenced by HTML specification (for 2D Canvas) and CSS Images 4 (for gradients)

## Normative references:
- CSS Color 5, (should be informative) is a bikeshed error (mentioned in example)
- CSS Images 4 (should be informative) currently a WD
- CSS Text Decoration (should be informative) currently WD
- CSS Transitions (should be informative) currently WD
- Filter Effects  (should be informative) currently WD

# Wide Review
[Horizontal review](https://github.com/w3c/csswg-drafts/issues/4943) is [complete](https://www.w3.org/PM/horizontal/review.html?shortname=css-color)
Several aspects of CSS Color 4 were discussed at the [Color Workshop](https://www.w3.org/Graphics/Color/Workshop/talks.html#color4)

# Issues addressed
There are (currently) [4 open issues, 198 closed](https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Acss-color-4), and most new issues are raised by implementers. 

# Formal Objections
None

# Implementation
It is implemented and shipped in WebKit in its entirety, and is now being implemented in Gecko and Chromium as well. It is also implemented in JavaScript libraries such as [color.js](https://colorjs.io/), Python libraries such as [Coloraide](https://pypi.org/project/coloraide/) and [in PostCSS](https://github.com/postcss/postcss-color-function)

Test [coverage](https://github.com/w3c/csswg-drafts/issues/6306) in [WPT](https://wpt.fyi/results/css/css-color?label=experimental&label=master&aligned) is good (9k subtests), and the spec is fully annotated for WPT so each tested section has links to tests and test results.

Conformance to CSS Color 4 is [part of Interop 2022](https://github.com/web-platform-tests/interop-2022/issues/20) as [Color Spaces and Functions](https://wpt.fyi/results/css/css-color?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-color)

# Patent disclosures
[IPR](https://www.w3.org/groups/wg/css/ipr)

**Comment by svgeesus** [comment]
[Normative references check](https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2022%2FWD-css-color-4-20220628%2F) but see [false positives from WPT links](https://github.com/plehegar/normative-references/issues/8)

**Comment by swickr** [comment]
Transition approved.

The horizontal reviews were recorded quite a while ago.  Please request from the horizontal review groups that they at least scan the changes since their most recent reviews and confirm they have done so before requesting CR Exit.

**Comment by svgeesus** [comment]
Publication requested 29 June, expected 5 July

**Comment by svgeesus** [comment]
[Published 2022-07-05](https://www.w3.org/TR/2022/CR-css-color-4-20220705/)
