### ISSUE TITLE
FPWD Request for Multi-Screen Window Placement

### ISSUE THREAD

**Issue by tidoust** [w3c/transitions#438]
# Document title, URLs, estimated publication date
- Title: Multi-Screen Window Placement
- Editor's Draft: https://w3c.github.io/window-placement/
- Publication date: Thursday 30 June 2022

# Abstract
This document defines a web platform API that allows script to query the device for information about its screens, and place content on specific screens.

# Status
This section describes the status of this document at the time of its publication. A list of current W3C publications and the latest revision of this technical report can be found in the [W3C technical reports index](https://www.w3.org/TR/) at https://www.w3.org/TR/.

This document was published by the [Second Screen Working Group](https://www.w3.org/groups/wg/secondscreen) as a Working Draft using the [Recommendation track](https://www.w3.org/2021/Process-20211102/#recs-and-notes). This document is intended to become a W3C Recommendation.

The Second Screen Working Group maintains [a list of all bug reports that the group has not yet addressed](https://github.com/w3c/window-placement/issues). This draft highlights some of the pending issues that are still to be discussed in the working group. No decision has been taken on the outcome of these issues including whether they are valid. Pull requests with proposed specification text for outstanding issues are strongly encouraged.

This document is a First Public Working Draft.

Publication as a First Public Working Draft does not imply endorsement by W3C and its Members. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the [W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy-20200915/). W3C maintains a [public list of any patent disclosures](https://www.w3.org/2004/01/pp-impl/74168/status) made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains [Essential Claim(s)](https://www.w3.org/Consortium/Patent-Policy-20200915/#def-essential) must disclose the information in accordance with [section 6 of the W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy-20200915/#sec-Disclosure).

This document is governed by the [2 November 2021 W3C Process Document](https://www.w3.org/2021/Process-20211102/).

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-secondscreen/2022Jun/0024.html

# Information about implementations known to the Working Group
- [Implemented in Chrome](https://chromestatus.com/feature/5252960583942144)

**Comment by plehegar** [comment]
Approved.

Please make sure to get a review from the Fullscreen spec folks (among others), since your spec might be doing monkey-patching. @annevk

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/WD-window-placement-20220630/
