### ISSUE TITLE
REC Request for DID 1.0 Recommendation

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#439]
---

# Document title, URLs, estimated publication date

Decentralized Identifiers (DIDs) v1.0
https://w3c.github.io/did-core/
Estimated publication: July 2022

# Abstract

https://w3c.github.io/did-core/#abstract

# Status

https://w3c.github.io/did-core/#sotd

# Link to internal AC Review results

https://www.w3.org/2002/09/wbs/33280/did-core-pr/results

# Formal Objections

https://www.w3.org/2022/03/did-fo-report.html

**Comment by plehegar** [comment]
[[
If there was any [dissent](https://www.w3.org/Consortium/Process/Drafts/director-free/#def-Dissent) in Advisory Committee reviews, the [Team](https://www.w3.org/Consortium/Process/Drafts/director-free/#team) must publish the substantive content of the dissent to W3C and the general public, and must [formally address](https://www.w3.org/Consortium/Process/Drafts/director-free/#formally-addressed) the comment at least 14 days before publication as a [W3C Recommendation](https://www.w3.org/Consortium/Process/Drafts/director-free/#RecsW3C).
]]
https://www.w3.org/2021/Process-20211102/#formally-addressed

The [substantive content of the dissent](https://www.w3.org/2022/03/did-fo-report.html) is available.

The Director issued a decision today, which starts the 14 days period before publication.

**Comment by plehegar** [comment]
[Director's decision](https://www.w3.org/2022/06/DIDRecommendationDecision.html) is also available publicly.

**Comment by swickr** [comment]
Published 19 July; see [announcement](https://www.w3.org/blog/news/archives/9618).
