### ISSUE TITLE
First Note request for ‘MathML Media-type Declarations’

### ISSUE THREAD

**Issue by bert-github** [w3c/transitions#440]
# Document title, URLs, estimated publication date
Title: MathML Media-type Declarations
Editors' draft: https://w3c.github.io/mathml-docs/mathml-media-types/
Expected URL: https://www.w3.org/TR/mathml-media-types/
Estimated date: 19 July 2022

# Abstract

> This normative text registers three media types for MathML, application/mathml+xml, application/mathml-presentation+xml and application/mathml-content+xml, in conformance with [[RFC4288](https://w3c.github.io/mathml-docs/mathml-media-types/NOTE-mathml-media-types.html#bib-rfc4288)] and [[W3CRegMedia](https://w3c.github.io/mathml-docs/mathml-media-types/NOTE-mathml-media-types.html#bib-w3cregmedia)]. The media-types have been approved by IESG for registration with IANA as [announced by IETF](http://www.ietf.org/mail-archive/web/ietf-announce/current/msg07890.html) and are visible on the list of application media-types [[MediaTypesList](https://w3c.github.io/mathml-docs/mathml-media-types/NOTE-mathml-media-types.html#bib-mediatypeslist)].

# Status of the Document

> This section describes the status of this document at the time of its publication. A list of current W3C publications and the latest revision of this technical report can be found in the [W3C technical reports index](https://www.w3.org/TR/) at https://www.w3.org/TR/.
> 
> This document was published by the [Math Working Group](https://www.w3.org/groups/wg/math) as a Group Note using the [Note track](https://www.w3.org/2021/Process-20211102/#recs-and-notes).
> 
> Group Notes are not endorsed by W3C nor its Members.
> 
> This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.
> 
> The [W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy/) does not carry any licensing requirements or commitments on this document.
> 
> This document is governed by the [2 November 2021 W3C Process Document](https://www.w3.org/2021/Process-20211102/).

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/www-math/2022Jul/0000.html

# Is it intended to be a W3C Statement?
No

**Comment by plehegar** [comment]
Approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/NOTE-mathml-media-types-20220721/
