### ISSUE TITLE
FPWD Request for Payment Request 1.1

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/transitions#442]
# Document title, URLs, estimated publication date

Title: Payment Request 1.1
URL: https://w3c.github.io/payment-request/?specStatus=FPWD 
Publication Date: ASAP 

# Abstract
https://w3c.github.io/payment-request/?specStatus=FPWD#abstract

# Status
https://w3c.github.io/payment-request/?specStatus=FPWD#sotd

# Is it a delta specification intended to become a W3C Recommendation?
NO

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-payments-wg/2022Jul/0013.html

# Information about implementations known to the Working Group
Changes to 1.1 are implemented in Safari.

**Comment by marcoscaceres** [comment]
Please kindly let me know of when might be a suitable publication date and I can provide a link (and/or generate a static doc).

**Comment by plehegar** [comment]
Approved

**Comment by plehegar** [comment]
Note: It is NOT meant to become a delta specification.

**Comment by marcoscaceres** [comment]
fixed the delta thing... sorry about that.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/WD-payment-request-1.1-20220726/
