### ISSUE TITLE
FPWD Request for Verifiable Credentials Data Model v2.0

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#445]
# Document title, URLs, estimated publication date

- Verifiable Credentials Data Model v2.0
- https://www.w3.org/TR/2022/WD-vc-data-model-2.0-20220811/
- Date 2022-08-11

# Abstract

https://www.w3.org/TR/2022/WD-vc-data-model-2.0-20220811/#abstract

# Status

https://www.w3.org/TR/2022/WD-vc-data-model-2.0-20220811/#sotd

# Is it a delta specification intended to become a W3C Recommendation?

No

# Link to group's decision to request transition

https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-07-27-vcwg#resolution1

# Information about implementations known to the Working Group

This is document is mostly identical to the 1.1 Recommendation:

https://www.w3.org/TR/2022/REC-vc-data-model-20220303/

meaning that the implementation report for 1.1 is relevant:

https://w3c.github.io/vc-test-suite/implementations/

cc @msporny @Sakurann @brentzundel

**Comment by plehegar** [comment]
Approved

**Comment by iherman** [comment]
Publication done (see, eg, [HPN announcement](https://www.w3.org/blog/news/archives/9650)), closing the issue.
