### ISSUE TITLE
First Note request for <W3C Accessibility Maturity Model>

### ISSUE THREAD

**Issue by ruoxiran** [w3c/transitions#447]
# Document title, URLs, estimated publication date
Title: W3C Accessibility Maturity Model
URLs (I will put the document to right place after transition): https://raw.githack.com/w3c/maturity-model/FPWD-2022-0830/snapshot/DNOTE-maturity-model-20220826.html
Estimated publication date: 2022-08-30

# Abstract

The W3C Accessibility Maturity Model is a guide for organizations to evaluate and improve their business processes to produce digital products that are accessible to people with disabilities. Use of the W3C Accessibility Maturity Model will provide organizations informative guidance (guidance that is not normative and does not set requirements) on improving accessibility policies, processes, and outcomes.

This document is designed to work for any size of organization, from small to large corporations or government agencies. Additionally, this is intended to be independent of the requirements set forth in relevant technical accessibility standards, such as the Web Content Accessibility Guidelines (WCAG).

# Status of the Document

This document was published by the [Accessible Platform Architectures Working Group](https://www.w3.org/groups/wg/apa) as a Group Draft Note using the [Note track](https://www.w3.org/2021/Process-20211102/#recs-and-notes).
Group Draft Notes are not endorsed by W3C nor its Members.
This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.
The [W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy/) does not carry any licensing requirements or commitments on this document.
This document is governed by the [2 November 2021 W3C Process Document](https://www.w3.org/2021/Process-20211102/).

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-apa-admin/2022Aug/0020.html

# Is it intended to be a W3C Statement?

no

**Comment by plehegar** [comment]
Approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/DNOTE-maturity-model-20220906/
