### ISSUE TITLE
CR Request for WebXR Augmented Reality Module - Level 1

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#448]
# Document title, URLs, estimated publication date
WebXR Augmented Reality Module - Level 1
https://www.w3.org/TR/webxr-ar-module-1/
2022-09-06

# Abstract
The WebXR Augmented Reality module expands the [WebXR Device API](https://www.w3.org/TR/webxr/) with the functionality available on AR hardware.

# Status
https://www.w3.org/TR/webxr-ar-module-1/#sotd

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-immersive-web-wg/2022Jan/0010.html

# Changes
https://www.w3.org/TR/webxr-ar-module-1/#changes-from-20191010 (from FPWD to now)

# Requirements satisfied
yes

# Dependencies met (or not)
yes (linking to WebXR Device API)

# Wide Review
* I18N review https://github.com/w3c/i18n-request/issues/182
* TAG review https://github.com/w3ctag/design-reviews/issues/462
* Privacy review https://github.com/w3cping/privacy-request/issues/91
* Accessibility review https://github.com/w3c/a11y-request/issues/32
* Security review https://github.com/w3c/security-request/issues/31

# Issues addressed
https://github.com/immersive-web/webxr-ar-module/issues

# Formal Objections
none

# Implementation
https://wpt.fyi/results/webxr/ar-module?label=experimental&label=master&aligned

# Patent disclosures
https://www.w3.org/groups/wg/immersive-web/ipr

**Comment by rekliner** [comment]
I'm excited to see this enter CR phase so soon, browsers will not be far behind.

**Comment by plehegar** [comment]
[Group decision](https://lists.w3.org/Archives/Public/public-immersive-web-wg/2022Feb/0005.html) to move forward.

**Comment by plehegar** [comment]
[Normative references](https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fwww.w3.org%2FTR%2Fwebxr-ar-module-1%2F)

**Comment by swickr** [comment]
The TAG review appears to have been done shortly after FPWD and before the addition of XRInteractionMode  and first person observer view.  Please confirm with the TAG [via @ylafon] if the TAG wants to take another look.

I do not see CR Exit criteria documented; that needs to be added.  We also noticed that the CR of WebXR Device API is also missing CR Exit criteria (we failed to notice this at that time); where are those?

I note that Security Review w3c/security-request/issues/31 has been open since 27 May.  Unless significant security issues arise before the above issues are addressed, I will permit this to advance to CR and expect security review to be completed during CR.

**Comment by ylafon** [comment]
> The TAG review appears to have been done shortly after FPWD and before the addition of XRInteractionMode and first person observer view. Please confirm with the TAG [via @ylafon] if the TAG wants to take another look.
> 
Ideally, send a request to the TAG along with the list of changes since the FPWD so that the TAG can evaluate quickly the request.
Thanks

**Comment by himorin** [comment]
Delta TAG review completed, https://github.com/w3ctag/design-reviews/issues/769
asking for transition.

**Comment by himorin** [comment]
> I do not see CR Exit criteria documented; that needs to be added. We also noticed that the CR of WebXR Device API is also missing CR Exit criteria (we failed to notice this at that time); where are those?

CR exit text is added/merged at https://github.com/tabatkins/bikeshed-boilerplate/pull/28#event-7684109954
not yet propagated to WebXR Device API /TR/ one (will be updated via next GHAction, or by manual update...)

**Comment by swickr** [comment]
Transition approved.

**Comment by himorin** [comment]
published.
https://www.w3.org/TR/2022/CR-webxr-ar-module-1-20221101/
