### ISSUE TITLE
CR Request for WebXR Gamepads Module - Level 1

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#449]
# Document title, URLs, estimated publication date
WebXR Gamepads Module - Level 1
https://www.w3.org/TR/webxr-gamepads-module-1/
2022-09-06 (if HR with no reply is resolved)

# Abstract
This specification module describes support for accessing button, trigger, thumbstick, and touchpad data associated with virtual reality (VR) and augmented reality (AR) devices on the Web.

# Status
https://www.w3.org/TR/webxr-gamepads-module-1/#sotd

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-immersive-web-wg/2022Jan/0010.html

# Changes
https://www.w3.org/TR/webxr-gamepads-module-1/#changes-from-20191010 (from FPWD to now)

# Requirements satisfied
yes

# Dependencies met (or not)
yes

# Wide Review
* I18N review: https://github.com/w3c/i18n-request/issues/181
* TAG review https://github.com/w3ctag/design-reviews/issues/430
* Privacy review https://github.com/w3cping/privacy-request/issues/89
* Accessibility review: https://github.com/w3c/a11y-request/issues/30 (no reply over 3mo, sent reminder 1mo ago also)
* Security review: https://github.com/w3c/security-request/issues/29

# Issues addressed
https://github.com/immersive-web/webxr-gamepads-module/issues

# Formal Objections
none

# Implementation
https://wpt.fyi/results/webxr/gamepads-module?label=experimental&label=master&aligned&view=subtest

# Patent disclosures
https://www.w3.org/groups/wg/immersive-web/ipr

**Comment by swickr** [comment]
#27 is still open and is labeled tag-needs-resolution. There is an associated PR that isn't merged.  This blocks advancing to CR.

In addition, the TAG review appears to have been done before substantive additions. Please confirm with the TAG [via @ylafon] if the TAG wants to take another look.

This spec refers to physical buttons.  It should have a11y review.

CR Exit criteria will need to be specified.

**Comment by plehegar** [comment]
ping @michael-n-cooper @becka11y @JaninaSajka on this transition request. Can we have eyes on this spec from an accessibility perspective?

**Comment by michael-n-cooper** [comment]
@plehegar APA has been working on a comment and should submit it this week.

**Comment by plehegar** [comment]
waiting https://github.com/w3c/gamepad/pull/158
