### ISSUE TITLE
FPWD Request for Mathematical Markup Language (MathML) Version 4.0

### ISSUE THREAD

**Issue by bert-github** [w3c/transitions#451]
# Document title, URLs, estimated publication date
Title: Mathematical Markup Language (MathML) Version 4.0
Editors' Draft: https://w3c.github.io/mathml/
Proposed URL: https://www.w3.org/TR/mathml4/
Estimated date: 8 September 2022 or 20 September 2022

# Abstract
https://w3c.github.io/mathml/#abstract

# Status
https://w3c.github.io/mathml/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://www.w3.org/mid/CAESRWkDpEd33heKNJMS-ddVW01MeaQbqSfk=EyTxTh84mw8RUg@mail.gmail.com

# Information about implementations known to the Working Group
no information yet (but as much is essentially the same as MathML3, much is expected to work already)

**Comment by plehegar** [comment]
Approved
