### ISSUE TITLE
First Note request for HEVC (H.265) WebCodecs registration

### ISSUE THREAD

**Issue by tidoust** [w3c/transitions#452]
# Document title, URLs, estimated publication date

The Media Working Group would like to publish a new registry entry for the WebCodecs codec registry. This document is to be published as Draft Note:
* [HEVC (H.265) WebCodecs Registration](https://w3c.github.io/webcodecs/hevc_codec_registration.html)

Publication date: after TPAC 2022 publication moratorium.

# Abstract

This registration is entered into the [[webcodecs-codec-registry]](https://w3c.github.io/webcodecs/hevc_codec_registration.html#biblio-webcodecs-codec-registry). It describes, for HEVC (H.265), the (1) fully qualified codec strings, (2) the codec-specific [EncodedVideoChunk](https://w3c.github.io/webcodecs/#encodedvideochunk) [[[internal data]]](https://w3c.github.io/webcodecs/#dom-encodedvideochunk-internal-data-slot) bytes, (3) the [VideoDecoderConfig.description](https://w3c.github.io/webcodecs/#dom-videodecoderconfig-description) bytes, (4) the values of [EncodedVideoChunk](https://w3c.github.io/webcodecs/#encodedvideochunk) [[[type]]](https://w3c.github.io/webcodecs/#dom-encodedvideochunk-type-slot), and (5) the codec-specific extensions to [VideoEncoderConfig](https://w3c.github.io/webcodecs/#dictdef-videoencoderconfig).

The registration is not intended to include any information on whether a codec format is encumbered by intellectual property claims. Implementers and authors are advised to seek appropriate legal counsel in this matter if they intend to implement or use a specific codec format. Implementers of WebCodecs are not required to support the HEVC / H.265 codec.

This registration is non-normative.

# Status of the Document

Same as the one used in other WebCodecs registrations, e.g. see the [SOTD of the VP9 WebCodecs Registration](https://www.w3.org/TR/webcodecs-vp9-codec-registration/#status).

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-media-wg/2022Jul/0008.html

# Is it intended to be a W3C Statement?

No

**Comment by plehegar** [comment]
Approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/DNOTE-webcodecs-hevc-codec-registration-20220927/
