### ISSUE TITLE
CR Snapshot Update Request for Time Ontology in OWL

### ISSUE THREAD

**Issue by lvdbrink** [w3c/transitions#454]
# Document URLs
Current candidate rec: https://www.w3.org/TR/2020/CR-owl-time-20200326/

Candidate rec we want to publish: https://w3c.github.io/sdw/time/

# Link to group's decision to request transition
[[Call for consensus]](https://lists.w3.org/Archives/Public/public-sdwig/2021Jun/0008.html)

# Link to previous Candidate Recommendation transition or update request
[[Issue 228]](https://github.com/w3c/transitions/issues/228)

# Substantive changes
The proposed updated version has three changes:
1. New [Section 6 - IANA Considerations](https://w3c.github.io/sdw/time/#iana-links), to support the registration of link relations in https://www.iana.org/assignments/link-relations/link-relations.xhtml
2. Three additional time-unit individuals for [Decade, Century and Millenium](https://raw.githack.com/w3c/sdw/issue1261/time/index.html#Individuals)
3. Improvements to textual definitions of [`before`](https://w3c.github.io/sdw/time/#time:before) and [`after`](https://w3c.github.io/sdw/time/#time:after)

# Any changes in requirements?
None

# Wide Review of substantive changes
[[Clarify the intended directionality of time:before and time:after]](https://github.com/w3c/sdw/issues/1241)

# Issues status
[[list of issues]](https://github.com/w3c/sdw/labels/time)

# Formal Objections
none

# Any changes in implementation information?
none

# Deadline for further comments
[TODO: add date or duration]

# Any changes in patent disclosures?
None

See [Requirements for updating a Candidate Recommendation Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot) for further information.

**Comment by plehegar** [comment]
* [HTML diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2020%2FCR-owl-time-20200326%2F&doc2=https%3A%2F%2Fw3c.github.io%2Fsdw%2Ftime%2F)
* [Normative references](https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fw3c.github.io%2Fsdw%2Ftime%2F)
* [Horizontal Review Issues](https://www.w3.org/PM/horizontal/review.html?shortname=owl-time)


Were the horizontal groups given proper opportunities to review the proposed substantive changes? If not, is there a rational to skip those?

**Comment by aphillips** [comment]
I18N did not receive a request to review these changes. A quick look at the diff indicates that some of the examples might need closer review by our WG. I did not see substantive changes that are likely to cause problems for us.

I note that one of our issues (https://github.com/w3c/sdw/issues/888 aka https://github.com/w3c/i18n-activity/issues/404) is not yet fully satisfied, although the host group closed the issue and we didn't review that decision until today.

**Comment by lvdbrink** [comment]
> @tidoust @lvdbrink , I suggest that the document be published as a Candidate Recommendation Draft while we're sorting out the wide review?

Yes, please!

@tidoust is not our team contact anymore. @bert-github could you help us get the horizontal reviews?

**Comment by swickr** [comment]
CR Draft is an appropriate step.  Thanks @plehegar @lvdbrink @bert-github 

You should also update the Working Group link in the SOTD to either https://www.w3.org/groups/wg/sdw or https://www.w3.org/2021/sdw/

**Comment by lvdbrink** [comment]
I updated the Working Group link and also the link to the charter in the SOTD. See https://github.com/w3c/sdw/commit/cbac15a65280b79b83294dcf507bba075cfb5426

@bert-github can you do the next steps in CR Draft charter publication?

**Comment by lvdbrink** [comment]
We now have a [group resolution](https://lists.w3.org/Archives/Public/public-sdw-wg/2022Oct/0005.html) from the current WG. 

As I mentioned before, the working group link and link to the charter have been updated as requested. 

Can we proceed with publication as a CRD?

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/CRD-owl-time-20221115/
