### ISSUE TITLE
FPWD Request for "A Well-Known URL for Changing Passwords"

### ISSUE THREAD

**Issue by mikewest** [w3c/transitions#455]
# Document title, URLs, estimated publication date

"A Well-Known URL for Changing Passwords", https://w3c.github.io/webappsec-change-password-url/, ASAP.

# Abstract

This specification defines a well-known URL that sites can use to make their change password forms discoverable by tools. This simple affordance provides a way for software to help the user find the way to change their password.

# Status

This is a public copy of the editors’ draft. It is provided for discussion only and may change at any moment. Its publication here does not imply endorsement of its contents by W3C. Don’t cite this document other than as work in progress.

Changes to this document may be tracked at https://github.com/w3c/webappsec.

The ([archived](https://lists.w3.org/Archives/Public/public-webappsec/)) public mailing list [public-webappsec@w3.org](mailto:public-webappsec@w3.org?Subject=%5Bchange-password-url%5D%20PUT%20SUBJECT%20HERE) (see [instructions](https://www.w3.org/Mail/Request)) is preferred for discussion of this specification. When sending e-mail, please put the text “change-password-url” in the subject, preferably like this: “[change-password-url] …summary of comment…”

This document was produced by the [Web Application Security Working Group](https://www.w3.org/2011/webappsec/).

This document was produced by a group operating under the [W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy-20170801/). W3C maintains a [public list of any patent disclosures](https://www.w3.org/2004/01/pp-impl/49309/status) made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains [Essential Claim(s)](https://www.w3.org/Consortium/Patent-Policy-20170801/#def-essential) must disclose the information in accordance with [section 6 of the W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy-20170801/#sec-Disclosure).

This document is governed by the [15 September 2020 W3C Process Document](https://www.w3.org/2020/Process-20200915/).

# Is it a delta specification intended to become a W3C Recommendation?

No.

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-webappsec/2020May/0001.html

# Information about implementations known to the Working Group

Implemented in Safari, Chrome, and Firefox, as well as many websites (https://web.dev/change-password-url/#how-it-is-used-in-real-world is an outdated list; it's longer today).

**Comment by plehegar** [comment]
Please, drop "webappsec" from the shortname, since we don't encode group shortnames in /TR URLs.

ie use something along:
* "https://www.w3.org/TR/change-password-url/"
* "https://www.w3.org/TR/well-known-url-change-password/"

**Comment by plehegar** [comment]
Assuming the shortname gets updated, this is approved for publication.

**Comment by hober** [comment]
> Please, drop "webappsec" from the shortname, since we don't encode group shortnames in /TR URLs.

It's not in the short name. Here's what the Bikeshed file declares:

```
Shortname: change-password-url
```

**Comment by plehegar** [comment]
My mistake then. We're all good.

**Comment by sideshowbarker** [comment]
ack — I’ll attempt to get this published in TR today (Thursday) or tomorrow
