### ISSUE TITLE
FPWD Request for Trace Context Level 2

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#458]
# Document title, URLs, estimated publication date

https://w3c.github.io/trace-context/?specStatus=FPWD&publishDate=2022-09-29

# Abstract

This specification defines standard HTTP headers and a value format to propagate context information that enables distributed tracing scenarios. The specification standardizes how context information is sent and modified between services. Context information uniquely identifies individual requests in a distributed system and also defines a means to add and propagate provider-specific context information.

# Status

Publication as a First Public Working Draft does not imply endorsement by W3C and its Members.
This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.
This document was produced by a group operating under the [1 August 2017 W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy-20170801/). W3C maintains a [public list of any patent disclosures](https://www.w3.org/groups/wg/distributed-tracing/ipr) made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains [Essential Claim(s)](https://www.w3.org/Consortium/Patent-Policy-20170801/#def-essential) must disclose the information in accordance with [section 6 of the W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy-20170801/#sec-Disclosure).
This document is governed by the [2 November 2021 W3C Process Document](https://www.w3.org/2021/Process-20211102/).

# Is it a delta specification intended to become a W3C Recommendation?

No

Diff with Level 1:
 https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Ftrace-context-1%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Ftrace-context%2F%3FspecStatus%3DWD%26shortName%3Dfoo

# Link to group's decision to request transition

[[
Meeting: 2022-09-27

Group is in agreement that we are ready to publish FPWD for level 2.
]]
https://docs.google.com/document/d/12AAIbnkt_AH1YjZwUwxirX_7WA7aWOSXpDweCgfqIiQ/edit#heading=h.evmoceg7viif

# Information about implementations known to the Working Group

None

cc @SergeyKanzhelev @kalyanaj

**Comment by swickr** [comment]
Transition approved.  (FPWD)

The tooling behind https://w3c.github.io/trace-context/ isn't currently working; it currently only returns a Glossary with two items.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/WD-trace-context-2-20220929/
