### ISSUE TITLE
FPWD Request for Scroll-linked Animations Level 1

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#460]
# Document title, URLs, estimated publication date
Scroll-linked Animations Level 1
https://www.w3.org/TR/scroll-animations-1/
Thursday?

# Abstract
https://drafts.csswg.org/scroll-animations-1/#abstract

# Status
https://drafts.csswg.org/scroll-animations-1/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://logs.csswg.org/irc.w3.org/css/2022-09-15/#e1503883

# Information about implementations known to the Working Group
prototyping in Blink

**Comment by plehegar** [comment]
https://drafts.csswg.org/scroll-animations-1/ gives me an index of the file system :(  ( @plinss , is it something on the server side?)

**Comment by plehegar** [comment]
Approved

**Comment by xfq** [comment]
> https://drafts.csswg.org/scroll-animations-1/ gives me an index of the file system :( ( @plinss , is it something on the server side?)

Works for me now.

The server status is tracked in https://github.com/w3c/csswg-drafts/issues/6528

**Comment by svgeesus** [comment]
Publication request sent 2022-10-21, expected publication 2022-10-25 after moratorium ends

**Comment by svgeesus** [comment]
[Published 25 Oct 2022](https://www.w3.org/TR/2022/WD-scroll-animations-1-20221025/)
