### ISSUE TITLE
FPWD Request for CSS View Transitions Level 1

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#461]
# Document title, URLs, estimated publication date
CSS View Transitions Level 1
http://www.w3.org/TR/css-view-transitions-1/
Tuesday?

# Abstract
https://drafts.csswg.org/css-shared-element-transitions-1/#abstract

# Status
https://drafts.csswg.org/css-shared-element-transitions-1/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://logs.csswg.org/irc.w3.org/css/2022-09-15/#e1503557

# Information about implementations known to the Working Group
in-progress prototyping in Blink

**Comment by khushalsagar** [comment]
@plehegar friendly ping. Is there anything missing to resolve this?

**Comment by plehegar** [comment]
Approved. I was able to see the draft.

**Comment by svgeesus** [comment]
@khushalsagar There is a publishing moratorium this week, so the document will be published Tues 25 October.

**Comment by svgeesus** [comment]
@khushalsagar you don't seem to have a W3C account, could you [create one](https://www.w3.org/accounts/request) please? Publication checks are failing because you don't have a w3cid. Also, GitHub will flag any edits you make to the spec until you make one, and link it to your GitHub id. Thanks!

**Comment by khushalsagar** [comment]
My W3C account is ksagar and it is linked to this github account. I just verified under Connected Accounts on w3.org. Let me know if there is still an issue.

**Comment by svgeesus** [comment]
Publication request sent 2022-10-21, expected publication 2022-10-25 after moratorium ends

**Comment by svgeesus** [comment]
[Published 25 Oct 2022](https://www.w3.org/TR/2022/WD-css-view-transitions-1-20221025/)
