### ISSUE TITLE
CR Request for Core Accessibility API Mappings 1.2

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/transitions#462]
CR Request for Core-AAM 1.2

# Document title, URLs, estimated publication date
title: Core Accessibility API Mappings 1.2
editors' draft: https://w3c.github.io/core-aam/
tr: https://www.w3.org/TR/core-aam-1.2/
publication date: 11 October 2022

# Abstract
This document describes how user agents should expose semantics of web content languages to accessibility APIs. This helps users with disabilities to obtain and interact with information using assistive technologies. Documenting these mappings promotes interoperable exposure of roles, states, properties, and events implemented by accessibility APIs and helps to ensure that this information appears in a manner consistent with author intent.

This Core Accessibility API Mappings specification defines support that applies across multiple content technologies, including general keyboard navigation support and mapping of general-purpose roles, states, and properties provided in Web content via WAI-ARIA [WAI-ARIA-1.2]. Other Accessibility API Mappings specifications depend on and extend this Core specification for specific technologies, including native technology features and WAI-ARIA extensions. This document updates and will eventually supersede the guidance in the Core Accessibility API Mappings 1.1 [CORE-AAM-1.1] W3C Recommendation. It is part of the WAI-ARIA suite described in the WAI-ARIA Overview.

# Status
This is a Candidate Recommendation of Core-AAM 1.2 by the Accessible Rich Internet Applications Working Group of the Web Accessibility Initiative. The Working Group publishes content here that is ready for inclusion in the implementation report. A history of changes to Core-AAM 1.2 is available in the appendix. Core-AAM is a living standard and future updates will be published as Candidate Recommendation Snapshots.

The Accessible Rich Internet Applications Working Group seeks feedback on any aspect of the specification. When submitting feedback, please consider issues in the context of the companion documents. To comment, file an issue in the W3C Core-AAM GitHub repository. If this is not feasible, send email to public-aria@w3.org (comment archive). In-progress updates to the document may be viewed in the publicly visible editors' draft.

This document was published by the Accessible Rich Internet Applications Working Group as a Candidate Recommendation Snapshot using the Recommendation track.

Publication as a Candidate Recommendation does not imply endorsement by W3C and its Members. A Candidate Recommendation Snapshot has received wide review, is intended to gather implementation experience, and has commitments from Working Group members to royalty-free licensing for implementations.

This Candidate Recommendation is not expected to advance to Proposed Recommendation any earlier than 11 November 2022.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 2 November 2021 W3C Process Document. 

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-aria-admin/2022Oct/0000.html

# Changes
https://w3c.github.io/core-aam/#changelog

# Requirements satisfied
The ARIA WG has used a [workflow](https://www.w3.org/WAI/ARIA/workflow) that involves annual releases. Features to add in these annual releases are described in the [roadmap](https://www.w3.org/WAI/ARIA/roadmap) and this version represents incremental progress towards that.

# Dependencies met (or not)
Dependencies have not changed. The WG has engaged with most of the groups listed in the [ARIA WG charter](https://www.w3.org/2022/02/aria-charter).

# Wide Review
Horizontal reviews are tracked at https://github.com/w3c/core-aam/issues/116. Accessibility, Privacy, and Security did not provide feedback, and I18N filed a comment which was addressed. TAG review was not sought because there have been no structural changes to Core-AAM since the previous review of ARIA: https://github.com/w3ctag/design-reviews/issues/586.

# Issues addressed
https://github.com/w3c/core-aam/issues/

Core-AAM is becoming an evergreen specification, so some issues have not yet been addressed and may relate to ARIA features that are not yet complete.

# Formal Objections
There are no Formal Objections.

# Implementation
https://w3c.github.io/test-results/core-aam-1.2/

Implementations are ready, but the test suite results tracking is behind and will be updated soon. We are also exploring incorporating test results directly into updates of the evergreen spec.

# Patent disclosures
https://www.w3.org/groups/wg/aria/ipr#disclosures

**Comment by plehegar** [comment]
One tweak for the SOTD, since the spec is not expected to reach PR:
[[
This Candidate Recommendation is not expected to advance to Proposed Recommendation any earlier than 11 November 2022.
]]
should read:
[[
Comments are welcome at any time but most especially before 11 November 2022.
]]

**Comment by michael-n-cooper** [comment]
@plehegar the SOTD text you mention is generated by Respec. I tried removing the "crEnd" config but Respec complained. While this could be updated by manual publication, it would be better to get respec to output the text you want.

I did change the date to 2 Dec, in the publication branch.

@swickr we have added privacy and security sections. I think this is ready for re-review.

**Comment by swickr** [comment]
Transition approved.

**Comment by michael-n-cooper** [comment]
[Published](https://www.w3.org/TR/2022/CR-core-aam-1.2-20221122/)
