### ISSUE TITLE
FPWD Request for PNG 3rd Edition

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#464]
# Document title, URLs, estimated publication date
Portable Network Graphics (PNG) Specification (Third Edition)
https://w3c.github.io/PNG-spec/
Tues 25 Oct 2022

# Abstract
This document describes PNG (Portable Network Graphics), an extensible file format for the [lossless](https://w3c.github.io/PNG-spec/#dfn-lossless), portable, well-compressed storage of static and animated raster images. PNG provides a patent-free replacement for GIF and can also replace many common uses of TIFF. Indexed-colour, greyscale, and [truecolour](https://w3c.github.io/PNG-spec/#3truecolour) images are supported, plus an optional alpha channel. Sample depths range from 1 to 16 bits.

PNG is designed to work well in online viewing applications, such as the World Wide Web, so it is fully streamable with a progressive display option. PNG is robust, providing both full file integrity checking and simple detection of common transmission errors. Also, PNG can store colour space data for improved colour matching on heterogeneous platforms.

This specification defines two Internet Media Types, image/png and image/apng.
https://w3c.github.io/PNG-spec/#abstract

# Status
https://w3c.github.io/PNG-spec/#sotd (as ED)

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
 - https://github.com/w3c/PNG-spec/issues/219

# Information about implementations known to the Working Group
Widely implemented since 1995

**Comment by svgeesus** [comment]
Publication request sent 2022-10-17 pending approval, expected publication 2022-10-25 after moratorium ends

**Comment by svgeesus** [comment]
Shortname renamed from `png` to `png-3` at request of webmaster.

**Comment by svgeesus** [comment]
ping @plehegar

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
[Published 25 Oct 2022](https://www.w3.org/TR/2022/WD-png-3-20221025/)

[Home page news](https://www.w3.org/blog/news/archives/9718)
