### ISSUE TITLE
First Note request for <Collaboration Tools Accessibility User Requirements>

### ISSUE THREAD

**Issue by ruoxiran** [w3c/transitions#466]
# Document title, URLs, estimated publication date
Title: Collaboration Tools Accessibility User Requirements
URL(I will put the document to /TR after transition): https://raw.githack.com/w3c/ctaur/FPWD-2022/DNOTE-ctaur-20221027.html
Estimated publication date: 2022-11-01

# Abstract

https://raw.githack.com/w3c/ctaur/FPWD-2022/DNOTE-ctaur-20221027.html#abstract

# Status of the Document

https://raw.githack.com/w3c/ctaur/FPWD-2022/DNOTE-ctaur-20221027.html#sotd

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-apa-admin/2022Oct/0023.html

# Is it intended to be a W3C Statement?
no

**Comment by ruoxiran** [comment]
hi @plehegar, is any progress on this transition request?

**Comment by plehegar** [comment]
Approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2022/DNOTE-ctaur-20221108/
