### ISSUE TITLE
CR Request for Web of Things (WoT) Thing Description 1.1

### ISSUE THREAD

**Issue by sebastiankb** [w3c/transitions#467]
# Document title, URLs, estimated publication date
Web of Things (WoT) Thing Description 1.1
Editor draft: https://w3c.github.io/wot-thing-description/
[Static CR snapshot: https://github.com/w3c/wot-thing-description/blob/main/publication/ver11/5-cr/Overview.html](https://github.com/w3c/wot-thing-description/blob/main/publication/ver11/5-cr/Overview.html)
Publication as soon as possible after October 26 (actual date needs to be updated in document)

# Abstract
 This document describes a formal information model and a common representation for a Web of Things (WoT) Thing Description 1.1. A Thing Description describes the metadata and interfaces of Things, where a Thing is an abstraction of a physical or virtual entity that provides interactions to and participates in the Web of Things. Thing Descriptions provide a set of interactions based on a small vocabulary that makes it possible both to integrate diverse devices and to allow diverse applications to interoperate. Thing Descriptions, by default, are encoded in a JSON format that also allows JSON-LD processing. The latter provides a powerful foundation to represent knowledge about Things in a machine-understandable way. A Thing Description instance can be hosted by the Thing itself or hosted externally when a Thing has resource restrictions (e.g., limited memory space) or when a Web of Things-compatible legacy device is retrofitted with a Thing Description. Furthermore, this document introduces the Thing Model, which allows authors to describe only the model or class of an Internet of Things (IoT) entity. Thing Models can be seen as a template for Thing Description instances, but with reduced constraints such as no or few requirements for specific communication metadata.

This specification describes a superset of the features defined in Thing Description 1.0. Unless otherwise specified, documents created with version 1.0 of this specification remain compatible with Thing Description 1.1. 

# Status
[Status of the document (https://w3c.github.io/wot-thing-description/#sotd](https://w3c.github.io/wot-thing-description/#sotd)

# Link to group's decision to request transition
[Resolution to request CR transition for WoT Thing Description 1.1 in WG call October 26.](https://www.w3.org/2022/10/26-wot-minutes.html#t08)

# Changes
Changes from 03 August 2022 Working Draft
- Status of the document Section: add list of at-risk features
- All TD examples: fix highlighting problems and improve formatting
- add security scheme auto, provide definition what "satisfying" a securityDefinition means and new wording of assertion (td-security-no-secrets) in Section 5.3.3.1
- Section 6.3.9.4 additionalResponses has been newly added.
- remove TD Context Extensions CoAP example in Section 7.2
- remove reference to Binding Document in assertion (bindings-requirements-scheme) in Section 8.3
- Chapter 9 Thing Model moved before 10. Security Considerations and 11. Privacy Consideration
- tm:required is replaced by tm:optional in Section 11.3.4
- Section 12.3.2: add CoAP Content-Format ID for Thing Model

# Requirements satisfied
Requirements laid out in the WG charter for this deliverable were satisfied except for TD canonization and signing, which was deferred to future work.

# Dependencies met (or not)
none

# Wide Review

- Wide review was requested from Accessibility, Internationalization, Security, Privacy, and TAG and all issues raised addressed (although in some cases we have not yet gotten confirmation that the issues were addressed from the reviewers): 
  - https://github.com/w3ctag/design-reviews/issues/715
  - https://github.com/w3cping/privacy-request/issues/84
  - https://github.com/w3c/security-request/issues/26
  - https://github.com/w3c/a11y-request/issues/21
  - https://github.com/w3c/i18n-request/issues/171
  
- The Societal Impact questionnaire has not yet been filled in but will be completed prior to PR.

# Issues addressed

- General issue tracker: https://github.com/w3c/wot-thing-description/issues
- Issues marked [resolve by PR](https://github.com/w3c/wot-thing-description/labels/by%20PR%20transition) will be addressed prior to PR transition. These are editorial.
- All other open issues will be deferred to future work (e.g. in a new charter) or some closed (since issue was solved)

# Formal Objections
None at present.

# Implementation
A DRAFT implementation report is available at https://w3c.github.io/wot-thing-description/testing/report11.html. This will be updated during the CR review period to address
at-risk items and add testimonials.

# Patent disclosures
None.

**Comment by plehegar** [comment]
* [Horizontal issues](https://www.w3.org/PM/horizontal/review.html?shortname=wot-thing-description)
* [Normative references](https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fw3c.github.io%2Fwot-thing-description%2F)

**Comment by swickr** [comment]
CR Exit criteria are missing.

**Comment by sebastiankb** [comment]
CR Exit criteria text is now provided by the merged PR https://github.com/w3c/wot-thing-description/pull/1736

**Comment by sebastiankb** [comment]
@swickr are the some news about the CR publication?

**Comment by plehegar** [comment]
Approved.

Thank you for updating the CR exit criteria.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2023/CR-wot-thing-description11-20230119/
