### ISSUE TITLE
[TTWG] CR transition for IMSC 1.1

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#47]
# Document title, URLs, estimated publication date

TTML Profiles for Internet Media Subtitles and Captions 1.1
https://rawgit.com/w3c/imsc/IMSC1.1-CR/imsc1/spec/ttml-ww-profiles.html
03 May 2018
# Abstract
https://rawgit.com/w3c/imsc/IMSC1.1-CR/imsc1/spec/ttml-ww-profiles.html#abstract-0

# Status
https://rawgit.com/w3c/imsc/IMSC1.1-CR/imsc1/spec/ttml-ww-profiles.html#status-of-this-document
# Decision
https://www.w3.org/2018/03/22-tt-minutes.html#resolution01
https://www.w3.org/2018/04/05-tt-minutes.html#item04

# Changes

* Clarify the use of recommended character sets (https://github.com/w3c/imsc/issues/236)
* Update feature list per TTML2 CR (https://github.com/w3c/imsc/issues/341)
* Refactor profile signaling provisions (https://github.com/w3c/imsc/issues/331)
* Remove recommendation against TAB characters per TTML2 semantics (https://github.com/w3c/imsc/issues/353)
* Clarify fillLineGap semantics when applied to successive <p> elements (https://github.com/w3c/imsc/issues/263)
* Clarify forcedDisplay semantics (https://github.com/w3c/imsc/issues/284)
* Clarify handling of foreign elements and attributes (https://github.com/w3c/imsc/issues/213)
* Clarify style resolution procedure (https://github.com/w3c/imsc/issues/300)
* Remove recommendations on time expressions and ttp:cellResolution (https://github.com/w3c/imsc/issues/329)
* Remove ttp:version and fix examples (https://github.com/w3c/imsc/issues/261)
* Prohibit simultaneous tts:origin and tts:position (https://github.com/w3c/imsc/issues/289)
* Remove background-color feature per removal in TTML2 (https://github.com/w3c/imsc/issues/255)
* Remove rubyOverhang related features (https://github.com/w3c/imsc/issues/286 and https://github.com/w3c/imsc/issues/285)
* Deprecate ittp:aspectRatio in favor of ttp:displayAspectRatio (https://github.com/w3c/imsc/issues/273)
* Deprecate ittm:altText in favor of altText named metadata item (https://github.com/w3c/imsc/issues/274)
* Deprecate #progressivelyDecodable (https://github.com/w3c/imsc/issues/272) 
* Deprecates #writingMode-horizontal-rl in Image Profile (https://github.com/w3c/imsc/issues/147)
* Updated profile signaling and resolution to match TTML2 semantics (https://github.com/w3c/imsc/issues/3, https://github.com/w3c/imsc/issues/124 and https://github.com/w3c/imsc/issues/125)

from
  https://rawgit.com/w3c/imsc/IMSC1.1-CR/imsc1/spec/ttml-ww-profiles.html#substantive-changes-summary

Diff:
 https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2017%2FWD-ttml-imsc1.1-20171017%2F&doc2=https%3A%2F%2Frawgit.com%2Fw3c%2Fimsc%2FIMSC1.1-CR%2Fimsc1%2Fspec%2Fttml-ww-profiles.html

# Requirements satisfied

No requirements document.

# Dependencies met (or not)

W3C Groups:
  https://lists.w3.org/Archives/Public/public-tt/2017Oct/0106.html
  https://lists.w3.org/Archives/Public/public-apa/2018Jan/0042.html
EBU
 https://lists.w3.org/Archives/Public/public-tt/2018Jan/0044.html

References:
https://labs.w3.org/normative-references/check?url=https%3A%2F%2Frawgit.com%2Fw3c%2Fimsc%2FIMSC1.1-CR%2Fimsc1%2Fspec%2Fttml-ww-profiles.html

# Wide Review

https://github.com/w3c/imsc/issues?utf8=%E2%9C%93&q=label%3Aimsc1.1

# Issues addressed

Issues were addressed at:
https://github.com/w3c/imsc/issues?utf8=%E2%9C%93&q=label%3Aimsc1.1

# Formal Objections

None

# Implementation

For this specification to exit the CR stage, at least 2 independent implementations of every feature defined in this specification but not already present in either [TTML2] or [ttml-imsc1.0.1] need to be documented in the implementation report. The Working Group does not require that implementations are publicly available but encourages them to be so.

The Working Group has not identified features "at risk" for this specification.

No preliminary implementation report.

This Candidate Recommendation is expected to advance to Proposed Recommendation no earlier than 31 May 2018. 

# Patent disclosures

None

https://www.w3.org/2004/01/pp-impl/34314/status

**Comment by plehegar** [comment]
Response to APA comments: http://www.w3.org/2018/02/28-apa-minutes.html#item02

**Comment by swickr** [comment]
Approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2018/CR-ttml-imsc1.1-20180503/
