### ISSUE TITLE
CR Snapshot Update Request for CSS Values and Units L3

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#470]
# Document URLs
https://www.w3.org/TR/css-values-3/
https://drafts.csswg.org/css-values-3/

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/www-style/2022Oct/0022.html

# Link to previous Candidate Recommendation transition or update request
[[TODO: add link]](https://github.com/w3c/transitions/issues/136)

# Substantive changes
[[TODO: focus on substantive changes]](https://drafts.csswg.org/css-values-3/#changes)

# Any changes in requirements?
none

# Wide Review of substantive changes
Other than dropping the at-risk feature, changes were a handful of minor fixes and clarifications.

# Issues status
All closed accepted or retracted, except one about viewport units that's still under discussion.

# Formal Objections
None

# Any changes in implementation information?
Not really

# Deadline for further comments
No deadline, but everything is implemented so we can't make many changes

# Any changes in patent disclosures?
None

See [Requirements for updating a Candidate Recommendation Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot) for further information.

**Comment by plehegar** [comment]
previous CR request: https://github.com/w3c/transitions/issues/115

**Comment by plehegar** [comment]
previous versions links in https://drafts.csswg.org/css-values-3/ are wrong. Doesn't mention the 2019 CR version. Please change that to use history link instead.

**Comment by plehegar** [comment]
substantive changes: https://drafts.csswg.org/css-values-3/#changes

**Comment by plehegar** [comment]
No needs-resolution issues in https://www.w3.org/PM/horizontal/review.html?shortname=css-values

**Comment by swickr** [comment]
Transition approved.

**Comment by svgeesus** [comment]
Publication requested 21 Nov, expected 22 Nov

**Comment by svgeesus** [comment]
Publication requested 29 Nov expected 1 Dec

**Comment by svgeesus** [comment]
[Published 01 Dec 2022](https://www.w3.org/TR/2022/CR-css-values-3-20221201/)
