### ISSUE TITLE
First Note request for CSS Snapshot 2022

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#471]
# Document title, URLs, estimated publication date

CSS Snapshot 2022
https://www.w3.org/TR/css-2022/
https://www.w3.org/TR/CSS/

# Abstract

https://drafts.csswg.org/css-2022/#abstract

# Status of the Document

https://drafts.csswg.org/css-2022/#sotd

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/www-style/2022Aug/0006.html

# Is it intended to be a W3C Statement?

No

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Publication request sent 21 Nov, expected 22 Nov
