### ISSUE TITLE
Add WG abbreviation to issue template

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#472]
It would be helpful, I think, if we added something like `(WGABBR)` to the issue templates, to make it easy and reliable to search for e.g. all the issues from CSSWG.

**Comment by plehegar** [comment]
The transition issue notifier should now add those labels automatically. It's looking for the github repo associated with the document so, if it reaches a wrong conclusion, it will put the wrong label. this could be fixed manually after the fact.

So, you can now seatrch per WG, eg
https://github.com/w3c/transitions/issues?q=is%3Aissue+is%3Aclosed+label%3Awg%2Fi18n-core
