### ISSUE TITLE
FPWD Request for RDF Dataset Canonicalization

### ISSUE THREAD

**Issue by pchampin** [w3c/transitions#473]
# Document title, URLs, estimated publication date
RDF Dataset Canonicalization
https://w3c.github.io/rdf-canon/spec/
Publication date: 2022-11-17

# Abstract
RDF [[RDF11-CONCEPTS](https://w3c.github.io/rdf-canon/spec/#bib-rdf11-concepts)] describes a graph-based data model for making claims about the world and provides the foundation for reasoning upon that graph of information. At times, it becomes necessary to compare the differences between sets of graphs, digitally sign them, or generate short identifiers for graphs via hashing algorithms. This document outlines an algorithm for normalizing [RDF datasets](https://w3c.github.io/rdf-canon/spec/#dfn-rdf-dataset) such that these operations can be performed.

# Status
https://w3c.github.io/rdf-canon/spec/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://www.w3.org/2022/11/09-rch-minutes.html#r03
Note that the URL in that resolution is different from the URL at the top of this transition request,
because there was a further resolution to rename the repo from `rch-rdc` to `rdf-canon`:
https://www.w3.org/2022/11/09-rch-minutes.html#r04

# Information about implementations known to the Working Group
URDNA2015 is implemented in
* [jsonld.js](https://github.com/digitalbazaar/jsonld.js/#user-content-canonize)
* [ruby-rdf](https://github.com/ruby-rdf/rdf-normalize)

**Comment by plehegar** [comment]
Approved

**Comment by gkellogg** [comment]
Give me a publication date, and I'll re-generate the snapshot for that date. It was originally generated for Nov 17 publication.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2023/WD-rdf-canon-20230205/
