### ISSUE TITLE
CR Request for Web of Things (WoT) Architecture 1.1

### ISSUE THREAD

**Issue by sebastiankb** [w3c/transitions#474]
# Document title, URLs, estimated publication date
Web of Things (WoT) Architecture 1.1
Editor draft: https://w3c.github.io/wot-architecture/
[Static CR snapshot: https://github.com/w3c/wot-architecture/blob/main/publication/ver11/3-cr/Overview.html](https://github.com/w3c/wot-architecture/blob/main/publication/ver11/3-cr/Overview.html)
Publication as soon as possible after November 2 (actual date needs to be updated in document)

# Abstract
The W3C Web of Things (WoT) enables interoperability across IoT platforms and application domains. The goal of the WoT is to preserve and complement existing IoT standards and solutions. The W3C WoT architecture is designed to describe what exists, and only prescribes new mechanisms when necessary.

This WoT Architecture specification describes the abstract architecture for the W3C Web of Things. This abstract architecture is based on requirements that were derived from use cases for multiple application domains. Several modular building blocks were identified whose detailed specifications are given in other documents. This document describes how these building blocks are related and work together. The WoT abstract architecture defines a basic conceptual framework that can be mapped onto a variety of concrete deployment scenarios, several examples of which are given. However, the abstract architecture described in this specification does not itself define concrete mechanisms or prescribe any concrete implementation. 

# Status
[Status of the document (https://w3c.github.io/wot-architecture/#sotd](https://w3c.github.io/wot-architecture/#sotd)

# Link to group's decision to request transition
[Resolution to request CR transition for Web of Things (WoT) Architecture 1.1 in WG call November 2.](https://www.w3.org/2022/11/02-wot-minutes.html#t11)

# Changes
Changes from the WD published September 7, 2022
- Modify [Section 7, WoT Building Blocks](https://w3c.github.io/wot-architecture/#sec-wot-building-blocks) so that it is informative.
- Add terminology entries for Profile, System, and Directory.
- Updates to affiliation of Matthias Kovatsch (as a former editor).
- Add/update references to the WoT Use Cases and Requirements [[WOT-USE-CASES-REQUIREMENTS](https://w3c.github.io/wot-architecture/#bib-wot-use-cases-requirements)] document.

# Requirements satisfied
Requirements laid out in the WG charter for this deliverable were satisfied.

# Dependencies met (or not)
none

# Wide Review

- Wide review was requested from Accessibility, Internationalization, Security, Privacy, and TAG and all issues raised addressed (although in some cases we have not yet gotten confirmation that the issues were addressed from the reviewers): 
  - https://github.com/w3ctag/design-reviews/issues/736
  - https://github.com/w3cping/privacy-request/issues/86
  - https://github.com/w3c/security-request/issues/27
  - https://github.com/w3c/a11y-request/issues/23
  - https://github.com/w3c/i18n-request/issues/178
  
- The Societal Impact questionnaire has not yet been filled in but will be completed prior to PR.

# Issues addressed

- General issue tracker: https://github.com/w3c/wot-architecture/issues
- Issues marked [resolve by PR](https://github.com/w3c/wot-architecture/issues?q=is%3Aissue+is%3Aopen+label%3A%22by+PR+transition%22) will be addressed prior to PR transition. These are editorial.
- All other open issues will be deferred to future work (e.g. in a new charter) or some closed (since issue was solved)

# Formal Objections
None at present.

# Implementation
A DRAFT implementation report is available at https://w3c.github.io/wot-architecture/testing/report11.html. This will be updated during the CR review period to address
at-risk items and add testimonials.

# Patent disclosures
None.

**Comment by swickr** [comment]
We note that [#809](https://github.com/w3c/wot-architecture/issues/809) is still open and this causes confusion.  For example, what is the status of and relationship to [wot-binding-templates](https://www.w3.org/TR/wot-binding-templates/)?  Is that a normative dependency? If that WG Note is a vocabulary definition then consider supporting it via a Registry.

It appears that the Security and Privacy review was done prior to the addition of Trusted Environment.  Was another review done after these changes?

**Comment by mlagally** [comment]
@sebastiankb 
Please fix the estimated publication date, it states Oct 26th which does not reflect the actual time line.

**Comment by sebastiankb** [comment]
@mlagally done

**Comment by mmccool** [comment]
@swickr regarding the following:

> It appears that the Security and Privacy review was done prior to the addition of Trusted Environment. Was another review done after these changes?

I looked at the PR timeline and it seems only the formal *definition* of this term was added post-review to the Terminology section.  The term however was already in use under the Security Considerations section for the version that was reviewed.

Here is the relevant PR: https://github.com/w3c/wot-architecture/pull/781

So to resolve this we would like to ask someone to (ideally, quickly) review (just) the new definition, e.g. the above PR.  How can we do that?

**Comment by swickr** [comment]
Thank you for pointing to https://github.com/w3c/wot-architecture/pull/781 @mmccool.  The full status of the security review is not clear but I concur that the trusted environment concept was present in the May draft.

**Comment by mmccool** [comment]
@swickr I also noticed that the issue calling for a security review is still open.  It would be good to get formal closure on this including the above terminology definition.  See the comment I added here: https://github.com/w3c/security-request/issues/27#issuecomment-1329080096

**Comment by plehegar** [comment]
After checking with @samuelweiler , the security review questions have been resolved.

At this point, you may want to close [#809](https://github.com/w3c/wot-architecture/issues/809) if you're done fixing the references.

Approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2023/CR-wot-architecture11-20230119/
