### ISSUE TITLE
FPWD Request for JSON Web Signature 2020

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#475]
# Document title, URLs, estimated publication date
- JSON Web Signature 2020
- https://www.w3.org/TR/2022/WD-vc-jws-2020-20221208/
- 2022-12-08

# Abstract

https://www.w3.org/TR/2022/WD-vc-jws-2020-20221208/#abstract

# Status

https://www.w3.org/TR/2022/WD-vc-jws-2020-20221208/#sotd

# Is it a delta specification intended to become a W3C Recommendation?

No

# Link to group's decision to request transition

https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-10-26-vcwg#resolution2

# Information about implementations known to the Working Group

Has some implementations based on the 1st version of VC

---

CC @brentzundel @Sakurann @OR13 @selfissued

**Comment by plehegar** [comment]
Approved

**Comment by iherman** [comment]
Publication request sent: https://lists.w3.org/Archives/Team/webreq/2022Dec/0000.html

**Comment by iherman** [comment]
Document published.
