### ISSUE TITLE
CR Request for <WAI-Adapt: Symbols Module>

### ISSUE THREAD

**Issue by ruoxiran** [w3c/transitions#478]
NOTE: This transition request is related to the previous request issue #443, we had a discussion during TPAC 2022 with TAG, and the primary take-away was that we had too many, seemingly unrelated attributes in the CR draft we'd put forward. we also recall hearing that the AAC symbols attribute was the most "architecturally sound" of all our proposed attributes. so we have dropped all attributes from our proposed CR except symbol support to fulfill the Wide Review.

# Document title, URLs, estimated publication date
title: WAI-Adapt: Symbols Module  (we changed the document name from WAI-Adapt: Content Module to WAI-Adapt: Symbols Module.)
URL: https://raw.githack.com/w3c/adapt/CR-symbols/snapshots/symbols/Overview.html
estimated publication date: 2022-12-20

# Abstract
https://raw.githack.com/w3c/adapt/CR-symbols/snapshots/symbols/Overview.html#abstract

# Status
https://raw.githack.com/w3c/adapt/CR-symbols/snapshots/symbols/Overview.html#sotd

# Link to group's decision to request transition

[
https://www.w3.org/2022/12/07-apa-minutes.html#r01
https://lists.w3.org/Archives/Public/public-apa-admin/2022Jul/0022.html
]

# Changes
we have dropped all attributes from our proposed CR #443 except symbol support.
we changed the document name from WAI-Adapt: Content Module to WAI-Adapt: Symbols Module.
we changed the short name from adapt-content to adapt-symbols.
aac-registry #477 will be normatively referenced for the BCI index.
Please find other changes in the adapt GitHub commits: https://github.com/w3c/adapt/commits/main/symbols

# Requirements satisfied
[we have published a draft note for requirements of the document, sections 2.1 to 2.2 related to this publication. https://www.w3.org/TR/adapt-requirements/]

# Dependencies met (or not)
[
https://www.w3.org/2021/08/apa-wg-charter#coordination
this is the dependencies met for the whole APA WG, with regard to WAI-Adapt TF, we had liaisons with i18n 
, WebFonts and Epub.
]

# Wide Review
[
TAG:  we had a discussion during TPAC 2022, the primary take-away was that we had too many, seemingly unrelated attributes in the CR draft we'd put forward. we also recall hearing that the AAC symbols attribute was the most "architecturally sound" of all our proposed attributes. so we have dropped all attributes from our proposed CR except symbol support. See also APA/TAG during TPAC2022: [Unblocking the WAI-Adapt Content Module 1.0 CR](https://www.w3.org/2022/09/13-apa-minutes.html#t01). TAG issue archive in [mailing list](https://lists.w3.org/Archives/Group/group-apa-chairs/2022Nov/0066.html), and tracked by APA at: https://github.com/w3c/adapt/issues/234

i18n: closed, https://github.com/https://github.com/w3c/i18n-activity/issues/1545
a11y: closed, https://github.com/https://github.com/w3c/a11y-request/issues/15
Privacy and security: closed the wide review issue at: https://github.com/https://github.com/w3c/adapt/issues/131. But the relevant one at PING is still open, https://github.com/https://github.com/w3cping/tracking-issues/issues/245, I have confirmed with PLH last transition, and he mentioned we can continue the CR process. The document had a Privacy and Security Consideration section at: https://raw.githack.com/w3c/adapt/CR-symbols/snapshots/symbols/Overview.html#privacy-and-security-considerations

there is also a web fonts review request from PLH at: https://lists.w3.org/Archives/Public/public-adapt/2022Dec/0000.html
]

# Issues addressed
[
https://github.com/w3c/adapt/issues?q=is%3Aissue+is%3Aopen+label%3A%221%29+content+module%22
Issues related to this publication have been closed, and two of those remaining issues are related to future implementation plans, and another one is the remaining TAG tracker issue.
]

# Formal Objections
[no objection]

# Implementation
[
Exit Criteria: https://raw.githack.com/w3c/adapt/CR-symbols/snapshots/symbols/Overview.html#candidate-recommendation-exit-criteria

See preliminary [implementation information in Explainer](https://www.w3.org/TR/adapt/#vocabulary-implementations).
There are some early [implementations of content](https://github.com/w3c/adapt/wiki/Implementations-of-Semantics) that can maximize the benefit for users.

minimum CR duration: 6 months]

# Patent disclosures
[https://www.w3.org/groups/wg/apa/ipr#disclosures]

**Comment by plehegar** [comment]
(We're doing a final ping to the TAG)

**Comment by plehegar** [comment]
This transition is now approved.

The TAG will follow-up but is fine with this document moving forward.

**Comment by ylafon** [comment]
See [TAG's minutes](https://github.com/w3ctag/meetings/blob/gh-pages/2022/telcons/12-19-minutes.md#cr-request-for-wai-adapt-symbols-module---ylafon-1)

**Comment by ruoxiran** [comment]
thanks to Philippe, Yves.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2023/CR-adapt-symbols-20230105/
