### ISSUE TITLE
FPWD Request for <Compute Pressure>

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#479]
# Document title, URLs, estimated publication date
Compute Pressure Level 1
https://wicg.github.io/compute-pressure/
2022-12-15

Please check [url with parameters](https://wicg.github.io/compute-pressure/?specStatus=FPWD&shortName=compute-pressure;publishDate=2022-12-15&group=wg/das) for material of publication by DAS WG.

# Abstract
https://wicg.github.io/compute-pressure/?specStatus=FPWD&shortName=compute-pressure;publishDate=2022-12-15&group=wg/das#abstract

# Status
https://wicg.github.io/compute-pressure/?specStatus=FPWD&shortName=compute-pressure;publishDate=2022-12-15&group=wg/das#sotd

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
CfC https://lists.w3.org/Archives/Public/public-device-apis/2022Dec/0003.html
Resolution https://lists.w3.org/Archives/Public/public-device-apis/2022Dec/0007.html

# Information about implementations known to the Working Group
Implemented in Chromium behind a flag.

**Comment by plehegar** [comment]
Approved

**Comment by himorin** [comment]
published: https://www.w3.org/TR/2022/WD-compute-pressure-20221220/
