### ISSUE TITLE
[PEWG] CR transition for Pointer Events (Level 2)

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#48]
# Document title, URLs, estimated publication date
https://w3c.github.io/pointerevents/?specStatus=CR
W3C Candidate Recommendation
03 May 2018

# Abstract
https://w3c.github.io/pointerevents/?specStatus=CR#abstract-0

# Status

This specification is an update to [PointerEvents] which was shipped broadly only by Microsoft Internet Explorer and Microsoft Edge (though a further independent and mostly interoperable implementation was present in a pre-release build of Mozilla Firefox when the Pointer Events specification was published as a W3C Recommendation). Level 2 includes editorial clarifications, new features and minor breaking changes that address certain limitations and concerns that have been raised about aspects of the design, in an effort to enable wider browser adoption.

This Candidate Recommendation is expected to advance to Proposed Recommendation no earlier than 31 May 2018. 

For this specification to exit the CR stage, at least 2 independent implementations of every feature defined in this specification but not already present in Pointer Events 1 (https://www.w3.org/TR/2015/REC-pointerevents-20150224/).

[insert other boilerplate bits here]

# Changes

Since 04 April 2018:

* additional security/privacy clarifications following horizontal review
https://github.com/w3c/pointerevents/pull/252

* Add boundary events in implicit capture scenarios
 https://github.com/w3c/pointerevents/issues/173

# Requirements satisfied

 no requirements

# Dependencies met (or not)

Reached out to various groups:
 https://lists.w3.org/Archives/Public/public-pointer-events/2018AprJun/#msg48events/2018AprJun/0046.html

# Wide Review
https://github.com/w3c/pointerevents/issues

# Issues addressed

All issues were addressed at
 https://github.com/w3c/pointerevents/issues

# Formal Objections

none

# Implementation

This Candidate Recommendation is expected to advance to Proposed Recommendation no earlier than 31 May 2018. 

For this specification to exit the CR stage, at least 2 independent implementations of every feature defined in this specification but not already present in Pointer Events 1 (https://www.w3.org/TR/2015/REC-pointerevents-20150224/).

# Information about implementations known to the Working Group

[TODO: add any preliminary information that you might have]

# Patent disclosures

None
https://www.w3.org/2004/01/pp-impl/59096/status

**Comment by patrickhlauke** [comment]
I believe both Blink and Gecko implemented most of the new features, but I will check with the WG for details on the test results. To clarify: do all tests need to pass/all features be fully implemented now, or when we get to the transition request to PR? And do all tests need to pass fully, or am I remembering right that the important thing is that for any tests that may currently fail due to a bug or development still in progress, that there must be at minimum indication that there is active work going on to implement (i.e. that the spec isn't spec'ing features that UAs are showing no intention of actually implementing)?

**Comment by plehegar** [comment]
re implemented, only for the PR transition. re fully, it depends on the nature of the test. if it's a corner case or bug fix, you could argue that it's fine to move to PR anyway.

**Comment by patrickhlauke** [comment]
Thanks @plehegar (also for pushing this to the chairs list, while I'm still trying to herd cats regarding the test results)

**Comment by plehegar** [comment]
Diff: https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fpointerevents2%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttp%3A%2F%2Fw3c.github.io%2Fpointerevents%2Findex.html%3FspecStatus%3DWD%3BshortName%3Dpointerevents2
