### ISSUE TITLE
CR Snapshot Update Request for Web Content Accessibility Guidelines (WCAG) 2.2

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/transitions#482]
# Document URLs
TR: https://www.w3.org/TR/WCAG22/
Editors' draft: https://w3c.github.io/wcag/guidelines/22/
Publication staging: https://raw.githack.com/w3c/wcag/2023-01_CR/guidelines/index.html

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/w3c-wai-gl/2023JanMar/0142.html

# Link to previous Candidate Recommendation transition or update request
https://github.com/w3c/transitions/issues/450

# Substantive changes
2.5.8 Target Size (Minimum): Changed to the exceptions for spacing and incline targets and a new note on interpreting line height.
3.2.6 Consistent Help: Changed to the first note.
3.3.8 Accessible Authentication:  Changed the first note.
3.3.9 Accessible Authentication (No Exception): Renamed to Accessible Authentication (Enhanced)
4.1.1 Parsing: Removed

# Any changes in requirements?
None

# Wide Review of substantive changes
Changes are made in response to issues filed on the previous CR, which was announced on the usual WAI wide review channels
The Working Group intends to solicit wide review again on this CRS. Feedback will either support advancing to PR, or another action.

# Issues status
https://github.com/w3c/wcag/issues?q=is%3Aissue+is%3Aopen+label%3A%22WCAG+2.2%22+-label%3AUnderstanding+-label%3ATechniques+created%3A%3E2022-09-06+-label%3A%22Response-Only%22

At time of writing there are 3 open issues. #2909 and #2901 were opened after the issue deadline, when this CR publication was already in motion. #2784 is editorial.

# Formal Objections
None

# Any changes in implementation information?
2.4.11 Focus Appearance remains at risk.
CR testing is under way at https://www.w3.org/WAI/GL/WCAG22/CR/evaluation_summary.
The final implementation report will be at https://www.w3.org/WAI/WCAG22/implementation-report/.

# Deadline for further comments
24 February 2023

# Any changes in patent disclosures?
None

**Comment by plehegar** [comment]
The change log seems out of date. None of the substantive changes listed above are present in that section.

Was there any horizontal review of the substantive changes, including 2.58 and 4.1.1?

**Comment by michael-n-cooper** [comment]
Change log is fixed.

Upon discussion with PLH, I learned that this could be published as a CRD instead of a CRS. That is done: https://www.w3.org/TR/2023/CRD-WCAG22-20230125/.

Horizontal review will be run on this publication.
