### ISSUE TITLE
First Note request for CSS Snapshot 2023

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#485]
# Document title, URLs, estimated publication date

CSS Snapshot 2023
https://w3c.github.io/csswg-drafts/css-2023/
Tues 14 Feb 2023

# Abstract

This document collects together into one definition all the specs that together form the current state of Cascading Style Sheets ([CSS](https://www.w3.org/TR/CSS/)) as of 2023. The primary audience is CSS implementers, not CSS authors, as this definition includes modules by specification stability, not Web browser adoption rate.
CSS is a language for describing the rendering of structured documents (such as HTML and XML) on screen, on paper, etc.

# Status of the Document

https://w3c.github.io/csswg-drafts/css-2023/#sotd (as ED)

# Link to group's decision to request transition

https://github.com/w3c/csswg-drafts/issues/7883#issuecomment-1423006035

# Is it intended to be a W3C Statement?

No

**Comment by plehegar** [comment]
Approved.

The SOTD will need some updates to be pubrules happy since no longer use the full "Patent Policy paragraph" in Notes.

**Comment by svgeesus** [comment]
[Published 14 Feb 2023](https://www.w3.org/TR/2023/DNOTE-css-2023-20230214/)
