### ISSUE TITLE
First Note request for Gurmukhi Layout Requirements

### ISSUE THREAD

**Issue by r12a** [w3c/transitions#486]
# Document title, URLs, estimated publication date
Gurmukhi Layout Requirements
https://www.w3.org/TR/2023/DNOTE-guru-lreq-20230214/
14 Feb

# Abstract
This document describes requirements for the layout and presentation of text in the Punjabi language, using the Gurmukhi script when they are used by Web standards and technologies, such as HTML, CSS, Mobile Web, Digital Publications, and Unicode.

# Status of the Document
Draft Note (FPWD)

# Link to group's decision to request transition
https://www.w3.org/2023/02/09-i18n-minutes.html#t06

# Is it intended to be a W3C Statement?
No

**Comment by plehegar** [comment]
Approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2023/DNOTE-guru-lreq-20230214/
