### ISSUE TITLE
FPWD Request for CSS Animations Level 2

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#488]
# Document title, URLs, estimated publication date
CSS Animations Module Level 2
https://www.w3.org/TR/css-animations-2/
sometime next week?

# Abstract
https://drafts.csswg.org/css-animations-2/#abstract

# Status
https://drafts.csswg.org/css-animations-2/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
Yes; but it should be undelta-ified once CSS Animations Level 1 stabilizes in CR.

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/www-style/2023Feb/0002.html

# Information about implementations known to the Working Group
The `animation-timeline` property has an implementation in Chrome due to the dependency from Scroll Animations.

**Comment by plehegar** [comment]
https://www.w3.org/TR/css-animations-1/ was not updated since 2018. Yet I see substantive updates in the editor's draft, like adding a length attribute to the CSSKeyframesRule interface. What's the story for CSS Animations 1? Can we get it updated as part of this new version as well?

**Comment by svgeesus** [comment]
Waiting for response to https://github.com/w3c/csswg-drafts/issues/8464 before proceeding

**Comment by SebastianZ** [comment]
The editor information is outdated on that spec. Both @birtles and @dbaron are not working for Mozilla anymore. I think that should be updated before publishing.

Sebastian

**Comment by dbaron** [comment]
I think the sensible way to update my affiliation would be to list both affiliations, such as "Google (previously Mozilla)".  I don't see an obvious way to do that in Bikeshed's syntax, though...

**Comment by svgeesus** [comment]
> The editor information is outdated on that spec. Both @birtles and @dbaron are not working for Mozilla anymore.

I [updated @dbaron to current yesterday](https://github.com/w3c/csswg-drafts/commit/2412e2b0ba516fd8520fa4c3f7c777f29e56e3e5). Will update @birtles.

>  I don't see an obvious way to do that in Bikeshed's syntax, though...

Nor do I, sorry.

**Comment by svgeesus** [comment]
[editor affiliations updated](https://github.com/w3c/csswg-drafts/commit/e95e89652277ba54f410e44fcfcefadf1b3a4498)

**Comment by svgeesus** [comment]
@plh asked:

> What's the story for CSS Animations 1? Can we get it updated as part of this new version as well?

I created [an issue in CSSWG](https://github.com/w3c/csswg-drafts/issues/8464) and there is an ongoing CfC to publish, which closes Tuesday 28 Feb. 

I added a Changes since Level 1 section to CSS Animations 2 (which is currently a delta spec).

On Monday 27 Feb I plan to prep both CSS Animations 1 and 2 for publication on Thurs 2 March, so they will be published together.

**Comment by svgeesus** [comment]
@plh approve please?

Publication of CSS Animations 2 (as FPWD) and CSS Animations 1 (as updated WD) set up for Thursday 2 March.

**Comment by svgeesus** [comment]
- [RESOLVED: Publish updated WD of css-animations-1](https://github.com/w3c/csswg-drafts/issues/8464#issuecomment-1447532232)

**Comment by plehegar** [comment]
Thank you for looking into this.

Aprroved.

**Comment by svgeesus** [comment]
[CSS https://www.w3.org/TR/2023/WD-css-animations-1-20230302/Animations 2 FPWD](https://www.w3.org/TR/2023/WD-css-animations-2-20230302/) and [CSS Animations 1 WD]() published today.
