### ISSUE TITLE
WAI-ARIA 1.2 PR Transition Request

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/transitions#489]
## Document title, URIs, and [estimated publication date](https://www.w3.org/Guide/transitions?profile=PR&pr=new#schedule-pubreq).

Accessible Rich Internet Applications (WAI-ARIA) 1.2

[https://www.w3.org/TR/2023/PR-WAI-ARIA-1.2-20230328/](https://www.w3.org/TR/2023/PR-WAI-ARIA-1.2-20230328/)

28 March 2023

## Abstract

Accessibility of web content requires semantic information about widgets, structures, and behaviors, in order to allow assistive technologies to convey appropriate information to persons with disabilities. This specification provides an ontology of roles, states, and properties that define accessible user interface elements and can be used to improve the accessibility and interoperability of web content and applications. These semantics are designed to allow an author to properly convey user interface behaviors and structural information to assistive technologies in document-level markup. This version adds features new since WAI-ARIA 1.1 [wai-aria-1.1] to improve interoperability with assistive technologies to form a more consistent accessibility model for [HTML] and [SVG2]. This specification complements both [HTML] and [SVG2].

This document is part of the WAI-ARIA suite described in the WAI-ARIA Overview.

## Status

WAI-ARIA 1.2 was published as a [Candidate Recommendation on 8 December 2021](https://www.w3.org/TR/wai-aria-1.2/). Since then the Working Group has collected implementation experience for the specification, as well as for [Core Accessibility API Mappings 1.2](https://www.w3.org/TR/core-aam-1.2/) which was necessary for this specification to move forward. For details about implementation experience and disposition of items at risk in the Candidate Recommendation, see the [WAI-ARIA 1.2 Implementation Report](https://w3c.github.io/test-results/core-aam-1.2/). A [history of changes to WAI-ARIA 1.2](https://www.w3.org/TR/2023/PR-WAI-ARIA-1.2-20230221/#changelog) is available in the appendix.

W3C Advisory Committee Members are invited to send formal review comments to the W3C Team until **28 February 2023**. Comments should be made using the [Call for Review WBS ](https://www.w3.org/2002/09/wbs/33280/ARIA2022-12PR/)form. To comment, aside from Advisory Committee comments, [file an issue in the W3C ARIA GitHub repository](https://github.com/w3c/aria/issues/new). If this is not feasible, send email to public-aria@w3.org ([comment archive](http://lists.w3.org/Archives/Public/public-aria/)). In-progress updates to the document may be viewed in the [publicly visible editors' draft](http://w3c.github.io/aria/aria/aria.html).

This document is intended to become a W3C Recommendation. Note that substantive technical comments were expected during the Candidate Recommendation review period that ended 21 December 2021.

Please see the Working Group's [implementation report](https://w3c.github.io/test-results/core-aam-1.2/).

## group’s decision to request transition

[https://lists.w3.org/Archives/Public/public-aria-admin/2023Feb/0000.html](https://lists.w3.org/Archives/Public/public-aria-admin/2023Feb/0000.html)

## Changes

[https://www.w3.org/TR/2023/PR-WAI-ARIA-1.2-20230221/#changelog](https://www.w3.org/TR/2023/PR-WAI-ARIA-1.2-20230221/#changelog)

Removed [at risk section as well as features marked at risk ](https://github.com/w3c/aria/pull/1874) at CR. Updated tests to reflect current status of prohibition of aria-roledescription for generic role, which now has two implementations.

## Requirements satisfied

No new requirements apply.

## Dependencies met (or not)

No changes since CR.

## Wide Review

The horizontal review results were tracked in [https://github.com/w3c/aria/labels/1.2-Blocking](https://github.com/w3c/aria/labels/1.2-Blocking), and there was not any outstanding issue.

## Issues addressed

No major issues raised in the CR period, and no issues raised after the CR ended. All [open issues ](https://github.com/w3c/aria/labels/1.2-Blocking)have been addressed.

## Implementation report

An [Implementation Report](https://w3c.github.io/test-results/core-aam-1.2/) is available, documenting at least two independent implementations for every feature.

## Patent disclosures

[https://www.w3.org/groups/wg/webapps/ipr](https://www.w3.org/groups/wg/webapps/ipr)

[https://www.w3.org/groups/wg/aria/ipr](https://www.w3.org/groups/wg/aria/ipr)

## Has anything changed on the patent disclosure page since the previous transition? Have there been any incomplete or problematic disclosures?

No.

**Comment by jennyliang220** [comment]
This document doesn't pass the html validator [see errors in pubrules](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2023%2FPR-WAI-ARIA-1.2-20230221%2F&profile=PR&validation=simple-validation&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020), but **The document is erroring on `role=”time”`, which will become valid HTML once WAI-ARIA 1.2 is a Proposed Recommendation.**. @plehegar, can we ignore the errors?

**Comment by daniel-montalvo** [comment]
Thanks @jennyliang220  for clarifying this.

We would kindly request an exception as per the comments above.

**Comment by jennyliang220** [comment]
Once the document has the approval as well as the exception, it's good to publish :)

**Comment by plehegar** [comment]
Do you have a test for the IDL interface mixin? Looking at [#1843](https://github.com/w3c/aria/issues/1843), it would be good to have one. This is not blocking for the PR.

The following issues are blocking:

- There are a few occurrences of linking to https://www.w3.org/TR/html/ and https://www.w3.org/TR/dom/. Use https://html.spec.whatwg.org/ and https://dom.spec.whatwg.org/ instead.

- The proposed document still contains the features at risk. It's not clear of those features will stay in or not, but you cannot list them at risk in the Proposed Recommendation. It's not that you have 2 implementations for each feature at risk, such the prohibition of aria-roledescription for the generic role.

- The implementation report contains links to a machine that no longer exists (w3c-test.org). Why are those tests not on wpt.fyi directly?

**Comment by plehegar** [comment]
It's fine to ignore the HTML validator error for role=time

**Comment by daniel-montalvo** [comment]
> It's fine to ignore the HTML validator error for role=time

**Comment by daniel-montalvo** [comment]
Thanks @plehegar for having a look at this.

> The following issues are blocking:
> 
> * There are a few occurrences of linking to https://www.w3.org/TR/html/ and https://www.w3.org/TR/dom/. Use https://html.spec.whatwg.org/ and https://dom.spec.whatwg.org/ instead.

Done.

> * The proposed document still contains the features at risk. It's not clear of those features will stay in or not, but you cannot list them at risk in the Proposed Recommendation. You seem to be missing 2 implementations for each feature at risk, such as the prohibition of aria-roledescription for the generic role.

This has been taken care of in
https://github.com/w3c/aria/pull/1874

These are now removed.

> * The implementation report contains links to a machine that no longer exists (w3c-test.org). Why are those tests not on wpt.fyi directly?

Tagging @spectranaut to see if she can help with this.

> Do you have a test for the IDL interface mixin? Looking at [#1843](https://github.com/w3c/aria/issues/1843), it would be good to have one. This is not blocking for the PR.

Tagging @spectranaut to see if she can help with this.

**Comment by spectranaut** [comment]
> > * The implementation report contains links to a machine that no longer exists (w3c-test.org). Why are those tests not on wpt.fyi directly?
> 
> Tagging @spectranaut to see if she can help with this.

I'm not sure what link he is talking about.. I just looked through the ARIA and couldn't find a link to w3c-test.org. On the other hand, the reason these tests are not on wpt.fyi is because WPT does not have the tooling to run these tests. The tests are in the WPT repo, but as "manual" tests, which means that there is no tooling within WPT to run them. So we are running them locally and posting them here: https://w3c.github.io/test-results/core-aam-1.2/

That link is accurately in the 1.2 publication branch!

> 
> > Do you have a test for the IDL interface mixin? Looking at [#1843](https://github.com/w3c/aria/issues/1843), it would be good to have one. This is not blocking for the PR.
> 
> Tagging @spectranaut to see if she can help with this.

I'll look into this.

**Comment by spectranaut** [comment]
Now I understand, there are some incorrect links on this page, I'll fix that: https://w3c.github.io/test-results/core-aam-1.2/

**Comment by spectranaut** [comment]
@daniel-montalvo 

The link in the implementation report have been updated to point to the tests in WPT: https://bugs.webkit.org/show_bug.cgi?id=252681

Additionally, on the question of aria-roledescription prohibited on generic: WebKit (on mac) decided they will only disallow aria-roledescription on "div" and "span", but it looks like they overlooked the role="generic" case, I filed an issue: https://bugs.webkit.org/show_bug.cgi?id=252681

aria-roledescription prohibited on generic does have three complete implementation, chromium on linux, chromium on mac and chromium on windows with IA2.

**Comment by spectranaut** [comment]
> > Do you have a test for the IDL interface mixin? Looking at [#1843](https://github.com/w3c/aria/issues/1843), it would be good to have one. This is not blocking for the PR.
> 
> Tagging @spectranaut to see if she can help with this.

We do have tests, in WPT: https://wpt.fyi/results/html/dom/aria-element-reflection.html?label=experimental&label=master&aligned&view=subtest

**Comment by daniel-montalvo** [comment]
Thanks for these updates @spectranaut 

> aria-roledescription prohibited on generic does have three complete implementation, chromium on linux, chromium on mac and chromium on windows with IA2.

@plehegar  Would you be OK with this?

**Comment by plehegar** [comment]
- aria-roledescription prohibited on generic passes on Chromium with 3 different assistive technologies tools. it seems that the prohibition is enforced by Chromium. 
- aria-expanded=true seems only supported at best by Firefox/ATK and Chromium/ATK, which seems that only ATK supports it.
  -> aria-expanded=true on alert 1 (why alert is OK but not alert 1)
  -> same for aria-expanded=true on banner 1, dialog 1, feed 1, form 1, group 1, aria-posinset and aria-setsize on treegrid row 2, aria-posinset and aria-setsize on treegrid row 3

If the two statements above are correct, this would be only one implementation for those features.

There are still links going nowhere in the implementation report. See https://validator.w3.org/checklink?uri=https%3A%2F%2Fw3c.github.io%2Ftest-results%2Fcore-aam-1.2%2Fall.html&hide_type=all&depth=&check=Check

**Comment by daniel-montalvo** [comment]
The links all pass now: 

https://validator.w3.org/checklink?uri=https%3A%2F%2Fw3c.github.io%2Ftest-results%2Fcore-aam-1.2%2Fall.html&hide_type=all&depth=&check=Check

And the test to prohibit roledescription on generic elements also passed now on webkit, as the test was update to match webkit's and chrome's implementation:


https://w3c.github.io/test-results/core-aam-1.2/all.html#test-file-14

**Comment by plehegar** [comment]
https://www.w3.org/TR/2023/PR-wai-aria-1.2-20230328/
