### ISSUE TITLE
[TTWG] CR transition for WebVTT

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#49]
# Document title, URLs, estimated publication date
WebVTT: The Web Video Text Tracks Format
https://rawgit.com/w3c/webvtt/gh-pages/archives/2018-04-15/Overview.html

# Abstract

This specification defines WebVTT, the Web Video Text Tracks format. Its main use is for marking up external text track resources in connection with the HTML <track> element. WebVTT files provide captions or subtitles for video content, and also text video descriptions [MAUR], chapters for content navigation, and more generally any form of metadata that is time-aligned with audio or video content.

This specification is based on the Draft Community Group Report of the Web Media Text Tracks Community Group.

# Status

This document was produced by the W3C Timed Text Working Group as a Candidate Recommendation. This document is intended to become a W3C Recommendation. If you wish to make comments regarding this document, please send them to public-tt@w3.org (subscribe, archives) with [webvtt] at the start of your email’s subject. All comments are welcome. W3C publishes a Candidate Recommendation to indicate that the document is believed to be stable and to encourage implementation by the developer community. This document will remain a Candidate Recommendation at least until 15 July 2018 in order to ensure the opportunity for wide review.
Please see the Working Group's Implementation Report.
For this specification to exit the CR stage, at least 2 independent implementations of every feature defined in this specification need to be documented in the implementation report. The implementation report is based on implementer-provided test results for the test suite. The Working Group does not require that implementations are publicly available but encourages them to be so.
The Working Group has not identified features "at risk" for this specification.
A cumulative summary of all changes applied to this version since the WebVTT First Public Working Draft was published is available at Changes from FPWD WebVTT.
For convenience, a complete diff between this version and the WebVTT previous Working Draft was published is found at Diff from previous Working Draft WebVTT.
Publication as a Candidate Recommendation does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress. 
This document was produced by a group operating under the 5 February 2004 W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.
This document is governed by the 1 February 2018 W3C Process Document.

Group decision:
 https://lists.w3.org/Archives/Public/public-tt/2018Apr/0056.html

# Changes

https://rawgit.com/w3c/webvtt/gh-pages/archives/2018-04-15/changes.html

Diff:
 https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fwebvtt1%2F&doc2=https%3A%2F%2Frawgit.com%2Fw3c%2Fwebvtt%2Fgh-pages%2Farchives%2F2018-04-15%2FOverview.html
https://rawgit.com/w3c/webvtt/gh-pages/archives/2018-04-15/diff.html

# Requirements satisfied

No requirements document but MAUR was used.

# Dependencies met (or not)

https://rawgit.com/w3c/webvtt/gh-pages/archives/2018-04-15/Overview.html#normative

# Wide Review

https://github.com/w3c/webvtt/issues?q=is:issue+label:WR

https://www.w3.org/wiki/TimedText/WebVTT_Wide_Review

APA
 https://lists.w3.org/Archives/Public/public-tt/2018Jan/0281.html

# Issues addressed

https://github.com/w3c/webvtt/issues

Several issues were delayed to v.next:
 https://github.com/w3c/webvtt/issues?q=is%3Aissue+is%3Aopen+label%3AVTT-next

# Formal Objections

None

# Implementation

For this specification to exit the CR stage, at least 2 independent implementations of every feature defined in this specification need to be documented in the implementation report. The implementation report is based on implementer-provided test results for the test suite.

This document will remain a Candidate Recommendation at least until 15 July 2018 in order to ensure the opportunity for wide review.

The Working Group has not identified features "at risk" for this specification.

# Information about implementations known to the Working Group

There is ongoing implementations in several browsers.

# Patent disclosures

https://www.w3.org/2004/01/pp-impl/49309/status

**Comment by dwsinger** [comment]
This sentence has words funny in order put "For convenience, a complete diff between this version and the WebVTT previous Working Draft was published is found at Diff from previous Working Draft WebVTT."

and the "Information about implementations" should surely link to https://www.w3.org/wiki/TimedText/EffortsAndSpecifications#WebVTT-based_efforts_and_specifications

**Comment by plehegar** [comment]
https://www.w3.org/TR/2018/CR-ttml-imsc1.1-20180503/

**Comment by plehegar** [comment]
For dependencies, I took the easy road, ie a link to the normative references section:
 https://www.w3.org/Guide/transitions?profile=CR&cr=new#dependencies-met

**Comment by dwsinger** [comment]
Indeed, done and announced.
