### ISSUE TITLE
REC Request for CSS Box 3

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#494]
---

# Document title, URLs, estimated publication date
CSS Box Model Module Level 3
https://www.w3.org/TR/2023/PR-css-box-3-20230216/ (as PR)
after approval

# Abstract

This specification describes the margin and padding properties, which create spacing in and around a CSS box.
CSS is a language for describing the rendering of structured documents (such as HTML and XML) on screen, on paper, etc. 

# Status

https://www.w3.org/TR/2023/PR-css-box-3-20230216/#sotd (as PR)

# Link to group's decision to request transition

See https://github.com/w3c/transitions/issues/469

# Wide Review

No change

# Dependencies

No change

# Issues addressed

None raised during AC review

# Link to internal AC Review results

https://www.w3.org/2002/09/wbs/33280/css-box-3-2023/results

# Formal Objections

None

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
CSS Box 3 Rec publication requested 03 Apr, expected 06 Apr.

**Comment by svgeesus** [comment]
[CSS 3 Box REC published 6 Apr 2023](https://www.w3.org/TR/2023/REC-css-box-3-20230406/)
