### ISSUE TITLE
CR Request for W3C TraceContext Level 2 Specification

### ISSUE THREAD

**Issue by kalyanaj** [w3c/transitions#495]
# Document title, URLs, estimated publication date
Title: Trace Context Level 2
URL: https://w3c.github.io/trace-context/ (latest editors' draft)
Estimated publication date: After approval (no other strong deadline).

# Abstract
This specification defines standard HTTP headers and a value format to propagate context information that enables distributed tracing scenarios. The specification standardizes how context information is sent and modified between services. Context information uniquely identifies individual requests in a distributed system and also defines a means to add and propagate provider-specific context information.

# Status
Level 1 of this specification is already in Recommendation status since 2019. This is a minor incremental update to it called Trace Context Level 2:
https://w3c.github.io/trace-context/ (latest editor's draft)
https://www.w3.org/TR/trace-context-2/ (FPWD)

# Link to group's decision to request transition
We discussed this in the Distributed Tracing WG meeting on 03/28/2023. The group unanimously decided to request this transition. Meeting notes are at: https://docs.google.com/document/d/1EaY1zhmlOut4qZzpFue4vLc96_GrRWMtmzXYLfd1Ehc/edit#.

# Changes
The main changes are:
- It introduces a new "flag" in the traceparent header called the random-trace-id flag. This is to indicate if the trace-id was generated randomly (or pseudo-randomly). 
- If the random-trace-id flag is set, at least the right-most 7 bytes of the trace-id MUST be randomly (or pseudo-randomly) generated.

# Requirements satisfied
No specific requirements document was created.

# Dependencies met (or not)
Please see next section. 

# Wide Review
Yes the wide review was done (https://github.com/w3c/trace-context/issues/492) and issues have been addressed.

# Issues addressed
- Change the defining document for HTTP from RFC7230 to RFC9110 (https://github.com/w3c/trace-context/issues/519)
- When headers should be propagated in browsers should be made more clear (https://github.com/w3c/trace-context/issues/510)
- Adopt either span-id or parent-id for section headings (https://github.com/w3c/trace-context/issues/509)
- Why should keys be restricted to lowercase ASCII? (https://github.com/w3c/trace-context/issues/508)
- Version number relationship to ASCII and UTF-8 (https://github.com/w3c/trace-context/issues/507)
- Specification of lowercase is incomplete (https://github.com/w3c/trace-context/issues/506)

# Formal Objections
None so far

# Implementation
https://github.com/open-telemetry/oteps/pull/226/ is an OpenTelemetry sampler specification enhancement proposal that references the above specification. 
Minimum CR duration: 3 months
Exit criteria: At least 2 implementations adopting this specification and making use of it. The test suite will be updated as well.

# Patent disclosures
None

**Comment by ylafon** [comment]
Hi @kalyanaj 
Looking at the diff from the FPWD and the editor's draft linked, I see the whole section 4 `Trace Context HTTP Response Headers Format` as not been reviewed.
Could you clarify?
Thanks

**Comment by plehegar** [comment]
we have a dedicated branch for level-2. I'll generate a WD for it to make it clear which document should be published as CR.

**Comment by ylafon** [comment]
I would note also that I found a TAG review of the [Trace Context Level 2 changes](https://github.com/w3ctag/design-reviews/issues/777), so the diff from v1 REC to v2 FPWD, but not the review of Trace Context Level 1. Did that happen, or what is missed?

**Comment by plehegar** [comment]
I created a snapshot of the level 2 branch:
- [Level 2 2023-04-05](https://htmlpreview.github.io/?https://raw.githubusercontent.com/w3c/trace-context/wd-level-2-snapshot/spec/snapshot.html)
- [Diff with FPWD](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Ftrace-context-2%2F&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Ftrace-context%2Fwd-level-2-snapshot%2Fspec%2Fsnapshot.html)

**Comment by plehegar** [comment]
I could not locate a formal TAG review request in late 2018.

I did find [minutes from TPAC 2018](https://docs.google.com/document/d/12yecf7L1uibMIGP_YkTRM-KKCZZkluqmYqXxGFHD5J4/edit#heading=h.scqwjmur3q8z), which include discussion on structured headers.

**Comment by plehegar** [comment]
See also https://github.com/w3c/trace-context/issues/197#issuecomment-462906592

**Comment by ylafon** [comment]
> I could not locate a formal TAG review request in late 2018.
> 
> I did find [minutes from TPAC 2018](https://docs.google.com/document/d/12yecf7L1uibMIGP_YkTRM-KKCZZkluqmYqXxGFHD5J4/edit#heading=h.scqwjmur3q8z), which include discussion on structured headers.

That document is private

**Comment by plehegar** [comment]
Also published a WD: https://www.w3.org/TR/2023/WD-trace-context-2-20230406/

**Comment by plehegar** [comment]
SOTD for CR:
[[
This new version adds considerations for the generation of the trace-id and span-id fields, and adds the random trace ID flag.

This document was published by the [Distributed Tracing Working Group](https://www.w3.org/groups/wg/distributed-tracing) as a Candidate Recommendation Snapshot using the [Recommendation track](https://www.w3.org/2021/Process-20211102/#recs-and-notes).
Publication as a Candidate Recommendation does not imply endorsement by W3C and its Members. A Candidate Recommendation Snapshot has received [wide review](https://www.w3.org/2021/Process-20211102/#dfn-wide-review), is intended to gather [implementation experience](https://github.com/w3c/trace-context/#reference-implementations), and has commitments from Working Group members to [royalty-free licensing](https://www.w3.org/Consortium/Patent-Policy/#sec-Requirements) for implementations.
This Candidate Recommendation is not expected to advance to Proposed Recommendation any earlier than 07 April 2023.

The Working Group instends to demonstrate at least 2 implementations adopting this specification and making use of it, using a test suite.

This document was produced by a group operating under the [1 August 2017 W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy-20170801/). W3C maintains a [public list of any patent disclosures](https://www.w3.org/groups/wg/distributed-tracing/ipr) made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains [Essential Claim(s)](https://www.w3.org/Consortium/Patent-Policy-20170801/#def-essential) must disclose the information in accordance with [section 6 of the W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy-20170801/#sec-Disclosure).
This document is governed by the [2 November 2021 W3C Process Document](https://www.w3.org/2021/Process-20211102/).
]]

**Comment by ylafon** [comment]
Thanks for the clarifications and new document published.
Transition is approved.

**Comment by plehegar** [comment]
pubreq: https://lists.w3.org/Archives/Team/webreq/2023Apr/0014.html

**Comment by plehegar** [comment]
https://www.w3.org/TR/2023/CR-trace-context-2-20230418/
