### ISSUE TITLE
FPWD Request for W3C Badging API

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#497]
# Document title, URLs, estimated publication date
Badging API
https://www.w3.org/TR/badging/
W3C First Public Working Draft 06 April 2023

# Abstract
This specification defines an API that allows [installed web applications](https://www.w3.org/TR/appmanifest/#dfn-installed-web-application) to set an application badge, which is usually shown alongside the application's icon on the device's home screen or application dock.

# Status
https://w3c.github.io/badging/?specStatus=FPWD#sotd

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://github.com/w3c/badging/issues/99

# Information about implementations known to the Working Group
Implemented in Chrome + Edge on multiple platforms, and also in Safari 16.4 for iOS and made available when a web application is added to the home screen. (Informed by @marcoscaceres , thanks!)

**Comment by plehegar** [comment]
Approved

**Comment by siusin** [comment]
Published as an FPWD on 6 April ->
https://www.w3.org/TR/2023/WD-badging-20230406/
