### ISSUE TITLE
FPWD Request for "Dubbing and Audio description Profiles of TTML2"

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#499]
# Document title, URLs, estimated publication date
Dubbing and Audio description Profiles of TTML2
ED: https://w3c.github.io/dapt/
TR: https://www.w3.org/TR/dapt/
Date: 2023-04-20

# Abstract
https://w3c.github.io/dapt/#abstract
This specification defines DAPT, a TTML-based file format for the exchange of timed text content in dubbing and audio description workflows. 

# Status
https://w3c.github.io/dapt/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
cfc: https://www.w3.org/2023/03/30-tt-minutes.html#r01
resolution: https://www.w3.org/2023/04/13-tt-minutes.html#x059

# Information about implementations known to the Working Group
not yet

**Comment by himorin** [comment]
cc @nigelmegitt @gkatsev

**Comment by plehegar** [comment]
Approved

**Comment by himorin** [comment]
published https://www.w3.org/TR/2023/WD-dapt-20230425/
