### ISSUE TITLE
FPWD Request for "Securing Verifiable Credentials using JSON Web Tokens"

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#500]
# Document title, URLs, estimated publication date

Title: Securing Verifiable Credentials using JSON Web Tokens
- URL: https://www.w3.org/TR/2023/WD-vc-jwt-20230427/
- Expected Publication date 2023 Apr 27
- short name: vc-jwt

# Abstract
See https://www.w3.org/TR/2023/WD-vc-jwt-20230427/#abstract

# Status
See https://www.w3.org/TR/2023/WD-vc-jwt-20230427/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
(https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-03-22-vcwg#resolution3)

# Information about implementations known to the Working Group
Implementations on an earlier version exist as part of Verifiable Credentials v1.0 deployments, experimental implementations for the new version also exist

cc @brentzunel @sakurann @OR13

**Comment by plehegar** [comment]
Approved

**Comment by iherman** [comment]
Published, closing (see https://www.w3.org/blog/news/archives/9901)
