### ISSUE TITLE
FPWD Request for the "Verifiable Credentials Status List 2021" specification

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#501]
# Document title, URLs, estimated publication date

Title: Verifiable Credentials Status List v2021
- URL: https://www.w3.org/TR/2023/WD-vc-status-list-20230427/
- Expected Publication date 2023 Apr 27
- short name: vc-status-list-2021

# Abstract
See https://www.w3.org/TR/2023/WD-vc-status-list-20230427/#abstract

# Status
See https://www.w3.org/TR/2023/WD-vc-status-list-20230427#sotd

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-04-19-vcwg#resolution1

# Information about implementations known to the Working Group
There are experimental implementations, not yet in production

cc @brentzundel @sakurann @OR13 @dlongley @msporny @mprorock @mkhraisha

**Comment by plehegar** [comment]
Approved

**Comment by iherman** [comment]
Publication request sent: https://lists.w3.org/Archives/Group/group-vc-wg-chairs/2023Apr/0018.html
