### ISSUE TITLE
FPWD Request for 17 specifications from the RDF-star WG

### ISSUE THREAD

**Issue by pchampin** [w3c/transitions#502]
# Common information

* Estimated publication date:
  + 2023-05-04
* Is it a delta specification intended to become a W3C Recommendation?
  + no
* WG decision
  + https://www.w3.org/2023/04/20-rdf-star-minutes.html#r02
* Information about implementations known to the Working Group:
  + CG implementation reports: https://w3c.github.io/rdf-star/reports/

# Document specifc information

Title:    RDF 1.2 Concepts and Abstract Syntax
URL:      https://w3c.github.io/rdf-concepts/spec/
Abstract: https://w3c.github.io/rdf-concepts/spec/#abstract
Status:   https://w3c.github.io/rdf-concepts/spec/#sotd

Title:    RDF 1.2 Schema
URL:      https://w3c.github.io/rdf-schema/spec/
Abstract: https://w3c.github.io/rdf-schema/spec/#abstract
Status:   https://w3c.github.io/rdf-schema/spec/#sotd

Title:    RDF 1.2 Semantics
URL:      https://w3c.github.io/rdf-semantics/spec/
Abstract: https://w3c.github.io/rdf-semantics/spec/#abstract
Status:   https://w3c.github.io/rdf-semantics/spec/#sotd

Title:    RDF 1.2 N-Quads
URL:      https://w3c.github.io/rdf-n-quads/spec/
Abstract: https://w3c.github.io/rdf-n-quads/spec/#abstract
Status:   https://w3c.github.io/rdf-n-quads/spec/#sotd

Title:    RDF 1.2 N-Triples
URL:      https://w3c.github.io/rdf-n-triples/spec/
Abstract: https://w3c.github.io/rdf-n-triples/spec/#abstract
Status:   https://w3c.github.io/rdf-n-triples/spec/#sotd

Title:    RDF 1.2 TriG
URL:      https://w3c.github.io/rdf-trig/spec/
Abstract: https://w3c.github.io/rdf-trig/spec/#abstract
Status:   https://w3c.github.io/rdf-trig/spec/#sotd

Title:    RDF 1.2 Turtle
URL:      https://w3c.github.io/rdf-turtle/spec/
Abstract: https://w3c.github.io/rdf-turtle/spec/#abstract
Status:   https://w3c.github.io/rdf-turtle/spec/#sotd

Title:    RDF 1.2 XML Syntax
URL:      https://w3c.github.io/rdf-xml/spec/
Abstract: https://w3c.github.io/rdf-xml/spec/#abstract
Status:   https://w3c.github.io/rdf-xml/spec/#sotd

Title:    SPARQL 1.2 Query Language
URL:      https://w3c.github.io/sparql-query/spec/
Abstract: https://w3c.github.io/sparql-query/spec/#abstract
Status:   https://w3c.github.io/sparql-query/spec/#sotd

Title:    SPARQL 1.2 Update
URL:      https://w3c.github.io/sparql-update/spec/
Abstract: https://w3c.github.io/sparql-update/spec/#abstract
Status:   https://w3c.github.io/sparql-update/spec/#sotd

Title:    SPARQL 1.2 Service Description
URL:      https://w3c.github.io/sparql-service-description/spec/
Abstract: https://w3c.github.io/sparql-service-description/spec/#abstract
Status:   https://w3c.github.io/sparql-service-description/spec/#sotd

Title:    SPARQL 1.2 Federated Query
URL:      https://w3c.github.io/sparql-federated-query/spec/
Abstract: https://w3c.github.io/sparql-federated-query/spec/#abstract
Status:   https://w3c.github.io/sparql-federated-query/spec/#sotd

Title:    SPARQL 1.2 Query Results JSON Format
URL:      https://w3c.github.io/sparql-results-json/spec/
Abstract: https://w3c.github.io/sparql-results-json/spec/#abstract
Status:   https://w3c.github.io/sparql-results-json/spec/#sotd

Title:    SPARQL 1.2 Query Results CSV and TSV Formats
URL:      https://w3c.github.io/sparql-results-csv-tsv/spec/
Abstract: https://w3c.github.io/sparql-results-csv-tsv/spec/#abstract
Status:   https://w3c.github.io/sparql-results-csv-tsv/spec/#sotd

Title:    SPARQL 1.2 Query Results XML Format
URL:      https://w3c.github.io/sparql-results-xml/spec/
Abstract: https://w3c.github.io/sparql-results-xml/spec/#abstract
Status:   https://w3c.github.io/sparql-results-xml/spec/#sotd

Title:    SPARQL 1.2 Protocol
URL:      https://w3c.github.io/sparql-protocol/spec/
Abstract: https://w3c.github.io/sparql-protocol/spec/#abstract
Status:   https://w3c.github.io/sparql-protocol/spec/#sotd

Title:    SPARQL 1.2 Graph Store Protocol
URL:      https://w3c.github.io/sparql-graph-store-protocol/spec/
Abstract: https://w3c.github.io/sparql-graph-store-protocol/spec/#abstract
Status:   https://w3c.github.io/sparql-graph-store-protocol/spec/#sotd

**Comment by plehegar** [comment]
Approved.

**Comment by plehegar** [comment]
Published on May 16
