### ISSUE TITLE
REC Request for EPUB 3.3., EPUB 3.3 Reading Systems, EPUB Accessibility 1.1

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#505]
# Pointer to the internal transition request mail:

https://lists.w3.org/Archives/Team/w3t-comm/2023May/0080.html

# Document titles, URLs, estimated publication dates

* EPUB 3.3
  * URL: https://www.w3.org/TR/epub-33/
  * Long URL: https://www.w3.org/TR/2023/REC-epub-33-20230525/
  * Editor's Draft: https://w3c.github.io/epub-specs/epub33/core/
  * Estimated Publication date: 2023-05-25
* EPUB 3.3 Reading Systems
  * URL: https://www.w3.org/TR/epub-rs-33/
  * Long URL: https://www.w3.org/TR/2023/REC-epub-rs-33-20230525/
  * Editor's Draft: https://w3c.github.io/epub-specs/epub33/rs/
  * Estimated Publication date: 2023-05-25
* EPUB Accessibility 1.1
  * URL: https://www.w3.org/TR/epub-a11y-11/
  * Long URL: https://www.w3.org/TR/2023/REC-epub-a11y-11-20230525/
  * Editor's Draft: https://w3c.github.io/epub-specs/epub33/a11y/
  * Estimated Publication date: 2023-05-25

# Abstract

* https://www.w3.org/TR/2023/REC-epub-33-20230525/#abstract
* https://www.w3.org/TR/2023/REC-epub-rs-33-20230525/
* https://www.w3.org/TR/2023/REC-epub-a11y-11-20230525/#abstract

# Status

* https://www.w3.org/TR/2023/REC-epub-33-20230525/#sotd
* https://www.w3.org/TR/2023/REC-epub-rs-33-20230525//#sotd
* https://www.w3.org/TR/2023/REC-epub-a11y-11-20230525/#sotd

# Link to group's decision to request transition

- https://lists.w3.org/Archives/Public/public-epub-wg/2023Feb/0000.html

# Wide Review

No change since PR Request (see #496)

# Dependencies

No change since PR Request (see #496)

# Issues addressed

Since #496 four minor (essentially editorial) issues have been raised, which will be recorded as errata after the publication. All other open issues have been deferred by the WG before #496.

See https://github.com/w3c/epub-specs/issues/

# Link to internal AC Review results

https://www.w3.org/2002/09/wbs/33280/epub-pr/results

# Formal Objections

None.

cc @wareid @shiestyle @dauwhe @mattgarrish

**Comment by mattgarrish** [comment]
> The normative reference to PNG links to the latest version of PNG, which is the Third Edition. While the reference section means to use the Second Edition which is the latest recommendation.

That comes straight from specref: https://www.specref.org/?q=png

As far as I'm aware, we can't override it unless we devise a new reference name (png-2?) and put it in a local biblio file -- or hack some javascript to post-process the specification.

**Comment by iherman** [comment]
Publication request sent: https://lists.w3.org/Archives/Team/webreq/2023May/0019.html

**Comment by iherman** [comment]
Recommendations published, see, e.g., https://www.w3.org/2023/05/pressrelease-epub33-rec.html.en

Closing.
