### ISSUE TITLE
FPWD Request for Verifiable Credentials JSON Schema Specification 2023

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#507]
# Document title, URLs, estimated publication date

Title: Verifiable Credentials JSON Schema Specification 2023
- URL: https://www.w3.org/TR/2023/WD-vc-json-schema-20230523/
- Expected Publication date 2023 May 23
- short name: vc-json-schema

# Abstract
See https://www.w3.org/TR/2023/WD-vc-json-schema-20230523/#abstract

# Status
See https://www.w3.org/TR/2023/WD-vc-json-schema-20230523/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-05-17-vcwg#resolution1

# Information about implementations known to the Working Group
There are experimental implementations, not yet in production

---

cc @brentzunel @sakurann @decentralgabe @OR13 @andresuribe87

**Comment by marcoscaceres** [comment]
Nothing against Verifiable Credentials, but having a spec for a JSON schema seems odd to me? It be like having a spec for a jpeg photo. 

Isn’t it just a schema for an existing specification? Why not just publish the schema itself (which is just JSON). 

That’s what we do with Web Manifest and it’s just maintained independently. The main spec just references it non-normatively. 

https://www.w3.org/TR/appmanifest/#json-schema

**Comment by decentralgabe** [comment]
@marcoscaceres because the VCDM uses JSON-LD you need to define types to extend it. This spec exists to define a type to use JSON Schema.

**Comment by iherman** [comment]
> current link can be found here https://w3c.github.io/vc-json-schema/FPWD/2023-05-23/

The document has also be uploaded to its "official" URL.

**Comment by iherman** [comment]
> @marcoscaceres because the VCDM uses JSON-LD you need to define types to extend it. This spec exists to define a type to use JSON Schema.

To make @decentralgabe's answer maybe a bit more general: a VC uses a vocabulary for its data model, and other vocabularies defined in other specifications specified by the WG for other functionalities (like signatures), to result in a standard data structure that can be used by different serializations. This FPWD adds two classes to that vocabulary for the purpose of linking to JSON schemas.

**Comment by plehegar** [comment]
Only section 2 and 3 are normative.

Section 3 is a registry. 

Section 2 defines 2 URLs. Again, this feels like registry entries.

The fact is that the entire Section 4 Processing is non-normative so I don't know what we expect from implementations that could be validated during the CR phase.

It seems to me that a better way would be to publish it on the Note track to become a Statement or on the Registry track to become a Registry.

editorial: abstract contains "... are the that of of verifiability ..."

**Comment by decentralgabe** [comment]
@plehegar please keep in mind this is just a FPWD. We have discussed making more sections normative. If you would prefer we do that sooner, happy to make the processing section normative now.

In fact, the types will be registered in our [VC Specs Directory](https://w3c.github.io/vc-specs-dir/), as an earlier draft of the spec from the CCG was ([there's a PR to do that here](https://github.com/w3c/vc-specs-dir/pull/19)).

To use these registered types, they need to be normatively defined _somewhere_ which is the purpose of the spec. Quite similar to [VC Status List 2021](https://w3c.github.io/vc-status-list-2021/) and the [BBS Cryptosuite 2023](https://w3c.github.io/vc-di-bbs/).

The goal is being able to normatively create and use Verifiable Credentials that make use of JSON Schema. Without this going through, I do not see how that is achievable.

**Comment by plehegar** [comment]
@decentralgabe thank you for the clarifications. That makes sense. 

Approved to be published on the Recommendation track.

**Comment by iherman** [comment]
Publication request sent: https://lists.w3.org/Archives/Team/webreq/2023May/0016.html

**Comment by iherman** [comment]
Publication done https://www.w3.org/TR/vc-json-schema/

closing
