### ISSUE TITLE
CR Request for UI Events KeyboardEvent code Values

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#508]
# Document title, URLs, estimated publication date
UI Events KeyboardEvent code Values
https://www.w3.org/TR/uievents-code/
30 May 2023

# Abstract
This specification defines the values for the KeyboardEvent.code attribute, which is defined as part of the UI Events Specification [UIEvents]. The code value contains information about the key event that can be used to identify the physical key being pressed by the user.

# Status

This document was published by the [Web Applications Working Group](https://www.w3.org/groups/wg/webapps) as a Candidate Recommendation Snapshot using the [Recommendation track](https://www.w3.org/2021/Process-20211102/#recs-and-notes).
Publication as a Candidate Recommendation does not imply endorsement by W3C and its Members. A Candidate Recommendation Snapshot has received [wide review](https://www.w3.org/2021/Process-20211102/#dfn-wide-review), is intended to gather [implementation experience](https://w3c.github.io/uievents-code/impl-report.html), and has commitments from Working Group members to [royalty-free licensing](https://www.w3.org/Consortium/Patent-Policy/#sec-Requirements) for implementations.Future updates to this specification may incorporate [new features](https://www.w3.org/2021/Process-20211102/#allow-new-features).

This Candidate Recommendation is not expected to advance to Proposed Recommendation any earlier than 27 June 2023.

This document was produced by a group operating under the [W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy/). W3C maintains a [public list of any patent disclosures](https://www.w3.org/groups/wg/webapps/ipr) made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains [Essential Claim(s)](https://www.w3.org/Consortium/Patent-Policy/#def-essential) must disclose the information in accordance with [section 6 of the W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy/#sec-Disclosure).

This document is governed by the [2 November 2021 W3C Process Document](https://www.w3.org/2021/Process-20211102/).

# Link to group's decision to request transition
https://github.com/w3c/uievents-code/issues/40

# Changes
None. All the changes are editorial.

# Requirements satisfied
None.

# Dependencies met (or not)
This document has normative references to the UIEvents spec, which is still a WD but has been widely implemented.

# Wide Review
https://github.com/w3c/uievents-code/issues/35#issuecomment-1330866968
The groups requested another wide review in 2022.

# Issues addressed
https://github.com/w3c/uievents-code/issues
All the technical issues have been addressed.

# Formal Objections
None.

# Implementation
https://w3c.github.io/uievents-code/impl-report.html

# Patent disclosures
https://www.w3.org/2004/01/pp-impl/83482/status 
This spec was previously published as a CR in the WebPlatform WG. This publication is intended to trigger a CfE in the WebApps WG.

**Comment by plehegar** [comment]
Approved

**Comment by siusin** [comment]
https://www.w3.org/TR/2023/CR-uievents-code-20230530/
