### ISSUE TITLE
[CSSWG] Proposal to supersede CSS2

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#51]
# title, URL of the document to be superseded
Cascading Style Sheets, level 2 CSS2 Specification
[https://www.w3.org/TR/REC-CSS2/](https://www.w3.org/TR/REC-CSS2/)

# title, URL of the newer version
Cascading Style Sheets Level 2 Revision 2 (CSS 2.2) Specification
[https://www.w3.org/TR/CSS22/](https://www.w3.org/TR/CSS22/)

# Link to group's decision to request superseding
> Use CSS 2.2 for the next REC track revision of CSS 2.1, and then append "2nd edition", "3rd edition" etc. for subsequent Edited Recommendations.

[Minutes of 12 April CSS f2f meeting ](https://www.w3.org/2018/04/12-css-minutes.html#item38)
[Naming of revision of CSS 2.1](https://github.com/w3c/csswg-drafts/issues/2008)

# Rationale
CSS 2.1 consisted of the interoperable parts of CSS 2, with much clearer and more precise specification text and better testing. The non-interoperable parts were split into CSS 3 modules and have been separately progressed. Thus, we want anyone linking to the 1998 CSS2 Recommendation to know they are looking in the wrong place.
CSS 2.2 is CSS 2.1 plus errata, and is the current best source of CSS 2 information.

# Implementation
Widely implemented by every browser since CSS 2.1 was published in 2011.

**Comment by fantasai** [comment]
My understanding was that the group decided that /TR/REC-CSS2/ should alias to /TR/CSS2/ and that no further process efforts were needed. This was a webreq request only, not a transition request.

**Comment by fantasai** [comment]
The CSSWG merged CSS21 under the CSS2 shortname already (the same as it merged css-grid-layout-1 under css-grid). From W3C's perspective, these should now be the same specification, and the matter is just about making sure that W3C's systems (URL rewriting, TR data) reflect that fact.

**Comment by plehegar** [comment]
I believe the request is actually about http://www.w3.org/TR/1998/REC-CSS2-19980512 .
@svgeesus , can you confirm?

**Comment by fantasai** [comment]
@plehegar If that was the issue, then we'd need to supersede every dated copy of a REC which has since been updated to make it clear that it's an outdated version of that specification. I'm pretty sure the Superseded status is not intended for doing that, it's intended for end-of-lifing a specification which has been superseded by a different specification, e.g. CSS1 (which is no longer maintained) by CSS2 (which is).

We do need to deal with /TR/REC-CSS2 which was supposed to have been redirected to /TR/CSS2, but redirection is not the same thing as a transition request to supersede.

**Comment by plehegar** [comment]
agreed. So, my latest understanding is:

1. Redirect /TR/REC-CSS2 to /TR/CSS2
2. the CSS Working Group will retire CSS 2.2 at some point.
3. No action is needed for  http://www.w3.org/TR/1998/REC-CSS2-19980512

Correct?

**Comment by fantasai** [comment]
Correct!

**Comment by plehegar** [comment]
yes, webreq is enough.

**Comment by plehegar** [comment]
Closing since this is no longer a transition
