### ISSUE TITLE
FPWD Request for 2 specifications from the RDF-star WG

### ISSUE THREAD

**Issue by pchampin** [w3c/transitions#511]
# Common information

* Estimated publication date:
  + 2023-06-06
* Is it a delta specification intended to become a W3C Recommendation?
  + no
* WG decision
  + https://www.w3.org/2023/05/25-rdf-star-minutes.html#r02
* Information about implementations known to the Working Group:
  + CG implementation reports: https://w3c.github.io/rdf-star/reports/

# Document specifc information

Title:    RDF 1.2 Semantics
URL:      https://w3c.github.io/rdf-semantics/publication-snapshots/FPWD/Overview.html
Abstract: https://w3c.github.io/rdf-semantics/publication-snapshots/FPWD/Overview.html#abstract
Status:   https://w3c.github.io/rdf-semantics/publication-snapshots/FPWD/Overview.html#sotd

Title:    SPARQL 1.2 Entailment Regimes
URL:      https://w3c.github.io/sparql-entailment/publication-snapshots/FPWD/Overview.html
Abstract: https://w3c.github.io/sparql-entailment/publication-snapshots/FPWD/Overview.html#abstract
Status:   https://w3c.github.io/sparql-entailment/publication-snapshots/FPWD/Overview.html#sotd

**Comment by plehegar** [comment]
https://www.w3.org/TR/2023/WD-rdf12-semantics-20230615/
https://www.w3.org/TR/2023/WD-sparql12-entailment-20230615/
