### ISSUE TITLE
[CSSWG] FPNote request for css-2018

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#54]
# Document title, URLs, estimated publication date

**CSS Snapshot 2018**
https://drafts.csswg.org/css-2018/
next tues or thurs after transition decision

# Abstract

This document collects together into one definition all the specs that together form the current state of Cascading Style Sheets (CSS) as of 2018. The primary audience is CSS implementers, not CSS authors, as this definition includes modules by specification stability, not Web browser adoption rate.
CSS is a language for describing the rendering of structured documents (such as HTML and XML) on screen, on paper, in speech, etc. 

# Status

https://drafts.csswg.org/css-2018/#status (as ED)

# Link to group's decision to request transition

https://github.com/w3c/csswg-drafts/issues/2388#issuecomment-380003405

# Information about implementations known to the Working Group

All of this is implemented

**Comment by plehegar** [comment]
Transition approved.

**Comment by svgeesus** [comment]
Some broken links, working with editor to fix

**Comment by svgeesus** [comment]
@florian

**Comment by svgeesus** [comment]
@florian

**Comment by svgeesus** [comment]
@frivoal which of the [three open issues on Snapshot 2018](https://github.com/w3c/csswg-drafts/labels/snapshot-2018) need to be fixed before publication? One of them is marked as "needs edits". Shoud the other two be discussed on a call?

**Comment by frivoal** [comment]
We're down to two, and I've put both of them on agenda+.

**Comment by svgeesus** [comment]
Thanks, @frivoal

**Comment by frivoal** [comment]
We're down to 0 open issues. Publish away.

Note: We have not (yet) reached agreement on doing away with the current dated shortname scheme, so (for this year at least) do publish under `TR/css-2018/`

**Comment by plehegar** [comment]
@svgeesus @xfq , friendly ping on this one. This seems good to go.

**Comment by svgeesus** [comment]
Thanks plh, have been chasing @frivoal for a while now but missed the 0 issues notice.

**Comment by svgeesus** [comment]
Preparing for Thursday 15 Nov, have corrected status boilerplate etc for a 2018 WG Note. Pubrules happy except [still 12 broken links](https://validator.w3.org/checklink?uri=https://www.w3.org/TR/2018/NOTE-css-2018-20181115/&recursive=on) to other csswg specs.

**Comment by svgeesus** [comment]
Just for archiving:

error Lines: 423, 795, 864, 1122, 1170, 1497, 1862 https://www.w3.org/TR/css-flexbox-1/
    Status: 200 OK

    Some of the links to this resource point to broken URI fragments (such as index.html#fragment). 
    Broken fragments:

        https://www.w3.org/TR/css-flexbox-1/#content-size (line 864)
        https://www.w3.org/TR/css-flexbox-1/#automatic-minimum-size (line 795)
        https://www.w3.org/TR/css-flexbox-1/#transferred-size (line 1170)
        https://www.w3.org/TR/css-flexbox-1/#specified-size (line 1122)
        https://www.w3.org/TR/css-flexbox-1/#valdef-min-width-auto (line 1497)

error Lines: 790, 831, 892, 956, 1080, 1087, 1116 https://drafts.csswg.org/css-syntax-3/
    Status: 200 OK

    Some of the links to this resource point to broken URI fragments (such as index.html#fragment). 
    Broken fragments:

        https://drafts.csswg.org/css-syntax-3/#css-at-rule (line 790)
        https://drafts.csswg.org/css-syntax-3/#css-qualified-rule (line 1087)
        https://drafts.csswg.org/css-syntax-3/#css-declaration (line 892)
        https://drafts.csswg.org/css-syntax-3/#css-preserved-tokens (line 1080)
        https://drafts.csswg.org/css-syntax-3/#css-function (line 956)
        https://drafts.csswg.org/css-syntax-3/#css-simple-block (line 1116)
        https://drafts.csswg.org/css-syntax-3/#css-component-value (line 831)

**Comment by frivoal** [comment]
These errors were all in links generated by bikeshed, and should go away by just reruning bikeshed. That should happen automatically, but may have been blocked by a fatal error due to css-timing-1 being renamed into css-easing-1, and bikeshed not finding the old name anymore. I'm fixing that, will try pubrules' link checker afterwards, and will report back.

**Comment by frivoal** [comment]
Seems fine now: https://validator.w3.org/checklink?uri=https%3A%2F%2Fdrafts.csswg.org%2Fcss-2018%2F&hide_type=all&recursive=on&depth=&check=Check

**Comment by svgeesus** [comment]
Yeah after a bikeshed update, I am now getting that same fatal error

```
$ bikeshed spec
FATAL ERROR: Unknown spec name 'css-timing-1' on <index type="dfn" data-link-status="TR" data-link-spec="
        css2,
        css-syntax-3,
        css-style-attr-1,
        mediaqueries-3,
        mediaqueries-4,
        css-conditional-3,
        css-namespaces-3,
        selectors-3,
        css-cascade-3,
        css-cascade-4,
        css-values-3,
        css-color-3,
        css-backgrounds-3,
        css-images-3,
        css-fonts-3,
        css-multicol-1,
        css-ui-3,
        compositing-1,
        css-writing-modes-3,
        css-transitions-1,
        css-animations-1,
        css-timing-1,
        css-flexbox-1,
        css-transforms-1,
        css-variables-1,
        css-text-3,
        css-counter-styles-3,
        css-masking-1,
        css-shapes-1,
        css-text-decor-3,
        css-will-change-1,
        css-speech-1,
        css-align-3,
        css-grid-1,
        filter-effects-1,
        css-break-3,
        css-contain-1,
        css-scroll-snap-1"></index>
 ✘  Did not generate, due to fatal errors
```

Will continue to investigate.

**Comment by frivoal** [comment]
please pick up the updated Overview.bs I made a few hours ago, it resolves that issue.

**Comment by svgeesus** [comment]
Yes, I have now done that (and re-applied my .bs edits on that) and then generated the .html (and re-applied my html edits on top of _that_) and now it all works. Phew!

**Comment by svgeesus** [comment]
([bikeshed should make  CSSWG NOTEs wth actual status sections, now](https://github.com/tabatkins/bikeshed/pull/1391))

**Comment by frivoal** [comment]
> and re-applied my .bs edits on that

What are these? Send a PR?

**Comment by svgeesus** [comment]
not needed:

```
TR: https://www.w3.org/TR/css-2018/
Date: 2018-11-15
Prepare for TR: yes
```
The html edits were more extensive (see patch above, now merged) and also deleting spurious ``-0-` level in the middle of the URL.

**Comment by svgeesus** [comment]
All good, publication request sent, expected publication tomorrow

**Comment by svgeesus** [comment]
[Published 15 Nov 2018](https://www.w3.org/TR/2018/NOTE-css-2018-20181115/)
