### ISSUE TITLE
PR Request for Web of Things (WoT) Architecture 1.1

### ISSUE THREAD

**Issue by mmccool** [w3c/transitions#552]
Ready for review.

# Document title, URLs, estimated publication date
- Title: Web of Things (WoT) Architecture 1.1
- https://www.w3.org/TR/wot-architecture11/
- Update from https://www.w3.org/TR/2023/CR-wot-architecture11-20230119/ to new version at https://github.com/w3c/wot-architecture/blob/main/publication/ver11/4-pr/Overview.html
- See also diff at https://github.com/w3c/wot-architecture/blob/main/publication/ver11/4-pr/diff.html
- Rendered versions of above new versions:
    - https://w3c.github.io/wot-architecture/publication/ver11/4-pr/Overview.html
    - https://w3c.github.io/wot-architecture/publication/ver11/4-pr/diff.html

# Abstract
<p>The <abbr title="World Wide Web Consortium">W3C</abbr> Web of
Things (WoT) enables interoperability across IoT platforms and
application domains. The goal of the WoT is to preserve and
complement existing IoT standards and solutions. The <abbr title=
"World Wide Web Consortium">W3C</abbr> WoT architecture is designed
to describe what exists, and only prescribes new mechanisms when
necessary.</p>
<p>This <em>WoT Architecture</em> specification describes the
abstract architecture for the <abbr title=
"World Wide Web Consortium">W3C</abbr> Web of Things. This abstract
architecture is based on requirements that were derived from use
cases for multiple application domains. Several modular building
blocks were identified whose detailed specifications are given in
other documents. This document describes how these building blocks
are related and work together. The WoT abstract architecture
defines a basic conceptual framework that can be mapped onto a
variety of concrete deployment scenarios, several examples of which
are given. However, the abstract architecture described in this
specification does not itself define concrete mechanisms or
prescribe any concrete implementation.</p>

# Status
- CR review period started 2023.01.19, ended 2023.06.08.
- Requesting transition to PR status.
- All issues in repository either addressed by document or marked for resolution in future versions of the document.

# Will new features be allowed to be incorporated in the Recommendation?
- No new normative features will be added to the PR before transition to Recommendation.
- Based on feedback during the review period, we may add or modify informative content.
- Future versions of the specification (e.g. 1.2, 2.0) may add new normative content.  The following statement has been added to the Status of this Document section: "Future updates to this specification may incorporate [new features](https://www.w3.org/2021/Process-20211102/#allow-new-features).", but our understanding is that this refers to completely new versions, not differences between the PR and Recommendation versions.

# Link to group's decision to request transition
[WoT Minutes June 7 - Resolution 1](https://www.w3.org/2023/06/07-wot-minutes.html#r01)

# Changes
- No new assertions added; some at-risk assertions removed due to insufficient implementation, others had testing resolved during CR period.  Please see diff (links above)

# Requirements satisfied
- Overall description of WoT abstract architecture
- Central location for security and privacy assertions
- Explanation of new normative deliverables, e.g. Discovery, and how they fit into WoT Architecture.

# Dependencies met (or not)

# Wide Review
Completed:
- Internationalization
- TAG
- Security
- Privacy
- Accessibility

# Issues addressed
See https://github.com/w3c/wot-architecture/issues?q=is%3Aissue+is%3Aclosed and https://github.com/w3c/wot-architecture/labels/by%20PR%20transition. 

# Formal Objections
None.

# Implementation
- Implementation report (rendered version) is at https://w3c.github.io/wot-architecture/testing/report11.html.
- Github repo location (source for the above): https://github.com/w3c/wot-architecture/blob/main/testing/report11.html
    
# Patent disclosures
None

**Comment by plehegar** [comment]
There is a new a11y section in the specification. Was the loop properly closed with APA? cc @michael-n-cooper   @ruoxiran

**Comment by ruoxiran** [comment]
> There is a new a11y section in the specification. Was the loop properly closed with APA? cc @michael-n-cooper @ruoxiran

Yes, APA has reviewed and approved this document. Thanks.

**Comment by plehegar** [comment]
Approved

**Comment by ashimura** [comment]
working with the Webmaster to publish the Proposed REC on July 6

**Comment by ashimura** [comment]
The expected Proposed Recommendation was published on July 11.

Please see: https://www.w3.org/TR/2023/PR-wot-architecture11-20230711/
