### ISSUE TITLE
PR Request for Web of Things (WoT) Discovery

### ISSUE THREAD

**Issue by mmccool** [w3c/transitions#553]
Ready for review.

# Document title, URLs, estimated publication date
- Title: Web of Things (WoT) Discovery
- https://www.w3.org/TR/wot-discovery/
- Update from https://www.w3.org/TR/2023/CR-wot-discovery-20230119/ to new version at https://github.com/w3c/wot-discovery/blob/main/publication/5-pr/Overview.html
- See also diff at https://github.com/w3c/wot-discovery/blob/main/publication/5-pr/diff.html
- Rendered versions of above new versions:
    - https://w3c.github.io/wot-discovery/publication/5-pr/Overview.html
    - https://w3c.github.io/wot-discovery/publication/5-pr/diff.html

# Abstract
<p>The <abbr title="World Wide Web Consortium">W3C</abbr> Web of
Things (WoT) is intended to enable interoperability across IoT
platforms and application domains. One key mechanism for
accomplishing this goal is the definition and use of metadata
describing the interactions an IoT device or service makes
available over the network at a suitable level of abstraction. The
WoT Thing Description specification satisfies this objective.</p>
<p>However, in order to use a Thing its Thing Description first has
to be obtained. The <em>WoT Discovery</em> process described in
this document addresses this problem. WoT Discovery needs to
support the distribution of WoT Thing Descriptions in a variety of
use cases. This includes ad-hoc and engineered systems; during
development and at runtime; and on both local and global networks.
The process also needs to work with existing discovery mechanisms,
be secure, protect private information, and be able to efficiently
handle updates to WoT Thing Descriptions and the dynamic and
diverse nature of the IoT ecosystem.</p>
<p>The WoT Discovery process is divided into two phases,
Introduction, and Exploration. The Introduction phase leverages
existing discovery mechanisms but does not directly expose
metadata; they are simply used to discover Exploration services,
which provide metadata but only after secure authentication and
authorization. This document normatively defines two Exploration
services: for distributing a single WoT Thing Description from a
regular web service, including as a special case self-description;
and a searchable WoT Thing Description Directory service for
collections of Thing Descriptions. A variety of Introduction
services are also described and where necessary normative
definitions are given to support them.</p>

# Status
- CR review period started 2023.01.19, ended 2023.06.08.
- Requesting transition to PR status.
- All issues in repository either addressed by document or marked for resolution in future versions of the document.

# Will new features be allowed to be incorporated in the Recommendation?
- No new normative features will be added to the PR before transition to Recommendation.
- Based on feedback during the review period, we may add or modify informative content.
- Future versions of the specification (e.g. 1.2, 2.0) may add new normative content.  The following statement has been added to the Status of this Document section: "Future updates to this specification may incorporate [new features](https://www.w3.org/2021/Process-20211102/#allow-new-features).", but our understanding is that this refers to completely new versions, not differences between the PR and Recommendation versions.

# Link to group's decision to request transition
[WoT Minutes June 7 - Resolution 2](https://www.w3.org/2023/06/07-wot-minutes.html#r02)

# Changes
- No new assertions added; some at-risk assertions removed due to insufficient implementation, others had testing resolved during CR period.  Please see diff (links above)

# Requirements satisfied
- Process defined for accessing Thing metadata (Thing Descriptions) in both local and global network contexts, while maintaining access controls for security and privacy

# Dependencies met (or not)

# Wide Review
Completed:
- Internationalization
- TAG
- Security
- Privacy
- Accessibility

# Issues addressed
See https://github.com/w3c/wot-discovery/issues?q=is%3Aissue+is%3Aclosed and https://github.com/w3c/wot-discovery/labels/resolve%20by%20PR.

# Formal Objections
None.

# Implementation
- Implementation report (rendered version) is at https://w3c.github.io/wot-discovery/testing/report.html.
- Github repo location (source for the above): https://github.com/w3c/wot-discovery/blob/main/testing/report.html.

# Patent disclosures
None

**Comment by ashimura** [comment]
The expected Proposed Recommendation was published on July 11.

Please see: https://www.w3.org/TR/2023/PR-wot-discovery-20230711/
