### ISSUE TITLE
PR Request for Web of Things (WoT) Thing Description 1.1

### ISSUE THREAD

**Issue by mmccool** [w3c/transitions#554]
Ready for review.

# Document title, URLs, estimated publication date
- Title: Web of Things (WoT) Thing Description 1.1
- https://www.w3.org/TR/wot-thing-description11/
- Update from https://www.w3.org/TR/2023/CR-wot-thing-description11-20230119/ to new version at https://github.com/w3c/wot-thing-description/blob/main/publication/ver11/6-pr/Overview.html
- See also diff at https://github.com/w3c/wot-thing-description/blob/main/publication/ver11/6-pr/diff.html
- Rendered versions of above new versions:
    - https://w3c.github.io/wot-thing-description/publication/ver11/6-pr/Overview.html
    - https://w3c.github.io/wot-thing-description/publication/ver11/6-pr/diff.html

# Abstract
<p>This document describes a formal information model and a
    common representation for a Web of Things (WoT) Thing
    Description 1.1. A Thing Description describes the metadata and
    interfaces of Things, where
    a Thing is an abstraction of a
    physical or virtual entity that provides interactions to and
    participates in the Web of Things. Thing Descriptions provide a
    set of interactions based on a small vocabulary that makes it
    possible both to integrate diverse devices and to allow diverse
    applications to interoperate. Thing Descriptions, by default,
    are encoded in a JSON format that also allows JSON-LD
    processing. The latter provides a powerful foundation to
    represent knowledge about Things in a machine-understandable
    way. A Thing Description instance can be hosted by the Thing itself or hosted externally
    when a Thing has resource
    restrictions (e.g., limited memory space) or when a Web of
    Things-compatible legacy device is retrofitted with a Thing
    Description. Furthermore, this document introduces the Thing
    Model, which allows authors to describe only the model or class
    of an Internet of Things (IoT) entity. Thing Models can be seen
    as a template for Thing Description instances, but with reduced
    constraints such as no or few requirements for specific
    communication metadata.</p>
    <p>This specification describes a superset of the features
    defined in Thing Description 1.0.
    Unless otherwise specified, documents created with version 1.0
    of this specification remain compatible with Thing Description
    1.1.</p>

# Status
- CR review period started 2023.01.19, ended 2023.06.08.
- Requesting transition to PR status.
- All issues in repository either addressed by document or marked for resolution in future versions of the document.

# Will new features be allowed to be incorporated in the Recommendation?
- No new normative features will be added to the PR before transition to Recommendation.
- Based on feedback during the review period, we may add or modify informative content.
- Future versions of the specification (e.g. 1.2, 2.0) may add new normative content.  The following statement has been added to the Status of this Document section: "Future updates to this specification may incorporate [new features](https://www.w3.org/2021/Process-20211102/#allow-new-features).", but our understanding is that this refers to completely new versions, not differences between the PR and Recommendation versions.

# Link to group's decision to request transition
[WoT Minutes June 7 - Resolution 3](https://www.w3.org/2023/06/07-wot-minutes.html#r03)

# Changes
- No new assertions added; some at-risk assertions removed due to insufficient implementation, others had testing resolved during CR period.  Please see diff (links above)

# Requirements satisfied
- Information model and serialization format for WoT Thing Description 1.1, with various improvements over the first (1.0) version of WoT Thing Description

# Dependencies met (or not)

# Wide Review
Completed:
- Internationalization
- TAG
- Security
- Privacy
- Accessibility

# Issues addressed
See https://github.com/w3c/wot-thing-description/issues?q=is%3Aissue+is%3Aclosed and https://github.com/w3c/wot-thing-description/labels/by%20PR%20transition. 

# Formal Objections
None.

# Implementation
- Implementation report (rendered version) is at https://w3c.github.io/wot-thing-description/testing/report11.html.
- Github repo location (source for the above): https://github.com/w3c/wot-thing-description/blob/main/testing/report11.html.
    
# Patent disclosures
None

**Comment by plehegar** [comment]
Approved

**Comment by ashimura** [comment]
working with the Webmaster to publish the Proposed REC on July 6

**Comment by ashimura** [comment]
The expected Proposed Recommendation was published on July 11.

Please see: https://www.w3.org/TR/2023/PR-wot-thing-description11-20230711/
