### ISSUE TITLE
CR Request for IMSC Hypothetical Render Model (imsc-hrm)

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#555]
# Document title, URLs, estimated publication date
IMSC Hypothetical Render Model
TR: https://www.w3.org/TR/imsc-hrm/
ED: https://w3c.github.io/imsc-hrm/spec/imsc-hrm.html

# Abstract
https://w3c.github.io/imsc-hrm/spec/imsc-hrm.html#abstract

# Status
https://w3c.github.io/imsc-hrm/spec/imsc-hrm.html#sotd

Note, WG has one open PR, and SoTD will be updated as 
https://pr-preview.s3.amazonaws.com/w3c/imsc-hrm/pull/59.html#sotd

# Link to group's decision to request transition
CfC: https://lists.w3.org/Archives/Public/public-tt/2023May/0007.html
Resolution: https://www.w3.org/2023/06/08-tt-minutes.html#r01

# Changes
https://w3c.github.io/imsc-hrm/spec/imsc-hrm.html#substantive-changes-summary

# Requirements satisfied
IMSC-HRM was initially developed as a part of IMSC recommendation, so requirements are satisfied during IMSC development.

# Dependencies met (or not)
yes

# Wide Review
tag: https://github.com/w3ctag/design-reviews/issues/788
a11y: https://github.com/w3c/a11y-request/issues/19
i18n: https://github.com/w3c/i18n-request/issues/167
privacy: https://github.com/w3cping/privacy-request/issues/65
security: https://github.com/w3c/security-request/issues/18 (no action taken)

# Issues addressed
issues were addressed as:
https://github.com/w3c/imsc-hrm/issues?q=is%3Aissue+is%3Aclosed

# Formal Objections
none

# Implementation
WG plans to update one open source validator implementation of IMSC-HRM, to match with implementation requirement described in [proposed SoTD](https://pr-preview.s3.amazonaws.com/w3c/imsc-hrm/pull/59.html#sotd).

# Patent disclosures
https://www.w3.org/groups/wg/timed-text/ipr

/cc @nigelmegitt @gkatsev @palemieux

**Comment by plehegar** [comment]
https://www.w3.org/TR/2023/CR-imsc-hrm-20230622/
