### ISSUE TITLE
[CSSWG] PR request for css-fonts-3

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#56]
# Document title, URLs, estimated publication date

CSS Fonts Module Level 3
https://drafts.csswg.org/css-fonts-3/
Next available Tues or Thurs after Transition decision

# Abstract

This CSS3 module describes how font properties are specified and how font resources are loaded dynamically. The contents of this specification are a consolidation of content previously divided into CSS3 Fonts and CSS3 Web Fonts modules. The description of font load events was moved into the CSS Font Loading module. 

# Status

https://drafts.csswg.org/css-fonts-3/#status (as ED)

# Link to group's decision to request transition

16:16:48 [dael]
    RESOLVED: Request transition to proposed rec for Fonts L3
https://www.w3.org/2018/06/20-css-irc#T16-16-32

# Changes

https://drafts.csswg.org/css-fonts-3/#recent-changes

# Requirements satisfied

(No requirements document)

# Dependencies met (or not)

[CSS-VALUES-3]  is in CR
All other normative references at Rec or equivalent (IETF Proposed Standard, ISO standard, etc)
[HTML5] is referenced.

# Wide Review

[15 March 2018 Updated Candidate Recommendation](https://www.w3.org/TR/2018/CR-css-fonts-3-20180315/) listed some features at risk, which are now dropped from Fonts 3 (moved to Fonts 4)

# Issues addressed

See Disposition of Comments for issued raised since the March 2018 CR
https://drafts.csswg.org/issues?spec=css-fonts-3&doc=pr-2018

# Formal Objections

None

# Implementation

Widely implemented by all major browsers. Test suite shows 474 tests, all with at least two passing implementations
https://test.csswg.org/harness/results/css-fonts-3_dev/grouped/

# Patent disclosures

None
https://www.w3.org/2004/01/pp-impl/32061/status

**Comment by svgeesus** [comment]
From https://lists.w3.org/Archives/Member/chairs/2018AprJun/0125.html

> While reviewing this we discovered an oversight in Section 3.5 Font size; the normative definition of length-percentage is missing (as it appears in the Fonts Level 4 editor's draft).  This needs to be fixed before this spec can replace the previous Recommendation.

> Please send a transition request to update the CR.

> There was one other substantive change in 4.3 that will be covered by this updated CR as well.

> There are some normative references that should be updated as well.

> Assuming these changes are made, the updated CR is approved.

**Comment by svgeesus** [comment]
Closed by https://github.com/w3c/transitions/issues/57

**Comment by svgeesus** [comment]
CR resulted in no comments. Can we now move forward to PR?

**Comment by plehegar** [comment]
Re exclusion period, no, you don't need to wait:
[[
[...] the deadline for Advisory Committee review [...] should be at least 10 days after the end of the last Exclusion Opportunity per section 4 of the W3C Patent Policy
]]
https://www.w3.org/2018/Process-20180201/#rec-pr

With your CR published on June 26, you can follow this timeline:
 https://w3c.github.io/spec-releases/milestones/?cr=2018-06-26&noFPWD=true

You'll get approval to move to PR this Friday, unless the Director has questions.

**Comment by swickr** [comment]
Transition approved.

**Comment by svgeesus** [comment]
(Preliminary) publication request sent 9 Aug. WBS prepared. Comm draft sent.

**Comment by svgeesus** [comment]
(Preliminary) publication request sent 9 Aug. WBS prepared. Comm draft sent.

**Comment by xfq** [comment]
[PR published](https://www.w3.org/TR/2018/PR-css-fonts-3-20180814/).
