### ISSUE TITLE
CR Request for  css-view-transitions-1

### ISSUE THREAD

**Issue by khushalsagar** [w3c/transitions#561]
CSS View Transitions L1 is ready to transition to CR. See discussion at https://github.com/w3c/csswg-drafts/issues/8878.

# Document title, URLs, estimated publication date
CSS View Transitions Module Level 1.

# Abstract
This module defines the View Transition API, along with associated properties and pseudo-elements. View Transitions is a feature that allows developers to create animated transitions between visual states of the [document](https://dom.spec.whatwg.org/#concept-document).

# Status
Status is [here](https://www.w3.org/TR/css-view-transitions-1/#sotd).

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/www-style/2023Aug/0001.html

# Changes
Changes since FPWD are documented [here](https://www.w3.org/TR/css-view-transitions-1/#changes).

# Requirements satisfied
Yes.

# Dependencies met (or not)
N/A

# Wide Review
Horizontal reviews are tracked [here](https://github.com/w3c/csswg-drafts/issues/8109).

The [Mozilla RFP](https://github.com/mozilla/standards-positions/issues/677) and [Webkit RFP](https://github.com/WebKit/standards-positions/issues/48) are additional links for cross-browser review.

# Issues addressed
List of issues addressed in this spec is [here](https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+label%3Acss-view-transitions-1).

# Formal Objections
None

# Implementation
Blink implementation is spec compliant. WPTs for the module are [here](https://wpt.fyi/results/css/css-view-transitions?label=master).

# Patent disclosures
None. The spec is listed in ipr [here](https://www.w3.org/groups/wg/css/ipr#:~:text=CSS%20View%20Transitions%20Module%20Level%201)

# Additional Notes
None

@svgeesus

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Draft transition announcement sent to comm team.

@plehegar please edit your approval comment to the exact string "Transition approved." which apparently Echidna needs.

**Comment by xueyuanjia** [comment]
draft transition received.

**Comment by plehegar** [comment]
> @plehegar please edit your approval comment to the exact string "Transition approved." which apparently Echidna needs.

done

**Comment by svgeesus** [comment]
publication requested (manually) 3 Sept expected 5 Sept

**Comment by svgeesus** [comment]
[Published 5 Sept](https://www.w3.org/TR/2023/CR-css-view-transitions-1-20230905/)

**Comment by khushalsagar** [comment]
I'm using bikeshed to do an automatic CR snapshot for this but its stuck on "update-tr-shortlink". @plehegar does this need some manual approval? @tabatkins @svgeesus fyi.

**Comment by plehegar** [comment]
@khushalsagar , I don't see a trace of your attempt in https://lists.w3.org/Archives/Public/public-tr-notifications/2024Mar/ . So, you're getting the error earlier on. Can you point to where you see the error online ?

**Comment by khushalsagar** [comment]
Sure, this is the link I got from bikeshed for tracking status: https://labs.w3.org/echidna/api/status?id=de363264-d5ed-42cd-9cc9-3f7ab0ad125b.
