### ISSUE TITLE
First Note request for Catalan Gap Analysis

### ISSUE THREAD

**Issue by r12a** [w3c/transitions#563]
# Document title, URLs, estimated publication date
Catalan Gap Analysis

https://www.w3.org/TR/2023/DNOTE-latn-ca-gap-20230822/Overview.html

22 August 2023

# Abstract
This document describes and prioritises gaps for the support of Catalan on the Web and in eBooks. In particular, it is concerned with text layout. It checks that needed features are supported in W3C specifications, in particular HTML and CSS and those relating to digital publications. It also checks whether the features have been implemented in browsers and ereaders. This is a preliminary analysis.

# Status of the Document
 https://www.w3.org/TR/2023/DNOTE-latn-ca-gap-20230822/Overview.html#sotd

# Link to group's decision to request transition
https://www.w3.org/2023/08/17-i18n-minutes.html#t02

# Is it intended to be a W3C Statement?
No

**Comment by plehegar** [comment]
Approved

**Comment by r12a** [comment]
@plh do you need to reapprove this given that the short name is now latn-ca-gap, rather than latin-ca-gap ?

**Comment by svgeesus** [comment]
[published 22 Aug 2023](https://www.w3.org/TR/2023/DNOTE-latn-ca-gap-20230822/Overview.html)
