### ISSUE TITLE
FPWD Request for CSS Transitions Level 2

### ISSUE THREAD

**Issue by dbaron** [w3c/transitions#564]
# Document title, URLs, estimated publication date
CSS Transitions Level 2
https://drafts.csswg.org/css-transitions-2/
maybe August 29?

# Abstract
https://drafts.csswg.org/css-transitions-2/#abstract

# Status
https://drafts.csswg.org/css-transitions-2/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
yes

# Link to group's decision to request transition
https://logs.csswg.org/irc.w3.org/css/2023-08-23/#e1567884

# Information about implementations known to the Working Group
https://chromestatus.com/feature/4515377717968896
https://chromestatus.com/feature/5071230636392448
(I think there is probably some implementation experience for the web animations integration parts too, but I'm not sure about details.)

**Comment by plehegar** [comment]
Approved

**Comment by dbaron** [comment]
@svgeesus Can you handle requesting publication, or should I do so?

I think the draft should be ready, modulo changing the current `Status: ED` into `Status: FPWD` and `Date: 2023-??-??`, running `bikeshed`, and fixing up the `default.css` link.  (And maybe other fixups that you know but that I've forgotten!)

**Comment by svgeesus** [comment]
@dbaron I can do it; target date will be Tues 5 Sept.
