### ISSUE TITLE
CR Request for PNG Third Edition

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#566]
# Document title, URLs, estimated publication date

Portable Network Graphics (PNG) Specification (Third Edition)
https://w3c.github.io/PNG-spec/
After TPAC moratorium ends

# Abstract
[Abstract](https://w3c.github.io/PNG-spec/#abstract)

# Status
[Status, as ED](https://w3c.github.io/PNG-spec/#sotd)

# Link to group's decision to request transition
[CfC: publish Candidate Recommendation](https://github.com/w3c/PNG-spec/issues/340#issuecomment-1699953334)

# Changes
[Changes since the Working Draft of 20 July 2023 (Third Edition)](https://w3c.github.io/PNG-spec/#F-ChangeList)

# Requirements satisfied
See [Motivating Use Cases](https://github.com/w3c/PNG-spec/blob/main/Third_Edition_Explainer.md#motivating-use-cases) in the Explainer

# Dependencies met (or not)
No change

# Wide Review
[Wide Review of FPWD of PNG, 3rd Edition](https://github.com/w3c/PNG-spec/issues/228)

# Issues addressed
[Issues](https://github.com/w3c/PNG-spec/issues)

# Formal Objections
None

# Implementation
From [the Explainer](https://github.com/w3c/PNG-spec/blob/main/Third_Edition_Explainer.md#stakeholder-feedback--opposition):

-    [Mozilla] : Positive, implements APNG
-    [Chromium] : Positive, implements APNG and CICP
-    [WebKit] : Positive, implements APNG
-    [HDR content creators] : Positive, re-use of existing workflows

Tests for new features are being added to WPT

# Patent disclosures
[None](https://www.w3.org/groups/wg/png/ipr/), no open exclusion opportunity

**Comment by plehegar** [comment]
No needs-resolution horizontal issues: https://www.w3.org/PM/horizontal/review.html?shortname=png

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Thanks for the approval. The PNG WG is aware that publication will happen after the TPAC moratorium ends.

**Comment by svgeesus** [comment]
Publication requested 19 Sept expected 21 Sept

**Comment by svgeesus** [comment]
[Published 21 Sept 2023](https://www.w3.org/TR/2023/CR-png-3-20230921/)
