### ISSUE TITLE
First Note request for "Client-Edge-Cloud coordination Use Cases and Requirements"

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/transitions#568]
# Document title, URLs, estimated publication date
Title: Client-Edge-Cloud coordination Use Cases and Requirements

URL: https://w3c.github.io/edge-computing-web-exploration/
Publication date: as soon as practical

# Abstract

>  This document introduces the use cases and requirements of a client, edge, and cloud coordination mechanism and its standardization. 

# Status of the Document

> This section describes the status of this document at the time of its publication. A list of current W3C publications and the latest revision of this technical report can be found in the [W3C technical reports index](https://www.w3.org/TR/) at https://www.w3.org/TR/.
> 
> This is still a work in progress. The proposal is being incubated in the [W3C Web & Networks Interest Group](https://github.com/w3c/web-networks/).
> 
> This document was published by the [Web & Networks Interest Group](https://www.w3.org/groups/ig/web-networks) as a Group Draft Note using the [Note track](https://www.w3.org/2023/Process-20230612/#recs-and-notes).
> 
> Group Draft Notes are not endorsed by W3C nor its Members.
> 
> This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.
> 
> The [W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy/) does not carry any licensing requirements or commitments on this document.
> 
> This document is governed by the [12 June 2023 W3C Process Document](https://www.w3.org/2023/Process-20230612/).

# Link to group's decision to request transition
https://lists.w3.org/Archives/Member/member-networks-ig/2023Jul/0003.html

# Is it intended to be a W3C Statement?
No

**Comment by plehegar** [comment]
Approved

**Comment by dontcallmedom** [comment]
published at https://www.w3.org/TR/2023/DNOTE-edge-cloud-reqs-20230926/
