### ISSUE TITLE
REC Request for WCAG 2.2

### ISSUE THREAD

**Issue by iadawn** [w3c/transitions#570]
# Link to internal transition

https://lists.w3.org/Archives/Team/w3t-comm/2023Sep/0225.html

# Link to previous transition

#559

**Comment by plehegar** [comment]
[[
Examples of additional content controlled by the user agent include browser tooltips created through use of the HTML [title attribute](https://www.w3.org/TR/html/dom.html#the-title-attribute).
]]

That references the wrong version of the HTML spec. Please update to point to https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute 

Also consider adding the HTML spec as an informative reference.

**Comment by plehegar** [comment]
Section 5 Conformance:

You need to reconcile the differences between the 2 paragraphs in the intro of section 5 and the 2 paragraphs in section 5.1.1.

**Comment by plehegar** [comment]
(waiting on i18n to confirm their needs-resolution closures)

**Comment by iadawn** [comment]
> Section 5 Conformance:
> 
> You need to reconcile the differences between the 2 paragraphs in the intro of section 5 and the 2 paragraphs in section 5.1.1.

Fixed

**Comment by plehegar** [comment]
Approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/WCAG22/

**Comment by plehegar** [comment]
https://www.w3.org/TR/2023/REC-WCAG22-20231005/
