### ISSUE TITLE
First Note request for RCH WG — Explainer and Use Cases

### ISSUE THREAD

**Issue by pchampin** [w3c/transitions#572]
# Document title, URLs, estimated publication date
Title: RDF Dataset Canonicalization and Hash Working Group — Explainer and Use Cases
URL: https://w3c.github.io/rch-explainer/publication-snapshots/NOTE/Overview.html
Estimated publication date: 2023-10-19

# Abstract
https://w3c.github.io/rch-explainer/publication-snapshots/NOTE/Overview.html#abstract

# Status of the Document
https://w3c.github.io/rch-explainer/publication-snapshots/NOTE/Overview.html#sotd

# Link to group's decision to request transition
https://github.com/w3c/rch-explainer/issues/9

# Is it intended to be a W3C Statement?
No

**Comment by plehegar** [comment]
Approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2023/NOTE-rch-explainer-20231019/
