### ISSUE TITLE
CR Request for Data Catalog Vocabulary (DCAT) - Version 3 - vocab-dcat-3

### ISSUE THREAD

**Issue by pchampin** [w3c/transitions#578]
# Document title, URLs, estimated publication date
Title: Data Catalog Vocabulary (DCAT) - Version 3
URL: https://w3c.github.io/dxwg/dcat/publication-snapshots/CR/Overview.html
Estimated publication date: 2023-10-31

# Abstract
https://w3c.github.io/dxwg/dcat/publication-snapshots/CR/Overview.html#abstract

# Status
https://w3c.github.io/dxwg/dcat/publication-snapshots/CR/Overview.html#sotd

# Link to group's decision to request transition
https://www.w3.org/mid/CABUZhHkO2d4BZPAgVVWTONS4xe4Lta5E1QA+HhJvQfrbLO_RJQ@mail.gmail.com

# Changes
https://w3c.github.io/dxwg/dcat/publication-snapshots/CR/Overview.html#changes

# Requirements satisfied
yes

# Dependencies met (or not)
none

# Wide Review
https://github.com/w3c/dxwg/issues/1502
(see also [a summary](https://docs.google.com/document/d/1EPQKTLXHlJUTDWqGrK3tRbfLC3mKHjEu_E26veTcC-U/edit) of the coordination with all groups listed in the charter)

# Issues addressed
https://github.com/w3c/dxwg/issues?q=is%3Aissue+is%3Aopen+label%3Adcat+-label%3Afuture-work
The remaining open issues are either administrative (w3c/dxwg#1561), or purely editorial (w3c/dxwg#1352, w3c/dxwg#1223) and can be processed during the CR review period.

# Formal Objections
None

# Implementation
https://w3c.github.io/dxwg/dcat3-implementation-report/
(currently empty, but some implementations have been collected already)

# Patent disclosures
https://www.w3.org/groups/wg/dx/ipr/

**Comment by plehegar** [comment]
http://www.w3.org/ns/adms redirects to a document now maintained by a CG. That document claims: "This vocabulary has the status [Candidate Recommendation](htpps://www.w3.org/2021/Process-20211102/#RecsCR) published at 2023-06-21.", with a link to our Process. That document is NOT a Candidate Recommendation as defined by W3C. Even when [published at W3C](https://www.w3.org/TR/vocab-adms), it used to be a Note. Yet, the document claims that the latest version of the Recommendation is published at W3C, which was never the case. This needs to be fixed.

**Comment by plehegar** [comment]
I'll check with @npdoty the status of https://github.com/w3c/dxwg/issues/1524 .

**Comment by plehegar** [comment]
In J.2 Informative References, the link to https://www.w3.org/TR/vocab-adms/ now points to a deprecated document.

**Comment by pchampin** [comment]
> In J.2 Informative References, the link to https://www.w3.org/TR/vocab-adms/ now points to a deprecated document.

Yes, this has been discussed, and the conclusion was to stick to the old version of the vocabulary for the moment : 
https://github.com/w3c/dxwg/issues/1570#issuecomment-1656943616

**Comment by pchampin** [comment]
> http://www.w3.org/ns/adms redirects to a document now maintained by a CG. That document claims: "This vocabulary has the status Candidate Recommendation published at 2023-06-21.", with a link to our Process. That document is NOT a Candidate Recommendation as defined by W3C. Even when [published at W3C](https://www.w3.org/TR/vocab-adms), it used to be a Note. Yet, the document claims that the latest version of the Recommendation is published at W3C, which was never the case. This needs to be fixed.

The document now presents itself as a "SEMIC Candidate Recommendation" and does link to the W3C process.

**Comment by plehegar** [comment]
It still says:
[[
Latest Recommendation:
  https://www.w3.org/TR/vocab-adms
]]

**Comment by pchampin** [comment]
@plehegar https://www.w3.org/TR/vocab-adms/  has been updated.

**Comment by plehegar** [comment]
Approved

**Comment by pchampin** [comment]
published today https://www.w3.org/TR/2024/CR-vocab-dcat-3-20240118/
