### ISSUE TITLE
REC Request for WoT Discovery (wot-discovery), WoT Thing Description 1.1 (wot-thing-description11) and WoT Architecture 1.1 (wot-architecture11)

### ISSUE THREAD

**Issue by ashimura** [w3c/transitions#579]
# Pointer to the internal transition request mail:
https://lists.w3.org/Archives/Team/w3t-comm/2023Nov/0200.html

---
# Document title, URLs, estimated publication date
* Web of Things (WoT) Discovery
  * URL: https://w3c.github.io/wot-discovery/publication/6-rec/Overview.html
  * estimated publication date: 30 November 2023
* Web of Things (WoT) Thing Description 1.1
  * URL: https://w3c.github.io/wot-thing-description/publication/ver11/7-rec/Overview.html
  * estimated publication date: 30 November 2023
* Web of Things (WoT) Architecture 1.1
  * URL: https://w3c.github.io/wot-architecture/publication/ver11/5-rec/Overview.html
  * estimated publication date: 30 November 2023

**Note:** Schema files and Ontology files related to the above specs (more specifically, WoT Discovery and WoT Thing Description 1.1) are installed under https://github.com/w3c/wot-resources and redirection from https://www.w3.org to that area is being set up (by the publication date).

# Abstract
* https://w3c.github.io/wot-discovery/publication/6-rec/Overview.html#abstract
* https://w3c.github.io/wot-thing-description/publication/ver11/7-rec/Overview.html#abstract
* https://w3c.github.io/wot-architecture/publication/ver11/5-rec/Overview.html#abstract

# Status
* https://w3c.github.io/wot-discovery/publication/6-rec/Overview.html#sotd
* https://w3c.github.io/wot-thing-description/publication/ver11/7-rec/Overview.html#sotd
* https://w3c.github.io/wot-architecture/publication/ver11/5-rec/Overview.html#sotd

# Link to group's decision to request transition
* https://www.w3.org/2023/11/15-wot-minutes.html#r02

# Wide Review
No change since the Proposed Rec Request:
* [WoT Discovery](https://github.com/w3c/transitions/issues/553)
* [WoT Thing Description 1.1](https://github.com/w3c/transitions/issues/554)
* [WoT Architecture 1.1](https://github.com/w3c/transitions/issues/552)

# Dependencies
No change since the Proposed Rec Request;
* [WoT Discovery](https://github.com/w3c/transitions/issues/553)
* [WoT Thing Description 1.1](https://github.com/w3c/transitions/issues/554)
* [WoT Architecture 1.1](https://github.com/w3c/transitions/issues/552)

# Issues addressed
* WoT Discovery
  * All the open issues have been identified as "Resources", "defer to Discovery 2.0" or "question"
  * See: https://github.com/w3c/wot-discovery/issues
* WoT Thing Description 1.1
  * All the open issues have been identified as "Tooling", "Defer to TD 2.0", "linting", "Resources" or "question"
  * See: https://github.com/w3c/wot-thing-description/issues
* WoT Architecture 1.1
  *All the open issues have been identified as "implementation report" or "defer to arch 2.0"
  * See: https://github.com/w3c/wot-architecture/issues

# Link to internal AC Review results
* WoT Discovery: https://www.w3.org/2002/09/wbs/33280/PR-wot-discovery/results
* WoT Thing Description 1.1: https://www.w3.org/2002/09/wbs/33280/PR-wot-thing-description11/results
* WoT Architeture 1.1: https://www.w3.org/2002/09/wbs/33280/PR-wot-architecture11/results

# Formal Objections
None.

**Note:** There was a comment pointing out that there was a mark of "at risk" within the section "5.3.3.4 ComboSecurityScheme" from WoT Thing Description 1.1 spec, but that was a typo and has been removed already.

**Comment by plehegar** [comment]
You might want to update of test 148: well-known-operation-types-only in the implementation report to match the latest wording from the TD spec.

**Comment by mmccool** [comment]
I will correct this by the REC publication.

**Comment by plehegar** [comment]
Approved.

**Comment by ashimura** [comment]
Thanks a lot, @plehegar !

Unfortunately, (as I mentioned in the internal transition request mail above), the final wrap-up work by the WoT WG got a bit delayed:
* diff from Proposed REC (done)
* fixing the expression of assertion 148 commented above (Pullrequest to be merged)
* namespace URI redirection for schema/ontology files (just done)
* add brief description for the ontology files for WoT Discovery (ongoing)

So we'd like to aim for Dec 5 instead as the Pubdate.

I'll fix the Pubdate within the three REC drafts for that purpose.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2023/REC-wot-discovery-20231205/
https://www.w3.org/TR/2023/REC-wot-thing-description11-20231205/
https://www.w3.org/TR/2023/REC-wot-architecture11-20231205/
