### ISSUE TITLE
[Payments] CR Update for payment-request

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#58]
# Link to previous Candidate Recommendation transition request

https://lists.w3.org/Archives/Member/chairs/2017JulSep/0125.html

# Substantive changes

- PaymentRequest.onpaymentmethodchange and PaymentMethodChangeEvent added
- PaymentRequest.show function option parameter added
- PaymentCurrencyAmount.currencySystem removed (used to be at risk)
- PaymentDetailsUpdate.shippingAddressErrors added
- PaymentItemType and PaymentItem.type added (at risk)
- PaymentAddress.regionCode added
- PaymentResponse.retry() added
- Update a PaymentRequest 's details algorithm added

Diff from previous reference draft:
https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2017%2FCR-payment-request-20170914%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fpayment-request%2F%3FspecStatus%3DCR%3BshortName%3Dpayment-request

Diff from previous publication:
https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2018%2FCR-payment-request-20180607%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fpayment-request%2F%3FspecStatus%3DCR%3BshortName%3Dpayment-request

# Any changes in normative references?

None since previous publication

# Any changes in requirements?

No requirement document but PaymentResponse.retry() was added

# Wide Review of substantive changes

All changes were due to implementation feedback.

https://github.com/w3c/payment-request/issues/735

# Issues status

Recently updated closed issues:
 https://github.com/w3c/payment-request/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed
Open CR Exit issues:
  https://github.com/w3c/payment-request/issues?q=is%3Aissue+is%3Aopen+label%3ACR-Exit
Recently updated open issues:
  https://github.com/w3c/payment-request/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

# Formal Objections

None

# Any changes in implementation information?

The API is getting mode widely adopted:
  https://caniuse.com/#feat=payment-request

https://github.com/web-platform-tests/wpt/pulls?q=is%3Aopen+is%3Apr+label%3Apayment-request

Test suite (in progress):
  http://w3c-test.org/payment-request/
  https://github.com/web-platform-tests/wpt/pulls?q=is:pr+label:payment-request

The features at risk were changed to:
[[
* PaymentItem's type member and the PaymentItemType enum (see issue 163). 
* As the optional detailsPromise argument of the show() method was added late in the Candidate Recommendation phase, the working group is treating it "at risk" and considering moving it to a future version of the specification. This is to avoid this version of the specification from being delayed from progressing along the Recommendation Track, in case we can't get two interoperable implementations in a timely manner. However, if it gets interoperably implemented relatively quickly, the feature will remain in this version of the specification. 
]]

# Deadline for further comments

4 weeks after publication (~mid-August)

# Any changes in patent disclosures?

yes. 

See https://www.w3.org/2017/11/wpwg-pag/report

https://www.w3.org/2004/01/pp-impl/83744/status#current-disclosures

**Comment by plehegar** [comment]
Also
 https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fw3c.github.io%2Fpayment-request%2F

**Comment by plehegar** [comment]
See also
 https://github.com/w3c/payment-request/releases
in particular:
 https://github.com/w3c/payment-request/compare/CR...gh-pages

**Comment by swickr** [comment]
Transition approved.

**Comment by xueyuanjia** [comment]
Draft transition approved.

**Comment by marcoscaceres** [comment]
@plehegar I've tried republishing recently via the script, but it doesn't seem to be working anymore? :(

When I `curl`, it doesn't show any error (just gives me back a random token, as expected). Could you help me check what's happened so I can republish?

**Comment by plehegar** [comment]
1) You have a duplicate ID error in your document it seems. See
  https://lists.w3.org/Archives/Public/public-tr-notifications/2018Sep/0014.html
2) Note that if you're making substantive changes, you'll need a new Director's approval. https://github.com/w3c/transitions/issues/58 can't be reused for that anymore.

**Comment by marcoscaceres** [comment]
Thanks! I wasn't sure where to look. Stating the obvious here, but would be super nice receive failure emails without having to subscribe to public-tr-notifications (I guess the cheap option is to subscribe and filter).

**Comment by plehegar** [comment]
I think the main issue with doing so is that we don't know how to identify which of the listed editors is/are the active one(s). @deniak

**Comment by marcoscaceres** [comment]
can add a css class or something if it helps. Other option might be to put an email into the URL of the request itself. That might be easier, as it can be targeted at one or more persons, like:

url?cc=marcos@marcosc.com,other@foo.com

**Comment by deniak** [comment]
@marcoscaceres, see https://github.com/w3c/transitions/issues/58. I'll try to find some time to implement that feature this week (cc @tripu)

**Comment by marcoscaceres** [comment]
@deniak that would be awesome! If you need review or whatever, let me know (was #58 above correct? it just points to this bug?)

**Comment by deniak** [comment]
Oups, I meant https://github.com/w3c/echidna/issues/285

**Comment by deniak** [comment]
@marcoscaceres @plehegar, you can now pass a QS param `cc=` with a  list of comma-separated emails and the notification will also be sent there (see [wiki](https://github.com/w3c/echidna/wiki/How-to-use-Echidna#using-echidna-publication-without-curl))

**Comment by marcoscaceres** [comment]
Nice!!! Thanks for making this possible.

**Comment by marcoscaceres** [comment]
@deniak, from the wiki, it seems to be only supported not using curl... is that correct? I assume it also works with curl?

**Comment by deniak** [comment]
Sorry, I'll improve the documentation but it should work with any POST requests, whatever tool you are using.
