### ISSUE TITLE
FPWD Request for MiniApp Addressing

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#581]
# Document title, URLs, estimated publication date
MiniApp Addressing
https://www.w3.org/TR/miniapp-addressing/
09 January 2024

# Abstract
This specification defines how MiniApps are located, which is called MiniApp Addressing, including the specifications for specific MiniApp URI syntax components based on the URI specification and the process to dereference the MiniApp URI. Implementing this specification enables the user agent to locate MiniApp resources.

# Status
The Working Group is publishing this specification as a Draft Note to encourage early review. This specification is not yet on the W3C standards track.

MiniApps 工作组将本规范作为备忘草案发布，以鼓励对该文档的早期审阅。该规范尚未进入 W3C 标准轨道。

This document was published by the [MiniApps Working Group](https://www.w3.org/groups/wg/miniapps) as a First Public Working Draft using the [Recommendation track](https://www.w3.org/2023/Process-20231103/#recs-and-notes).
Publication as a First Public Working Draft does not imply endorsement by W3C and its Members.
This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.
This document was produced by a group operating under the [W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy/). W3C maintains a [public list of any patent disclosures](https://www.w3.org/groups/wg/miniapps/ipr) made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains [Essential Claim(s)](https://www.w3.org/Consortium/Patent-Policy/#def-essential) must disclose the information in accordance with [section 6 of the W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy/#sec-Disclosure).
This document is governed by the [03 November 2023 W3C Process Document](https://www.w3.org/2023/Process-20231103/).

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://github.com/w3c/miniapp/issues/204
Note: In the latest MiniApp Vendors' meeting, this spec is among the most popular proposals.

# Information about implementations known to the Working Group
The MiniApp Vendors intended to implement this spec as the first / basic miniapp standard.

**Comment by plehegar** [comment]
Approved.

As a side, I think you're missing the token "/" between your uri-prefix and uri-infix components, and also between uri-infix and identify components.

**Comment by dontcallmedom** [comment]
> The Working Group is publishing this specification as a Draft Note to encourage early review. This specification is not yet on the W3C standards track.

> This document was published by the [MiniApps Working Group](https://www.w3.org/groups/wg/miniapps) as a First Public Working Draft using the [Recommendation track](https://www.w3.org/2023/Process-20231103/#recs-and-notes).

I assume this is indeed a FPWD and no longer a Draft Note, but if so, the SOTD should remove the contradiction.

**Comment by siusin** [comment]
> I assume this is indeed a FPWD and no longer a Draft Note, but if so, the SOTD should remove the contradiction.

Ahh, indeed! I'll review the document again before publishing the FPWD.

Thanks for the comments.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2024/WD-miniapp-addressing-20240131/
