### ISSUE TITLE
[webperf] CR for user-timing-2

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#59]
# Document title, URLs, estimated publication date
User Timing Level 2
https://www.w3.org/TR/user-timing-2/
07 June 2018

# Abstract
This specification defines an interface to help web developers measure 
the performance of their applications by giving them access to high 
precision timestamps.

# Status
This section describes the status of this document at the time of its 
publication. Other documents may supersede this document. A list of 
current W3C publications and the latest revision of this technical 
report can be found in the W3C technical reports index at 
https://www.w3.org/TR/.

User Timing Level 2 replaces the first version of [USER-TIMING] and 
includes:

Support for PerformanceMark and PerformanceMeasure in Web Workers 
[WORKERS] via integration with [HR-TIME-2];
Processing clarifications for mark names that reference 
PerformanceTiming interface defined in [NAVIGATION-TIMING].

This document was published by the Web Performance Working Group as a 
Candidate Recommendation. This document is intended to become a W3C 
Recommendation. Feedback and comments on this specification are welcome. 
Please use Github issues or send them to public-web-perf@w3.org 
(subscribe, archives) with [UserTiming] at the start of your email's 
subject. W3C publishes a Candidate Recommendation to indicate that the 
document is believed to be stable and to encourage implementation by the 
developer community. This Candidate Recommendation is expected to 
advance to Proposed Recommendation no earlier than 07 September 2017.

The Group expects to demonstrate at least 2 implementations of all the 
features in this specification. There are no features at risk and 
significant change since the previous publication. Please see the 
Working Group's implementation report.

Publication as a Candidate Recommendation does not imply endorsement by 
the W3C Membership. This is a draft document and may be updated, 
replaced or obsoleted by other documents at any time. It is 
inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the 5 February 
2004 W3C Patent Policy. W3C maintains a public list of any patent 
disclosures made in connection with the deliverables of the group; that 
page also includes instructions for disclosing a patent. An individual 
who has actual knowledge of a patent which the individual believes 
contains Essential Claim(s) must disclose the information in accordance 
with section 6 of the W3C Patent Policy.

This document is governed by the 1 February 2018 W3C Process Document.

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-web-perf/2018May/0006.html
[[
Resolved: User timing is moving to CR
]]

# Substantive Changes
User Timing Level 2 replaces the first version of [USER-TIMING] and 
includes:

Support for PerformanceMark and PerformanceMeasure in Web Workers 
[WORKERS] via integration with [HR-TIME-2];
Processing clarifications for mark names that reference 
PerformanceTiming interface defined in [NAVIGATION-TIMING].

# Requirements satisfied
No special requirements.

# Dependencies met (or not)
This specification has normative references to the following spec that 
is not CR yet:
Web Workers <https://www.w3.org/TR/workers/>
Web Workers has been widely implemented and used across the Web platform 
<https://wpt.fyi/results/workers>. The UT-2 spec is using the core 
concept of Workers as we add support for PerformanceMark and 
PerformanceMeasure in Web Workers.

# Wide Review
Wide review request for User Timing 2 
<https://lists.w3.org/Archives/Public/public-review-announce/2016Nov/0004.html>
There isn't any substantive change added to this spec since the 20161101 
Working Draft.

# Issues addressed
All outstanding issues for Level 2 are resolved 
<https://github.com/w3c/user-timing/issues>.

# Formal Objections
None.

# Implementation
All the features in L2 already have shipping implementations in the 
major browsers (all green in Chrome, Firefox and Safari, WIP in Edge) 
<https://wpt.fyi/results/user-timing>.

# Patent disclosures
https://www.w3.org/2004/01/pp-impl/45211/status
None.

**Comment by plehegar** [comment]
(previously approved at https://lists.w3.org/Archives/Member/chairs/2018AprJun/0097.html )

**Comment by swickr** [comment]
Transition approved.

**Comment by siusin** [comment]
We've made all the changes required at https://lists.w3.org/Archives/Team/w3t-comm/2018Jun/0202.html in commit [#97c791a](https://github.com/w3c/user-timing/commit/97c791ab1c70694c840f205da6c35f128d3973a2).

**Comment by xueyuanjia** [comment]
Draft transition approved.
