### ISSUE TITLE
PR Request for IMSC Hypothetical Render Model (imsc-hrm)

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#590]
# Document title, URLs, estimated publication date
IMSC Hypothetical Render Model
TR: https://www.w3.org/TR/imsc-hrm/
ED: https://w3c.github.io/imsc-hrm/spec/imsc-hrm.html

# Abstract
https://w3c.github.io/imsc-hrm/spec/imsc-hrm.html#abstract

# Status
https://w3c.github.io/imsc-hrm/spec/imsc-hrm.html#sotd

# Will new features be allowed to be incorporated in the Recommendation?
Yes.
(Resolution of CfC: https://lists.w3.org/Archives/Public/public-tt/2024Feb/0002.html)

# Link to group's decision to request transition
CfC: https://lists.w3.org/Archives/Public/public-tt/2024Jan/0000.html
Resolution: https://lists.w3.org/Archives/Public/public-tt/2024Jan/0005.html

# Changes
https://w3c.github.io/imsc-hrm/spec/imsc-hrm.html#changes-since-the-first-candidate-recommendation

# Requirements satisfied
IMSC-HRM was initially developed as a part of IMSC recommendation, so requirements are satisfied during IMSC development.

# Dependencies met (or not)
yes

# Wide Review
before 1st CRS
tag: https://github.com/w3ctag/design-reviews/issues/788
a11y: https://github.com/w3c/a11y-request/issues/19
i18n: https://github.com/w3c/i18n-request/issues/167
privacy: https://github.com/w3cping/privacy-request/issues/65
security: https://github.com/w3c/security-request/issues/18 (no action taken)

No new feature added, one at-risk feature removed, after 1st CRS.

# Issues addressed
https://github.com/w3c/imsc-hrm/issues?q=is%3Aissue+is%3Aclosed

# Formal Objections
none

# Implementation
https://www.w3.org/wiki/TimedText/IMSC-HRM-1ED-Implementation-Report
lists both:
- test results from two implementations
- imscHRM successfully run over sets of IMSC documents from multiple content producing implementations

# Patent disclosures
https://www.w3.org/groups/wg/timed-text/ipr/#current-disclosures

**Comment by nigelmegitt** [comment]
Sorry for the late notice, I think I'm going to have to ask you to hold this while we return to the question of if this is an updateable rec or not - I only noticed from this transition request that it is not but I see now that we did not put the right text into the SOTD. I would like to return this question to the TTWG and check if we have consensus to change it before we publish as a Rec.

Issue raised as w3c/imsc-hrm#78.

**Comment by nigelmegitt** [comment]
Cfc concluded at https://lists.w3.org/Archives/Public/public-tt/2024Feb/0002.html with no objections. 

@himorin please could you adjust this transition request to change "Will new features be allowed to be incorporated in the Recommendation?" to "Yes" and then proceed, i.e. take this off "hold"?

**Comment by himorin** [comment]
> @himorin please could you adjust this transition request to change "Will new features be allowed to be incorporated in the Recommendation?" to "Yes" and then proceed, i.e. take this off "hold"?

changed with adding a link to the resolution.

**Comment by plehegar** [comment]
* [Diff from previous CR Snapshot](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2023%2FCR-imsc-hrm-20230622%2F&doc2=https%3A%2F%2Fw3c.github.io%2Fimsc-hrm%2Fspec%2Fimsc-hrm.html)

**Comment by plehegar** [comment]
The Working Group reported using around 28,502 documents against one of the validating implementation (as [discussed with the Council](https://www.w3.org/2023/03/council-ttwg-report.html#recommendations)). This was done in addition to using 2 validating implementations against the hand-crafted test suite.

Approved, but we'd like to see the final SOTD before publication (@himorin , pleaqse cc @ylafon and me on the publication request).

**Comment by nigelmegitt** [comment]
@plehegar I don't think we're expecting to make any particular changes to the SOTD relative to w3c/imsc-hrm#77 - is there something you are hoping to be present in that text, or removed from it? For example the addition of some description of how the CR exit criteria were met?

**Comment by plehegar** [comment]
> @plehegar I don't think we're expecting to make any particular changes to the SOTD relative to [w3c/imsc-hrm#77](https://github.com/w3c/imsc-hrm/pull/77) - is there something you are hoping to be present in that text, or removed from it? For example the addition of some description of how the CR exit criteria were met?

Nope. Just wanted to make sure the SOTD is finalized porperly.

**Comment by nigelmegitt** [comment]
Late change to the SotD agreed, confirmed at https://lists.w3.org/Archives/Public/public-tt/2024Feb/0007.html - removes the CR exit criteria, which were left in by oversight. I think this means we can continue with the transition, @himorin @plehegar as per w3c/imsc-hrm#77.

**Comment by himorin** [comment]
@nigelmegitt @plehegar A package installed at
https://www.w3.org/TR/2024/PR-imsc-hrm-20240229/

I'll send out publication request shortly.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2024/PR-imsc-hrm-20240229/
