### ISSUE TITLE
CR Request for Digital Publishing  ARIA Module and Accessibility APIs Mapping 1.1

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/transitions#591]
# Document title, URLs, estimated publication date
https://www.w3.org/TR/2024/CR-dpub-aria-1.1-20240227/
https://www.w3.org/TR/2024/CR-dpub-aam-1.1-20240227/
27 Feb 2024

# Abstract
https://www.w3.org/TR/2024/CR-dpub-aria-1.1-20240227/#abstract
https://www.w3.org/TR/2024/CR-dpub-aam-1.1-20240227/#abstract

# Status
https://www.w3.org/TR/2024/CR-dpub-aria-1.1-20240227/#sotd
https://www.w3.org/TR/2024/CR-dpub-aam-1.1-20240227/#sotd

# Link to group's decision to request transition
https://www.w3.org/2024/02/08-aria-minutes#t05
https://www.w3.org/2024/02/08-aria-minutes#t06

# Changes
https://www.w3.org/TR/2024/CR-dpub-aria-1.1-20240227/#changelog
https://www.w3.org/TR/2024/CR-dpub-aam-1.1-20240227/#changelog

# Requirements satisfied

Yes.

# Dependencies met (or not)

Dependencies are not likely to change

# Wide Review

https://github.com/w3ctag/design-reviews/issues/821
https://github.com/w3cping/privacy-request/issues/116
https://github.com/w3c/a11y-request/issues/55
https://github.com/w3c/i18n-request/issues/207

All relevant wide review issues are tracked at 
https://github.com/w3c/dpub-aria/issues

# Issues addressed
https://github.com/w3c/dpub-aria/issues?q=is%3Aissue+is%3Aclosed

# Formal Objections
None

# Implementation
https://www.w3.org/2024/02/27-dpub-aam-1.1-implementation-report.html

# Patent disclosures
https://www.w3.org/groups/wg/aria/ipr/

**Comment by plehegar** [comment]
Approved.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2024/CR-dpub-aria-1.1-20240227/
https://www.w3.org/TR/2024/CR-dpub-aam-1.1-20240227/
