### ISSUE TITLE
PR Request for RDF Dataset Canonicalization - RDF-CANON

### ISSUE THREAD

**Issue by pchampin** [w3c/transitions#593]
# Document title, URLs, estimated publication date
RDF Dataset Canonicalization — A Standard RDF Dataset Canonicalization Algorithm
https://w3c.github.io/rdf-canon/publication-snapshots/PR/Overview.html
2024-03-19

# Abstract
https://w3c.github.io/rdf-canon/publication-snapshots/PR/Overview.html#abstract

# Status
https://w3c.github.io/rdf-canon/publication-snapshots/PR/Overview.html#sotd

# Will new features be allowed to be incorporated in the Recommendation?
Yes
(group decision: https://www.w3.org/2024/02/28-rch-minutes.html#r02)

# Link to group's decision to request transition
https://www.w3.org/2024/02/28-rch-minutes.html#r02

# Changes
https://w3c.github.io/rdf-canon/publication-snapshots/PR/Overview.html#changes-from-cr

See also [HTML diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Frdf-canon%2Fpublication-snapshots%2FCR%2FOverview.html&doc2=https%3A%2F%2Fw3c.github.io%2Frdf-canon%2Fpublication-snapshots%2FPR%2FOverview.html)

# Requirements satisfied
The group made the decision early on to merge the two specifications listed in its charter (RDC and RDH). The RDF-CANON spefication meets the requitements of both :
* it defines an algorithm that implements an RDF Dataset Canonicalization function
* it provies a standard serialization for the result of this function (based on N-Quads), on which a hash function can trivially be applied

# Dependencies met (or not)
There were no major dependencies.

# Wide Review
Completed: https://github.com/w3c/rdf-canon/issues?q=is%3Aissue+is%3Aclosed+label%3AHorizontalReview

# Issues addressed
All pending issues were addressed: https://github.com/w3c/rdf-canon/issues

# Formal Objections
None

# Implementation
Implementation report: https://w3c.github.io/rdf-canon/reports/
Test suite: https://w3c.github.io/rdf-canon/tests/
8 independant implementations have been reported, with a minimum of 6 implementations passing each test.

# Patent disclosures
None (https://www.w3.org/groups/wg/epub/ipr/)

@philarcher @peacekeeper @gkellogg @dlongley @yamdan

**Comment by plehegar** [comment]
Approved.

Congratulations.

**Comment by plehegar** [comment]
https://www.w3.org/TR/2024/PR-rdf-canon-20240326/
