### ISSUE TITLE
FPWD Request for CSS View Transitions Module Level 2 - css-view-transitions-2

### ISSUE THREAD

**Issue by noamr** [w3c/transitions#595]
# Document title, URLs, estimated publication date
CSS View Transitions Module Level 2, https://drafts.csswg.org/css-view-transitions-2/, April 10?

# Abstract
This module defines how the View Transition API works with cross-document navigations.

# Status
This is a public copy of the editors’ draft. It is provided for discussion only and may change at any moment. Its publication here does not imply endorsement of its contents by W3C. Don’t cite this document other than as work in progress.

Please send feedback by [filing issues in GitHub](https://github.com/w3c/csswg-drafts/issues) (preferred), including the spec code “css-view-transitions-2” in the title, like this: “[css-view-transitions-2] …summary of comment…”. All issues and comments are [archived](https://lists.w3.org/Archives/Public/public-css-archive/). Alternately, feedback can be sent to the ([archived](https://lists.w3.org/Archives/Public/www-style/)) public mailing list [www-style@w3.org](mailto:www-style@w3.org?Subject=%5Bcss-view-transitions-2%5D%20PUT%20SUBJECT%20HERE).

This document is governed by the [03 November 2023 W3C Process Document](https://www.w3.org/2023/Process-20231103/).
# Is it a delta specification intended to become a W3C Recommendation?
not sure what this means? This is currently a delta of css-view-transitions-1 in some sense.

# Link to group's decision to request transition
https://github.com/w3c/csswg-drafts/issues/10096#issuecomment-2023168412

# Information about implementations known to the Working Group
Active implementation in chrome, about to ship.

**Comment by plehegar** [comment]
fyi, [delta specification](https://www.w3.org/2005/07/13-pubrules-about#delta). Unless this new spec intends to superde the old spec wghile referencing it, it's not a delta spec. I believe this is not intended to become a delta specifcation: it extends level1 without superseding it.

Approved.

**Comment by khushalsagar** [comment]
Is there any action required from the spec editors to move forward here?

**Comment by khushalsagar** [comment]
No worries @svgeesus. Thank you! :)

**Comment by khushalsagar** [comment]
@svgeesus just checking in. Has this been published yet?

**Comment by plehegar** [comment]
https://www.w3.org/TR/2024/WD-css-view-transitions-2-20240516/
