### ISSUE TITLE
First Note request for Khmer Layout Requirements - khmr-lreq

### ISSUE THREAD

**Issue by r12a** [w3c/transitions#596]
# Document title, URLs, estimated publication date
Khmer Layout Requirements
DNOTE-khmr-lreq-20240411
for 11 April

# Abstract
This document describes or points to requirements for the layout and presentation of text in languages that use the Khmer script. The target audience is developers of Web standards and technologies, such as HTML, CSS, Mobile Web, Digital Publications, and Unicode, as well as implementers of web browsers, ebook readers, and other applications that need to render Khmer text.

# Status of the Document
FPDNOTE

# Link to group's decision to request transition
https://www.w3.org/2024/03/28-i18n-minutes.html#t06

# Is it intended to be a W3C Statement?
No

**Comment by plehegar** [comment]
Approved
