### ISSUE TITLE
CR Snapshot Update Request for CSS Multi-column Layout Level 1 - css-multicol-1

### ISSUE THREAD

**Issue by rachelandrew** [w3c/transitions#598]
# Document URLs

https://drafts.csswg.org/css-multicol/

# Link to group's decision to request transition

https://github.com/w3c/csswg-drafts/issues/6900#issuecomment-1944639417

# Link to previous Candidate Recommendation transition or update request

https://github.com/w3c/csswg-drafts/issues/6612#issuecomment-920189454

# Substantive changes

One minor change as a clarification. https://drafts.csswg.org/css-multicol/#changes-from-20211012

# Any changes in requirements?

None

# Wide Review of substantive changes

The CSSWG felt this minor change would not require a further wide review. See discussion in resolution.

# Issues status

No open issues.

# Formal Objections

None

# Any changes in implementation information?

Multicol is widely implemented. The intention is to progress to Proposed Recommendation after this CRS, should no additional issues be raised. 

# Deadline for further comments

28 days.

# Any changes in patent disclosures?

None

See [Requirements for updating a Candidate Recommendation Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot) for further information.

**Comment by plehegar** [comment]
Transition approved.

**Comment by svgeesus** [comment]
Publication requested 6 May expected 9 May

**Comment by plehegar** [comment]
https://www.w3.org/TR/2024/CR-css-multicol-1-20240516/
