### ISSUE TITLE
First Note request for Thai Layout Requirements - thai-lreq

### ISSUE THREAD

**Issue by r12a** [w3c/transitions#605]
# Document title, URLs, estimated publication date
Thai Layout Requirements
https://www.w3.org/TR/2024/DNOTE-thai-lreq-20240430/
30 Apr 2024

# Abstract
This document describes or points to requirements for the layout and presentation of text in languages that use the Thai script. The target audience is developers of Web standards and technologies, such as HTML, CSS, Mobile Web, Digital Publications, and Unicode, as well as implementers of web browsers, ebook readers, and other applications that need to render Thai text.

# Status of the Document
https://www.w3.org/TR/2024/DNOTE-thai-lreq-20240430/#sotd

# Link to group's decision to request transition
https://www.w3.org/2024/04/18-i18n-minutes.html#t05

# Is it intended to be a W3C Statement?
No

**Comment by plehegar** [comment]
Approved

**Comment by ylafon** [comment]
Was published at https://www.w3.org/TR/2024/DNOTE-thai-lreq-20240430/
