### ISSUE TITLE
FPWD Request for Controller Documents 1.0 - controller-document

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#610]
# Document title, URLs, estimated publication date

Title: Controller Documents 1.0
- Final URL: https://www.w3.org/TR/2024/WD-vc-controller-document-20240530/
- Editor's draft: https://w3c.github.io/vc-controller-document/FPWD/2024-FPWD/
- Expected Publication date 2023 May 30
- short name: controller-document

# Abstract
See https://w3c.github.io/vc-controller-document/FPWD/2024-FPWD/#abstract

# Status
See https://w3c.github.io/vc-controller-document/FPWD/2024-FPWD/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-05-08-vcwg#resolution1

# Information about implementations known to the Working Group
There are experimental implementations, not yet in production

# Note 

This specification aims at "abstracting out" some concepts, notions, vocabulary terms, etc, that are shared not only by other VC documents, but also standards defined elsewhere, such as the DID specification. In this respect, this document does not add anything fundamentally new to the VC architecture.

If this specification goes ahead, the similar/original terms in other specifications will be removed in favor of normative references to this specification.

cc @brentzunel @msporny @selfissued

**Comment by plehegar** [comment]
Transition approved

**Comment by iherman** [comment]
Publication request went out for the 23rd of May

**Comment by iherman** [comment]
Published, see https://www.w3.org/news/2024/first-public-working-draft-controller-documents-1-0/

Closing issue.
