### ISSUE TITLE
REC Request for RDF Dataset Canonicalization - RDF-CANON

### ISSUE THREAD

**Issue by pchampin** [w3c/transitions#611]
---

# Document title, URLs, estimated publication date
RDF Dataset Canonicalization — A Standard RDF Dataset Canonicalization Algorithm
https://w3c.github.io/rdf-canon/publication-snapshots/REC/Overview.html
2024-05-21

# Abstract
https://w3c.github.io/rdf-canon/publication-snapshots/REC/Overview.html#abstract

# Status
https://w3c.github.io/rdf-canon/publication-snapshots/REC/Overview.html#sotd

# Link to group's decision to request transition
https://www.w3.org/2024/02/28-rch-minutes.html#r02

# Wide Review
Completed: https://github.com/w3c/rdf-canon/issues?q=is%3Aissue+is%3Aclosed+label%3AHorizontalReview

# Dependencies
There were no major dependencies.

# Issues addressed
All pending issues were addressed: https://github.com/w3c/rdf-canon/issues

# Link to internal AC Review results
https://www.w3.org/2002/09/wbs/33280/rdf-canon-pr/results

# Formal Objections
None

**Comment by plehegar** [comment]
Approved
