### ISSUE TITLE
REC Update Request for Media Queries Level 3 - mediaqueries-3

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#612]
# Document title, URLs, estimated publication date
Media Queries Level 3
https://www.w3.org/TR/2024/REC-mediaqueries-3-20240516/

# Abstract
https://www.w3.org/TR/2024/REC-mediaqueries-3-20240516/#abstract

# Status
https://www.w3.org/TR/2024/REC-mediaqueries-3-20240516/#status

# Link to group's decision to request the update
https://github.com/w3c/csswg-drafts/issues/10245#issuecomment-2097023803

# Link to Last Call for Review of Proposed Amendments
https://lists.w3.org/Archives/Member/w3c-ac-members/2022AprJun/0002.html

# Wide Review of Proposed Amendments
https://github.com/w3c/csswg-drafts/issues/10245#issuecomment-2073863058

# Issues addressed
https://www.w3.org/TR/2024/REC-mediaqueries-3-20240516/#changes-2012

# Link to internal AC Review results
https://www.w3.org/2002/09/wbs/33280/mediaqueries-3-proposedcorrections-2022/results

# Formal Objections
See https://github.com/w3c/csswg-drafts/issues/10245#issuecomment-2073863058

# Implementation
https://www.w3.org/TR/2024/REC-mediaqueries-3-20240516/#changes-2012

# Patent disclosures
https://www.w3.org/groups/wg/css/ipr

**Comment by plehegar** [comment]
Transition approved.

The publication draft still contains the mention "proposed correction". With this approval, the normative text ought to be updated.

In addition, please [consider using HTML and DOM LS](https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2024%2FREC-mediaqueries-3-20240516%2F) for the 2 following references to the HTML specification:

https://www.w3.org/TR/1999/REC-html401-19991224/present/styles.html
https://www.w3.org/TR/1999/REC-html401-19991224/types.html

**Comment by svgeesus** [comment]
> The publication draft still contains the mention "proposed correction". With this approval, the normative text ought to be updated.

No, the spec is correct.

The text from the _earlier_ proposed correction has been made normative. This publication also adds a _new_ proposed correction.

**Comment by svgeesus** [comment]
From [the editor](https://github.com/w3c/csswg-drafts/issues/10245#issuecomment-2116758902), regarding HTML 4 references:

> They are used to refer to what the HTML 4 spec said about what then-future features should do, and it serves as historical background for this spec, so I think it should stay as is.

**Comment by plehegar** [comment]
Approved.

**Comment by svgeesus** [comment]
[Published 21 May 2024](https://www.w3.org/TR/2024/REC-mediaqueries-3-20240521/)
