### ISSUE TITLE
First Note request for EPUB Fixed Layout Accessibility - epub-fxl-a11y/

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#613]
# Document title, URLs, estimated publication date

- EPUB Fixed Layout Accessibility
- Editor's draft: https://w3c.github.io/epub-specs/epub33/fxl-a11y/?specStatus=NOTE&publishDate=2024-05-30
- Estimated publication date: 30 May, if the approval arrives in time, otherwise 6 June

# Abstract

This document, EPUB Fixed Layout Accessibility, outlines the goals for EPUB accessible fixed layout ebooks while acknowledging the challenges unique to the fixed layout format.

# Status of the Document

https://w3c.github.io/epub-specs/epub33/fxl-a11y/?specStatus=NOTE&publishDate=2024-05-30#sotd

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-pm-wg/2024May/0019.html  (closing a vote by email starting at https://lists.w3.org/Archives/Public/public-pm-wg/2024May/0002.html)

# Is it intended to be a W3C Statement?

No.

Cc: @wareid @TzviyaSiegman @shiestyle

**Comment by plehegar** [comment]
Approved.

**Comment by iherman** [comment]
Publication requested for 30th of May

**Comment by iherman** [comment]
Note published: https://www.w3.org/TR/2024/NOTE-epub-fxl-a11y-20240530

Closing the issue
