### ISSUE TITLE
Use the real Github issues templates

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/transitions#62]
It would be a better integration if you could use the real issue templates provided by GitHub
See: https://help.github.com/articles/about-issue-and-pull-request-templates/#issue-templates

(I discussed this with @deniak)

**Comment by tripu** [comment]
Cool, I didn't know multiple templates were supported now!

However, templates still don't provide assignees, labels, projects, milestones, etc. I think the best approach is to continue using query params like `assignee` and `labels`, and to replace `title` and `body` with the new param `template` and the right template filename in each case&nbsp;&mdash;&nbsp;*title* and *label* will be set by that template file.

https://help.github.com/articles/about-automation-for-issues-and-pull-requests-with-query-parameters/#filling-issues-and-pull-requests-with-custom-templates

**Comment by dontcallmedom** [comment]
templates [now can have assignees and labels](https://blog.github.com/changelog/2018-12-05-issue-template-automation-improvements/)

**Comment by plehegar** [comment]
We now have templates!
