### ISSUE TITLE
First Note request for Verifiable Credentials Overview - vc-overview

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#623]
# Document title, URLs, estimated publication date

- Verifiable Credentials Overview
- https://w3c.github.io/vc-overview/?specStatus=NOTE
- 2024-06-13

# Abstract

> Credentials are a part of our daily lives; driver's licenses are used to assert that we are capable of operating a motor vehicle, university degrees can be used to assert our level of education, and government-issued passports enable us to travel between countries. The family of W3C Recommendations for Verifiable Credentials, described in this overview document, provides a mechanism to express these sorts of credentials on the Web in a way that is cryptographically secure, privacy respecting, and machine-verifiable.

# Status of the Document

See https://w3c.github.io/vc-overview/?specStatus=NOTE#sotd

# Link to group's decision to request transition

https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-05-vcwg#resolution1

# Is it intended to be a W3C Statement?

No

cc @brendzundel

**Comment by plehegar** [comment]
Approved.

**Comment by iherman** [comment]
Publication request sent: https://lists.w3.org/Archives/Team/webreq/2024Jun/0002.html

**Comment by ylafon** [comment]
Published at https://www.w3.org/TR/2024/NOTE-vc-overview-20240613/
