### ISSUE TITLE
[other/tag] Request a statement review for Ethical Web Principles

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#624]
# Document title, URL
https://www.w3.org/TR/ethical-web-principles/

# Abstract

See published Note

# Status

See published Note

# Wide Review

We most recently presented this document at the AC meeting in 2024 and had generally good feedback there. 

A11Y request: https://github.com/w3c/a11y-request/issues/75#issuecomment-2126782306 

I18N request feedback: https://github.com/w3ctag/ethical-web-principles/issues/116 - we resolved with [PR 119](https://github.com/w3ctag/ethical-web-principles/pull/119).

PING feedback: the PING group did raise an issue https://github.com/w3ctag/ethical-web-principles/issues/94 however the TAG agreed that the issue had been dealt with in the existing tech https://github.com/w3ctag/ethical-web-principles/issues/94#issuecomment-1661896067 and while some discussion on this point continued, we agreed to put it on thee back burner for now. 

As noted in the acknowledgements section, this document has had review from tech ethicists as well people in the community. We reached out to civil society and advocacy groups, as well as regulators (though the latter often cannot comment officially) and communicated about it on social media. The UN Office of the High Commissioner  on Human Rights mentioned our document in their presentation to the Advisory Committee, noting it as an example of “growing awareness among SSOs and those active in standard-setting processes of the importance of human rights”. https://www.w3.org/2024/Talks/ac-slides/human-rights/OHCHR.pdf It was also highlighted in the report from the same office on “Human rights and technical standard-setting processes…” https://digitallibrary.un.org/record/4031373 also quoted the Ethical Web Principles as an example of “growing awareness of the importance of human rights among standard-setting organizations.” The document has been reference in the W3C Vision doc as well as the Ethical Principles for Web Machine Learning  https://www.w3.org/TR/webmachinelearning-ethics/ issued by the Machine Learning Working Group, among other references.

# Link to group's decision to request transition

The TAG recorded a [consensus decision](https://github.com/w3ctag/meetings/blob/gh-pages/2024/telcons/05-20-minutes.md#recorded-consensus-in-ethical-web-principles-transition-request ) here to move the document forward for transition to statement. 

# Issues addressed

[53  issues](https://github.com/w3ctag/ethical-web-principles/issues) were closed and processed. The remaining issues, the group explicitly decided to leave to a future revision (‘back urner’). No commenter has expressed dissatisfaction with the resolutions. We have highlighted significant contributions from commenters in the [Acknowledgements section](https://www.w3.org/TR/ethical-web-principles/#acknowlegements) of the document.

# Formal Objections

No formal objections were received by the task force during the development of this document.

**Comment by plehegar** [comment]
It's not clear what the TAG plans for a few open issues, such as https://github.com/w3ctag/ethical-web-principles/issues/121 , https://github.com/w3ctag/ethical-web-principles/issues/120, https://github.com/w3ctag/ethical-web-principles/issues/92 .

Are those for a next revision ?

**Comment by plehegar** [comment]
cc @plinss @ylafon @torgo

**Comment by ylafon** [comment]
Note that https://www.w3.org/TR/2024/DNOTE-ethical-web-principles-20240610/ was published, merging an editorial PR (https://github.com/w3ctag/ethical-web-principles/pull/122)

**Comment by plehegar** [comment]
PING: https://github.com/w3ctag/ethical-web-principles/issues/94 should indeed in the next version.

**Comment by plehegar** [comment]
https://github.com/w3ctag/ethical-web-principles/issues/121 remains to be classified.

**Comment by torgo** [comment]
We're still talking about this one. We may make some progress at the f2f.

**Comment by ylafon** [comment]
https://github.com/w3ctag/ethical-web-principles/issues/121 has been closed.
https://www.w3.org/TR/2024/DNOTE-ethical-web-principles-20240718/ has been published as a result of closing it.

**Comment by plehegar** [comment]
Approved.

The Note for the AC Review is https://www.w3.org/TR/2024/DNOTE-ethical-web-principles-20240718/  .

Per [Process](https://www.w3.org/policies/process/20231103/#w3c-statement):

the [Team](https://www.w3.org/policies/process/20231103/#team) must then begin an Advisory Committee Review on the question of whether the document is appropriate to publish as a [W3C Statement](https://www.w3.org/policies/process/20231103/#statement)
During this review period, the Note MUST not be updated during the AC review.
