### ISSUE TITLE
First Note request for Perso-arabic Kashmiri Layout Requirements - arab-ks-lreq

### ISSUE THREAD

**Issue by r12a** [w3c/transitions#625]
# Document title, URLs, estimated publication date
Perso-arabic Kashmiri Layout Requirements
https://www.w3.org/TR/2024/DNOTE-arab-ks-lreq-20240618/
18 June 2024

# Abstract
This document describes or points to requirements for the layout and presentation of text in Kashimiri using the Perso-arabic script when it is used by Web standards and technologies, such as HTML, CSS, Mobile Web, Digital Publications, and Unicode.

# Status of the Document
https://www.w3.org/TR/2024/DNOTE-arab-ks-lreq-20240618/#sotd

# Link to group's decision to request transition
https://www.w3.org/2024/06/06-i18n-minutes.html#t06
https://www.w3.org/2024/06/06-i18n-minutes.html#t09

# Is it intended to be a W3C Statement?
No

**Comment by plehegar** [comment]
Approved

**Comment by r12a** [comment]
Published at https://www.w3.org/TR/arab-ks-lreq/

**Comment by ylafon** [comment]
P
