### ISSUE TITLE
FPWD Request for Accessibility Conformance Testing (ACT) Rules Format 1.1 - act-rules-format-1.1

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/transitions#628]
# Document title, URLs, estimated publication date
https://www.w3.org/TR/2024/WD-act-rules-format-1.1-20240618/

# Abstract
https://www.w3.org/TR/2024/WD-act-rules-format-1.1-20240618/#abstract

# Status
https://www.w3.org/TR/2024/WD-act-rules-format-1.1-20240618/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
Yes

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/w3c-wai-gl/2024AprJun/0130.html

# Information about implementations known to the Working Group

We have at least two automated tools and one manual tester that implement rules based on this format. Current rules are being updated to match the new features introduced in this updated version.

**Comment by plehegar** [comment]
Editor's draft is at https://w3c.github.io/wcag-act/act-rules-format.html (the links above weren't working yet).

Approved.

**Comment by daniel-montalvo** [comment]
Thanks for warning @plehegar 

Document should be ready at https://www.w3.org/TR/2024/WD-act-rules-format-1.1-20240618?

Just forgot to add "2024" to the URI.

**Comment by ylafon** [comment]
Published at https://www.w3.org/TR/2024/WD-act-rules-format-1.1-20240618/
