### ISSUE TITLE
DRY Request for WebCodecs VideoFrame Metadata Registry - webcodecs-video-frame-metadata-registry

### ISSUE THREAD

**Issue by tidoust** [w3c/transitions#629]
# Document title, URLs, estimated publication date

- Title: WebCodecs VideoFrame Metadata Registry
- URL: https://w3c.github.io/webcodecs/video_frame_metadata_registry.html
- Estimated publication date: 25 June 2024

# Abstract

"This registry is intended to enumerate the metadata fields that can be attached to [`VideoFrame`](https://w3c.github.io/webcodecs/#videoframe) objects via the [`VideoFrameMetadata`](https://w3c.github.io/webcodecs/#dictdef-videoframemetadata) dictionary."
https://w3c.github.io/webcodecs/video_frame_metadata_registry.html#abstract

# Status

The Status of This Document section in the Editor's Draft is not the right one (because there is no notion of an Editor's Draft of a Draft Registry in ReSpec). The expected Status of this Document will be the same as the one in the other Draft Registry that the group already published:
https://www.w3.org/TR/webcodecs-codec-registry/#sotd

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-media-wg/2024Jun/0009.html

**Comment by plehegar** [comment]
Approved.

**Comment by tidoust** [comment]
Published at https://www.w3.org/TR/2024/DRY-webcodecs-video-frame-metadata-registry-20240702/
