### ISSUE TITLE
Notify Chairs and Comm of new transition requests

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/transitions#63]
In order to continue to notify by emails Chairs and Comm of incoming transition requests you could use 
[github-notify-ml](https://github.com/dontcallmedom/github-notify-ml/) (using the proper combination of events and filters).
Note that this only sends email in digest mode (ie at max once a day).

(I discussed this with @deniak, that would answer @koalie recent comment)

**Comment by svgeesus** [comment]
That would be good. I have seen a couple of instances where this repo was updated by chairs was not copied, thus delaying the start of the one-week timeout.

**Comment by plehegar** [comment]
This should be addressed for the requirements in #71

**Comment by plehegar** [comment]
fyi, the code is at https://github.com/w3c/transition-issues-bot
as soon as I have a labs.w3.org, I'll start live testing the email and setting labels.

**Comment by plehegar** [comment]
New notification is deployed.
