### ISSUE TITLE
REC Update Request for CSS Containment Module Level 1 - css-contain-1

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#630]
# Document title, URLs, estimated publication date

CSS Containment Module Level 1
https://drafts.csswg.org/css-contain-1/
Tue 25 June 2024

# Abstract

This CSS module describes the [contain](https://drafts.csswg.org/css-contain-1/#propdef-contain) property, which indicates that the element’s subtree is independent of the rest of the page. This enables heavy optimizations by user agents when used well.
[CSS](https://www.w3.org/TR/CSS/) is a language for describing the rendering of structured documents (such as HTML and XML) on screen, on paper, etc.

# Status

https://drafts.csswg.org/css-contain-1/#sotd (as ED)

# Link to group's decision to request the update

> RESOLVED: We request a updated recommendation, with the three proposed changes folded in
https://github.com/w3c/csswg-drafts/issues/6900#issuecomment-2160081795

# Link to Last Call for Review of Proposed Amendments

https://lists.w3.org/Archives/Member/w3c-ac-members/2022OctDec/0009.html

# Wide Review of Proposed Amendments

https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Acss-contain-1+

# Issues addressed

No issues raised on the proposed amendments. There is [one open issue](https://github.com/w3c/csswg-drafts/issues/7875), unrelated, which once resolved will be addressed with a future candidate correction.

# Link to internal AC Review results

https://www.w3.org/2002/09/wbs/33280/containment-1-pc2022/results

# Formal Objections

none

# Implementation

https://drafts.csswg.org/css-contain-1/implementation-report-2022-09

# Patent disclosures

https://www.w3.org/groups/wg/css/ipr/

cc @frivoal

**Comment by plehegar** [comment]
Approved.

**Comment by svgeesus** [comment]
Publication request sent 21 June expected 25 June

**Comment by svgeesus** [comment]
[Published 25 June](https://www.w3.org/TR/2024/REC-css-contain-1-20240625/)
