### ISSUE TITLE
First Note request for Urdu Gap Analysis - arab-ur-gap

### ISSUE THREAD

**Issue by r12a** [w3c/transitions#632]
# Document title, URLs, estimated publication date
Urdu Gap Analysis
https://www.w3.org/TR/2024/DNOTE-arab-ur-gap-20240702/
2 July 2024

# Abstract
This document describes and prioritises gaps for the support of Urdu on the Web and in eBooks. In particular, it is concerned with text layout. It checks that needed features are supported in W3C specifications, in particular HTML and CSS and those relating to digital publications. It also checks whether the features have been implemented in browsers and ereaders.

# Status of the Document
https://www.w3.org/TR/2024/DNOTE-arab-ur-gap-20240702/Overview.html#sotd

# Link to group's decision to request transition
https://www.w3.org/2024/06/20-i18n-minutes.html#t06

# Is it intended to be a W3C Statement?
No

**Comment by plehegar** [comment]
Approved
