### ISSUE TITLE
FPWD Request for EME - `encrypted-media-2` / DRY Request for EME HDCP Version Registry - `eme-hdcp-version-registry`

### ISSUE THREAD

**Issue by tidoust** [w3c/transitions#633]
2 requests in one.

# Document title, URLs, estimated publication date
- Encrypted Media Extensions: https://w3c.github.io/encrypted-media/
- Encrypted Media Extensions HDCP Version Registry: https://w3c.github.io/encrypted-media/hdcp-version-registry.html
- Both documents to be published jointly on 2 July 2024 (or later)

From a shortname versioning perspective, the goal with EME is to follow the same path as for MSE:
- create `encrypted-media-1` for the first Recommendation
- use `encrypted-media-2` for the new version
- make `encrypted-media` an alias that targets the new version

# Abstract

See [EME abstract](https://w3c.github.io/encrypted-media/#abstract). No change compared to previously published Recommendation.

See [EME HDCP Version Registry abstract](https://w3c.github.io/encrypted-media/hdcp-version-registry.html#abstract):
> This registry defines the set of High-bandwidth Digital Content Protection (HDCP) versions used with the Encrypted Media Extensions getStatusForPolicy method [[ENCRYPTED-MEDIA](https://w3c.github.io/encrypted-media/hdcp-version-registry.html#bib-encrypted-media)].
>
> This registry is non-normative.

# Status

- [EME Status of this Document](https://w3c.github.io/encrypted-media/#sotd)
- The Status of this Document section of the [HDCP Version Registry](https://w3c.github.io/encrypted-media/hdcp-version-registry.html#sotd) is currently incorrect because there is no Editor's Draft of a DRY in ReSpec, but will be the same as the one used in WebCodecs registries once published.

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-media-wg/2024Jun/0019.html

# Information about implementations known to the Working Group
The EME spec is implemented across core browsers. The new version adds two features (mentioned in the charter of the group) and integrates a number of maintenance fixes. Core browsers already ship or are implementing the changes.

**Comment by plehegar** [comment]
Approved

**Comment by tidoust** [comment]
Specs published on 18 July 2024:
https://www.w3.org/TR/2024/WD-encrypted-media-2-20240718/
https://www.w3.org/TR/2024/DRY-eme-hdcp-version-registry-20240718/
