### ISSUE TITLE
DRY Requests for previous MSE/EME registry notes, and associated NOTE Requests

### ISSUE THREAD

**Issue by tidoust** [w3c/transitions#635]
3 related DRY requests combined with 9 NOTE requests about MSE/EME that are on the Media WG's plate but were last published as NOTES before the Media WG got created. 

The DRY requests are meant to put the documents on the Registry track, which didn't exist previously. The NOTE requests are simply meant to allow the Media WG to publish editorial updates that were made to align with the latest version of ReSpec (and enable auto-publish afterwards).

# Document titles, URLs, estimated publication dates

For the DRY requests:
* Media Source Extensions Byte Stream Format Registry
  https://w3c.github.io/mse-byte-stream-format-registry/
  `mse-byte-stream-format-registry`
* Encrypted Media Extensions Initialization Data Format Registry
  https://w3c.github.io/encrypted-media/format-registry/initdata/index.html
  `eme-initdata-registry`
* Encrypted Media Extensions Stream Format Registry
  https://w3c.github.io/encrypted-media/format-registry/stream/index.html
  `eme-stream-registry`

For the NOTE requests (same shortnames as before):
* MSE Byte Stream Formats:
  * WebM Byte Stream Format
    https://w3c.github.io/mse-byte-stream-format-webm/
  * ISOBMFF Byte Stream Format
    https://w3c.github.io/mse-byte-stream-format-isobmff/
  * MPEG-2 TS Byte Stream Format
    https://w3c.github.io/mse-byte-stream-format-mp2t/
  * MPEG Audio Byte Stream Format
    https://w3c.github.io/mse-byte-stream-format-mpeg-audio/
* EME Initialization Data Formats:
  * "cenc" Initialization Data Format
    https://w3c.github.io/encrypted-media/format-registry/initdata/cenc.html
  * "keyids" Initialization Data Format
    https://w3c.github.io/encrypted-media/format-registry/initdata/keyids.html
  * "webm" Initialization Data Format
    https://w3c.github.io/encrypted-media/format-registry/initdata/webm.html
* EME Stream Formats:
  * ISO Common Encryption Protection Scheme for ISO Base Media File Format Stream Format
    https://w3c.github.io/encrypted-media/format-registry/stream/mp4.html
  * WebM Stream Format
    https://w3c.github.io/encrypted-media/format-registry/stream/webm.html

In terms of publication date, it would probably make sense to group all of these publications with #633. I'd need a bit of time to prepare all documents for publication. *11 July 2024* or later would seem reasonable.

# Abstract

The abstracts have not changed since publication of the former Notes, except to add "This registry is non-normative." in the abstracts of the DRY registries, as done in other registries published by the Media WG.

# Status

As with the other DRY requests, the Status of this Document sections for the DRY documents are not the expected ones because there is no Editor's Draft of a DRY in ReSpec, but will be the same as the other registries published by the Media WG, see for example: https://www.w3.org/TR/webcodecs-video-frame-metadata-registry/#sotd

The MSE and EME NOTES will adopt the usual Status of this Document sections of the Media WG, for example: https://www.w3.org/TR/webcodecs-vp8-codec-registration/#sotd (except that status will be "Group Note", and not "Draft Group Note").

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-media-wg/2024Jul/0000.html

# Information about implementations known to the Working Group
No change. The registries and Notes are used and supported where appropriate in browsers that implement MSE/EME already.

**Comment by plehegar** [comment]
Approved

**Comment by tidoust** [comment]
All specs published on 18 July, see [blog post](https://www.w3.org/news/2024/drafts-and-notes-update-of-the-media-source-extensions-mse-and-encrypted-media-extensions-eme-families-of-specifications/) for details.
