### ISSUE TITLE
FPWD Request for CSS Scroll Snap Module Level 2 - css-scroll-snap-2

### ISSUE THREAD

**Issue by DavMila** [w3c/transitions#638]
# Document title, URLs, estimated publication date
CSS Scroll Snap Module Level 2, https://drafts.csswg.org/css-scroll-snap-2/, July 16

# Abstract
This module contains features to control panning and scrolling behavior with “snap positions”.

# Status
https://drafts.csswg.org/css-scroll-snap-2/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://github.com/w3c/csswg-drafts/issues/6985#issuecomment-2166073296

# Information about implementations known to the Working Group
Active implementation in chrome, about to ship.

**Comment by plehegar** [comment]
Approved.

**Comment by svgeesus** [comment]
Publication requested 2024-07-19, expected 2024-07-23

**Comment by svgeesus** [comment]
[Published 23 July 2024](https://www.w3.org/TR/2024/WD-css-scroll-snap-2-20240723/)
