### ISSUE TITLE
 First Note request for 5 i18n docs - latn-gap, latn-lreq, hebr-lreq, arab-lreq, hani-lreq

### ISSUE THREAD

**Issue by r12a** [w3c/transitions#639]
# Document title, URLs, estimated publication date

Latin Script Resources
https://www.w3.org/TR/2024/DNOTE-latn-lreq-20240716/
16 July 2024

Latin Script Gap Analysis 
https://www.w3.org/TR/2024/DNOTE-latn-gap-20240716/
16 July 2024

Hebrew Script Resources
https://www.w3.org/TR/2024/DNOTE-hebr-lreq-20240716/
16 July 2024

Arabic Script Resources
https://www.w3.org/TR/2024/DNOTE-arab-lreq-20240716/
16 July 2024

Chinese Script Resources
https://www.w3.org/TR/2024/DNOTE-hani-lreq-20240716/
16 July 2024

# Abstract
See documents

# Status of the Document
See documents

# Link to group's decision to request transition
https://www.w3.org/2024/07/11-i18n-minutes.html#t06
https://www.w3.org/2024/07/04-i18n-minutes.html#t06

# Is it intended to be a W3C Statement?
No

**Comment by plehegar** [comment]
Approved

**Comment by r12a** [comment]
Published.
