### ISSUE TITLE
First Note request for 8 i18n docs - cyrl-gap, cyrl-lreq, beng-lreq, deva-lreq, ethi-lreq, geor-lreq, kore-lreq, mong-lreq

### ISSUE THREAD

**Issue by r12a** [w3c/transitions#640]
# Document title, URLs, estimated publication date

Cyrillic Script Resources
https://www.w3.org/TR/2024/DNOTE-cyrl-lreq-20240723/
23 July 2024

Cyrillic Gap Analysis
https://www.w3.org/TR/2024/DNOTE-cyrl-gap-20240723/
23 July 2024

Bengali Script Resources
https://www.w3.org/TR/2024/DNOTE-beng-lreq-20240723/
23 July 2024

Devanagari Script Resources
https://www.w3.org/TR/2024/DNOTE-deva-lreq-20240723/
23 July 2024

Ethiopic Script Resources
https://www.w3.org/TR/2024/DNOTE-ethi-lreq-20240723/
23 July 2024

Georgian Script Resources
https://www.w3.org/TR/2024/DNOTE-geor-lreq-20240723/
23 July 2024

Korean Script Resources
https://www.w3.org/TR/2024/DNOTE-kore-lreq-20240723/
23 July 2024

Mongolian Script Resources
https://www.w3.org/TR/2024/DNOTE-mong-lreq-20240723/
23 July 2024

# Abstract
See documents

# Status of the Document
See documents

# Link to group's decision to request transition
https://www.w3.org/2024/07/18-i18n-minutes.html#t06
https://www.w3.org/2024/07/11-i18n-minutes.html#t06

# Is it intended to be a W3C Statement?
no
First Note request for 5 i18n docs - latn-gap, latn-lreq, hebr-lreq, arab-lreq, hani-lreq

**Comment by r12a** [comment]
ping @plehegar

**Comment by plehegar** [comment]
Approved
