### ISSUE TITLE
 First Note request for 9 i18n docs - grek-lreq, gujr-lreq, taml-lreq, java-lreq, cher-lreq, cans-lreq, osge-lreq, jpan-lreq, tibt-lreq 

### ISSUE THREAD

**Issue by r12a** [w3c/transitions#641]
# Document title, URLs, estimated publication date

Greek Script Resources
https://www.w3.org/TR/2024/DNOTE-grek-lreq-20240730/
30 July 2024

Gujarati Script Resources
https://www.w3.org/TR/2024/DNOTE-gujr-lreq-20240730/
30 July 2024

Tamil Script Resources
https://www.w3.org/TR/2024/DNOTE-taml-lreq-20240730/
30 July 2024

Javanese Script Resources
https://www.w3.org/TR/2024/DNOTE-java-lreq-20240730/
30 July 2024

Cherokee Script Resources
https://www.w3.org/TR/2024/DNOTE-cher-lreq-20240730/
30 July 2024

Canadian Syllabics Script Resources
https://www.w3.org/TR/2024/DNOTE-cans-lreq-20240730/
30 July 2024

Osage Script Resources
https://www.w3.org/TR/2024/DNOTE-osge-lreq-20240730/
30 July 2024

Japanese Script Resources
https://www.w3.org/TR/2024/DNOTE-jpan-lreq-20240730/
30 July 2024

Tibetan Script Resources
https://www.w3.org/TR/2024/DNOTE-tibt-lreq-20240730/
30 July 2024

# Abstract
See documents

# Status of the Document
See documents

# Link to group's decision to request transition
https://www.w3.org/2024/07/25-i18n-minutes.html#t06
https://www.w3.org/2024/07/18-i18n-minutes.html#t06

# Is it intended to be a W3C Statement?

no

**Comment by plehegar** [comment]
Approved.

**Comment by r12a** [comment]
@plehegar  I edited the comment to correct the name of Gujarati Gap Analysis --> Gujarati Script Resources. The title of the document itself is correct, this was just a typo in this request.
