### ISSUE TITLE
CR Snapshot and CR Draft Update Request for Payment Request API - payment-request

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/transitions#643]
Hello all,

Payment Request API was published as a Recommendation on 8 September 2022 . As part of that journey the Working Group removed some features related to addresses (shipping and billing) in response to feedback received during privacy and internationalization reviews. However, both Chromium and Webkit browsers had already shipped with support for the address features and, several years later, they continue to support those features. The browser implementers have requested that we re-align the specification with implementations and endeavor to resolve any previously raised issues.

For that reason, the Web Payments WG has reached a decision to request to republish Payment Request twice in quick succession:

* As a Candidate Recommendation snapshot with no changes from the Recommendation
* As a Candidate Recommendation Draft, restoring the features related to addresses.

That would achieve our goal of having a draft document on the TR page with features currently shipping in browsers, and we would then work to address the issues that were previously raised before advancing to Proposed Recommendation.

# Document URLs

* [CR Snapshot](https://www.w3.org/2024/07/prapi/CR-payment-request-20240710.html)
* [CR Draft](https://www.w3.org/2024/07/prapi/CRD-payment-request-20240710.html)

# Link to group's decision to request transition

* [Decision to publish the CRs](https://lists.w3.org/Archives/Public/public-payments-wg/2024Aug/0001.html)

# Link to previous Candidate Recommendation transition or update request

* [Recommendation request from February 2022](https://github.com/w3c/transitions/issues/411)

# Substantive changes

The [diff between CR Snapshot and CR Draft](https://www.w3.org/2024/07/prapi/diff-20240710.html) amounts to:

* Re-introduce addresses. Some of the material has been moved to another specification --[Contact Picker API](https://w3c.github.io/contact-picker/)-- because standardized addresses are useful on the Web beyond payments. The updated Payment Request API retains much of the original text related to addresses, but also includes some references to Contact Picker API.
* [Changes related to user activation](https://github.com/w3c/payment-request/pull/1009)
* Editorial fixes (e.g., due to changes in referenced specifications) and a bug fix (related to show() only being callable in a foreground tab).

# Any changes in requirements?

None.

# Wide Review of substantive changes

We believe the W3C Process allows us to publish these documents without first getting wide review of reintroduction of these features. We plan to get wide review before advancing to Proposed Recommendation.

# Issues status

The [Payment Request issues list](https://github.com/w3c/payment-request/issues).

# Formal Objections

No new Formal Objections since publication of the Recommendation.

# Any changes in implementation information?

As mentioned above, implementations are shipping support for the re-introduced address feature. Regarding removal of the user activation requirement, we do not yet have two implementations and are tracking that via [issue 1025](https://github.com/w3c/payment-request/issues/1025).

# Deadline for further comments

1 October 2024

# Any changes in patent disclosures?

None.

See [Requirements for updating a Candidate Recommendation Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot) for further information.

**Comment by plehegar** [comment]
Approved.

Just in case you feel ambitious: the changelog in the CR snapshot contains the list of changes applied to CR Draft (eg it's listing the addition of the user activation requirement section even it's not part of the snapshot). Since the snapshot is meant to get replaced right away, that's ok.

**Comment by ianbjacobs** [comment]
Thank you @plehegar. I have sent a publication request to the Webmaster.
