### ISSUE TITLE
FPWD Request for CSS Easing Functions Level 2 - css-easing-2

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#646]
# Document title, URLs, estimated publication date

**CSS Easing Functions Level 2**
https://drafts.csswg.org/css-easing-2/
Tues 20 Aug 2024

# Abstract

This CSS module describes a way for authors to define a transformation that controls the rate of change of some value. Applied to animations, such transformations can be used to produce animations that mimic physical phenomena such as momentum or to cause the animation to move in discrete steps producing robot-like movement. Level 2 adds more sophisticated functions for custom easing curves.
[CSS](https://www.w3.org/TR/CSS/) is a language for describing the rendering of structured documents (such as HTML and XML) on screen, on paper, etc.

# Status

https://drafts.csswg.org/css-easing-2/#sotd (as ED)

# Is it a delta specification intended to become a W3C Recommendation?

No

# Link to group's decision to request transition

RESOLVED: Add ChrisL and TabAtkins for easing level 2 and publish FWD
https://github.com/w3c/csswg-drafts/issues/10688#issuecomment-2289215756

# Information about implementations known to the Working Group

Already very good implementation, long past time to become a FPWD!
https://wpt.fyi/results/css/css-easing/

![image](https://github.com/user-attachments/assets/da522139-65c5-47f3-8dbb-9624721bd14c)

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Publication request sent Mon 26 Aug expected Thurs 29 August

**Comment by svgeesus** [comment]
https://www.w3.org/TR/2024/WD-css-easing-2-20240829/
