### ISSUE TITLE
FPWD Request for Federated Credential Management API - fedcm

### ISSUE THREAD

**Issue by simoneonofri** [w3c/transitions#647]
# Document title, URLs, estimated publication date
**Federated Credential Management API**
https://w3c-fedid.github.io/FedCM/
21 Aug 2024

# Abstract
A Web Platform API that allows users to login to websites with their federated accounts in a privacy preserving manner.

# Status
[Draft Community Group Report](https://www.w3.org/standards/types#CG-DRAFT)

# Is it a delta specification intended to become a W3C Recommendation?
no (ref. to glossary here https://www.w3.org/2005/07/13-pubrules-about)

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-fedid-wg/2024Aug/0003.html

# Information about implementations known to the Working Group

https://wpt.fyi/results/?q=fedcm%2F*&run_id=5184803087581184&run_id=5171450571128832&run_id=5093247806603264&run_id=5155690759061504

**Comment by wseltzer** [comment]
Repo has now moved under the WG, putting the draft spec at, https://w3c-fedid.github.io/FedCM/

**Comment by plehegar** [comment]
Approved, as long as the Status is updated to make it a proper FPWD.

Note that the document contains the Login Status API as well. I guess the document split will happen later, which is fine.

**Comment by simoneonofri** [comment]
created the PR https://github.com/w3c-fedid/FedCM/pull/634

**Comment by simoneonofri** [comment]
Installed here:

https://www.w3.org/TR/2024/WD-fedcm-1-20240820/Overview.html

Waiting the last detail for publication tomorrow

**Comment by simoneonofri** [comment]
Published https://www.w3.org/news/2024/first-public-working-draft-federated-credential-management-api/
