### ISSUE TITLE
REC Request for Data Catalog Vocabulary (DCAT), Version 3 - VOCAB-DCAT-3

### ISSUE THREAD

**Issue by pchampin** [w3c/transitions#648]
# Document title, URLs, estimated publication date

Title: Data Catalog Vocabulary (DCAT) - Version 3
URL: http://htmlpreview.github.io/?https://raw.githubusercontent.com/w3c/dxwg/rec-snapshot-2024/dcat/publication-snapshots/REC/Overview.html
Estimated publication date: 2024-08-22

# Abstract

http://htmlpreview.github.io/?https://raw.githubusercontent.com/w3c/dxwg/rec-snapshot-2024/dcat/publication-snapshots/REC/Overview.html#abstract

# Status

http://htmlpreview.github.io/?https://raw.githubusercontent.com/w3c/dxwg/rec-snapshot-2024/dcat/publication-snapshots/REC/Overview.html#sotd

# Link to group's decision to request transition

https://www.w3.org/2002/09/wbs/99375/dcat-3-to-pr/results

# Wide Review

No change during AC review.

https://github.com/w3c/dxwg/issues/1502
(see also [a summary](https://docs.google.com/document/d/1EPQKTLXHlJUTDWqGrK3tRbfLC3mKHjEu_E26veTcC-U/edit) of the coordination with all groups listed in the charter)

# Issues addressed

All pending issues were addressed: https://github.com/w3c/dxwg/issues?q=is%3Aissue+is%3Aopen+label%3Adcat+-label%3Afuture-work
The remaining open issues do not impact the recommendation itself:

* w3c/dxwg#1352 concerns (non-substantive) additions to the companion RDF files
* w3c/dxwg#1223 concerns the referencing of DCAT in [specref](https://www.specref.org/)

# Link to internal AC Review results

https://www.w3.org/2002/09/wbs/33280/pr-vocab-dcat-3/results

# Formal Objections

None

**Comment by plehegar** [comment]
Approved.

**Comment by plehegar** [comment]
Note: the Proposed Recommendation indicated that DCAT 3 supersedes DCAT 2. We will supersede DCAT 2 as part of publishing DCAT 3 as a REC.
