### ISSUE TITLE
FPWD Request for CSS Values and Units Module Level 5 - css-values-5

### ISSUE THREAD

**Issue by dbaron** [w3c/transitions#649]
# Document title, URLs, estimated publication date
CSS Values and Units Module Level 5
https://drafts.csswg.org/css-values-5/
Thursday 5 September 2024?

# Abstract
This CSS module describes the common values and units that CSS properties accept and the syntax used for describing them in CSS property definitions.
[CSS](https://www.w3.org/TR/CSS/) is a language for describing the rendering of structured documents (such as HTML and XML) on screen, on paper, etc.

# Status
https://drafts.csswg.org/css-values-5/#sotd (currently ED, will change for WD)

# Is it a delta specification intended to become a W3C Recommendation?
it's currently a delta specification but is intended to become un-delta-fied before recommendation.  (I don't know if that means the answer is yes or no.)

# Link to group's decision to request transition
https://github.com/w3c/csswg-drafts/issues/6900#issuecomment-2289210116

# Issues
https://github.com/w3c/csswg-drafts/labels/css-values-5

# Information about implementations known to the Working Group
* Chrome has an experimental implementation of `progress()`, `media-progress()` and `container-progress()`.
* Implementation of `attr()` is in progress in Chrome.
* Implementation of `calc-size()` and `interpolate-size` is in progress in Chrome.

**Comment by dbaron** [comment]
cc @tabatkins @svgeesus @mirisuzanne @fantasai

**Comment by plehegar** [comment]
Approved.

This will not be a delta specification. As long as the merge is done BEFORE this moves to Candidate Recommendation, this should be fine. See also [Can a Working Group publish a version 2.1 of a Recommendation that defines conformance by reference to the 2.0 Recommendation, plus a few new features defined in 2.1?](https://www.w3.org/2003/12/22-pp-faq#diffspec). In the meantime, the PP commitments from the FPWD will only be on the diff.

**Comment by svgeesus** [comment]
(Pubrules service is down)

**Comment by svgeesus** [comment]
Publication requested Fri 30 Aug expected Tue 03 Sept

**Comment by svgeesus** [comment]
[Published 3 Sept 2024](https://www.w3.org/TR/2024/WD-css-values-5-20240903/)
