### ISSUE TITLE
[TAG] Proposal to obsolete Widgets family of specs

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#65]
# title, URL of the document to be obsoleted

* Name: Widget specs
* Specification URL: https://www.w3.org/TR/?title=widget

# title, URL of the newer version

Service workers and web manifest are better solutions to the same problem.

# Link to group's decision to request obsoleting

https://cryptpad.w3ctag.org/code/#/1/view/fGfpK-rLumdNCoVxnbfPGQ/T1Uf78xBR2PBXovu7Y3OxVaAa0o+xcTiyK3bI4HzC9s/

# Rationale

See https://github.com/w3ctag/obsoletion/issues/3

# Implementation

The following implementations of this specification are known:

  Apache Cordoba
  Apache Wookie
  Other implementations are gone...

There are some stats on usage here:
https://www.scnsoft.com/blog/apache-cordova-is-there-a-future-for-it

(cc @ylafon )

**Comment by plehegar** [comment]
It appears that this request doesn't need Director's approval:
* the Director should object in the TAG instead if needed since he is a participant there
* the Process is clear that the Director MUST begin an AC review when requested to do so anyway.

However, the Director may provide/add comments in the AC review form if he wishes, thus the request are still necessary even if those will always be approved.

See also:
[[
Per section 6.9, in some conditions, the Director is required to accept the transition request.
]]
https://www.w3.org/Guide/transitions?profile=PR-OBSL

**Comment by swickr** [comment]
Specifically, there are 4 Recommendations, 3 Notes, and 1 abandoned WD:

[Widget Interface Recommendation](http://www.w3.org/TR/2013/REC-widgets-apis-20131031/) 2013-10-31
[XML Digital Signatures for Widgets Recommendation](http://www.w3.org/TR/2013/REC-widgets-digsig-20130418/) 2013-04-18
[Packaged Web Apps (Widgets) - Packaging and XML Configuration Recommendation](http://www.w3.org/TR/2012/REC-widgets-20121127/) 2012-11-27
[Widget Access Request Policy Recommendation](http://www.w3.org/TR/2012/REC-widgets-access-20120207/) 2012-02-07

[Widget Updates](http://www.w3.org/TR/2013/NOTE-widgets-updates-20130606/)  2013-06-06
[Widget URI scheme Note](http://www.w3.org/TR/2012/NOTE-widgets-uri-20120313/) 2012-03-13
[Requirement For Standardizing Widgets Note](http://www.w3.org/TR/2011/NOTE-widgets-reqs-20110927/) 2011-09-27

[Widgets 1.0: The Widget Landscape Working Draft](http://www.w3.org/TR/2008/WD-widgets-land-20080414/) 2008-04-14

**Comment by swickr** [comment]
AC Call for Review should be issued.

I suggest using the sentence from Marco's request to the TAG https://github.com/w3ctag/obsoletion/issues/3  for justification and acknowledge Marcos as the originator of the request to obsolete as well as the primary editor of these specifications.

**Comment by plehegar** [comment]
[AC review started](https://lists.w3.org/Archives/Member/w3c-ac-members/2018JulSep/0035.html)

Deadline is Sep 27.
