### ISSUE TITLE
FPWD Request for CSS Grid Layout Module Level 3 - css-grid-3

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#650]
# Document title, URLs, estimated publication date
CSS Grid Layout Module Level 3
https://drafts.csswg.org/css-grid-3/
As soon as practical, preferably before TPAC

# Abstract
https://drafts.csswg.org/css-grid-3/#abstract

# Status
https://drafts.csswg.org/css-grid-3/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
yes (but it'll be un-delta-ified well before then)

# Link to group's decision to request transition
https://www.w3.org/2024/09/11-css-minutes.html#r01

# Issues
https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Acss-grid-3

# Information about implementations known to the Working Group
Implementations behind a flag in Gecko and WebKit, and Blink is working on one also.

**Comment by svgeesus** [comment]
Publication requested 17 Sept expected 19 Sept

**Comment by svgeesus** [comment]
[Published 19 Sept 2024](https://www.w3.org/TR/2024/WD-css-grid-3-20240919/)
