### ISSUE TITLE
First Note request for Verifiable Credential Extensions - vc-extensions (short name change)

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#654]
# Document title, URLs, estimated publication date

- title: Verifiable Credential Extensions
- URL: https://www.w3.org/TR/2024/NOTE-vc-extensions-20241010/ (not yet on server)
- Latest editor's draft: https://w3c.github.io/vc-extensions/
- Estimated date of publication: 2024-10-10

The document _replaces_ (with a new short name): [VC Specifications Directory](https://www.w3.org/TR/vc-specs-dir/)

# Abstract

This document serves as an unofficial directory for all known Verifiable Credential specifications whether they are released by a global standards setting organization, a community group, an open source project, or an individual.

# Status of the Document

See: https://w3c.github.io/vc-extensions/#sotd

# Link to group's decision to request transition

See https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-08-21-vcwg#section4-2

Note that this is not a new document; the decision was to rename an already existing WG Note, namely the [VC Specifications Directory](https://www.w3.org/TR/vc-specs-dir/). The necessary redirections will have to be made at the time of publication.

# Is it intended to be a W3C Statement?

No.

Cc @msporny

**Comment by plehegar** [comment]
Approved

**Comment by iherman** [comment]
Document published (actually at an earlier date): https://www.w3.org/TR/vc-extensions/
