### ISSUE TITLE
FPWD Request for Web Audio API 1.1 - web-audio-api-11

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#656]
# Document title, URLs, estimated publication date
Web Audio API 1.1
https://webaudio.github.io/web-audio-api/
once approved

# Abstract

This specification describes a high-level Web API for processing and synthesizing audio in web applications. The primary paradigm is of an audio routing graph, where a number of [AudioNode](https://webaudio.github.io/web-audio-api/#AudioNode) objects are connected together to define the overall audio rendering. The actual processing will primarily take place in the underlying implementation (typically optimized Assembly / C / C++ code), but [direct script processing and synthesis](https://webaudio.github.io/web-audio-api/#AudioWorklet) is also supported.

The [Introduction](https://webaudio.github.io/web-audio-api/#introductory) section covers the motivation behind this specification.

This API is designed to be used in conjunction with other APIs and elements on the web platform, notably: XMLHttpRequest [[XHR]](https://webaudio.github.io/web-audio-api/#biblio-xhr) (using the responseType and response attributes). For games and interactive applications, it is anticipated to be used with the canvas 2D [[2dcontext]](https://webaudio.github.io/web-audio-api/#biblio-2dcontext) and WebGL [[WEBGL]](https://webaudio.github.io/web-audio-api/#biblio-webgl) 3D graphics APIs.

# Status
https://webaudio.github.io/web-audio-api/#sotd (as ED)

# Is it a delta specification intended to become a W3C Recommendation?
No

# Link to group's decision to request transition
https://github.com/WebAudio/web-audio-api/issues/2602

# Issues
https://github.com/WebAudio/web-audio-api/issues

# Information about implementations known to the Working Group

Implementations ongoing in Chrome, WebKit, Firefox

**Comment by plehegar** [comment]
Approved

**Comment by plehegar** [comment]
(not yet published?)

**Comment by svgeesus** [comment]
> (not yet published?)

There was a publishing moratorium for two weeks. 5 Nov was the first publication day.

**Comment by svgeesus** [comment]
[Published 5 Nov 2024](https://www.w3.org/TR/2024/WD-webaudio-1.1-20241105/)
