### ISSUE TITLE
CR Snapshot Update Request for Verifiable Credentials Data Model v2.0 - vc-data-model

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#658]
# Document URLs

- Verifiable Credentials Data Model v2.0 (VC-DATA-MODEL-2.0)
  - https://w3c.github.io/vc-data-model/transitions/2024/CR2/ (not yet in place on /TR)
  - Proposed publication date: 2024-11-05
  - Editors' draft: https://w3c.github.io/vc-data-model/

# Link to group's decision to request transition

- https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-09-26-vcwg#resolution1

# Link to previous Candidate Recommendation transition or update request

- https://github.com/w3c/transitions/issues/587

# Substantive changes

See items under "Changes since the v2.0 First Candidate Recommendation": https://w3c.github.io/vc-data-model/transitions/2024/CR2/#revision-history

# Any changes in requirements?

None

# Wide Review of substantive changes

 Wide Review of substantive changes

None of the substantive changes since CR1 are related to Accessibility, Internationalization, Architecture, or Privacy. Some Security-related changes have been made, but the Security review is pending the creation of the Security Interest Group. We have written to each group above to get confirmation on if they concur with our analysis.

With respect to wide review, changes to the specification are circulated on a weekly basis to the W3C Credentials Community Group, which contains over 560+ individuals, with a number of them providing continued feedback since CR1. For example:

https://lists.w3.org/Archives/Public/public-credentials/2024Oct/0031.html

The test suites run on a weekly basis and implementers actively track how their implementations are performing. Ecosystem reports are also available and are tracked and commented on by organizations adopting vendor solutions: 

https://canivc.com/

Multiple implementers have also reviewed changes and have confirmed that they will implement or plan to implement all substantive changes since CR1. 

# Issues status

See https://github.com/w3c/vc-data-model/issues/

# Formal Objections

None

# Any changes in implementation information?

Two more implementations have been added to the test suite since CR1, bringing the total implementations registered in the VCDM v2.0 test suite to seven (7):

https://w3c.github.io/vc-data-model-2.0-test-suite/#conformance

...and the total number of VCWG implementations to fourteen (14): 

https://github.com/w3c/vc-test-suite-implementations/tree/main/implementations

The discrepancy is due to some implementers focusing on implementation of the Data Integrity test suites (more difficult) over the VCDM v2.0 test suite (easier).

# Deadline for further comments

30 days

# Any changes in patent disclosures?

None

cc: @msporny @brentzundel @dlongley @selfissued

---

(Edited 2024.10.26 by IH: updated the wide review section)

**Comment by plehegar** [comment]
I don't see any wide review requests for those changes, including horizontal reviews. Some changes impact [security](https://github.com/w3c/security-request/issues?q=is%3Aissue+is%3Aopen+verifiable)/[privacy](https://github.com/w3cping/privacy-request/issues?q=is%3Aissue+is%3Aclosed+verifiable) and would be good to get a review of those.

**Comment by iherman** [comment]
Raised https://github.com/w3cping/privacy-request/issues/146 and https://github.com/w3c/security-request/issues/78.

**Comment by iherman** [comment]
@plehegar, we have raised the privacy and security review requests (also for #658), and we got no reply since then. How long are we supposed to wait? It has been a month...

**Comment by simoneonofri** [comment]
@iherman for security, as the SING was announced few week ago, we started the security review of VCDM with @innotommy. So, it is in progress.

**Comment by iherman** [comment]
> @iherman for security, as the SING was announced few week ago, we started the security review of VCDM with @innotommy. So, it is in progress.

@simoneonofri we would like to publish the CR2 this year, which does not leave too much time...

**Comment by simoneonofri** [comment]
feedback on the review here, no blockers https://github.com/w3c/security-request/issues/58#issuecomment-2539902713

**Comment by plehegar** [comment]
Approved.

**Comment by iherman** [comment]
Document published and announced, see, e.g. https://www.w3.org/news/2024/five-candidate-recommendation-snapshots-published-by-the-verifiable-credentials-working-group/
