### ISSUE TITLE
FPWD Request for Audio Session - audio-session

### ISSUE THREAD

**Issue by tidoust** [w3c/transitions#661]
# Document title, URLs, estimated publication date

- Title: Audio Session
- URL: https://w3c.github.io/audio-session/
- Publication date: no specific urgency, once approved

# Abstract

This API defines an API surface for controlling how audio is rendered and interacts with other audio playing applications.

# Status

That will be the "usual" text. See https://w3c.github.io/audio-session/#sotd for the ED text.

# Is it a delta specification intended to become a W3C Recommendation?

No

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-media-wg/2024Oct/0011.html

# Issues

https://github.com/w3c/audio-session/issues

# Information about implementations known to the Working Group

Browser vendors present in the group are engaged and aligned on the specification with on-going implementations.

**Comment by plehegar** [comment]
Approved

**Comment by ylafon** [comment]
Published https://www.w3.org/TR/2024/WD-audio-session-20241113/
