### ISSUE TITLE
PR Request for UI Events KeyboardEvent code Values - uievents-code

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#663]
# Document title, URLs, estimated publication date
UI Events KeyboardEvent code Values
http://www.w3.org/TR/uievents-code/
[W3C Proposed Recommendation](https://www.w3.org/standards/types#PR) 12 November 2024

# Abstract
This specification defines the values for the KeyboardEvent.code attribute, which is defined as part of the UI Events Specification [[UIEvents]](https://w3c.github.io/uievents-code/#biblio-uievents). The code value contains information about the key event that can be used to identify the physical key being pressed by the user.

# Status
This document was published by the [Web Applications Working Group](https://www.w3.org/groups/wg/webapps) as a Proposed Recommendation using the [Recommendation track](https://www.w3.org/policies/process/20231103/#recs-and-notes).
Publication as a Proposed Recommendation does not imply endorsement by W3C and its Members.
This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.
The W3C Membership and other interested parties are invited to review the document and send comments through 10 December 2024. Advisory Committee Representatives should consult their [WBS questionnaires](https://www.w3.org/2002/09/wbs/myQuestionnaires). Note that substantive technical comments were expected during the Candidate Recommendation review period that ended 10 December 2024.

This document was produced by a group operating under the [W3C Patent Policy](https://www.w3.org/policies/patent-policy/). W3C maintains a [public list of any patent disclosures](https://www.w3.org/groups/wg/webapps/ipr) made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains [Essential Claim(s)](https://www.w3.org/policies/patent-policy/#def-essential) must disclose the information in accordance with [section 6 of the W3C Patent Policy](https://www.w3.org/policies/patent-policy/#sec-Disclosure).
This document is governed by the [03 November 2023 W3C Process Document](https://www.w3.org/policies/process/20231103/).

# Will new features be allowed to be incorporated in the Recommendation?
No.

# Link to group's decision to request transition
https://github.com/w3c/uievents-code/issues/43

# Changes
No.

# Requirements satisfied
No.

# Dependencies met (or not)
This specification includes normative references to the [UI Events](https://www.w3.org/TR/uievents/) specification, which is currently a WD but it is a stable and widely adopted document.

# Wide Review
https://github.com/w3c/uievents-code/issues/35

# Issues addressed
All technical issues are closed.

# Formal Objections
[TODO: All Formal Objections must have a public record in [public-review-comments](https://lists.w3.org/Archives/Public/public-review-comments/)]
None.

# Implementation
https://w3c.github.io/uievents-code/impl-report.html
All normative features have at least two implementations.

# Patent disclosures
https://www.w3.org/groups/wg/webapps/ipr

**Comment by plehegar** [comment]
Approved.

Congratulations

**Comment by ylafon** [comment]
Published https://www.w3.org/TR/2024/PR-uievents-code-20241126/
