### ISSUE TITLE
CR Request for Device Orientation and Motion - orientation-event

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#668]
# Document title, URLs, estimated publication date
Device Orientation and Motion
https://www.w3.org/TR/2024/WD-orientation-event-20241024/
2024-11-19 (if approved 2024-11-15)

# Abstract
https://www.w3.org/TR/2024/WD-orientation-event-20241024/#abstract

# Status
https://www.w3.org/TR/2024/WD-orientation-event-20241024/#sotd

# Link to group's decision to request transition
- resolution: https://www.w3.org/2024/09/24-dap-minutes.html#r01
- see [discussion thread](https://lists.w3.org/Archives/Team/w3t-archive/2024Nov/0102.html) for WebApps charter related.

# Changes
https://www.w3.org/TR/2024/WD-orientation-event-20241024/#changes

# Requirements satisfied
yes

# Dependencies met (or not)
dependencies unlikely to change

# Wide Review
- horizontal reviews' tracker: https://github.com/w3c/deviceorientation/issues/130
  - a11y: https://github.com/w3c/a11y-request/issues/71
  - i18n: https://github.com/w3c/i18n-request/issues/224
  - TAG: https://github.com/w3ctag/design-reviews/issues/928#issuecomment-1988078258
  - privacy: https://github.com/w3cping/privacy-request/issues/128
    - one tracker exists https://github.com/w3c/deviceorientation/issues/87 , and agreed to fixed before PR/REC https://github.com/w3cping/privacy-request/issues/128#issuecomment-1986979816
  - security: https://github.com/w3c/security-request/issues/63

# Issues addressed
https://github.com/w3c/deviceorientation/issues?q=is%3Aissue+is%3Aclosed

# Formal Objections
no

# Implementation
implementation report will be prepared per https://wpt.fyi/results/orientation-event

# Patent disclosures
- das: https://www.w3.org/groups/wg/das/ipr/
- webapps: https://www.w3.org/groups/wg/webapps/ipr/

**Comment by plehegar** [comment]
I see a lot of [open issues](https://github.com/w3c/deviceorientation/issues?q=is%3Aopen+is%3Aissue). Are you asserting that none of them have an impact on the design of the API ? Does this specification  actually satisfy the technical requirements of the Working Group and the spec is complete and fit for purpose ? Or are we at the stage where no further refinement to the text is expected without additional implementation experience and testing?

**Comment by plehegar** [comment]
There is an email thread about this with the Webpps and DAS chairs at
 https://lists.w3.org/Archives/Team/w3t-archive/2024Nov/0105.html
This might contain enough information to make a decision.

**Comment by himorin** [comment]
publication request sent https://lists.w3.org/Archives/Member/w3c-archive/2024Nov/0565.html

**Comment by himorin** [comment]
published https://www.w3.org/TR/2024/CR-orientation-event-20241121/
