### ISSUE TITLE
[SVGWG] CR update for SVG2

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#67]
# Link to group's decision to request transition
[RESOLUTION: Publish a new CR of SVG 2 as soon as possible.](https://www.w3.org/2018/07/30-svg-minutes.html#resolution01)

# Link to previous Candidate Recommendation transition request
[Transition request: SVG 2 to CR](https://lists.w3.org/Archives/Member/chairs/2016JulSep/0096.html)

# Substantive changes
A [complete list of changes since SVG 1.1](https://svgwg.org/svg2-draft/changes.html) is available. Changes since the 2016 CR are highlighted.

# Any changes in normative references?
References have been updated to latest versions.

# Any changes in requirements?
No change

# Wide Review of substantive changes
Each change was as a result of a GitHub issue, so the discussion for each one is on that issue. 

# Issues status
There are many open issues, so this will not be the last CR before PR. However, we want to publish an update showing progress to date, as the last /TR publication was September 2016.

[SVG 2.0 issues: open 48, closed 5](https://github.com/w3c/svgwg/milestone/4)

[SVG 2.1 issues: open 147, closed 2](https://github.com/w3c/svgwg/milestone/5)

# Formal Objections
None

# Any changes in implementation information?
Portions of the previously published SVG2 CR which do not have at least one
 implementation have been moved into a new, forward-looking SVG 2.1 document 
(which has not yet been published). 
Thus, the remaining features are believed to have at least one implementation.

Since the 2016 CR, tests have been added to WPT, so there is improved test coverage.

# Deadline for further comments
October 2018

# Any changes in patent disclosures?
No

**Comment by swickr** [comment]
Transition approved contingent upon there being no objections raised in the chairs list by midnight UTC on 6 August.

**Comment by svgeesus** [comment]
Publication request sent 05 Aug 2018

**Comment by svgeesus** [comment]
[Published, 7 Aug 2018](https://www.w3.org/TR/2018/CR-SVG2-20180807/)
