### ISSUE TITLE
First Note request for DID Resolution Extensions - did-extensions-resolution

### ISSUE THREAD

**Issue by pchampin** [w3c/transitions#672]
# Document

Title: DID Resolution Extensions – Known Extensions for DID Resolution and Dereferencing
URL: https://w3c.github.io/did-extensions/transitions/2024/NOTE/did-extensions-resolution/
 Estimated publication date: 21 November 2024

# Abstract

https://w3c.github.io/did-extensions/transitions/2024/NOTE/did-extensions-resolution/#abstract

# Status of the Document

https://w3c.github.io/did-extensions/transitions/2024/NOTE/did-extensions-resolution/#sotd

# Link to group's decision to request transition

* [Resolution to split `did-spec-registries` into separate NOTEs](https://www.w3.org/2024/08/01-did-minutes.html#r01)
* [Further WG discussion on using the pattern `did-extensions-X` for other notes](https://www.w3.org/2024/09/05-did-minutes.html#t08)

# Is it intended to be a W3C Statement?

No

**Comment by plehegar** [comment]
Approved

**Comment by plehegar** [comment]
https://www.w3.org/TR/2024/NOTE-did-extensions-resolution-20241119/
