### ISSUE TITLE
FPWD Request for WebDriver BiDi - webdriver-bidi

### ISSUE THREAD

**Issue by tidoust** [w3c/transitions#673]
# Document title, URLs, estimated publication date

- Title: WebDriver BiDi
- URL: https://w3c.github.io/webdriver-bidi/
- Publication date: no particular preferred day

# Abstract

This document defines the BiDirectional WebDriver Protocol, a mechanism for remote control of user agents.

# Status

See https://w3c.github.io/webdriver-bidi/#sotd for the ED version. ED boilerplate text to be replaced by FPWD boilerplate text.

# Is it a delta specification intended to become a W3C Recommendation?

No.

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-browser-tools-testing/2024OctDec/0008.html

# Issues

https://github.com/w3c/webdriver-bidi/issues

# Information about implementations known to the Working Group

Implementations in Chromium and Firefox, ongoing in WebKit. Also in test frameworks, including Puppeteer, Selenium, WebDriverIO. And Web Platform Tests!

**Comment by plehegar** [comment]
Approved.

**Comment by ylafon** [comment]
Published https://www.w3.org/TR/2024/WD-webdriver-bidi-20241121/
