### ISSUE TITLE
FPWD Request for Global Privacy Control - gpc

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#674]
# Document title, URLs, estimated publication date
https://w3c.github.io/gpc/?specStatus=FPWD&publishDate=2024-11-21

# Abstract

This document defines a signal, transmitted over HTTP and through the DOM, that conveys a person's request to websites and services to not sell or share their personal information with third parties. This standard is intended to work with existing and upcoming legal frameworks that render such requests enforceable.

# Status

This document was published by the [Privacy Working Group](https://www.w3.org/groups/wg/privacy) as a First Public Working Draft using the [Recommendation track](https://www.w3.org/policies/process/20231103/#recs-and-notes).

Publication as a First Public Working Draft does not imply endorsement by W3C and its Members.

This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the [W3C Patent Policy](https://www.w3.org/policies/patent-policy/). W3C maintains a [public list of any patent disclosures](https://www.w3.org/groups/wg/privacy/ipr) made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains [Essential Claim(s)](https://www.w3.org/policies/patent-policy/#def-essential) must disclose the information in accordance with [section 6 of the W3C Patent Policy](https://www.w3.org/policies/patent-policy/#sec-Disclosure).

This document is governed by the [03 November 2023 W3C Process Document](https://www.w3.org/policies/process/20231103/).

# Is it a delta specification intended to become a W3C Recommendation?

no

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-privacy/2024OctDec/0020.html

# Issues

https://github.com/w3c/gpc/issues

# Information about implementations known to the Working Group

Unknown

**Comment by plehegar** [comment]
cc @tjwhalen @npdoty

**Comment by ylafon** [comment]
Approved.

**Comment by ylafon** [comment]
Published https://www.w3.org/TR/2024/WD-gpc-20241121/
