### ISSUE TITLE
FPWD Request for Decentralized Identifier (DID) Resolution and DID URL Dereferencing v1.0 - did-resolution

### ISSUE THREAD

**Issue by pchampin** [w3c/transitions#675]
# Document title, URLs, estimated publication date

* Decentralized Identifier (DID) Resolution and DID URL Dereferencing v1.0 – Algorithms and guidelines for resolving DIDs and dereferencing DID URLs
* https://w3c.github.io/did-resolution/transitions/2024/FPWD/
* 2024-11-28

# Abstract
Decentralized identifiers (DIDs) are a new type of identifier for verifiable, "self-sovereign" digital identity. DIDs are fully under the control of the DID controller, independent from any centralized registry, identity provider, or certificate authority. DIDs resolve to DID Documents — simple documents that describe how to use that specific DID.

This document specifies the algorithms and guidelines for resolving DIDs and dereferencing DID URLs. 

# Status
https://w3c.github.io/did-resolution/transitions/2024/FPWD/#sotd

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://www.w3.org/2024/10/10-did-minutes.html#699d

# Issues
https://github.com/w3c/did-resolution/issues

# Information about implementations known to the Working Group

* https://github.com/decentralized-identity/did-resolver
* https://github.com/decentralized-identity/universal-resolver

**Comment by plehegar** [comment]
Approved

**Comment by ylafon** [comment]
Published https://www.w3.org/TR/2024/WD-did-resolution-20241128/
