### ISSUE TITLE
FPWD Request for Pointer Events Level 4 - pointerevents4

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#677]
# Document title, URLs, estimated publication date

https://w3c.github.io/pointerevents/?specStatus=FPWD&publishDate=2024-11-26

# Abstract

The features in this specification extend or modify those found in Pointer Events, a W3C Recommendation that describes events and related interfaces for handling hardware agnostic pointer input from devices including a mouse, pen, touchscreen, etc. For compatibility with existing mouse based content, this specification also describes a mapping to fire Mouse Events for other pointer device types.

# Status

This specification is an update to [[PointerEvents3](https://w3c.github.io/pointerevents/?specStatus=FPWD&publishDate=2024-11-26#bib-pointerevents3)]. It includes editorial clarifications and new features that facilitate more use cases.

This document was published by the [Pointer Events Working Group](https://www.w3.org/groups/wg/pointer-events) as a First Public Working Draft using the [Recommendation track](https://www.w3.org/policies/process/20231103/#recs-and-notes).

Publication as a First Public Working Draft does not imply endorsement by W3C and its Members.

This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the [W3C Patent Policy](https://www.w3.org/policies/patent-policy/). W3C maintains a [public list of any patent disclosures](https://www.w3.org/groups/wg/pointer-events/ipr) made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains [Essential Claim(s)](https://www.w3.org/policies/patent-policy/#def-essential) must disclose the information in accordance with [section 6 of the W3C Patent Policy](https://www.w3.org/policies/patent-policy/#sec-Disclosure).

This document is governed by the [03 November 2023 W3C Process Document](https://www.w3.org/policies/process/20231103/).

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
https://github.com/w3c/pointerevents/issues/506#issuecomment-2488626329

# Issues
https://github.com/w3c/pointerevents/issues/

# Information about implementations known to the Working Group
Unknown

cc @patrickhlauke

**Comment by ylafon** [comment]
Approved

**Comment by ylafon** [comment]
Published https://www.w3.org/TR/2024/WD-pointerevents4-20241128/
