### ISSUE TITLE
CR Request for Vibration API - vibration

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#680]
# Document title, URLs, estimated publication date
https://w3c.github.io/vibration/
Vibration API
2024-12-05 (at the most earliest)

Note: This is a update transition from REC to CRS per [Process 6.3.11.3. Revising a Recommendation: Substantive Changes, paragraph 2](https://www.w3.org/policies/process/20231103/#revised-rec-substantive). No WD has been published after last REC.

# Abstract
https://w3c.github.io/vibration/#abstract

# Status
https://w3c.github.io/vibration/#sotd

# Link to group's decision to request transition
https://www.w3.org/2024/09/24-dap-minutes.html#r03

# Changes
https://w3c.github.io/vibration/#changes

# Requirements satisfied
previously published as REC, yes.

# Dependencies met (or not)
Horizontal review groups agreed to work on fix for several foundings (e.g. https://github.com/w3c/vibration/issues/42, https://github.com/w3c/vibration/issues/50), there should be update before going further steps.

# Wide Review

- [tracker](https://github.com/w3c/vibration/issues/39)
  - [a11y](https://github.com/w3c/a11y-request/issues/87)
    - a11y group [agreed to work on one -needs-resolution issue after this CRS publication](https://github.com/w3c/vibration/issues/50#issuecomment-2460704204)
  - [TAG](https://github.com/w3ctag/design-reviews/issues/971)
    - satisfied with [concern](https://github.com/w3ctag/design-reviews/issues/971#issuecomment-2403446447)
  - [i18n](https://github.com/w3c/i18n-request/issues/236)
  - [privacy](https://github.com/w3cping/privacy-request/issues/138)
    - group raised one -needs-resolution but [agreed to take down into non-blocking issue](https://github.com/w3c/vibration/issues/42#issuecomment-2402813469)
  - [security](https://github.com/w3c/security-request/issues/71)
    - group raised one -needs-resolution but [agreed to work on one -needs-resolution issue after this CRS publication](https://lists.w3.org/Archives/Team/w3t-archive/2024Nov/0202.html)
    - group raised [one point](https://github.com/w3c/vibration/issues/48) during [review conversation](https://github.com/w3c/security-request/issues/71#issuecomment-2432844771) but not marked as -needs-resolution

# Issues addressed
https://github.com/w3c/vibration/issues

# Formal Objections
no.

# Implementation
implementation report [has not been updated from one at the time of last REC](https://github.com/w3c/vibration/issues/33), group will work on wpt issues and update implementation report during CRS phase.

# Patent disclosures
https://www.w3.org/groups/wg/das/ipr/

/cc @anssiko @reillyeon

**Comment by plehegar** [comment]
Approved.

**Comment by himorin** [comment]
published
https://www.w3.org/TR/2024/CR-vibration-20241128/
