### ISSUE TITLE
FPWD Request for CSS Display 4 - css-display-4

### ISSUE THREAD

**Issue by tabatkins** [w3c/transitions#685]
# Document title, URLs, estimated publication date
CSS Display 4: <https://drafts.csswg.org/css-display-4/>, next week? (Source file is clean and ready to publish; ChrisL can add a correct `Date` metadata and regenerate when needed.)

# Abstract
This module describes how the CSS formatting box tree is generated from the document element tree and defines the [display](https://drafts.csswg.org/css-display-4/#propdef-display) property that controls it.

# Status
<https://drafts.csswg.org/css-display-4/#sotd>

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
<https://github.com/w3c/csswg-drafts/issues/6900#issuecomment-2536613628>

# Issues
<https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Acss-display-4>

# Information about implementations known to the Working Group
New features are the 'reading-flow' property and the ability to transition/animate 'display'. I know that both of these have implementations (shipped or experimental) in Chrome, and have been at least reviewed by Mozilla and Apple devs, possibly implemented as well.

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Publication requested 17 Dec expected 19 Dec

**Comment by svgeesus** [comment]
[FPWD of CSS Display 4](https://www.w3.org/TR/2024/WD-css-display-4-20241219/) published 19 Dec
