### ISSUE TITLE
FPWD Request for CSS Multi-column Layout Module Level 2 - css-multicol-2

### ISSUE THREAD

**Issue by tabatkins** [w3c/transitions#686]
# Document title, URLs, estimated publication date
CSS Multi-column Layout Module Level 2: <https://drafts.csswg.org/css-multicol-2/>, next week? (Source file is clean and ready to publish; ChrisL can add a correct `Date` metadata and regenerate when needed.)

# Abstract
This specification describes multi-column layouts in CSS, a style sheet language for the web. Using functionality described in the specification, content can be flowed into multiple columns with a gap and a rule between them.

# Status
<https://drafts.csswg.org/css-multicol-2/#sotd>

# Is it a delta specification intended to become a W3C Recommendation?
no

# Link to group's decision to request transition
<https://github.com/w3c/csswg-drafts/issues/6900#issuecomment-2536613628>

# Issues
<https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Acss-multicol-2>

# Information about implementations known to the Working Group
New feature relative to Multicol 1 is the ::column pseudo-element. Chrome has an experimental implementation of this.

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Publication request sent 15 Dec expected 19 Dec

**Comment by svgeesus** [comment]
[FPWD of CSS Multicol 2](https://www.w3.org/TR/2024/WD-css-multicol-2-20241219/) published 19 Dec
