### ISSUE TITLE
FPWD Request for CSS Overflow Module Level 5 - css-overflow-5

### ISSUE THREAD

**Issue by tabatkins** [w3c/transitions#687]
# Document title, URLs, estimated publication date
CSS Overflow Module Level 5: <https://drafts.csswg.org/css-overflow-5/>, next week? (Source file is clean and ready to publish; ChrisL can add a correct `Date` metadata and regenerate when needed.)

# Abstract
This module contains the features of CSS relating to scrollable overflow handling in visual media. It builds on the CSS Overflow Module Level 4, adding the ability to generate and associate various scrolling controls (markers to indicate scroll progress, buttons to trigger scrolling), and adding an appendix containing an experimental exploration of redirecting overflow by fragmentation.

# Status
<https://drafts.csswg.org/css-overflow-5/#sotd>

# Is it a delta specification intended to become a W3C Recommendation?
yes

# Link to group's decision to request transition
<https://github.com/w3c/csswg-drafts/issues/6900#issuecomment-2536613628>

# Issues
<https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Acss-overflow-5>

# Information about implementations known to the Working Group
Chrome has experimental implementations of the scroll-related features. No current implementations, experimental or otherwise, exist for the overflow-redirection feature.

**Comment by plehegar** [comment]
Approved

**Comment by svgeesus** [comment]
Publication request sent 13 Dec, expected Tues 17 Dec

**Comment by svgeesus** [comment]
[FPWD of CSS Overflow 5 published 17 Dec](https://www.w3.org/TR/2024/WD-css-overflow-5-20241217/)
