### ISSUE TITLE
[WebPlatform] Proposal to obsolete view-mode

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#78]
This is following #65 .

One of the Widget specs is View-Mode Media Feature:
https://www.w3.org/TR/view-mode/

It is a maintenance spec of the Web Platform WG. The WG was therefore 
asked for consent to mark View-Mode Obsolete, and the CFC passed with 
only positive messages of support and no objections:
https://github.com/w3c/WebPlatformWG/issues/121#issuecomment-410518249

**Comment by swickr** [comment]
AC Call for Review should be issued.

I suggest using the sentence from Marco's request to the TAG https://github.com/w3ctag/obsoletion/issues/3 for justification and acknowledge Marcos as the originator of the request to obsolete as well as the primary editor of these specifications.

**Comment by plehegar** [comment]
[AC review started](https://lists.w3.org/Archives/Member/w3c-ac-members/2018JulSep/0035.html)

Deadline is Sep 27.
