### ISSUE TITLE
[DASWG] FPWD request for geolocation-sensor

### ISSUE THREAD

**Issue by xfq** [w3c/transitions#80]
# Document title, URLs, estimated publication date
Geolocation Sensor
https://xfq.github.io/testing/geolocation-sensor-WD/Overview.html
First Tuesday/Thursday after approval.

# Abstract
https://xfq.github.io/testing/geolocation-sensor-WD/Overview.html#abstract

# Status
https://xfq.github.io/testing/geolocation-sensor-WD/Overview.html#sotd

# Is it a delta specification intended to become a W3C Recommendation?
No.

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-device-apis/2018Aug/0008.html

# Information about implementations known to the Working Group
Polyfill: https://github.com/kenchris/sensor-polyfills/blob/master/src/geolocation-sensor.js

**Comment by plehegar** [comment]
Transition approved.

**Comment by xfq** [comment]
[Document published](https://www.w3.org/TR/2018/WD-geolocation-sensor-20180821/).
