### ISSUE TITLE
[CSSWG] CSS1 as a Superseded Recommendation

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#84]
[request was sent directly to the Director based on AC review results]

**Comment by swickr** [comment]
Transition approved.

There's a comment regarding whether these AC Reviews are necessary for superseding previous versions.  It is recommended that Proposed Recommendation transition reviews be explicit whether the new Rec is or is not intended to supersede the previous version.

**Comment by svgeesus** [comment]
Action item is on PLH

**Comment by svgeesus** [comment]
{Published 13 Sept 2018](https://www.w3.org/TR/2018/SPSD-CSS1-20180913/)
