### ISSUE TITLE
[TAG] Proposal to supersede WebCGM 1.x and 2.0

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#87]
# title, URL of the document to be obsoleted

* Name: WebCGM*
* Specification URLs:
  https://www.w3.org/TR/?title=cgm

# title, URL of the newer version

WebCGM 2.1
http://www.w3.org/TR/2010/REC-webcgm21-20100301/

# Link to group's decision to request obsoleting

https://github.com/w3ctag/meetings/blob/gh-pages/2018/04-tokyo/04-06-minutes.md

# Rationale

WebCGM 2.1 is a newer version and should be used instead of the old ones.

[[
WebCGM 2.1 is a superset of, and replaces, 2.0 and 1.0
The WebCGM WG
https://www.w3.org/Graphics/WebCGM/WG/
was closed in 2007.
]]
https://lists.w3.org/Archives/Public/www-tag/2017Apr/0012.html

(cc @ylafon )

**Comment by plehegar** [comment]
(also cc @svgeesus )

**Comment by svgeesus** [comment]
[I agreed in 2017 that these should be obsoleted](https://lists.w3.org/Archives/Public/www-tag/2017Apr/0012.html)

**Comment by plehegar** [comment]
We need to check with OASIS before moving forward:
  https://www.w3.org/TR/2007/REC-webcgm20-20070130/

**Comment by svgeesus** [comment]
Note:

> The Technical Committee was closed by Special Majority Vote of the TC on 21 January 2014 and is no longer active. Archives of its work remain publicly accessible and are linked from this page. OASIS appreciates the efforts of all those who participated in this TC.

https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=cgmo-webcgm

**Comment by svgeesus** [comment]
I alerted the OASIS-W3C liaison, Jamie Clark, to our proposed obsoletion. In addition to the OASIS-W3C MOU, Jamie is also the OASIS AC Rep so would additionally have a chance to comment during the AC review.

**Comment by plehegar** [comment]
OASIS was contacted but never responded. Moved to AC review.
