### ISSUE TITLE
Two "Implementation" headings IN CR template

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#90]
The CR transition template has two similar headings:

# Implementation
[TODO: preliminary implementation report? exit criteria?]

# Information about implementations known to the Working Group
[TODO: add any preliminary information that you might have]

The requirements for transition has [only one](https://www.w3.org/Guide/transitions?profile=CR&cr=new)

# Implementation

Inadvertent copy-paste or a deliberate change?

**Comment by plehegar** [comment]
Fixed in https://github.com/w3c/transitions/commit/20581ea059bdfb523decf3ca053d234668bde75f
