### ISSUE TITLE
[PointerEvents] PR request for pointerevents2

### ISSUE THREAD

**Issue by plehegar** [w3c/transitions#92]
# Document title, URLs, estimated publication date

https://w3c.github.io/pointerevents/?specStatus=PR;prEnd=2018-10-18;crEnd=2018-05-17;publishDate=2018-09-18

# Abstract

https://w3c.github.io/pointerevents/#abstract-0

# Status

https://w3c.github.io/pointerevents/?specStatus=PR;prEnd=2018-10-18;crEnd=2018-05-17;publishDate=2018-09-18#status-of-this-document

# Link to group's decision to request transition

https://lists.w3.org/Archives/Public/public-pointer-events/2018OctDec/0013.html

# Changes

No substantive changes since the publication of the CR.

minor clarification to make it clearer that pressure/tangentialPressure/tiltXY/twist are hardware and platform dependent.

Diff:
 https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fpointerevents2%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fpointerevents%2F%3FspecStatus%3DPR%3BshortName%3Dpointerevents2%3BprEnd%3D2018-10-18%3BcrEnd%3D2018-05-17%3BpublishDate%3D2018-09-18

Commits:
 https://github.com/w3c/pointerevents/commits/gh-pages/index.html

# Requirements satisfied

No change since previous transition.

# Dependencies met (or not)

* UIEvents:
 We rely on features from the MouseEvent interface that were part of DOM Level 2
  https://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-MouseEvent
  https://wpt.fyi/results/uievents/idlharness.window.html

# Wide Review

https://github.com/w3c/pointerevents/issues

# Issues addressed

https://github.com/w3c/pointerevents/issues

# Formal Objections

None

# Implementation

http://w3c.github.io/test-results/pointerevents/all.html
http://w3c.github.io/test-results/pointerevents/less-than-2.html

See also the discussion at
 https://lists.w3.org/Archives/Public/public-pointer-events/2018JulSep/0003.html

# Patent disclosures

No change
https://www.w3.org/2004/01/pp-impl/59096/status

**Comment by swickr** [comment]
Looking at this; giving chairs@w3 the opportunity to comment and waiting for the WG CfC to close.

**Comment by plehegar** [comment]
The Group CfC passed:
 https://lists.w3.org/Archives/Public/public-pointer-events/2018OctDec/0015.html

**Comment by plehegar** [comment]
published.
