### ISSUE TITLE
[47318] CR update for webrtc & webrtc-identity

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/transitions#93]
# Link to group's decision to request transition
https://www.w3.org/2018/06/19-webrtc-minutes#item08

# Link to previous Candidate Recommendation transition request
https://lists.w3.org/Archives/Member/chairs/2018AprJun/0091.html

# Substantive changes
* Split the document into two separate specifications (WebRTC 1.0 and Identity for  WebRTC)
* Other substantive changes that are unlikely to affect previous wide-reviews https://github.com/w3c/webrtc-pc/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+merged%3A%3E2018-06-08+-label%3AEditorial

# Any changes in normative references?
* addition of WHATWG HTML for the structured cloning algorithm reference
* addition of cross-reference between WebRTC and WebRTC identity

# Any changes in requirements?
N/A

# Wide Review of substantive changes
N/A

# Issues status
* 41 remaining open issues on WebRTC 1.0 https://github.com/w3c/webrtc-pc/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3Aeditorial
* 22 remaining issues on Identity for WebRTC https://github.com/w3c/webrtc-identity/issues

# Formal Objections
N/A

# Any changes in implementation information?
Interfaces in WebRTC 1.0 are gaining further and broader implementation in browsers but aren't all completely implemented yet.

# Deadline for further comments
31 Dec 2018

# Any changes in patent disclosures?
N/A

**Comment by swickr** [comment]
Transition approved.

The SoTD for webrtc-identity should note that it was previously included in the 21 June CR version of webrtc(-pc).

**Comment by plehegar** [comment]
https://www.w3.org/TR/2018/CR-webrtc-20180927/
https://www.w3.org/TR/2018/CR-webrtc-identity-20180927/
