### ISSUE TITLE
[SVGWG] CR update for SVG2

### ISSUE THREAD

**Issue by svgeesus** [w3c/transitions#94]
# Link to group's decision to request transition

[resolution: Publish updated CR](https://www.w3.org/2018/09/17-svg-irc#T19-38-58)
minutes, 17 Sept 2018 SVG WG telcon

# Link to previous Candidate Recommendation transition request

[CR update for SVG2](https://github.com/w3c/transitions/issues/67)

# Substantive changes

[Changes](https://svgwg.org/svg2-draft/changes.html)

Look for the label "Changed since 7 August 2018 CR"

# Any changes in normative references?

Some references updated to latest version

# Any changes in requirements?

None

# Wide Review of substantive changes

Each change was as a result of a GitHub issue, so the discussion for each one is on that issue. Changes list links to the GitHub issues.

# Issues status

For the SVG 2.0 milestone [51  open, 13 closed](https://github.com/w3c/svgwg/milestone/4)

The SVG WG would like to publish an updated CR to allow further review of changes made since the previous CR, and also to fix broken undated links to deleted chapters which the previous CR inadvertently introduced.

# Formal Objections

None

# Any changes in implementation information?

None

# Deadline for further comments

One month

# Any changes in patent disclosures?

No

**Comment by plehegar** [comment]
https://rawgit.com/w3c/svgwg/master/master/changes.html

**Comment by swickr** [comment]
Transition approved.

**Comment by svgeesus** [comment]
Publication request sent 3 Oct, expected publication 4 Oct

**Comment by plehegar** [comment]
https://www.w3.org/TR/2018/CR-SVG2-20181004/
