### ISSUE TITLE
[WebAuthn] Transition to Proposed Recommendation for WebAuthn

### ISSUE THREAD

**Issue by apowers313** [w3c/transitions#96]
#Title:
Web Authentication: An API for accessing Public Key Credentials
Level 1
https://www.w3.org/TR/webauthn/

See
https://lists.w3.org/Archives/Public/public-webauthn/2018Sep/0043.html

**Comment by plehegar** [comment]
Transition request is at https://lists.w3.org/Archives/Member/chairs/2018JulSep/0137.html

**Comment by swickr** [comment]
Original [9 March CR transition request](https://lists.w3.org/Archives/Member/chairs/2018JanMar/0096.html)

#66: 27 July CR update request

**Comment by plehegar** [comment]
(waiting on additional implementation documentation)

**Comment by plehegar** [comment]
This is still work in progress...

**Comment by plehegar** [comment]
https://www.w3.org/2019/01/webauthn-extensions.html

**Comment by plehegar** [comment]
https://www.w3.org/TR/2019/PR-webauthn-20190117/
