### ISSUE TITLE
[CSSWG] CR update for CSS-Contain

### ISSUE THREAD

**Issue by frivoal** [w3c/transitions#98]
# Link to group's decision to request transition:

https://lists.w3.org/Archives/Public/www-style/2018Oct/0005.html

# Link to previous Candidate Recommendation transition request:
https://lists.w3.org/Archives/Member/chairs/2018AprJun/0059.html

# Substantive changes
https://drafts.csswg.org/css-contain/#2018-05-24-changes

# Any changes in normative references?

* CSS-UI-3 moved from normative to informative reference (the `resize` property is cited only as an example)
* Reference to CSS-Values-3 (CR) updated by bikeshed to CSS-Values-4 (WD). Only used to refer to the `|` and `||` grammar constructs, which have existed in previous RECs. (@tabatkins Is there a way to make bikeshed link to values-3 for this?)

# Any changes in requirements?
No

# Wide Review of substantive changes
Disposition of Comments: https://drafts.csswg.org/css-contain/issues-2018-cr.html

# Issues status

All closed. See [DoC](https://drafts.csswg.org/css-contain/issues-2018-cr.html) and https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Acss-contain-1

# Formal Objections
None

# Any changes in implementation information?
[Numerous bug fixes in Chrome implementation](https://bugs.chromium.org/p/chromium/issues/list?can=1&q=[css-contain]%20status=Fixed&sort=-status&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified), [ongoing implementation in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1150081)

# Deadline for further comments

Resolution doesn't specify. I propose 6 weeks, which is more than the default period of 4weeks.

# Any changes in patent disclosures?
No: www.w3.org/2004/01/pp-impl/32061/status

**Comment by frivoal** [comment]
> svgeesus added Entering CR 

It's a CR update, not a new CR.

**Comment by fantasai** [comment]
@frivoal We don't have a distinct set of tags for that. I suppose I could rename the tag (re)Entering, unless @plehegar and @svgeesus think it would be better to create a separate set of tags for that.

**Comment by frivoal** [comment]
@svgeesus ready to go. Do you take care of tweaking the bikeshed source to generate the CR styled version, or should I?

**Comment by svgeesus** [comment]
@fantasai I think the Entering CR tag is used by tooling now, so should not be changed without investigating what would break. 
@frivoal the same tag is used for new and updated CRs. I agree the name is potentially confusing.
Next step is a directors decision.

**Comment by plehegar** [comment]
We aren't using the tag Entering CR for tooling purposes at the moment. We might (shoud?) get rid of those if confusing/unnecessary. Ideally, those tags can be managed by the tooling anyway if needed.

**Comment by swickr** [comment]
Transition approved.

**Comment by xfq** [comment]
[Document published](https://www.w3.org/TR/2018/CR-css-contain-1-20181108/).
